Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/cb_sample.h File Reference
cb_sample.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * cb_sample_setup (VW::config::options_i &options, vw &all)
Function Documentation
cb_sample_setup()
LEARNER::base_learner* cb_sample_setup (VW::config::options_i & options, vw & all)
Definition at line 97 of file cb_sample.cc.
References prediction_type::action_probs, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), vw::get_random_state(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   bool cb_sample_option = false;
   option_group_definition new_options("CB Sample");
   new_options.add(make_option("cb_sample", cb_sample_option).keep().help("Sample from CB pdf and swap top action."));
   options.add_and_parse(new_options);
   if (!cb_sample_option)
     return nullptr;
   if (options.was_supplied("no_predict"))
   {
     THROW("cb_sample cannot be used with no_predict, as there would be no predictions to sample.");
   }
   auto data = scoped_calloc_or_throw<cb_sample_data>(all.get_random_state());
   return make_base(init_learner(data, as_multiline(setup_base(options, all)), learn_or_predict<true>,
       learn_or_predict<false>, 1 /* weights */, prediction_type::action_probs));
 }