Vowpal Wabbit: LEARNER::multi_example_handler< context_type > Class Template Reference
LEARNER::multi_example_handler< context_type > Class Template Reference
Public Member Functions
multi_example_handler (const context_type context)
~multi_example_handler ()
void on_example (example *ec)
Private Member Functions
bool complete_multi_ex (example *ec)
bool try_complete_multi_ex (example *ec)
Private Attributes
context_type _context
multi_ex ec_seq
Detailed Description
template<typename context_type>
class LEARNER::multi_example_handler< context_type >
Definition at line 162 of file learner.cc.
Constructor & Destructor Documentation
multi_example_handler()
template<typename context_type > LEARNER::multi_example_handler< context_type >::multi_example_handler (const context_type context) inline
Definition at line 195 of file learner.cc.
 : _context(context) {}
~multi_example_handler()
template<typename context_type > LEARNER::multi_example_handler< context_type >::~multi_example_handler () inline
Definition at line 197 of file learner.cc.
   {
     if (!ec_seq.empty())
     {
       _context.template process<multi_ex, learn_multi_ex>(ec_seq);
     }
   }
Member Function Documentation
complete_multi_ex()
template<typename context_type > bool LEARNER::multi_example_handler< context_type >::complete_multi_ex (example * ec) inline private
Definition at line 165 of file learner.cc.
References LEARNER::example_is_newline_not_header(), VW::finish_example(), and example::l.
   {
     auto& master = _context.get_master();
     const bool is_test_ec = master.p->lp.test_label(&ec->l);
     const bool is_newline = (example_is_newline_not_header(*ec, master) && is_test_ec);
     if (!is_newline)
     {
       ec_seq.push_back(ec);
     }
     else
     {
       VW::finish_example(master, *ec);
     }
     return is_newline;
   }
on_example()
template<typename context_type > void LEARNER::multi_example_handler< context_type >::on_example (example * ec) inline
Definition at line 205 of file learner.cc.
   {
     if (try_complete_multi_ex(ec))
     {
       _context.template process<multi_ex, learn_multi_ex>(ec_seq);
       ec_seq.clear();
     }
   }
try_complete_multi_ex()
template<typename context_type > bool LEARNER::multi_example_handler< context_type >::try_complete_multi_ex (example * ec) inline private
Definition at line 181 of file learner.cc.
References example::end_pass, example_predict::indices, LEARNER::is_save_cmd(), and v_array< T >::size().
   {
     if (ec->indices.size() > 1)  // 1+ nonconstant feature. (most common case first)
       return complete_multi_ex(ec);
     else if (ec->end_pass)
       _context.template process<example, end_pass>(*ec);
     else if (is_save_cmd(ec))
       _context.template process<example, save>(*ec);
     else
       return complete_multi_ex(ec);
     return false;
   }
Member Data Documentation
_context
template<typename context_type > context_type LEARNER::multi_example_handler< context_type >::_context private
Definition at line 215 of file learner.cc.
ec_seq
template<typename context_type > multi_ex LEARNER::multi_example_handler< context_type >::ec_seq private
Definition at line 216 of file learner.cc.
The documentation for this class was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/learner.cc