Vowpal Wabbit: features::features_value_index_audit_range Class Reference
features::features_value_index_audit_range Class Reference
defines a "range" usable by C++ 11 for loops
#include <feature_group.h>
Public Member Functions
features_value_index_audit_range (features *outer)
iterator_all begin ()
iterator_all end ()
Private Attributes
features * _outer
Detailed Description
defines a "range" usable by C++ 11 for loops
Definition at line 254 of file feature_group.h.
Constructor & Destructor Documentation
features_value_index_audit_range()
features::features_value_index_audit_range::features_value_index_audit_range (features * outer) inline
Definition at line 260 of file feature_group.h.
 : _outer(outer) {}
Member Function Documentation
begin()
iterator_all features::features_value_index_audit_range::begin () inline
Definition at line 262 of file feature_group.h.
References v_array< T >::begin(), features::indicies, features::space_names, and features::values.
Referenced by INTERACTIONS::generate_interactions(), and unique_features().
     {
       return iterator_all(_outer->values.begin(), _outer->indicies.begin(), _outer->space_names.begin());
     }
end()
iterator_all features::features_value_index_audit_range::end () inline
Definition at line 266 of file feature_group.h.
References v_array< T >::end(), features::indicies, features::space_names, and features::values.
Referenced by INTERACTIONS::generate_interactions(), and unique_features().
 { return iterator_all(_outer->values.end(), _outer->indicies.end(), _outer->space_names.end()); }
Member Data Documentation
_outer
features* features::features_value_index_audit_range::_outer private
Definition at line 257 of file feature_group.h.
The documentation for this class was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/feature_group.h