Vowpal Wabbit: sparse_parameters Class Reference
sparse_parameters Class Reference
#include <array_parameters.h>
Public Types
typedef sparse_iterator< weight > iterator
typedef sparse_iterator< const weight > const_iterator
Public Member Functions
sparse_parameters (size_t length, uint32_t stride_shift=0)
sparse_parameters ()
bool not_null ()
sparse_parameters (const sparse_parameters &other)
sparse_parameters (sparse_parameters &&)=delete
weight * first ()
iterator begin ()
iterator end ()
const_iterator cbegin ()
const_iterator cend ()
weight & operator[] (size_t i)
const weight & operator[] (size_t i) const
weight & strided_index (size_t index)
void shallow_copy (const sparse_parameters &input)
template<class R , class T >
void set_default (R &info)
template<class T >
void set_default ()
void set_zero (size_t offset)
uint64_t mask () const
uint64_t seeded () const
uint32_t stride () const
uint32_t stride_shift () const
void stride_shift (uint32_t stride_shift)
void share (size_t)
~sparse_parameters ()
Private Attributes
weight_map _map
uint64_t _weight_mask
uint32_t _stride_shift
bool _seeded
bool _delete
void * default_data
float * default_value
void(* fun)(const weight *, void *)
Detailed Description
Definition at line 60 of file array_parameters.h.
Member Typedef Documentation
const_iterator
typedef sparse_iterator<const weight> sparse_parameters::const_iterator
Definition at line 73 of file array_parameters.h.
iterator
typedef sparse_iterator<weight> sparse_parameters::iterator
Definition at line 72 of file array_parameters.h.
Constructor & Destructor Documentation
sparse_parameters() [1/4]
sparse_parameters::sparse_parameters (size_t length, uint32_t stride_shift = 0) inline
Definition at line 79 of file array_parameters.h.
       : _map()
       , _weight_mask((length << stride_shift) - 1)
       , _stride_shift(stride_shift)
       , _seeded(false)
       , _delete(false)
       , default_data(nullptr)
       , fun(nullptr)
   {
     default_value = calloc_mergable_or_throw<weight>(stride());
   }
sparse_parameters() [2/4]
sparse_parameters::sparse_parameters () inline
Definition at line 91 of file array_parameters.h.
       : _map(), _weight_mask(0), _stride_shift(0), _seeded(false), _delete(false), default_data(nullptr), fun(nullptr)
   {
     default_value = calloc_mergable_or_throw<weight>(stride());
   }
sparse_parameters() [3/4]
sparse_parameters::sparse_parameters (const sparse_parameters & other) inline
Definition at line 99 of file array_parameters.h.
 { shallow_copy(other); }
sparse_parameters() [4/4]
sparse_parameters::sparse_parameters (sparse_parameters &&) delete
~sparse_parameters()
sparse_parameters::~sparse_parameters () inline
Definition at line 212 of file array_parameters.h.
   {
     if (!_delete && !_seeded)  // don't free weight vector if it is shared with another instance
     {
       for (auto iter = _map.begin(); iter != _map.end(); ++iter) free(iter->second);
       _map.clear();
       _delete = true;
     }
     if (default_data != nullptr)
       free(default_data);
     free(default_value);
   }
Member Function Documentation
begin()
iterator sparse_parameters::begin () inline
Definition at line 105 of file array_parameters.h.
   {
     weight_map::iterator i = _map.begin();
     return iterator(i, stride());
   }
cbegin()
const_iterator sparse_parameters::cbegin () inline
Definition at line 117 of file array_parameters.h.
   {
     weight_map::iterator i = _map.begin();
     return const_iterator(i, stride());
   }
cend()
const_iterator sparse_parameters::cend () inline
Definition at line 122 of file array_parameters.h.
   {
     weight_map::iterator i = _map.begin();
     return const_iterator(i, stride());
   }
end()
iterator sparse_parameters::end () inline
Definition at line 110 of file array_parameters.h.
   {
     weight_map::iterator i = _map.end();
     return iterator(i, stride());
   }
first()
weight* sparse_parameters::first () inline
Definition at line 102 of file array_parameters.h.
References THROW_OR_RETURN.
 { THROW_OR_RETURN("Allreduce currently not supported in sparse", nullptr); }
mask()
uint64_t sparse_parameters::mask () const inline
Definition at line 191 of file array_parameters.h.
Referenced by parameters::mask().
 { return _weight_mask; }
not_null()
bool sparse_parameters::not_null () inline
Definition at line 97 of file array_parameters.h.
Referenced by parameters::not_null().
 { return (_weight_mask > 0 && !_map.empty()); }
operator[]() [1/2]
weight& sparse_parameters::operator[] (size_t i) inline
Definition at line 128 of file array_parameters.h.
References sparse_iterator< T >::index().
   {
     uint64_t index = i & _weight_mask;
     weight_map::iterator iter = _map.find(index);
     if (iter == _map.end())
     {
       _map.insert(std::make_pair(index, calloc_mergable_or_throw<weight>(stride())));
       iter = _map.find(index);
       if (fun != nullptr)
         fun(iter->second, default_data);
     }
     return *(iter->second);
   }
operator[]() [2/2]
const weight& sparse_parameters::operator[] (size_t i) const inline
Definition at line 142 of file array_parameters.h.
References sparse_iterator< T >::index().
   {
     uint64_t index = i & _weight_mask;
     weight_map::const_iterator iter = _map.find(index);
     if (iter == _map.end())
       return *default_value;
     return *(iter->second);
   }
seeded()
uint64_t sparse_parameters::seeded () const inline
Definition at line 193 of file array_parameters.h.
Referenced by parameters::seeded().
 { return _seeded; }
set_default() [1/2]
template<class R , class T > void sparse_parameters::set_default (R & info) inline
Definition at line 171 of file array_parameters.h.
Referenced by save_load(), and GD::save_load().
   {
     R& new_R = calloc_or_throw<R>();
     new_R = info;
     default_data = &new_R;
     fun = (void (*)(const weight*, void*))T::func;
     fun(default_value, default_data);
   }
set_default() [2/2]
template<class T > void sparse_parameters::set_default () inline
Definition at line 181 of file array_parameters.h.
   {
     fun = (void (*)(const weight*, void*))T::func;
   }
set_zero()
void sparse_parameters::set_zero (size_t offset) inline
Definition at line 186 of file array_parameters.h.
Referenced by parameters::set_zero().
   {
     for (weight_map::iterator iter = _map.begin(); iter != _map.end(); ++iter) (&(*(iter->second)))[offset] = 0;
   }
shallow_copy()
void sparse_parameters::shallow_copy (const sparse_parameters & input) inline
Definition at line 153 of file array_parameters.h.
References _map, _stride_shift, _weight_mask, default_data, and default_value.
Referenced by parameters::shallow_copy().
   {
     // TODO: this is level-1 copy (weight* are stilled shared)
     if (!_seeded)
     {
       for (auto iter = _map.begin(); iter != _map.end(); ++iter) free(iter->second);
     }
     _map = input._map;
     _weight_mask = input._weight_mask;
     _stride_shift = input._stride_shift;
     free(default_value);
     default_value = calloc_mergable_or_throw<weight>(stride());
     memcpy(default_value, input.default_value, stride());
     default_data = input.default_data;
     _seeded = true;
   }
share()
void sparse_parameters::share (size_t) inline
Definition at line 209 of file array_parameters.h.
References THROW_OR_RETURN.
Referenced by parameters::share().
 { THROW_OR_RETURN("Operation not supported on Windows"); }
stride()
uint32_t sparse_parameters::stride () const inline
Definition at line 195 of file array_parameters.h.
Referenced by parameters::stride().
 { return 1 << _stride_shift; }
stride_shift() [1/2]
uint32_t sparse_parameters::stride_shift () const inline
Definition at line 197 of file array_parameters.h.
Referenced by accumulate(), accumulate_avg(), accumulate_weighted_avg(), and parameters::stride_shift().
 { return _stride_shift; }
stride_shift() [2/2]
void sparse_parameters::stride_shift (uint32_t stride_shift) inline
Definition at line 199 of file array_parameters.h.
References stride_shift().
   {
     _stride_shift = stride_shift;
     free(default_value);
     default_value = calloc_mergable_or_throw<weight>(stride());
     if (fun != nullptr)
       fun(default_value, default_data);
   }
strided_index()
weight& sparse_parameters::strided_index (size_t index) inline
Definition at line 151 of file array_parameters.h.
Referenced by parameters::strided_index().
 { return operator[](index << _stride_shift); }
Member Data Documentation
_delete
bool sparse_parameters::_delete private
Definition at line 67 of file array_parameters.h.
_map
weight_map sparse_parameters::_map private
Definition at line 63 of file array_parameters.h.
Referenced by shallow_copy().
_seeded
bool sparse_parameters::_seeded private
Definition at line 66 of file array_parameters.h.
_stride_shift
uint32_t sparse_parameters::_stride_shift private
Definition at line 65 of file array_parameters.h.
Referenced by shallow_copy().
_weight_mask
uint64_t sparse_parameters::_weight_mask private
Definition at line 64 of file array_parameters.h.
Referenced by shallow_copy().
default_data
void* sparse_parameters::default_data private
Definition at line 68 of file array_parameters.h.
Referenced by shallow_copy().
default_value
float* sparse_parameters::default_value private
Definition at line 69 of file array_parameters.h.
Referenced by shallow_copy().
fun
void(* sparse_parameters::fun) (const weight *, void *) private
Definition at line 76 of file array_parameters.h.
The documentation for this class was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/array_parameters.h