Vowpal Wabbit: parameters Class Reference
parameters Class Reference
#include <array_parameters.h>
Public Member Functions
weight & operator[] (size_t i)
uint32_t stride_shift ()
uint32_t stride ()
uint64_t mask ()
uint64_t seeded ()
void shallow_copy (const parameters &input)
void set_zero (size_t offset)
void share (size_t length)
void stride_shift (uint32_t stride_shift)
weight & strided_index (size_t index)
bool not_null ()
Public Attributes
bool adaptive
bool normalized
bool sparse
dense_parameters dense_weights
sparse_parameters sparse_weights
Detailed Description
Definition at line 226 of file array_parameters.h.
Member Function Documentation
mask()
uint64_t parameters::mask () inline
Definition at line 260 of file array_parameters.h.
References dense_parameters::mask(), and sparse_parameters::mask().
Referenced by Search::add_new_feature(), recall_tree_ns::add_node_id_feature(), GD::audit_feature(), audit_regressor_feature(), copy_example_to_adf(), flatten_example(), VW::get_features(), Search::search::get_mask(), learn_batch(), learn_with_metrics(), MARGINAL::make_marginal(), mf_print_offset_features(), multiply(), predict_or_learn(), MWT::predict_or_learn(), GraphTask::setup(), MARGINAL::update_marginal(), MWT::value_policy(), wid_mask(), and wid_mask_un_shifted().
   {
     if (sparse)
       return sparse_weights.mask();
     else
       return dense_weights.mask();
   }
not_null()
bool parameters::not_null () inline
Definition at line 319 of file array_parameters.h.
References dense_parameters::not_null(), and sparse_parameters::not_null().
Referenced by flatten_example().
   {
     if (sparse)
       return sparse_weights.not_null();
     else
       return dense_weights.not_null();
   }
operator[]()
weight& parameters::operator[] (size_t i) inline
Definition at line 236 of file array_parameters.h.
   {
     if (sparse)
       return sparse_weights[i];
     else
       return dense_weights[i];
   }
seeded()
uint64_t parameters::seeded () inline
Definition at line 268 of file array_parameters.h.
References dense_parameters::seeded(), and sparse_parameters::seeded().
Referenced by VW::finish().
   {
     if (sparse)
       return sparse_weights.seeded();
     else
       return dense_weights.seeded();
   }
set_zero()
void parameters::set_zero (size_t offset) inline
Definition at line 284 of file array_parameters.h.
References dense_parameters::set_zero(), and sparse_parameters::set_zero().
Referenced by parse_mask_regressor_args(), zero_derivative(), zero_preconditioner(), and zero_state().
   {
     if (sparse)
       sparse_weights.set_zero(offset);
     else
       dense_weights.set_zero(offset);
   }
shallow_copy()
void parameters::shallow_copy (const parameters & input) inline
Definition at line 276 of file array_parameters.h.
References dense_weights, dense_parameters::shallow_copy(), sparse_parameters::shallow_copy(), and sparse_weights.
Referenced by VW::seed_vw_model().
   {
     if (sparse)
       sparse_weights.shallow_copy(input.sparse_weights);
     else
       dense_weights.shallow_copy(input.dense_weights);
   }
share()
void parameters::share (size_t length) inline
Definition at line 293 of file array_parameters.h.
References dense_parameters::share(), and sparse_parameters::share().
Referenced by enable_sources().
   {
     if (sparse)
       sparse_weights.share(length);
     else
       dense_weights.share(length);
   }
stride()
uint32_t parameters::stride () inline
Definition at line 252 of file array_parameters.h.
References dense_parameters::stride(), and sparse_parameters::stride().
Referenced by bfgs_setup(), VW::get_stride(), learn_batch(), OjaNewton_setup(), and save_load().
   {
     if (sparse)
       return sparse_weights.stride();
     else
       return dense_weights.stride();
   }
stride_shift() [1/2]
uint32_t parameters::stride_shift () inline
Definition at line 244 of file array_parameters.h.
References dense_parameters::stride_shift(), and sparse_parameters::stride_shift().
Referenced by accumulate_weighted_avg(), Search::add_example_conditioning(), Search::add_neighbor_features(), Search::add_new_feature(), recall_tree_ns::add_node_id_feature(), ezexample::addf(), GD::audit_feature(), audit_regressor_feature(), audit_regressor_lda(), autolink_setup(), bfgs_setup(), CCB::ccb_explore_adf_setup(), copy_example_to_adf(), VW::export_example(), DepParserTask::extract_features(), finish_setup(), flatten_example(), ftrl_setup(), gd_mf_setup(), VW::get_features(), Search::search::get_stride_shift(), VW::get_weight(), init_global(), lda_setup(), learn_with_metrics(), OjaNewton_setup(), parse_sources(), predict_or_learn(), MWT::predict_or_learn(), GD::print_lda_features(), print_setup(), MARGINAL::save_load(), save_load(), memory_tree_ns::save_load_memory_tree(), VW::set_weight(), GraphTask::setup(), VW::setup_example(), stride_shift(), stride_un_shift(), svrg_setup(), un_ft_offset(), and MWT::value_policy().
   {
     if (sparse)
       return sparse_weights.stride_shift();
     else
       return dense_weights.stride_shift();
   }
stride_shift() [2/2]
void parameters::stride_shift (uint32_t stride_shift) inline
Definition at line 303 of file array_parameters.h.
References dense_parameters::stride_shift(), and sparse_parameters::stride_shift().
   {
     if (sparse)
       sparse_weights.stride_shift(stride_shift);
     else
       dense_weights.stride_shift(stride_shift);
   }
strided_index()
weight& parameters::strided_index (size_t index) inline
Definition at line 311 of file array_parameters.h.
References dense_parameters::strided_index(), and sparse_parameters::strided_index().
Referenced by OjaNewton::check(), OjaNewton::initialize_Z(), and save_load().
   {
     if (sparse)
       return sparse_weights.strided_index(index);
     else
       return dense_weights.strided_index(index);
   }
Member Data Documentation
adaptive
bool parameters::adaptive
Definition at line 229 of file array_parameters.h.
Referenced by accumulate_weighted_avg(), GD::audit_feature(), GD::end_pass(), GD::save_load(), GD::save_load_online_state(), GD::set_learn(), and GD::setup().
dense_weights
dense_parameters parameters::dense_weights
Definition at line 233 of file array_parameters.h.
Referenced by accumulate(), accumulate_avg(), accumulate_weighted_avg(), add_regularization(), bfgs_iter_middle(), bfgs_iter_start(), compute_coherence_metrics(), derivative_in_direction(), direction_magnitude(), end_examples(), finalize_preconditioner(), GD::foreach_feature(), INTERACTIONS::generate_interactions(), get_top_weights(), init_driver(), initialize_regressor(), GD::inline_predict(), mf_predict(), mf_train(), multipredict(), GD::multipredict(), preconditioner_to_regularizer(), regularizer_direction_magnitude(), regularizer_to_weight(), sanity_check_state(), save_load(), GD::save_load(), GD::save_load_online_state(), GD::save_load_regressor(), shallow_copy(), GD::sync_weights(), update_weight(), and wolfe_eval().
normalized
bool parameters::normalized
Definition at line 230 of file array_parameters.h.
Referenced by GD::save_load_online_state(), GD::set_learn(), and GD::setup().
sparse
bool parameters::sparse
Definition at line 232 of file array_parameters.h.
Referenced by accumulate(), accumulate_avg(), accumulate_weighted_avg(), add_regularization(), audit_regressor(), bfgs_iter_middle(), bfgs_iter_start(), compute_coherence_metrics(), derivative_in_direction(), direction_magnitude(), end_examples(), finalize_preconditioner(), GD::foreach_feature(), INTERACTIONS::generate_interactions(), get_top_weights(), init_driver(), initialize_regressor(), GD::inline_predict(), mf_predict(), mf_train(), multipredict(), GD::multipredict(), parse_args(), preconditioner_to_regularizer(), regularizer_direction_magnitude(), regularizer_to_weight(), sanity_check_state(), save_load(), GD::save_load(), GD::save_load_online_state(), GD::save_load_regressor(), GD::sync_weights(), update_weight(), and wolfe_eval().
sparse_weights
sparse_parameters parameters::sparse_weights
Definition at line 234 of file array_parameters.h.
Referenced by accumulate(), accumulate_avg(), accumulate_weighted_avg(), add_regularization(), audit_regressor(), bfgs_iter_middle(), bfgs_iter_start(), compute_coherence_metrics(), derivative_in_direction(), direction_magnitude(), end_examples(), finalize_preconditioner(), GD::foreach_feature(), INTERACTIONS::generate_interactions(), get_top_weights(), init_driver(), initialize_regressor(), GD::inline_predict(), mf_predict(), mf_train(), multipredict(), GD::multipredict(), preconditioner_to_regularizer(), regularizer_direction_magnitude(), regularizer_to_weight(), sanity_check_state(), save_load(), GD::save_load(), GD::save_load_online_state(), GD::save_load_regressor(), shallow_copy(), GD::sync_weights(), update_weight(), and wolfe_eval().
The documentation for this class was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/array_parameters.h