Vowpal Wabbit: VW::topk Class Reference
VW::topk Class Reference
Public Types
using const_iterator_t = container_t::const_iterator
Public Member Functions
topk (uint32_t k_num)
void predict (LEARNER::single_learner &base, multi_ex &ec_seq)
void learn (LEARNER::single_learner &base, multi_ex &ec_seq)
std::pair< const_iterator_t, const_iterator_t > get_container_view ()
void clear_container ()
Private Types
using container_t = std::multimap< float, v_array< char > >
Private Member Functions
void update_priority_queue (float pred, v_array< char > &tag)
Private Attributes
const uint32_t _k_num
container_t _pr_queue
Detailed Description
Definition at line 20 of file topk.cc.
Member Typedef Documentation
const_iterator_t
using VW::topk::const_iterator_t = container_t::const_iterator
Definition at line 25 of file topk.cc.
container_t
using VW::topk::container_t = std::multimap<float, v_array<char> > private
Definition at line 22 of file topk.cc.
Constructor & Destructor Documentation
topk()
VW::topk::topk (uint32_t k_num)
Definition at line 41 of file topk.cc.
 : _k_num(k_num) {}
Member Function Documentation
clear_container()
void VW::topk::clear_container ()
Definition at line 79 of file topk.cc.
References _pr_queue.
Referenced by finish_example().
 { _pr_queue.clear(); }
get_container_view()
std::pair< VW::topk::const_iterator_t, VW::topk::const_iterator_t > VW::topk::get_container_view ()
Definition at line 74 of file topk.cc.
References _pr_queue.
Referenced by finish_example().
 {
   return {_pr_queue.cbegin(), _pr_queue.cend()};
 }
learn()
void VW::topk::learn (LEARNER::single_learner & base, multi_ex & ec_seq)
Definition at line 52 of file topk.cc.
References LEARNER::learner< T, E >::learn(), and update_priority_queue().
Referenced by predict_or_learn().
 {
   for (auto ec : ec_seq)
   {
     base.learn(*ec);
     update_priority_queue(ec->pred.scalar, ec->tag);
   }
 }
predict()
void VW::topk::predict (LEARNER::single_learner & base, multi_ex & ec_seq)
Definition at line 43 of file topk.cc.
References LEARNER::learner< T, E >::predict(), and update_priority_queue().
Referenced by predict_or_learn().
 {
   for (auto ec : ec_seq)
   {
     base.predict(*ec);
     update_priority_queue(ec->pred.scalar, ec->tag);
   }
 }
update_priority_queue()
void VW::topk::update_priority_queue (float pred, v_array< char > & tag) private
Definition at line 61 of file topk.cc.
References _k_num, and _pr_queue.
Referenced by learn(), and predict().
 {
   if (_pr_queue.size() < _k_num)
   {
     _pr_queue.insert({pred, tag});
   }
   else if (_pr_queue.begin()->first < pred)
   {
     _pr_queue.erase(_pr_queue.begin());
     _pr_queue.insert({pred, tag});
   }
 }
Member Data Documentation
_k_num
const uint32_t VW::topk::_k_num private
Definition at line 36 of file topk.cc.
Referenced by update_priority_queue().
_pr_queue
container_t VW::topk::_pr_queue private
Definition at line 37 of file topk.cc.
Referenced by clear_container(), get_container_view(), and update_priority_queue().
The documentation for this class was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/topk.cc