Vowpal Wabbit: VW::vw_exception Class Reference
VW::vw_exception Class Reference
#include <vw_exception.h>
Public Member Functions
vw_exception (const char *file, int lineNumber, std::string const &message) noexcept
vw_exception (const vw_exception &ex) noexcept
vw_exception & operator= (const vw_exception &other) noexcept
~vw_exception () noexcept override
const char * what () const noexcept override
const char * Filename () const
int LineNumber () const
Private Attributes
const char * file
std::string message
int lineNumber
Detailed Description
Definition at line 22 of file vw_exception.h.
Constructor & Destructor Documentation
vw_exception() [1/2]
VW::vw_exception::vw_exception (const char * file, int lineNumber, std::string const & message) noexcept
Definition at line 10 of file vw_exception.cc.
     : file(pfile), message(pmessage), lineNumber(plineNumber)
 {
 }
vw_exception() [2/2]
VW::vw_exception::vw_exception (const vw_exception & ex) noexcept
Definition at line 15 of file vw_exception.cc.
     : file(ex.file), message(ex.message), lineNumber(ex.lineNumber)
 {
 }
~vw_exception()
VW::vw_exception::~vw_exception () override default noexcept
Referenced by operator=().
Member Function Documentation
Filename()
const char * VW::vw_exception::Filename () const
Definition at line 37 of file vw_exception.cc.
References file.
Referenced by main(), and parse_dispatch().
 { return file; }
LineNumber()
int VW::vw_exception::LineNumber () const
Definition at line 39 of file vw_exception.cc.
References lineNumber, sprintf_s, THROW, and vsprintf_s.
Referenced by main(), and parse_dispatch().
 { return lineNumber; }
operator=()
vw_exception & VW::vw_exception::operator= (const vw_exception & other) noexcept
Definition at line 20 of file vw_exception.cc.
References file, and ~vw_exception().
Referenced by VW::vw_argument_disagreement_exception::operator=(), VW::vw_argument_invalid_value_exception::operator=(), VW::vw_unrecognised_option_exception::operator=(), and VW::strict_parse_exception::operator=().
 {
   // check for self-assignment
   if (&other == this)
     return *this;
   file = other.file;
   message = other.message;
   lineNumber = other.lineNumber;
   return *this;
 }
what()
const char * VW::vw_exception::what () const override noexcept
Definition at line 35 of file vw_exception.cc.
References message.
Referenced by VW::config::options_boost_po::add_and_parse(), main(), and parse_dispatch().
 { return message.c_str(); }
Member Data Documentation
file
const char* VW::vw_exception::file private
Definition at line 26 of file vw_exception.h.
Referenced by Filename(), and operator=().
lineNumber
int VW::vw_exception::lineNumber private
Definition at line 31 of file vw_exception.h.
Referenced by LineNumber().
message
std::string VW::vw_exception::message private
Definition at line 28 of file vw_exception.h.
Referenced by what().
The documentation for this class was generated from the following files:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/vw_exception.h
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/vw_exception.cc