Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/explore_eval.cc File Reference
explore_eval.cc File Reference
#include "reductions.h"
#include "cb_algs.h"
#include "vw.h"
#include "cb_adf.h"
#include "rand48.h"
#include "gen_cs_example.h"
#include <memory>
Classes
struct EXPLORE_EVAL::explore_eval
Namespaces
EXPLORE_EVAL
Functions
void EXPLORE_EVAL::finish (explore_eval &data)
void EXPLORE_EVAL::output_example (vw &all, explore_eval &c, example &ec, multi_ex *ec_seq)
void EXPLORE_EVAL::output_example_seq (vw &all, explore_eval &data, multi_ex &ec_seq)
void EXPLORE_EVAL::finish_multiline_example (vw &all, explore_eval &data, multi_ex &ec_seq)
template<bool is_learn>
void EXPLORE_EVAL::do_actual_learning (explore_eval &data, multi_learner &base, multi_ex &ec_seq)
base_learner * explore_eval_setup (options_i &options, vw &all)
Function Documentation
explore_eval_setup()
base_learner* explore_eval_setup (options_i & options, vw & all)
Definition at line 186 of file explore_eval.cc.
References prediction_type::action_probs, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), label_type::cb, CB::cb_label, vw::delete_prediction, EXPLORE_EVAL::finish(), finish_multiline_example(), vw::get_random_state(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<explore_eval>();
   bool explore_eval_option = false;
   option_group_definition new_options("Explore evaluation");
   new_options.add(make_option("explore_eval", explore_eval_option).keep().help("Evaluate explore_eval adf policies"))
       .add(make_option("multiplier", data->multiplier)
                .help("Multiplier used to make all rejection sample probabilities <= 1"));
   options.add_and_parse(new_options);
   if (!explore_eval_option)
     return nullptr;
   data->all = &all;
   data->_random_state = all.get_random_state();
   if (options.was_supplied("multiplier"))
     data->fixed_multiplier = true;
   else
     data->multiplier = 1;
   if (!options.was_supplied("cb_explore_adf"))
     options.insert("cb_explore_adf", "");
   all.delete_prediction = nullptr;
   multi_learner* base = as_multiline(setup_base(options, all));
   all.p->lp = CB::cb_label;
   all.label_type = label_type::cb;
   learner<explore_eval, multi_ex>& l =
       init_learner(data, base, do_actual_learning<true>, do_actual_learning<false>, 1, prediction_type::action_probs);
   l.set_finish_example(finish_multiline_example);
   l.set_finish(finish);
   return make_base(l);
 }