Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/hashstring.h File Reference
hashstring.h File Reference
#include <cstdint>
#include "hash.h"
#include "future_compat.h"
Classes
struct substring
Functions
VW_STD14_CONSTEXPR uint64_t hashall (substring s, uint64_t h)
VW_STD14_CONSTEXPR uint64_t hashstring (substring s, uint64_t h)
Function Documentation
hashall()
VW_STD14_CONSTEXPR uint64_t hashall (substring s, uint64_t h) inline
Definition at line 13 of file hashstring.h.
References substring::begin, substring::end, and uniform_hash().
Referenced by getHasher().
 {
   return uniform_hash((unsigned char*)s.begin, s.end - s.begin, h);
 }
hashstring()
VW_STD14_CONSTEXPR uint64_t hashstring (substring s, uint64_t h) inline
Definition at line 18 of file hashstring.h.
References substring::begin, substring::end, and uniform_hash().
Referenced by vw_slim::example_predict_builder::example_predict_builder(), getHasher(), TC_parser< audit >::maybeFeature(), CB::parse_label(), COST_SENSITIVE::parse_label(), CB_EVAL::parse_label(), and vw_slim::example_predict_builder::push_feature_string().
 {
   // trim leading whitespace but not UTF-8
   for (; s.begin < s.end && *(s.begin) <= 0x20 && (int)*(s.begin) >= 0; s.begin++)
     ;
   // trim trailing white space but not UTF-8
   for (; s.end > s.begin && *(s.end - 1) <= 0x20 && (int)*(s.end - 1) >= 0; s.end--)
     ;
   size_t ret = 0;
   char* p = s.begin;
   while (p != s.end)
     if (*p >= '0' && *p <= '9')
       ret = 10 * ret + *(p++) - '0';
     else
       return uniform_hash((unsigned char*)s.begin, s.end - s.begin, h);
   return ret + h;
 }