Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/loss_functions.cc File Reference
loss_functions.cc File Reference
#include <math.h>
#include "correctedMath.h"
#include <iostream>
#include <stdlib.h>
#include <float.h>
#include "global_data.h"
#include "vw_exception.h"
Classes
class squaredloss
class classic_squaredloss
class hingeloss
class logloss
class quantileloss
class poisson_loss
Functions
loss_function * getLossFunction (vw &all, std::string funcName, float function_parameter)
Function Documentation
getLossFunction()
loss_function* getLossFunction (vw & all, std::string funcName, float function_parameter)
Definition at line 363 of file loss_functions.cc.
References shared_data::max_label, shared_data::min_label, noop_mm(), vw::sd, vw::set_minmax, and THROW.
Referenced by kernel_svm_setup(), log_multi_setup(), nn_setup(), parse_example_tweaks(), and loss_function::~loss_function().
 {
   if (funcName.compare("squared") == 0 || funcName.compare("Huber") == 0)
     return new squaredloss();
   else if (funcName.compare("classic") == 0)
     return new classic_squaredloss();
   else if (funcName.compare("hinge") == 0)
     return new hingeloss();
   else if (funcName.compare("logistic") == 0)
   {
     if (all.set_minmax != noop_mm)
     {
       all.sd->min_label = -50;
       all.sd->max_label = 50;
     }
     return new logloss();
   }
   else if (funcName.compare("quantile") == 0 || funcName.compare("pinball") == 0 || funcName.compare("absolute") == 0)
   {
     return new quantileloss(function_parameter);
   }
   else if (funcName.compare("poisson") == 0)
   {
     if (all.set_minmax != noop_mm)
     {
       all.sd->min_label = -50;
       all.sd->max_label = 50;
     }
     return new poisson_loss();
   }
   else
     THROW("Invalid loss function name: \'" << funcName << "\' Bailing!");
 }