Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/memory.h File Reference
memory.h File Reference
#include <cstdlib>
#include <cstdio>
#include <iostream>
#include <memory>
#include "vw_exception.h"
Macros
#define calloc_mergable_or_throw calloc_or_throw
Typedefs
using free_fn = void(*)(void *)
template<class T >
using free_ptr = std::unique_ptr< T, free_fn >
Functions
template<class T >
T * calloc_or_throw (size_t nmemb)
template<class T >
T & calloc_or_throw ()
template<class T >
void destroy_free (void *temp)
template<class T , typename... Args>
free_ptr< T > scoped_calloc_or_throw (Args &&... args)
void free_it (void *ptr)
Macro Definition Documentation
calloc_mergable_or_throw
#define calloc_mergable_or_throw calloc_or_throw
Definition at line 91 of file memory.h.
Referenced by scoped_calloc_or_throw().
Typedef Documentation
free_fn
using free_fn = void (*)(void*)
Definition at line 31 of file memory.h.
free_ptr
template<class T > using free_ptr = std::unique_ptr<T, free_fn>
Definition at line 34 of file memory.h.
Function Documentation
calloc_or_throw() [1/2]
template<class T > T* calloc_or_throw (size_t nmemb)
Definition at line 9 of file memory.h.
References THROW_OR_RETURN.
 {
   if (nmemb == 0)
     return nullptr;
   void* data = calloc(nmemb, sizeof(T));
   if (data == nullptr)
   {
     const char* msg = "internal error: memory allocation failed!\n";
     // use low-level function since we're already out of memory.
     fputs(msg, stderr);
     THROW_OR_RETURN(msg, nullptr);
   }
   return (T*)data;
 }
calloc_or_throw() [2/2]
template<class T > T& calloc_or_throw ()
Definition at line 26 of file memory.h.
 {
   return *calloc_or_throw<T>(1);
 }
destroy_free()
template<class T > void destroy_free (void * temp)
Definition at line 37 of file memory.h.
 {
   ((T*)temp)->~T();
   free(temp);
 }
free_it()
void free_it (void * ptr) inline
Definition at line 94 of file memory.h.
Referenced by deleter(), VW::finish(), free_svm_model(), VW::return_features(), VW::seed_vw_model(), cbify::~cbify(), and warm_cb::~warm_cb().
 {
   if (ptr != nullptr)
     free(ptr);
 }
scoped_calloc_or_throw()
template<class T , typename... Args> free_ptr<T> scoped_calloc_or_throw (Args &&... args)
Definition at line 44 of file memory.h.
References calloc_mergable_or_throw, and THROW.
 {
   T* temp = calloc_or_throw<T>(1);
   new (temp) T(std::forward<Args>(args)...);
   return std::unique_ptr<T, free_fn>(temp, destroy_free<T>);
 }