Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/multilabel_oaa.cc File Reference
multilabel_oaa.cc File Reference
#include <sstream>
#include <float.h>
#include "reductions.h"
#include "vw.h"
Classes
struct multi_oaa
Functions
template<bool is_learn>
void predict_or_learn (multi_oaa &o, LEARNER::single_learner &base, example &ec)
void finish_example (vw &all, multi_oaa &, example &ec)
LEARNER::base_learner * multilabel_oaa_setup (options_i &options, vw &all)
Function Documentation
finish_example()
void finish_example (vw & all, multi_oaa & , example & ec)
Definition at line 52 of file multilabel_oaa.cc.
References VW::finish_example(), and MULTILABEL::output_example().
 {
   MULTILABEL::output_example(all, ec);
   VW::finish_example(all, ec);
 }
multilabel_oaa_setup()
LEARNER::base_learner* multilabel_oaa_setup (options_i & options, vw & all)
Definition at line 58 of file multilabel_oaa.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), label_parser::delete_label, vw::delete_prediction, VW::finish_example(), LEARNER::init_learner(), vw::label_type, parser::lp, LEARNER::make_base(), VW::config::make_option(), label_type::multi, MULTILABEL::multilabel, prediction_type::multilabels, vw::p, LEARNER::learner< T, E >::set_finish_example(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<multi_oaa>();
   option_group_definition new_options("Multilabel One Against All");
   new_options.add(make_option("multilabel_oaa", data->k).keep().help("One-against-all multilabel with <k> labels"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("multilabel_oaa"))
     return nullptr;
   LEARNER::learner<multi_oaa, example>& l = LEARNER::init_learner(data, as_singleline(setup_base(options, all)),
       predict_or_learn<true>, predict_or_learn<false>, data->k, prediction_type::multilabels);
   l.set_finish_example(finish_example);
   all.p->lp = MULTILABEL::multilabel;
   all.label_type = label_type::multi;
   all.delete_prediction = MULTILABEL::multilabel.delete_label;
   return make_base(l);
 }
predict_or_learn()
template<bool is_learn> void predict_or_learn (multi_oaa & o, LEARNER::single_learner & base, example & ec)
Definition at line 19 of file multilabel_oaa.cc.
References v_array< T >::clear(), multi_oaa::k, example::l, label_data::label, MULTILABEL::labels::label_v, LEARNER::learner< T, E >::learn(), prediction_type::multilabels, polylabel::multilabels, polyprediction::multilabels, example::pred, LEARNER::learner< T, E >::predict(), v_array< T >::push_back(), polyprediction::scalar, polylabel::simple, and v_array< T >::size().
 {
   MULTILABEL::labels multilabels = ec.l.multilabels;
   MULTILABEL::labels preds = ec.pred.multilabels;
   preds.label_v.clear();
   ec.l.simple = {FLT_MAX, 1.f, 0.f};
   uint32_t multilabel_index = 0;
   for (uint32_t i = 0; i < o.k; i++)
   {
     if (is_learn)
     {
       ec.l.simple.label = -1.f;
       if (multilabels.label_v.size() > multilabel_index && multilabels.label_v[multilabel_index] == i)
       {
         ec.l.simple.label = 1.f;
         multilabel_index++;
       }
       base.learn(ec, i);
     }
     else
       base.predict(ec, i);
     if (ec.pred.scalar > 0.)
       preds.label_v.push_back(i);
   }
   if (is_learn && multilabel_index < multilabels.label_v.size())
     std::cout << "label " << multilabels.label_v[multilabel_index] << " is not in {0," << o.k - 1
               << "} This won't work right." << std::endl;
   ec.pred.multilabels = preds;
   ec.l.multilabels = multilabels;
 }