Vowpal Wabbit: MULTICLASS Namespace Reference
MULTICLASS Namespace Reference
Classes
struct label_t
Functions
char * bufread_label (label_t *ld, char *c)
size_t read_cached_label (shared_data *, void *v, io_buf &cache)
float weight (void *v)
char * bufcache_label (label_t *ld, char *c)
void cache_label (void *v, io_buf &cache)
void default_label (void *v)
bool test_label (void *v)
void delete_label (void *)
void parse_label (parser *, shared_data *sd, void *v, v_array< substring > &words)
void print_label_pred (vw &all, example &ec, uint32_t prediction)
void print_probability (vw &all, example &ec, uint32_t prediction)
void print_score (vw &all, example &ec, uint32_t prediction)
void direct_print_update (vw &all, example &ec, uint32_t prediction)
template<void(*)(vw &, example &, uint32_t) T>
void print_update (vw &all, example &ec, uint32_t prediction)
void print_update_with_probability (vw &all, example &ec, uint32_t pred)
void print_update_with_score (vw &all, example &ec, uint32_t pred)
void finish_example (vw &all, example &ec, bool update_loss)
template<class T >
void finish_example (vw &all, T &, example &ec)
template<class T >
void finish_example_without_loss (vw &all, T &, example &ec)
Variables
label_parser mc_label
Function Documentation
bufcache_label()
char* MULTICLASS::bufcache_label (label_t * ld, char * c)
Definition at line 36 of file multiclass.cc.
References c, MULTICLASS::label_t::label, and MULTICLASS::label_t::weight.
Referenced by cache_label().
 {
   memcpy(c, &ld->label, sizeof(ld->label));
   c += sizeof(ld->label);
   memcpy(c, &ld->weight, sizeof(ld->weight));
   c += sizeof(ld->weight);
   return c;
 }
bufread_label()
char* MULTICLASS::bufread_label (label_t * ld, char * c)
Definition at line 9 of file multiclass.cc.
References c, MULTICLASS::label_t::label, and MULTICLASS::label_t::weight.
Referenced by read_cached_label().
 {
   memcpy(&ld->label, c, sizeof(ld->label));
   c += sizeof(ld->label);
   memcpy(&ld->weight, c, sizeof(ld->weight));
   c += sizeof(ld->weight);
   return c;
 }
cache_label()
void MULTICLASS::cache_label (void * v, io_buf & cache)
Definition at line 45 of file multiclass.cc.
References io_buf::buf_write(), bufcache_label(), c, MULTICLASS::label_t::label, and MULTICLASS::label_t::weight.
 {
   char* c;
   label_t* ld = (label_t*)v;
   cache.buf_write(c, sizeof(ld->label) + sizeof(ld->weight));
   bufcache_label(ld, c);
 }
default_label()
void MULTICLASS::default_label (void * v)
Definition at line 53 of file multiclass.cc.
References MULTICLASS::label_t::label, and MULTICLASS::label_t::weight.
 {
   label_t* ld = (label_t*)v;
   ld->label = (uint32_t)-1;
   ld->weight = 1.;
 }
delete_label()
void MULTICLASS::delete_label (void *)
Definition at line 66 of file multiclass.cc.
 {}
direct_print_update()
void MULTICLASS::direct_print_update (vw & all, example & ec, uint32_t prediction)
Definition at line 131 of file multiclass.cc.
References vw::current_pass, vw::holdout_set_off, example::l, MULTICLASS::label_t::label, polylabel::multi, example::num_features, shared_data::print_update(), vw::progress_add, vw::progress_arg, and vw::sd.
 {
   all.sd->print_update(all.holdout_set_off, all.current_pass, ec.l.multi.label, prediction, ec.num_features,
       all.progress_add, all.progress_arg);
 }
finish_example() [1/2]
template<class T > void MULTICLASS::finish_example (vw & all, T & , example & ec)
Definition at line 28 of file multiclass.h.
References finish_example().
 {
   finish_example(all, ec, true);
 }
finish_example() [2/2]
void MULTICLASS::finish_example (vw & all, example & ec, bool update_loss)
Definition at line 155 of file multiclass.cc.
References substring::begin, substring::end, vw::final_prediction_sink, VW::finish_example(), namedlabels::get(), example::l, MULTICLASS::label_t::label, shared_data::ldict, loss(), polylabel::multi, polyprediction::multiclass, example::num_features, example::pred, vw::print, vw::print_text, vw::sd, example::tag, example::test_only, shared_data::update(), and example::weight.
Referenced by finish_example(), and finish_example_without_loss().
 {
   float loss = 0;
   if (ec.l.multi.label != (uint32_t)ec.pred.multiclass && ec.l.multi.label != (uint32_t)-1)
     loss = ec.weight;
   all.sd->update(ec.test_only, update_loss && (ec.l.multi.label != (uint32_t)-1), loss, ec.weight, ec.num_features);
   for (int sink : all.final_prediction_sink)
     if (!all.sd->ldict)
       all.print(sink, (float)ec.pred.multiclass, 0, ec.tag);
     else
     {
       substring ss_pred = all.sd->ldict->get(ec.pred.multiclass);
       all.print_text(sink, std::string(ss_pred.begin, ss_pred.end - ss_pred.begin), ec.tag);
     }
   MULTICLASS::print_update<direct_print_update>(all, ec, ec.pred.multiclass);
   VW::finish_example(all, ec);
 }
finish_example_without_loss()
template<class T > void MULTICLASS::finish_example_without_loss (vw & all, T & , example & ec)
Definition at line 34 of file multiclass.h.
References finish_example().
 {
   finish_example(all, ec, false);
 }
parse_label()
void MULTICLASS::parse_label (parser * , shared_data * sd, void * v, v_array< substring > & words)
Definition at line 68 of file multiclass.cc.
References float_of_substring(), namedlabels::get(), int_of_substring(), MULTICLASS::label_t::label, shared_data::ldict, v_array< T >::size(), THROW, and MULTICLASS::label_t::weight.
 {
   label_t* ld = (label_t*)v;
   switch (words.size())
   {
     case 0:
       break;
     case 1:
       ld->label = sd->ldict ? (uint32_t)sd->ldict->get(words[0]) : int_of_substring(words[0]);
       ld->weight = 1.0;
       break;
     case 2:
       ld->label = sd->ldict ? (uint32_t)sd->ldict->get(words[0]) : int_of_substring(words[0]);
       ld->weight = float_of_substring(words[1]);
       break;
     default:
       std::cerr << "malformed example!\n";
       std::cerr << "words.size() = " << words.size() << std::endl;
   }
   if (ld->label == 0)
     THROW("label 0 is not allowed for multiclass.  Valid labels are {1,k}"
         << (sd->ldict ? "\nthis likely happened because you specified an invalid label with named labels" : ""));
 }
print_label_pred()
void MULTICLASS::print_label_pred (vw & all, example & ec, uint32_t prediction)
Definition at line 96 of file multiclass.cc.
References substring::begin, vw::current_pass, substring::end, namedlabels::get(), vw::holdout_set_off, example::l, MULTICLASS::label_t::label, shared_data::ldict, polylabel::multi, example::num_features, shared_data::print_update(), vw::progress_add, vw::progress_arg, and vw::sd.
Referenced by print_update().
 {
   substring ss_label = all.sd->ldict->get(ec.l.multi.label);
   substring ss_pred = all.sd->ldict->get(prediction);
   all.sd->print_update(all.holdout_set_off, all.current_pass,
       !ss_label.begin ? "unknown" : std::string(ss_label.begin, ss_label.end - ss_label.begin),
       !ss_pred.begin ? "unknown" : std::string(ss_pred.begin, ss_pred.end - ss_pred.begin), ec.num_features,
       all.progress_add, all.progress_arg);
 }
print_probability()
void MULTICLASS::print_probability (vw & all, example & ec, uint32_t prediction)
Definition at line 106 of file multiclass.cc.
References vw::current_pass, vw::holdout_set_off, example::l, MULTICLASS::label_t::label, polylabel::multi, example::num_features, example::pred, shared_data::print_update(), vw::progress_add, vw::progress_arg, polyprediction::scalars, and vw::sd.
 {
   std::stringstream pred_ss;
   pred_ss << prediction << "(" << std::setw(2) << std::setprecision(0) << std::fixed
           << 100 * ec.pred.scalars[prediction - 1] << "%)";
   std::stringstream label_ss;
   label_ss << ec.l.multi.label;
   all.sd->print_update(all.holdout_set_off, all.current_pass, label_ss.str(), pred_ss.str(), ec.num_features,
       all.progress_add, all.progress_arg);
 }
print_score()
void MULTICLASS::print_score (vw & all, example & ec, uint32_t prediction)
Definition at line 119 of file multiclass.cc.
References vw::current_pass, vw::holdout_set_off, example::l, MULTICLASS::label_t::label, polylabel::multi, example::num_features, shared_data::print_update(), vw::progress_add, vw::progress_arg, and vw::sd.
 {
   std::stringstream pred_ss;
   pred_ss << prediction;
   std::stringstream label_ss;
   label_ss << ec.l.multi.label;
   all.sd->print_update(all.holdout_set_off, all.current_pass, label_ss.str(), pred_ss.str(), ec.num_features,
       all.progress_add, all.progress_arg);
 }
print_update()
template<void(*)(vw &, example &, uint32_t) T> void MULTICLASS::print_update (vw & all, example & ec, uint32_t prediction)
Definition at line 138 of file multiclass.cc.
References vw::bfgs, shared_data::dump_interval, shared_data::ldict, polyprediction::multiclass, example::pred, print_label_pred(), vw::quiet, vw::sd, and shared_data::weighted_examples().
 {
   if (all.sd->weighted_examples() >= all.sd->dump_interval && !all.quiet && !all.bfgs)
   {
     if (!all.sd->ldict)
       T(all, ec, prediction);
     else
       print_label_pred(all, ec, ec.pred.multiclass);
   }
 }
print_update_with_probability()
void MULTICLASS::print_update_with_probability (vw & all, example & ec, uint32_t pred)
Definition at line 149 of file multiclass.cc.
Referenced by finish_example_scores().
 {
   print_update<print_probability>(all, ec, pred);
 }
print_update_with_score()
void MULTICLASS::print_update_with_score (vw & all, example & ec, uint32_t pred)
Definition at line 153 of file multiclass.cc.
Referenced by finish_example_scores().
 { print_update<print_score>(all, ec, pred); }
read_cached_label()
size_t MULTICLASS::read_cached_label (shared_data * , void * v, io_buf & cache)
Definition at line 18 of file multiclass.cc.
References io_buf::buf_read(), bufread_label(), c, MULTICLASS::label_t::label, and MULTICLASS::label_t::weight.
 {
   label_t* ld = (label_t*)v;
   char* c;
   size_t total = sizeof(ld->label) + sizeof(ld->weight);
   if (cache.buf_read(c, total) < total)
     return 0;
   bufread_label(ld, c);
   return total;
 }
test_label()
bool MULTICLASS::test_label (void * v)
Definition at line 60 of file multiclass.cc.
References MULTICLASS::label_t::label.
 {
   label_t* ld = (label_t*)v;
   return ld->label == (uint32_t)-1;
 }
weight()
float MULTICLASS::weight (void * v)
Definition at line 30 of file multiclass.cc.
References MULTICLASS::label_t::weight.
 {
   label_t* ld = (label_t*)v;
   return (ld->weight > 0) ? ld->weight : 0.f;
 }
Variable Documentation
mc_label
label_parser MULTICLASS::mc_label
Initial value:
= {default_label, parse_label, cache_label, read_cached_label, delete_label, weight, nullptr,
    test_label, sizeof(label_t)}
Definition at line 93 of file multiclass.cc.
Referenced by add_to_vali(), LEARNER::init_multiclass_learner(), Search::mc_label_is_test(), Search::setup(), Search::train_single_example(), Search::search::~search(), and warm_cb::~warm_cb().