Vowpal Wabbit: CLASSWEIGHTS Namespace Reference
CLASSWEIGHTS Namespace Reference
Classes
struct classweights
Functions
template<bool is_learn, int pred_type>
static void predict_or_learn (classweights &cweights, LEARNER::single_learner &base, example &ec)
Function Documentation
predict_or_learn()
template<bool is_learn, int pred_type> static void CLASSWEIGHTS::predict_or_learn (classweights & cweights, LEARNER::single_learner & base, example & ec) static
Definition at line 47 of file classweight.cc.
References CLASSWEIGHTS::classweights::get_class_weight(), example::l, label_data::label, MULTICLASS::label_t::label, LEARNER::learner< T, E >::learn(), polylabel::multi, prediction_type::multiclass, LEARNER::learner< T, E >::predict(), prediction_type::scalar, polylabel::simple, and example::weight.
 {
   switch (pred_type)
   {
     case prediction_type::scalar:
       ec.weight *= cweights.get_class_weight((uint32_t)ec.l.simple.label);
       break;
     case prediction_type::multiclass:
       ec.weight *= cweights.get_class_weight(ec.l.multi.label);
       break;
     default:
       // suppress the warning
       break;
   }
   if (is_learn)
     base.learn(ec);
   else
     base.predict(ec);
 }