Vowpal Wabbit: VW::cb_explore_adf Namespace Reference
VW::cb_explore_adf Namespace Reference
Namespaces
bag
cover
first
greedy
regcb
softmax
Classes
struct cb_explore_adf_base
Functions
void sort_action_probs (v_array< ACTION_SCORE::action_score > &probs, const std::vector< float > &scores)
size_t fill_tied (v_array< ACTION_SCORE::action_score > &preds)
Function Documentation
fill_tied()
size_t VW::cb_explore_adf::fill_tied (v_array< ACTION_SCORE::action_score > & preds) inline
Definition at line 48 of file cb_explore_adf_common.h.
References v_array< T >::size().
Referenced by VW::cb_explore_adf::greedy::cb_explore_adf_greedy::predict_or_learn_impl(), VW::cb_explore_adf::bag::cb_explore_adf_bag::predict_or_learn_impl(), and VW::cb_explore_adf::cover::cb_explore_adf_cover::predict_or_learn_impl().
 {
   if (preds.size() == 0)
     return 0;
   size_t ret = 1;
   for (size_t i = 1; i < preds.size(); ++i)
     if (preds[i].score == preds[0].score)
       ++ret;
     else
       return ret;
   return ret;
 }
sort_action_probs()
void VW::cb_explore_adf::sort_action_probs (v_array< ACTION_SCORE::action_score > & probs, const std::vector< float > & scores) inline
Definition at line 29 of file cb_explore_adf_common.h.
References ACTION_SCORE::action_score::action, v_array< T >::begin(), v_array< T >::end(), and ACTION_SCORE::action_score::score.
Referenced by VW::cb_explore_adf::bag::cb_explore_adf_bag::predict_or_learn_impl(), and VW::cb_explore_adf::cover::cb_explore_adf_cover::predict_or_learn_impl().
 {
   // We want to preserve the score order in the returned action_probs if possible.  To do this,
   // sort top_actions and action_probs by the order induced in scores.
   std::sort(probs.begin(), probs.end(),
       [&scores](const ACTION_SCORE::action_score& as1, const ACTION_SCORE::action_score& as2) {
         if (as1.score > as2.score)
           return true;
         else if (as1.score < as2.score)
           return false;
         // equal probabilities
         if (scores[as1.action] < scores[as2.action])
           return true;
         else if (scores[as1.action] > scores[as2.action])
           return false;
         // equal probabilities and equal cost estimates
         return as1.action < as2.action;
       });
 }