Vowpal Wabbit: anonymous_namespace{lda_core.cc} Namespace Reference
anonymous_namespace{lda_core.cc} Namespace Reference
Functions
bool is_aligned16 (void *ptr)
Variables
v_array< float > new_gamma = v_init<float>()
v_array< float > old_gamma = v_init<float>()
Function Documentation
is_aligned16()
bool anonymous_namespace{lda_core.cc}::is_aligned16 (void * ptr) inline
Definition at line 115 of file lda_core.cc.
Referenced by ldamath::fastdigamma().
 {
 #if BOOST_VERSION >= 105600
   return boost::alignment::is_aligned(16, ptr);
 #else
   return ((reinterpret_cast<uintptr_t>(ptr) & 0x0f) == 0);
 #endif
 }
Variable Documentation
new_gamma
v_array<float> anonymous_namespace{lda_core.cc}::new_gamma = v_init<float>()
Definition at line 687 of file lda_core.cc.
Referenced by lda_loop().
old_gamma
v_array<float> anonymous_namespace{lda_core.cc}::old_gamma = v_init<float>()
Definition at line 688 of file lda_core.cc.
Referenced by lda_loop().