Vowpal Wabbit: SequenceTask Namespace Reference
SequenceTask Namespace Reference
Functions
void initialize (Search::search &sch, size_t &, options_i &)
void run (Search::search &sch, multi_ex &ec)
Variables
Search::search_task task = {"sequence", run, initialize, nullptr, nullptr, nullptr}
Function Documentation
initialize()
void SequenceTask::initialize (Search::search & sch, size_t & , options_i &)
Definition at line 34 of file search_sequencetask.cc.
References Search::AUTO_CONDITION_FEATURES, Search::AUTO_HAMMING_LOSS, Search::EXAMPLES_DONT_CHANGE, and Search::search::set_options().
 {
   sch.set_options(Search::AUTO_CONDITION_FEATURES |  // automatically add history features to our examples, please
       Search::AUTO_HAMMING_LOSS |     // please just use hamming loss on individual predictions -- we won't declare loss
       Search::EXAMPLES_DONT_CHANGE |  // we don't do any internal example munging
       0);
 }
run()
void SequenceTask::run (Search::search & sch, multi_ex & ec)
Definition at line 42 of file search_sequencetask.cc.
References Search::search::get_history_length(), Search::search::output(), predict(), Search::search::pretty_label(), Search::predictor::set_condition_range(), Search::predictor::set_input(), Search::predictor::set_oracle(), and Search::predictor::set_tag().
 {
   Search::predictor P(sch, (ptag)0);
   for (size_t i = 0; i < ec.size(); i++)
   {
     action oracle = ec[i]->l.multi.label;
     size_t prediction = P.set_tag((ptag)i + 1)
                             .set_input(*ec[i])
                             .set_oracle(oracle)
                             .set_condition_range((ptag)i, sch.get_history_length(), 'p')
                             .predict();
     if (sch.output().good())
       sch.output() << sch.pretty_label((uint32_t)prediction) << ' ';
   }
 }
Variable Documentation
task
Search::search_task SequenceTask::task = {"sequence", run, initialize, nullptr, nullptr, nullptr}
Definition at line 13 of file search_sequencetask.cc.