Vowpal Wabbit: VW::LEARNER Namespace Reference
VW::LEARNER Namespace Reference
Classes
struct finish_example_data
struct func_data
struct learn_data
struct learner
struct save_load_data
struct sensitivity_data
Typedefs
using base_learner = learner< char, char >
using single_learner = learner< char, example >
using multi_learner = learner< char, multi_ex >
Functions
func_data tuple_dbf (void *data, base_learner *base, void(*func)(void *))
void generic_driver (vw &all)
void generic_driver (const std::vector< vw *> &alls)
void generic_driver_onethread (vw &all)
void noop_sl (void *, io_buf &, bool, bool)
void noop (void *)
float noop_sensitivity (void *, base_learner &, example &)
float recur_sensitivity (void *, base_learner &, example &)
void increment_offset (example &ex, const size_t increment, const size_t i)
void increment_offset (multi_ex &ec_seq, const size_t increment, const size_t i)
void decrement_offset (example &ex, const size_t increment, const size_t i)
void decrement_offset (multi_ex &ec_seq, const size_t increment, const size_t i)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws, prediction_type_t pred_type)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t params_per_weight)
template<class T , class E , class L >
learner< T, E > & init_learner (void(*predict)(T &, L &, E &), size_t params_per_weight)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t params_per_weight, prediction_type_t pred_type)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &))
template<class T , class E , class L >
learner< T, E > & init_learner (L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &))
template<class T , class E , class L >
learner< T, E > & init_multiclass_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), parser *p, size_t ws, prediction_type_t pred_type=prediction_type_t::multiclass)
template<class T , class E , class L >
learner< T, E > & init_cost_sensitive_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), parser *p, size_t ws, prediction_type_t pred_type=prediction_type_t::multiclass)
template<class T , class E >
base_learner * make_base (learner< T, E > &base)
template<class T , class E >
multi_learner * as_multiline (learner< T, E > *l)
template<class T , class E >
single_learner * as_singleline (learner< T, E > *l)
template<bool is_learn>
void multiline_learn_or_predict (multi_learner &base, multi_ex &examples, const uint64_t offset, const uint32_t id=0)
Typedef Documentation
base_learner
typedef learner< char, char > VW::LEARNER::base_learner
Definition at line 37 of file learner.h.
multi_learner
typedef learner< char, multi_ex > VW::LEARNER::multi_learner
Definition at line 39 of file learner.h.
single_learner
typedef learner< char, example > VW::LEARNER::single_learner
Definition at line 38 of file learner.h.
Function Documentation
as_multiline()
template<class T , class E > multi_learner* VW::LEARNER::as_multiline (learner< T, E > * l)
Definition at line 466 of file learner.h.
References VW::LEARNER::learner< T, E >::is_multiline, and THROW.
 {
   if (l->is_multiline)  // Tried to use a singleline reduction as a multiline reduction
     return (multi_learner*)(l);
   THROW("Tried to use a singleline reduction as a multiline reduction");
 }
as_singleline()
template<class T , class E > single_learner* VW::LEARNER::as_singleline (learner< T, E > * l)
Definition at line 474 of file learner.h.
References VW::LEARNER::learner< T, E >::is_multiline, and THROW.
Referenced by ExpReplay::expreplay_setup().
 {
   if (!l->is_multiline)  // Tried to use a multiline reduction as a singleline reduction
     return (single_learner*)(l);
   THROW("Tried to use a multiline reduction as a singleline reduction");
 }
decrement_offset() [1/2]
void VW::LEARNER::decrement_offset (example & ex, const size_t increment, const size_t i) inline
Definition at line 118 of file learner.h.
References example_predict::ft_offset.
 {
   assert(ex.ft_offset >= increment * i);
   ex.ft_offset -= static_cast<uint32_t>(increment * i);
 }
decrement_offset() [2/2]
void VW::LEARNER::decrement_offset (multi_ex & ec_seq, const size_t increment, const size_t i) inline
Definition at line 124 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::learn(), VW::LEARNER::learner< T, E >::multipredict(), VW::LEARNER::learner< T, E >::predict(), VW::LEARNER::learner< T, E >::sensitivity(), and VW::LEARNER::learner< T, E >::update().
 {
   for (auto ec : ec_seq)
   {
     assert(ec->ft_offset >= increment * i);
     ec->ft_offset -= static_cast<uint32_t>(increment * i);
   }
 }
generic_driver() [1/2]
void VW::LEARNER::generic_driver (vw & all)
generic_driver() [2/2]
void VW::LEARNER::generic_driver (const std::vector< vw *> & alls)
generic_driver_onethread()
void VW::LEARNER::generic_driver_onethread (vw & all)
increment_offset() [1/2]
void VW::LEARNER::increment_offset (example & ex, const size_t increment, const size_t i) inline
Definition at line 108 of file learner.h.
References example_predict::ft_offset.
 {
   ex.ft_offset += static_cast<uint32_t>(increment * i);
 }
increment_offset() [2/2]
void VW::LEARNER::increment_offset (multi_ex & ec_seq, const size_t increment, const size_t i) inline
Definition at line 113 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::learn(), VW::LEARNER::learner< T, E >::multipredict(), VW::LEARNER::learner< T, E >::predict(), VW::LEARNER::learner< T, E >::sensitivity(), and VW::LEARNER::learner< T, E >::update().
 {
   for (auto ec : ec_seq) ec->ft_offset += static_cast<uint32_t>(increment * i);
 }
init_cost_sensitive_learner()
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_cost_sensitive_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, parser * p, size_t ws, prediction_type_t pred_type = prediction_type_t::multiclass)
Definition at line 448 of file learner.h.
References COST_SENSITIVE::cs_label, COST_SENSITIVE::finish_example(), init_learner(), parser::lp, and VW::LEARNER::learner< T, E >::set_finish_example().
 {
   learner<T, E>& l = learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, pred_type);
   dat.release();
   l.set_finish_example(COST_SENSITIVE::finish_example);
   p->lp = COST_SENSITIVE::cs_label;
   return l;
 }
init_learner() [1/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t ws, prediction_type_t pred_type)
Definition at line 367 of file learner.h.
References init_learner().
Referenced by ExpReplay::expreplay_setup().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, pred_type);
   dat.release();
   return *ret;
 }
init_learner() [2/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (free_ptr< T > & dat, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t params_per_weight)
Definition at line 378 of file learner.h.
References init_learner(), and scalar.
 {
   auto ret =
       &learner<T, E>::init_learner(dat.get(), (L*)nullptr, learn, predict, params_per_weight, prediction_type_t::scalar);
   dat.release();
   return *ret;
 }
init_learner() [3/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (void(*)(T &, L &, E &) predict, size_t params_per_weight)
Definition at line 390 of file learner.h.
References init_learner(), and scalar.
 {
   return learner<T, E>::init_learner(
       nullptr, (L*)nullptr, predict, predict, params_per_weight, prediction_type_t::scalar);
 }
init_learner() [4/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (free_ptr< T > & dat, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t params_per_weight, prediction_type_t pred_type)
Definition at line 397 of file learner.h.
References init_learner().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), (L*)nullptr, learn, predict, params_per_weight, pred_type);
   dat.release();
   return *ret;
 }
init_learner() [5/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t ws)
Definition at line 407 of file learner.h.
References init_learner().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, base->pred_type);
   dat.release();
   return *ret;
 }
init_learner() [6/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict)
Definition at line 418 of file learner.h.
References init_learner().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), base, learn, predict, 1, base->pred_type);
   dat.release();
   return *ret;
 }
init_learner() [7/7]
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_learner (L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict)
Definition at line 428 of file learner.h.
Referenced by init_cost_sensitive_learner(), init_learner(), and init_multiclass_learner().
 {
   return learner<T, E>::init_learner(nullptr, base, learn, predict, 1, base->pred_type);
 }
init_multiclass_learner()
template<class T , class E , class L > learner<T, E>& VW::LEARNER::init_multiclass_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, parser * p, size_t ws, prediction_type_t pred_type = prediction_type_t::multiclass)
Definition at line 435 of file learner.h.
References init_learner(), parser::lp, MULTICLASS::mc_label, and VW::LEARNER::learner< T, E >::set_finish_example().
 {
   learner<T, E>& l = learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, pred_type);
   dat.release();
   l.set_finish_example(MULTICLASS::finish_example<T>);
   p->lp = MULTICLASS::mc_label;
   return l;
 }
make_base()
template<class T , class E > base_learner* VW::LEARNER::make_base (learner< T, E > & base)
Definition at line 460 of file learner.h.
Referenced by ExpReplay::expreplay_setup(), and VW::LEARNER::learner< T, E >::init_learner().
 {
   return (base_learner*)(&base);
 }
multiline_learn_or_predict()
template<bool is_learn> void VW::LEARNER::multiline_learn_or_predict (multi_learner & base, multi_ex & examples, const uint64_t offset, const uint32_t id = 0)
Definition at line 482 of file learner.h.
References VW::LEARNER::learner< T, E >::learn(), and VW::LEARNER::learner< T, E >::predict().
 {
   std::vector<uint64_t> saved_offsets;
   saved_offsets.reserve(examples.size());
   for (auto ec : examples)
   {
     saved_offsets.push_back(ec->ft_offset);
     ec->ft_offset = offset;
   }
   if (is_learn)
     base.learn(examples, id);
   else
     base.predict(examples, id);
   for (size_t i = 0; i < examples.size(); i++) examples[i]->ft_offset = saved_offsets[i];
 }
noop()
void VW::LEARNER::noop (void *) inline
Definition at line 100 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
 {}
noop_sensitivity()
float VW::LEARNER::noop_sensitivity (void * , base_learner & , example &) inline
Definition at line 101 of file learner.h.
References recur_sensitivity().
Referenced by VW::LEARNER::learner< T, E >::init_learner().
 {
   std::cout << std::endl;
   return 0.;
 }
noop_sl()
void VW::LEARNER::noop_sl (void * , io_buf & , bool , bool) inline
Definition at line 99 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
 {}
recur_sensitivity()
float VW::LEARNER::recur_sensitivity (void * , base_learner & , example &)
Referenced by noop_sensitivity().
tuple_dbf()
func_data VW::LEARNER::tuple_dbf (void * data, base_learner * base, void(*)(void *) func) inline
Definition at line 49 of file learner.h.
References VW::LEARNER::func_data::base, VW::LEARNER::func_data::data, and VW::LEARNER::func_data::func.
Referenced by VW::LEARNER::learner< T, E >::set_end_examples(), VW::LEARNER::learner< T, E >::set_end_pass(), VW::LEARNER::learner< T, E >::set_finish(), and VW::LEARNER::learner< T, E >::set_init_driver().
 {
   func_data foo;
   foo.data = data;
   foo.base = base;
   foo.func = func;
   return foo;
 }