Vowpal Wabbit: CB_EVAL Namespace Reference
CB_EVAL Namespace Reference
Classes
struct label
Functions
float weight (void *v)
size_t read_cached_label (shared_data *sd, void *v, io_buf &cache)
void cache_label (void *v, io_buf &cache)
void default_label (void *v)
bool test_label (void *v)
void delete_label (void *v)
void copy_label (void *dst, void *src)
void parse_label (parser *p, shared_data *sd, void *v, v_array< substring > &words)
Variables
label_parser cb_eval
Function Documentation
cache_label()
void CB_EVAL::cache_label (void * v, io_buf & cache)
Definition at line 239 of file cb.cc.
References CB_EVAL::label::action, io_buf::buf_write(), c, CB::cache_label(), and CB_EVAL::label::event.
 {
   char* c;
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   cache.buf_write(c, sizeof(uint32_t));
   *(uint32_t*)c = ld->action;
   CB::cache_label(&(ld->event), cache);
 }
copy_label()
void CB_EVAL::copy_label (void * dst, void * src)
Definition at line 268 of file cb.cc.
References CB_EVAL::label::action, CB::copy_label(), and CB_EVAL::label::event.
 {
   CB_EVAL::label* ldD = (CB_EVAL::label*)dst;
   CB_EVAL::label* ldS = (CB_EVAL::label*)src;
   CB::copy_label(&(ldD->event), &(ldS)->event);
   ldD->action = ldS->action;
 }
default_label()
void CB_EVAL::default_label (void * v)
Definition at line 249 of file cb.cc.
References CB_EVAL::label::action, CB::default_label(), and CB_EVAL::label::event.
 {
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   CB::default_label(&(ld->event));
   ld->action = 0;
 }
delete_label()
void CB_EVAL::delete_label (void * v)
Definition at line 262 of file cb.cc.
References CB::delete_label(), and CB_EVAL::label::event.
 {
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   CB::delete_label(&(ld->event));
 }
parse_label()
void CB_EVAL::parse_label (parser * p, shared_data * sd, void * v, v_array< substring > & words)
Definition at line 276 of file cb.cc.
References CB_EVAL::label::action, v_array< T >::begin(), CB_EVAL::label::event, hashstring(), CB::parse_label(), v_array< T >::size(), and THROW.
 {
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   if (words.size() < 2)
     THROW("Evaluation can not happen without an action and an exploration");
   ld->action = (uint32_t)hashstring(words[0], 0);
   words.begin()++;
   CB::parse_label(p, sd, &(ld->event), words);
   words.begin()--;
 }
read_cached_label()
size_t CB_EVAL::read_cached_label (shared_data * sd, void * v, io_buf & cache)
Definition at line 227 of file cb.cc.
References CB_EVAL::label::action, io_buf::buf_read(), c, CB_EVAL::label::event, and CB::read_cached_label().
 {
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   char* c;
   size_t total = sizeof(uint32_t);
   if (cache.buf_read(c, total) < total)
     return 0;
   ld->action = *(uint32_t*)c;
   return total + CB::read_cached_label(sd, &(ld->event), cache);
 }
test_label()
bool CB_EVAL::test_label (void * v)
Definition at line 256 of file cb.cc.
References CB_EVAL::label::event, and CB::test_label().
 {
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   return CB::test_label(&ld->event);
 }
weight()
float CB_EVAL::weight (void * v)
Definition at line 221 of file cb.cc.
References CB_EVAL::label::event, and CB::label::weight.
 {
   CB_EVAL::label* ld = (CB_EVAL::label*)v;
   return ld->event.weight;
 }
Variable Documentation
cb_eval
label_parser CB_EVAL::cb_eval
Initial value:
= {default_label, parse_label, cache_label, read_cached_label, delete_label, weight, copy_label,
    test_label, sizeof(CB_EVAL::label)}
Definition at line 292 of file cb.cc.
Referenced by cb_algs_setup().