Vowpal Wabbit: prediction_type Namespace Reference
prediction_type Namespace Reference
Enumerations
enum prediction_type_t {
scalar, scalars, action_scores, action_probs,
multiclass, multilabels, prob, multiclassprobs,
decision_probs
}
Functions
const char * to_string (prediction_type_t prediction_type)
Enumeration Type Documentation
prediction_type_t
enum prediction_type::prediction_type_t
Enumerator
scalar
scalars
action_scores
action_probs
multiclass
multilabels
prob
multiclassprobs
decision_probs
Definition at line 18 of file learner.h.
 {
   scalar,
   scalars,
   action_scores,
   action_probs,
   multiclass,
   multilabels,
   prob,
   multiclassprobs,
   decision_probs
 };
Function Documentation
to_string()
const char * prediction_type::to_string (prediction_type_t prediction_type)
Definition at line 12 of file learner.cc.
References action_probs, action_scores, CASE, multiclass, multiclassprobs, multilabels, prob, scalar, and scalars.
Referenced by audit_regressor_feature(), cbify_setup(), cbifyldf_setup(), Search::end_examples(), GD::end_pass(), Search::end_pass(), CCB::inject_slot_id(), make_write_cache(), CCB::print_update(), save_load_header(), Search::setup(), and warm_cb_setup().
 {
   switch (prediction_type)
   {
     CASE(scalar)
     CASE(scalars)
     CASE(action_scores)
     CASE(action_probs)
     CASE(multiclass)
     CASE(multilabels)
     CASE(prob)
     CASE(multiclassprobs)
     default:
       return "<unsupported>";
   }
 }