Vowpal Wabbit: VW::config Namespace Reference
VW::config Namespace Reference
Classes
struct base_option
struct option_group_definition
struct options_boost_po
struct options_i
struct options_serializer_boost_po
struct options_serializer_i
struct typed_option
struct typelist
Typedefs
using supported_options_types = typelist< unsigned int, int, size_t, uint64_t, float, double, char, std::string, bool, std::vector< int >, std::vector< size_t >, std::vector< float >, std::vector< double >, std::vector< char >, std::vector< std::string > >
Functions
template<typename T >
typed_option< T > make_option (std::string name, T &location)
template<typename T >
bool operator== (typed_option< T > &lhs, typed_option< T > &rhs)
template<typename T >
bool operator!= (typed_option< T > &lhs, typed_option< T > &rhs)
bool operator== (const base_option &lhs, const base_option &rhs)
bool operator!= (const base_option &lhs, const base_option &rhs)
Typedef Documentation
supported_options_types
using VW::config::supported_options_types = typedef typelist<unsigned int, int, size_t, uint64_t, float, double, char, std::string, bool, std::vector<int>, std::vector<size_t>, std::vector<float>, std::vector<double>, std::vector<char>, std::vector<std::string> >
Definition at line 29 of file options_types.h.
Function Documentation
make_option()
template<typename T > typed_option<T> VW::config::make_option (std::string name, T & location)
Definition at line 80 of file options.h.
Referenced by active_cover_setup(), active_setup(), audit_regressor_setup(), autolink_setup(), baseline_setup(), bfgs_setup(), binary_setup(), boosting_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_explore_setup(), cb_sample_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), classweight_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), CSOAA::csoaa_setup(), ect_setup(), explore_eval_setup(), ExpReplay::expreplay_setup(), ftrl_setup(), gd_mf_setup(), Search::handle_condition_options(), EntityRelationTask::initialize(), SelectiveBranchingMT::initialize(), DepParserTask::initialize(), GraphTask::initialize(), SequenceSpanTask::initialize(), ArgmaxTask::initialize(), interact_setup(), kernel_svm_setup(), lda_setup(), log_multi_setup(), lrq_setup(), lrqfa_setup(), main(), marginal_setup(), memory_tree_setup(), mf_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), noop_setup(), oaa_setup(), OjaNewton_setup(), parse_args(), parse_diagnostics(), parse_example_tweaks(), parse_feature_tweaks(), parse_modules(), parse_output_model(), parse_output_preds(), parse_source(), print_setup(), recall_tree_setup(), scorer_setup(), sender_setup(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), GD::setup(), Search::setup(), stagewise_poly_setup(), svrg_setup(), topk_setup(), and warm_cb_setup().
 {
   return typed_option<T>(name, location);
 }
operator!=() [1/2]
template<typename T > bool VW::config::operator!= (typed_option< T > & lhs, typed_option< T > & rhs)
Definition at line 153 of file options.h.
References operator==().
 {
   return !(lhs == rhs);
 }
operator!=() [2/2]
bool VW::config::operator!= (const base_option & lhs, const base_option & rhs) inline
Definition at line 167 of file options.h.
 { return !(lhs == rhs); }
operator==() [1/2]
template<typename T > bool VW::config::operator== (typed_option< T > & lhs, typed_option< T > & rhs)
Definition at line 146 of file options.h.
References VW::config::typed_option< T >::default_value(), VW::config::base_option::m_help, VW::config::base_option::m_keep, VW::config::base_option::m_name, VW::config::base_option::m_short_name, and VW::config::base_option::m_type_hash.
Referenced by vw_slim::internal::collection_pair_iterator< It1, It2 >::operator!=(), and operator!=().
 {
   return lhs.m_name == rhs.m_name && lhs.m_type_hash == rhs.m_type_hash && lhs.m_help == rhs.m_help &&
       lhs.m_short_name == rhs.m_short_name && lhs.m_keep == rhs.m_keep && lhs.default_value() == rhs.default_value();
 }
operator==() [2/2]
bool VW::config::operator== (const base_option & lhs, const base_option & rhs) inline
Definition at line 161 of file options.h.
References VW::config::base_option::m_help, VW::config::base_option::m_keep, VW::config::base_option::m_name, VW::config::base_option::m_short_name, and VW::config::base_option::m_type_hash.
 {
   return lhs.m_name == rhs.m_name && lhs.m_type_hash == rhs.m_type_hash && lhs.m_help == rhs.m_help &&
       lhs.m_short_name == rhs.m_short_name && lhs.m_keep == rhs.m_keep;
 }