Vowpal Wabbit: BASELINE Namespace Reference
BASELINE Namespace Reference
Functions
void set_baseline_enabled (example *ec)
void reset_baseline_disabled (example *ec)
bool baseline_enabled (example *ec)
Function Documentation
baseline_enabled()
bool BASELINE::baseline_enabled (example * ec)
Definition at line 51 of file baseline.cc.
References anonymous_namespace{baseline.cc}::baseline_enabled_idx, f, example_predict::feature_space, and message_namespace.
Referenced by CB_ALGS::get_cost_pred(), predict_or_learn(), and sensitivity().
 {
   auto& fs = ec->feature_space[message_namespace];
   for (auto& f : fs)
   {
     if (f.index() == baseline_enabled_idx)
       return f.value() == 1;
   }
   return false;
 }
reset_baseline_disabled()
void BASELINE::reset_baseline_disabled (example * ec)
Definition at line 38 of file baseline.cc.
References anonymous_namespace{baseline.cc}::baseline_enabled_idx, f, example_predict::feature_space, and message_namespace.
Referenced by CB_ALGS::get_cost_pred().
 {
   auto& fs = ec->feature_space[message_namespace];
   for (auto& f : fs)
   {
     if (f.index() == baseline_enabled_idx)
     {
       f.value() = 0;
       return;
     }
   }
 }
set_baseline_enabled()
void BASELINE::set_baseline_enabled (example * ec)
Definition at line 23 of file baseline.cc.
References anonymous_namespace{baseline.cc}::baseline_enabled_idx, f, example_predict::feature_space, and message_namespace.
Referenced by CB_ALGS::get_cost_pred().
 {
   auto& fs = ec->feature_space[message_namespace];
   for (auto& f : fs)
   {
     if (f.index() == baseline_enabled_idx)
     {
       f.value() = 1;
       return;
     }
   }
   // if not found, push new feature
   fs.push_back(1, baseline_enabled_idx);
 }