Vowpal Wabbit: CB Namespace Reference
CB Namespace Reference
Classes
struct cb_class
struct label
Functions
char * bufread_label (CB::label *ld, char *c, io_buf &cache)
size_t read_cached_label (shared_data *, void *v, io_buf &cache)
float weight (void *v)
char * bufcache_label (CB::label *ld, char *c)
void cache_label (void *v, io_buf &cache)
void default_label (void *v)
bool test_label (void *v)
void delete_label (void *v)
void copy_label (void *dst, void *src)
void parse_label (parser *p, shared_data *, void *v, v_array< substring > &words)
bool ec_is_example_header (example const &ec)
void print_update (vw &all, bool is_test, example &ec, multi_ex *ec_seq, bool action_scores)
Variables
label_parser cb_label
struct CB::cb_class __attribute__
Function Documentation
bufcache_label()
char* CB::bufcache_label (CB::label * ld, char * c)
Definition at line 58 of file cb.cc.
References c, CB::label::costs, and CB::label::weight.
Referenced by cache_label().
 {
   *(size_t*)c = ld->costs.size();
   c += sizeof(size_t);
   for (auto const& cost : ld->costs)
   {
     *(cb_class*)c = cost;
     c += sizeof(cb_class);
   }
   memcpy(c, &ld->weight, sizeof(ld->weight));
   c += sizeof(ld->weight);
   return c;
 }
bufread_label()
char* CB::bufread_label (CB::label * ld, char * c, io_buf & cache)
Definition at line 17 of file cb.cc.
References io_buf::buf_read(), c, CB::label::costs, and CB::label::weight.
Referenced by read_cached_label().
 {
   size_t num = *(size_t*)c;
   ld->costs.clear();
   c += sizeof(size_t);
   size_t total = sizeof(cb_class) * num + sizeof(ld->weight);
   if (cache.buf_read(c, total) < total)
   {
     std::cout << "error in demarshal of cost data" << std::endl;
     return c;
   }
   for (size_t i = 0; i < num; i++)
   {
     cb_class temp = *(cb_class*)c;
     c += sizeof(cb_class);
     ld->costs.push_back(temp);
   }
   memcpy(&ld->weight, c, sizeof(ld->weight));
   c += sizeof(ld->weight);
   return c;
 }
cache_label()
void CB::cache_label (void * v, io_buf & cache)
Definition at line 72 of file cb.cc.
References io_buf::buf_write(), bufcache_label(), c, CB::label::costs, and CB::label::weight.
Referenced by CB_EVAL::cache_label().
 {
   char* c;
   CB::label* ld = (CB::label*)v;
   cache.buf_write(c, sizeof(size_t) + sizeof(cb_class) * ld->costs.size() + sizeof(ld->weight));
   bufcache_label(ld, c);
 }
copy_label()
void CB::copy_label (void * dst, void * src)
Definition at line 104 of file cb.cc.
References copy_array(), CB::label::costs, and CB::label::weight.
Referenced by add_to_vali(), VW::copy_example_data(), VW::copy_example_label(), CB_EVAL::copy_label(), and Search::predictor::set_input_at().
 {
   CB::label* ldD = (CB::label*)dst;
   CB::label* ldS = (CB::label*)src;
   copy_array(ldD->costs, ldS->costs);
   ldD->weight = ldS->weight;
 }
default_label()
void CB::default_label (void * v)
Definition at line 80 of file cb.cc.
References CB::label::costs, and CB::label::weight.
Referenced by CB_EVAL::default_label().
 {
   CB::label* ld = (CB::label*)v;
   ld->costs.clear();
   ld->weight = 1;
 }
delete_label()
void CB::delete_label (void * v)
Definition at line 98 of file cb.cc.
References CB::label::costs.
Referenced by VW::dealloc_example(), CB_EVAL::delete_label(), EntityRelationTask::finish(), DepParserTask::finish(), SequenceTask_DemoLDF::finish(), Search::predictor::free_ec(), cbify::~cbify(), Search::search::~search(), and warm_cb::~warm_cb().
 {
   CB::label* ld = (CB::label*)v;
   ld->costs.delete_v();
 }
ec_is_example_header()
bool CB::ec_is_example_header (example const & ec)
Definition at line 170 of file cb.cc.
References polylabel::cb, CB::label::costs, f, example::l, and v_array< T >::size().
Referenced by LEARNER::example_is_newline_not_header(), CB_ALGS::example_is_newline_not_header(), EXPLORE_EVAL::output_example(), VW::shared_feature_merger::predict_or_learn(), and print_update().
 {
   v_array<CB::cb_class> costs = ec.l.cb.costs;
   if (costs.size() != 1)
     return false;
   if (costs[0].probability == -1.f)
     return true;
   return false;
 }
parse_label()
void CB::parse_label (parser * p, shared_data * , void * v, v_array< substring > & words)
Definition at line 112 of file cb.cc.
References CB::cb_class::action, CB::cb_class::cost, CB::label::costs, v_array< T >::empty(), f, float_of_substring(), hashstring(), parser::parse_name, CB::cb_class::partial_prediction, CB::cb_class::probability, v_array< T >::size(), substring_equal(), THROW, tokenize(), and CB::label::weight.
Referenced by CB_EVAL::parse_label().
 {
   CB::label* ld = (CB::label*)v;
   ld->costs.clear();
   ld->weight = 1.0;
   for (auto const& word : words)
   {
     cb_class f;
     tokenize(':', word, p->parse_name);
     if (p->parse_name.empty() || p->parse_name.size() > 3)
       THROW("malformed cost specification: " << p->parse_name);
     f.partial_prediction = 0.;
     f.action = (uint32_t)hashstring(p->parse_name[0], 0);
     f.cost = FLT_MAX;
     if (p->parse_name.size() > 1)
       f.cost = float_of_substring(p->parse_name[1]);
     if (std::isnan(f.cost))
       THROW("error NaN cost (" << p->parse_name[1] << " for action: " << p->parse_name[0]);
     f.probability = .0;
     if (p->parse_name.size() > 2)
       f.probability = float_of_substring(p->parse_name[2]);
     if (std::isnan(f.probability))
       THROW("error NaN probability (" << p->parse_name[2] << " for action: " << p->parse_name[0]);
     if (f.probability > 1.0)
     {
       std::cerr << "invalid probability > 1 specified for an action, resetting to 1." << std::endl;
       f.probability = 1.0;
     }
     if (f.probability < 0.0)
     {
       std::cerr << "invalid probability < 0 specified for an action, resetting to 0." << std::endl;
       f.probability = .0;
     }
     if (substring_equal(p->parse_name[0], "shared"))
     {
       if (p->parse_name.size() == 1)
       {
         f.probability = -1.f;
       }
       else
         std::cerr << "shared feature vectors should not have costs" << std::endl;
     }
     ld->costs.push_back(f);
   }
 }
print_update()
void CB::print_update (vw & all, bool is_test, example & ec, multi_ex * ec_seq, bool action_scores)
Definition at line 180 of file cb.cc.
References polyprediction::a_s, vw::bfgs, shared_data::col_current_predict, vw::current_pass, shared_data::dump_interval, ec_is_example_header(), v_array< T >::empty(), vw::holdout_set_off, polyprediction::multiclass, example::num_features, example::pred, shared_data::print_update(), vw::progress_add, vw::progress_arg, vw::quiet, vw::sd, and shared_data::weighted_examples().
Referenced by MWT::finish_example(), output_and_account_confidence_example(), output_and_account_example(), EXPLORE_EVAL::output_example(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example(), CB_ALGS::output_example(), output_example(), CB_ADF::output_example(), CB_ADF::output_rank_example(), and shared_data::print_update().
 {
   if (all.sd->weighted_examples() >= all.sd->dump_interval && !all.quiet && !all.bfgs)
   {
     size_t num_features = ec.num_features;
     size_t pred = ec.pred.multiclass;
     if (ec_seq != nullptr)
     {
       num_features = 0;
       // TODO: code duplication csoaa.cc LabelDict::ec_is_example_header
       for (size_t i = 0; i < (*ec_seq).size(); i++)
         if (!CB::ec_is_example_header(*(*ec_seq)[i]))
           num_features += (*ec_seq)[i]->num_features;
     }
     std::string label_buf;
     if (is_test)
       label_buf = " unknown";
     else
       label_buf = " known";
     if (action_scores)
     {
       std::ostringstream pred_buf;
       pred_buf << std::setw(shared_data::col_current_predict) << std::right << std::setfill(' ');
       if (!ec.pred.a_s.empty())
         pred_buf << ec.pred.a_s[0].action << ":" << ec.pred.a_s[0].score << "...";
       else
         pred_buf << "no action";
       all.sd->print_update(all.holdout_set_off, all.current_pass, label_buf, pred_buf.str(), num_features,
           all.progress_add, all.progress_arg);
     }
     else
       all.sd->print_update(all.holdout_set_off, all.current_pass, label_buf, (uint32_t)pred, num_features,
           all.progress_add, all.progress_arg);
   }
 }
read_cached_label()
size_t CB::read_cached_label (shared_data * , void * v, io_buf & cache)
Definition at line 39 of file cb.cc.
References io_buf::buf_read(), bufread_label(), c, and CB::label::costs.
Referenced by CB_EVAL::read_cached_label().
 {
   CB::label* ld = (CB::label*)v;
   ld->costs.clear();
   char* c;
   size_t total = sizeof(size_t);
   if (cache.buf_read(c, total) < total)
     return 0;
   bufread_label(ld, c, cache);
   return total;
 }
test_label()
bool CB::test_label (void * v)
Definition at line 87 of file cb.cc.
References CB::label::costs.
Referenced by CB_EVAL::test_label().
 {
   CB::label* ld = (CB::label*)v;
   if (ld->costs.empty())
     return true;
   for (auto const& cost : ld->costs)
     if (FLT_MAX != cost.cost && cost.probability > 0.)
       return false;
   return true;
 }
weight()
float CB::weight (void * v)
Definition at line 52 of file cb.cc.
References CB::label::weight.
 {
   CB::label* ld = (CB::label*)v;
   return ld->weight;
 }
Variable Documentation
__attribute__
struct CB::cb_class CB::__attribute__
cb_label
label_parser CB::cb_label
Initial value:
= {default_label, parse_label, cache_label, read_cached_label, delete_label, weight, copy_label,
    test_label, sizeof(label)}
Definition at line 167 of file cb.cc.
Referenced by cb_adf_setup(), cb_algs_setup(), copy_example_to_adf(), explore_eval_setup(), init_adf_data(), mwt_setup(), CB_ALGS::output_example(), CB_EXPLORE::output_example(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), Search::setup(), cbify::~cbify(), and warm_cb::~warm_cb().