Vowpal Wabbit: HookTask Namespace Reference
HookTask Namespace Reference
Classes
struct task_data
Functions
void initialize (Search::search &sch, size_t &num_actions, options_i &arg)
void finish (Search::search &sch)
void run (Search::search &sch, multi_ex &)
void run_setup (Search::search &sch, multi_ex &)
void run_takedown (Search::search &sch, multi_ex &)
Variables
Search::search_task task = {"hook", run, initialize, finish, run_setup, run_takedown}
Function Documentation
finish()
void HookTask::finish (Search::search & sch)
Definition at line 32 of file search_hooktask.cc.
References HookTask::task_data::delete_extra_data, HookTask::task_data::delete_run_object, Search::search::get_task_data(), HookTask::task_data::run_object, HookTask::task_data::setup_object, and HookTask::task_data::takedown_object.
 {
   task_data* td = sch.get_task_data<task_data>();
   if (td->delete_run_object)
   {
     if (td->run_object)
       td->delete_run_object(td->run_object);
     if (td->setup_object)
       td->delete_run_object(td->setup_object);
     if (td->takedown_object)
       td->delete_run_object(td->takedown_object);
   }
   if (td->delete_extra_data)
     td->delete_extra_data(*td);
   delete td;
 }
initialize()
void HookTask::initialize (Search::search & sch, size_t & num_actions, options_i & arg)
Definition at line 16 of file search_hooktask.cc.
References HookTask::task_data::arg, HookTask::task_data::delete_extra_data, HookTask::task_data::delete_run_object, HookTask::task_data::num_actions, HookTask::task_data::run_f, HookTask::task_data::run_object, HookTask::task_data::run_setup_f, HookTask::task_data::run_takedown_f, Search::search::set_task_data(), HookTask::task_data::setup_object, and HookTask::task_data::takedown_object.
 {
   task_data* td = new task_data;
   td->run_f = nullptr;
   td->run_setup_f = nullptr;
   td->run_takedown_f = nullptr;
   td->run_object = nullptr;
   td->setup_object = nullptr;
   td->takedown_object = nullptr;
   td->delete_run_object = nullptr;
   td->delete_extra_data = nullptr;
   td->num_actions = num_actions;
   td->arg = &arg;
   sch.set_task_data<task_data>(td);
 }
run()
void HookTask::run (Search::search & sch, multi_ex &)
Definition at line 49 of file search_hooktask.cc.
References Search::search::get_task_data(), and HookTask::task_data::run_f.
 {
   task_data* td = sch.get_task_data<task_data>();
   if (td->run_f)
     td->run_f(sch);
   else
     std::cerr << "warning: HookTask::structured_predict called before hook is set" << std::endl;
 }
run_setup()
void HookTask::run_setup (Search::search & sch, multi_ex &)
Definition at line 58 of file search_hooktask.cc.
References Search::search::get_task_data(), and HookTask::task_data::run_setup_f.
 {
   task_data* td = sch.get_task_data<task_data>();
   if (td->run_setup_f)
     td->run_setup_f(sch);
 }
run_takedown()
void HookTask::run_takedown (Search::search & sch, multi_ex &)
Definition at line 65 of file search_hooktask.cc.
References Search::search::get_task_data(), and HookTask::task_data::run_takedown_f.
 {
   task_data* td = sch.get_task_data<task_data>();
   if (td->run_takedown_f)
     td->run_takedown_f(sch);
 }
Variable Documentation
task
Search::search_task HookTask::task = {"hook", run, initialize, finish, run_setup, run_takedown}
Definition at line 14 of file search_hooktask.cc.