Vowpal Wabbit: VW::cb_explore_adf::greedy Namespace Reference
VW::cb_explore_adf::greedy Namespace Reference
Classes
struct cb_explore_adf_greedy
Functions
LEARNER::base_learner * setup (VW::config::options_i &options, vw &all)
Function Documentation
setup()
LEARNER::base_learner * VW::cb_explore_adf::greedy::setup (VW::config::options_i & options, vw & all)
Definition at line 66 of file cb_explore_adf_greedy.cc.
References prediction_type::action_probs, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), label_type::cb, CB::cb_label, ACTION_SCORE::delete_action_scores(), vw::delete_prediction, f, finish_multiline_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, learn(), parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, predict(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   using config::make_option;
   bool cb_explore_adf_option = false;
   float epsilon = 0.;
   bool first_only = false;
   config::option_group_definition new_options("Contextual Bandit Exploration with Action Dependent Features");
   new_options
       .add(make_option("cb_explore_adf", cb_explore_adf_option)
                .keep()
                .help("Online explore-exploit for a contextual bandit problem with multiline action dependent features"))
       .add(make_option("epsilon", epsilon).keep().help("epsilon-greedy exploration"))
       .add(make_option("first_only", first_only).keep().help("Only explore the first action in a tie-breaking event"));
   options.add_and_parse(new_options);
   // NOTE: epsilon-greedy is the default explore type. This basically runs if none of the other explore strategies are
   // used
   bool use_greedy = !(options.was_supplied("first") || options.was_supplied("bag") || options.was_supplied("cover") ||
       options.was_supplied("regcb") || options.was_supplied("regcbopt") || options.was_supplied("softmax"));
   if (!cb_explore_adf_option || !use_greedy)
     return nullptr;
   // Ensure serialization of cb_adf in all cases.
   if (!options.was_supplied("cb_adf"))
   {
     options.insert("cb_adf", "");
   }
   all.delete_prediction = ACTION_SCORE::delete_action_scores;
   size_t problem_multiplier = 1;
   if (!options.was_supplied("epsilon"))
     epsilon = 0.05f;
   LEARNER::multi_learner* base = as_multiline(setup_base(options, all));
   all.p->lp = CB::cb_label;
   all.label_type = label_type::cb;
   using explore_type = cb_explore_adf_base<cb_explore_adf_greedy>;
   auto data = scoped_calloc_or_throw<explore_type>(epsilon, first_only);
   LEARNER::learner<explore_type, multi_ex>& l = LEARNER::init_learner(
       data, base, explore_type::learn, explore_type::predict, problem_multiplier, prediction_type::action_probs);
   l.set_finish_example(explore_type::finish_multiline_example);
   return make_base(l);
 }