Vowpal Wabbit: MULTILABEL Namespace Reference
MULTILABEL Namespace Reference
Classes
struct labels
Functions
char * bufread_label (labels *ld, char *c, io_buf &cache)
size_t read_cached_label (shared_data *, void *v, io_buf &cache)
float weight (void *)
char * bufcache_label (labels *ld, char *c)
void cache_label (void *v, io_buf &cache)
void default_label (void *v)
bool test_label (void *v)
void delete_label (void *v)
void copy_label (void *dst, void *src)
void parse_label (parser *p, shared_data *, void *v, v_array< substring > &words)
void print_update (vw &all, bool is_test, example &ec)
void output_example (vw &all, example &ec)
void print_update (vw &all, bool is_test, example &ec, const v_array< example *> *ec_seq)
Variables
label_parser multilabel
Function Documentation
bufcache_label()
char* MULTILABEL::bufcache_label (labels * ld, char * c)
Definition at line 43 of file multilabel.cc.
References c, MULTILABEL::labels::label_v, and v_array< T >::size().
Referenced by cache_label().
 {
   *(size_t*)c = ld->label_v.size();
   c += sizeof(size_t);
   for (unsigned int i = 0; i < ld->label_v.size(); i++)
   {
     *(uint32_t*)c = ld->label_v[i];
     c += sizeof(uint32_t);
   }
   return c;
 }
bufread_label()
char* MULTILABEL::bufread_label (labels * ld, char * c, io_buf & cache)
Definition at line 7 of file multilabel.cc.
References io_buf::buf_read(), c, v_array< T >::clear(), MULTILABEL::labels::label_v, and v_array< T >::push_back().
Referenced by read_cached_label().
 {
   size_t num = *(size_t*)c;
   ld->label_v.clear();
   c += sizeof(size_t);
   size_t total = sizeof(uint32_t) * num;
   if (cache.buf_read(c, (int)total) < total)
   {
     std::cout << "error in demarshal of cost data" << std::endl;
     return c;
   }
   for (size_t i = 0; i < num; i++)
   {
     uint32_t temp = *(uint32_t*)c;
     c += sizeof(uint32_t);
     ld->label_v.push_back(temp);
   }
   return c;
 }
cache_label()
void MULTILABEL::cache_label (void * v, io_buf & cache)
Definition at line 55 of file multilabel.cc.
References io_buf::buf_write(), bufcache_label(), c, MULTILABEL::labels::label_v, and v_array< T >::size().
 {
   char* c;
   labels* ld = (labels*)v;
   cache.buf_write(c, sizeof(size_t) + sizeof(uint32_t) * ld->label_v.size());
   bufcache_label(ld, c);
 }
copy_label()
void MULTILABEL::copy_label (void * dst, void * src)
Definition at line 82 of file multilabel.cc.
References copy_array(), and MULTILABEL::labels::label_v.
 {
   if (dst && src)
   {
     labels* ldD = (labels*)dst;
     labels* ldS = (labels*)src;
     copy_array(ldD->label_v, ldS->label_v);
   }
 }
default_label()
void MULTILABEL::default_label (void * v)
Definition at line 63 of file multilabel.cc.
References v_array< T >::clear(), and MULTILABEL::labels::label_v.
 {
   labels* ld = (labels*)v;
   ld->label_v.clear();
 }
delete_label()
void MULTILABEL::delete_label (void * v)
Definition at line 75 of file multilabel.cc.
References v_array< T >::delete_v(), and MULTILABEL::labels::label_v.
 {
   labels* ld = (labels*)v;
   if (ld)
     ld->label_v.delete_v();
 }
output_example()
void MULTILABEL::output_example (vw & all, example & ec)
Definition at line 140 of file multilabel.cc.
References f, vw::final_prediction_sink, example::l, MULTILABEL::labels::label_v, loss(), polylabel::multilabels, polyprediction::multilabels, example::num_features, example::pred, vw::print_text, print_update(), vw::sd, v_array< T >::size(), example::tag, test_label(), example::test_only, and shared_data::update().
Referenced by finish_example().
 {
   labels& ld = ec.l.multilabels;
   float loss = 0.;
   if (!test_label(&ld))
   {
     // need to compute exact loss
     labels preds = ec.pred.multilabels;
     labels given = ec.l.multilabels;
     uint32_t preds_index = 0;
     uint32_t given_index = 0;
     while (preds_index < preds.label_v.size() && given_index < given.label_v.size())
     {
       if (preds.label_v[preds_index] < given.label_v[given_index])
       {
         preds_index++;
         loss++;
       }
       else if (preds.label_v[preds_index] > given.label_v[given_index])
       {
         given_index++;
         loss++;
       }
       else
       {
         preds_index++;
         given_index++;
       }
     }
     loss += given.label_v.size() - given_index;
     loss += preds.label_v.size() - preds_index;
   }
   all.sd->update(ec.test_only, !test_label(&ld), loss, 1.f, ec.num_features);
   for (int sink : all.final_prediction_sink)
     if (sink >= 0)
     {
       std::stringstream ss;
       for (size_t i = 0; i < ec.pred.multilabels.label_v.size(); i++)
       {
         if (i > 0)
           ss << ',';
         ss << ec.pred.multilabels.label_v[i];
       }
       ss << ' ';
       all.print_text(sink, ss.str(), ec.tag);
     }
   print_update(all, test_label(&ec.l.multilabels), ec);
 }
parse_label()
void MULTILABEL::parse_label (parser * p, shared_data * , void * v, v_array< substring > & words)
Definition at line 92 of file multilabel.cc.
References v_array< T >::begin(), v_array< T >::clear(), v_array< T >::end(), MULTILABEL::labels::label_v, parser::parse_name, v_array< T >::push_back(), v_array< T >::size(), and tokenize().
 {
   labels* ld = (labels*)v;
   ld->label_v.clear();
   switch (words.size())
   {
     case 0:
       break;
     case 1:
       tokenize(',', words[0], p->parse_name);
       for (size_t i = 0; i < p->parse_name.size(); i++)
       {
         *(p->parse_name[i].end) = '\0';
         uint32_t n = atoi(p->parse_name[i].begin);
         ld->label_v.push_back(n);
       }
       break;
     default:
       std::cerr << "example with an odd label, what is ";
       for (size_t i = 0; i < words.size(); i++) std::cerr << words[i].begin << " ";
       std::cerr << std::endl;
   }
 }
print_update() [1/2]
void MULTILABEL::print_update (vw & all, bool is_test, example & ec, const v_array< example *> * ec_seq)
print_update() [2/2]
void MULTILABEL::print_update (vw & all, bool is_test, example & ec)
Definition at line 121 of file multilabel.cc.
References vw::bfgs, vw::current_pass, shared_data::dump_interval, vw::holdout_set_off, example::l, MULTILABEL::labels::label_v, polylabel::multilabels, polyprediction::multilabels, example::num_features, example::pred, shared_data::print_update(), vw::progress_add, vw::progress_arg, vw::quiet, vw::sd, v_array< T >::size(), and shared_data::weighted_examples().
Referenced by output_example().
 {
   if (all.sd->weighted_examples() >= all.sd->dump_interval && !all.quiet && !all.bfgs)
   {
     std::stringstream label_string;
     if (is_test)
       label_string << " unknown";
     else
       for (size_t i = 0; i < ec.l.multilabels.label_v.size(); i++) label_string << " " << ec.l.multilabels.label_v[i];
     std::stringstream pred_string;
     for (size_t i = 0; i < ec.pred.multilabels.label_v.size(); i++)
       pred_string << " " << ec.pred.multilabels.label_v[i];
     all.sd->print_update(all.holdout_set_off, all.current_pass, label_string.str(), pred_string.str(), ec.num_features,
         all.progress_add, all.progress_arg);
   }
 }
read_cached_label()
size_t MULTILABEL::read_cached_label (shared_data * , void * v, io_buf & cache)
Definition at line 28 of file multilabel.cc.
References io_buf::buf_read(), bufread_label(), c, v_array< T >::clear(), and MULTILABEL::labels::label_v.
 {
   labels* ld = (labels*)v;
   ld->label_v.clear();
   char* c;
   size_t total = sizeof(size_t);
   if (cache.buf_read(c, (int)total) < total)
     return 0;
   bufread_label(ld, c, cache);
   return total;
 }
test_label()
bool MULTILABEL::test_label (void * v)
Definition at line 69 of file multilabel.cc.
References MULTILABEL::labels::label_v, and v_array< T >::size().
Referenced by output_example().
 {
   labels* ld = (labels*)v;
   return ld->label_v.size() == 0;
 }
weight()
float MULTILABEL::weight (void *)
Definition at line 41 of file multilabel.cc.
 { return 1.; }
Variable Documentation
multilabel
label_parser MULTILABEL::multilabel
Initial value:
= {default_label, parse_label, cache_label, read_cached_label, delete_label, weight, copy_label,
    test_label, sizeof(labels)}
Definition at line 118 of file multilabel.cc.
Referenced by COST_SENSITIVE::finish_example(), memory_tree_setup(), and multilabel_oaa_setup().