Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/print.cc File Reference
print.cc File Reference
#include "gd.h"
#include <cfloat>
#include "reductions.h"
Classes
struct print
Functions
void print_feature (vw &, float value, uint64_t index)
void learn (print &p, LEARNER::base_learner &, example &ec)
LEARNER::base_learner * print_setup (options_i &options, vw &all)
Function Documentation
learn()
void learn (print & p, LEARNER::base_learner & , example & ec)
Definition at line 22 of file print.cc.
References print::all, v_array< T >::begin(), v_array< T >::empty(), label_data::initial, example::l, label_data::label, polylabel::simple, v_array< T >::size(), example::tag, and example::weight.
Referenced by print_setup().
 {
   label_data& ld = ec.l.simple;
   if (ld.label != FLT_MAX)
   {
     cout << ld.label << " ";
     if (ec.weight != 1 || ld.initial != 0)
     {
       cout << ec.weight << " ";
       if (ld.initial != 0)
         cout << ld.initial << " ";
     }
   }
   if (!ec.tag.empty())
   {
     cout << '\'';
     cout.write(ec.tag.begin(), ec.tag.size());
   }
   cout << "| ";
   GD::foreach_feature<vw, uint64_t, print_feature>(*(p.all), ec, *p.all);
   cout << std::endl;
 }
print_feature()
void print_feature (vw & , float value, uint64_t index)
Definition at line 14 of file print.cc.
 {
   cout << index;
   if (value != 1.)
     cout << ":" << value;
   cout << " ";
 }
print_setup()
LEARNER::base_learner* print_setup (options_i & options, vw & all)
Definition at line 45 of file print.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::init_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), parameters::stride_shift(), and vw::weights.
Referenced by parse_reductions().
 {
   bool print_option = false;
   option_group_definition new_options("Print psuedolearner");
   new_options.add(make_option("print", print_option).keep().help("print examples"));
   options.add_and_parse(new_options);
   if (!print_option)
     return nullptr;
   auto p = scoped_calloc_or_throw<print>();
   p->all = &all;
   all.weights.stride_shift(0);
   LEARNER::learner<print, example>& ret = init_learner(p, learn, learn, 1);
   return make_base(ret);
 }