Vowpal Wabbit: /mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/simple_label.h File Reference
simple_label.h File Reference
#include "label_parser.h"
Classes
struct label_data
Functions
void return_simple_example (vw &all, void *, example &ec)
bool summarize_holdout_set (vw &all, size_t &no_win_counter)
void print_update (vw &all, example &ec)
void output_and_account_example (vw &all, example &ec)
Variables
label_parser simple_label
Function Documentation
output_and_account_example()
void output_and_account_example (vw & all, example & ec)
Definition at line 119 of file simple_label.cc.
References f, vw::final_prediction_sink, example::l, label_data::label, example::loss, example::num_features, example::partial_prediction, example::pred, vw::print, print_update(), vw::raw_prediction, polyprediction::scalar, vw::sd, polylabel::simple, v_array< T >::size(), example::tag, example::test_only, shared_data::update(), example::weight, and shared_data::weighted_labels.
Referenced by return_simple_example().
 {
   label_data ld = ec.l.simple;
   all.sd->update(ec.test_only, ld.label != FLT_MAX, ec.loss, ec.weight, ec.num_features);
   if (ld.label != FLT_MAX && !ec.test_only)
     all.sd->weighted_labels += ((double)ld.label) * ec.weight;
   all.print(all.raw_prediction, ec.partial_prediction, -1, ec.tag);
   for (size_t i = 0; i < all.final_prediction_sink.size(); i++)
   {
     int f = (int)all.final_prediction_sink[i];
     all.print(f, ec.pred.scalar, 0, ec.tag);
   }
   print_update(all, ec);
 }
print_update()
void print_update (vw & all, example & ec)
Definition at line 109 of file simple_label.cc.
References vw::bfgs, vw::current_pass, shared_data::dump_interval, vw::holdout_set_off, example::l, label_data::label, example::num_features, example::pred, shared_data::print_update(), vw::progress_add, vw::progress_arg, vw::quiet, polyprediction::scalar, vw::sd, polylabel::simple, shared_data::weighted_labeled_examples, and shared_data::weighted_unlabeled_examples.
Referenced by output_and_account_example().
 {
   if (all.sd->weighted_labeled_examples + all.sd->weighted_unlabeled_examples >= all.sd->dump_interval && !all.quiet &&
       !all.bfgs)
   {
     all.sd->print_update(all.holdout_set_off, all.current_pass, ec.l.simple.label, ec.pred.scalar, ec.num_features,
         all.progress_add, all.progress_arg);
   }
 }
return_simple_example()
void return_simple_example (vw & all, void * , example & ec)
Definition at line 137 of file simple_label.cc.
References VW::finish_example(), and output_and_account_example().
Referenced by finish_example(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner(), and receive_result().
 {
   output_and_account_example(all, ec);
   VW::finish_example(all, ec);
 }
summarize_holdout_set()
bool summarize_holdout_set (vw & all, size_t & no_win_counter)
Definition at line 143 of file simple_label.cc.
References accumulate_scalar(), vw::all_reduce, vw::current_pass, f, shared_data::holdout_best_loss, shared_data::holdout_best_pass, shared_data::holdout_sum_loss_since_last_pass, vw::sd, and shared_data::weighted_holdout_examples_since_last_pass.
Referenced by GD::end_pass(), and end_pass().
 {
   float thisLoss = (all.sd->weighted_holdout_examples_since_last_pass > 0)
       ? (float)(all.sd->holdout_sum_loss_since_last_pass / all.sd->weighted_holdout_examples_since_last_pass)
       : FLT_MAX * 0.5f;
   if (all.all_reduce != nullptr)
     thisLoss = accumulate_scalar(all, thisLoss);
   all.sd->weighted_holdout_examples_since_last_pass = 0;
   all.sd->holdout_sum_loss_since_last_pass = 0;
   if (thisLoss < all.sd->holdout_best_loss)
   {
     all.sd->holdout_best_loss = thisLoss;
     all.sd->holdout_best_pass = all.current_pass;
     no_win_counter = 0;
     return true;
   }
   if ((thisLoss != FLT_MAX) ||
       (std::isfinite(
           all.sd->holdout_best_loss)))  // it's only a loss if we're not infinite when the previous one wasn't infinite
     no_win_counter++;
   return false;
 }
Variable Documentation
simple_label
label_parser simple_label
Definition at line 106 of file simple_label.cc.
Referenced by baseline_setup(), CSOAA::do_actual_learning_oaa(), CSOAA::do_actual_learning_wap(), CSOAA::make_single_prediction(), parser::parser(), and baseline::~baseline().