Vowpal Wabbit: VW::cb_explore_adf::bag::cb_explore_adf_bag Struct Reference
VW::cb_explore_adf::bag::cb_explore_adf_bag Struct Reference
Public Member Functions
cb_explore_adf_bag (float epsilon, size_t bag_size, bool greedify, bool first_only, std::shared_ptr< rand_state > random_state)
~cb_explore_adf_bag ()
void predict (LEARNER::multi_learner &base, multi_ex &examples)
void learn (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void predict_or_learn_impl (LEARNER::multi_learner &base, multi_ex &examples)
Private Attributes
float _epsilon
size_t _bag_size
bool _greedify
bool _first_only
std::shared_ptr< rand_state > _random_state
v_array< ACTION_SCORE::action_score > _action_probs
std::vector< float > _scores
std::vector< float > _top_actions
Detailed Description
Definition at line 24 of file cb_explore_adf_bag.cc.
Constructor & Destructor Documentation
cb_explore_adf_bag()
VW::cb_explore_adf::bag::cb_explore_adf_bag::cb_explore_adf_bag (float epsilon, size_t bag_size, bool greedify, bool first_only, std::shared_ptr< rand_state > random_state)
Definition at line 51 of file cb_explore_adf_bag.cc.
     : _epsilon(epsilon), _bag_size(bag_size), _greedify(greedify), _first_only(first_only), _random_state(random_state)
 {
 }
~cb_explore_adf_bag()
VW::cb_explore_adf::bag::cb_explore_adf_bag::~cb_explore_adf_bag ()
Definition at line 112 of file cb_explore_adf_bag.cc.
References _action_probs, and v_array< T >::delete_v().
 { _action_probs.delete_v(); }
Member Function Documentation
learn()
void VW::cb_explore_adf::bag::cb_explore_adf_bag::learn (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 44 of file cb_explore_adf_bag.cc.
References predict_or_learn_impl().
 { predict_or_learn_impl<true>(base, examples); }
predict()
void VW::cb_explore_adf::bag::cb_explore_adf_bag::predict (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 43 of file cb_explore_adf_bag.cc.
 { predict_or_learn_impl<false>(base, examples); }
predict_or_learn_impl()
template<bool is_learn> void VW::cb_explore_adf::bag::cb_explore_adf_bag::predict_or_learn_impl (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 58 of file cb_explore_adf_bag.cc.
References _action_probs, _bag_size, _epsilon, _first_only, _greedify, _random_state, _scores, _top_actions, ACTION_SCORE::begin_scores(), v_array< T >::clear(), ACTION_SCORE::end_scores(), exploration::enforce_minimum_probability(), f, VW::cb_explore_adf::fill_tied(), exploration::generate_bag(), v_array< T >::push_back(), v_array< T >::size(), VW::cb_explore_adf::sort_action_probs(), and BS::weight_gen().
Referenced by learn().
 {
   // Randomize over predictions from a base set of predictors
   v_array<ACTION_SCORE::action_score>& preds = examples[0]->pred.a_s;
   uint32_t num_actions = (uint32_t)examples.size();
   if (num_actions == 0)
   {
     preds.clear();
     return;
   }
   _scores.clear();
   for (uint32_t i = 0; i < num_actions; i++) _scores.push_back(0.f);
   _top_actions.assign(num_actions, 0);
   for (uint32_t i = 0; i < _bag_size; i++)
   {
     // avoid updates to the random num generator
     // for greedify, always update first policy once
     uint32_t count = is_learn ? ((_greedify && i == 0) ? 1 : BS::weight_gen(_random_state)) : 0;
     if (is_learn && count > 0)
       LEARNER::multiline_learn_or_predict<true>(base, examples, examples[0]->ft_offset, i);
     else
       LEARNER::multiline_learn_or_predict<false>(base, examples, examples[0]->ft_offset, i);
     assert(preds.size() == num_actions);
     for (auto e : preds) _scores[e.action] += e.score;
     if (!_first_only)
     {
       size_t tied_actions = fill_tied(preds);
       for (size_t i = 0; i < tied_actions; ++i) _top_actions[preds[i].action] += 1.f / tied_actions;
     }
     else
       _top_actions[preds[0].action] += 1.f;
     if (is_learn)
       for (uint32_t j = 1; j < count; j++)
         LEARNER::multiline_learn_or_predict<true>(base, examples, examples[0]->ft_offset, i);
   }
   _action_probs.clear();
   for (uint32_t i = 0; i < _scores.size(); i++) _action_probs.push_back({i, 0.});
   // generate distribution over actions
   exploration::generate_bag(
       begin(_top_actions), end(_top_actions), begin_scores(_action_probs), end_scores(_action_probs));
   exploration::enforce_minimum_probability(_epsilon, true, begin_scores(_action_probs), end_scores(_action_probs));
   sort_action_probs(_action_probs, _scores);
   for (size_t i = 0; i < num_actions; i++) preds[i] = _action_probs[i];
 }
Member Data Documentation
_action_probs
v_array<ACTION_SCORE::action_score> VW::cb_explore_adf::bag::cb_explore_adf_bag::_action_probs private
Definition at line 33 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl(), and ~cb_explore_adf_bag().
_bag_size
size_t VW::cb_explore_adf::bag::cb_explore_adf_bag::_bag_size private
Definition at line 28 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
_epsilon
float VW::cb_explore_adf::bag::cb_explore_adf_bag::_epsilon private
Definition at line 27 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
_first_only
bool VW::cb_explore_adf::bag::cb_explore_adf_bag::_first_only private
Definition at line 30 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
_greedify
bool VW::cb_explore_adf::bag::cb_explore_adf_bag::_greedify private
Definition at line 29 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
_random_state
std::shared_ptr<rand_state> VW::cb_explore_adf::bag::cb_explore_adf_bag::_random_state private
Definition at line 31 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
_scores
std::vector<float> VW::cb_explore_adf::bag::cb_explore_adf_bag::_scores private
Definition at line 34 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
_top_actions
std::vector<float> VW::cb_explore_adf::bag::cb_explore_adf_bag::_top_actions private
Definition at line 35 of file cb_explore_adf_bag.cc.
Referenced by predict_or_learn_impl().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/cb_explore_adf_bag.cc