Vowpal Wabbit: VW::cb_explore_adf::greedy::cb_explore_adf_greedy Struct Reference
VW::cb_explore_adf::greedy::cb_explore_adf_greedy Struct Reference
Public Member Functions
cb_explore_adf_greedy (float epsilon, bool first_only)
~cb_explore_adf_greedy ()=default
void predict (LEARNER::multi_learner &base, multi_ex &examples)
void learn (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void predict_or_learn_impl (LEARNER::multi_learner &base, multi_ex &examples)
Private Attributes
float _epsilon
bool _first_only
Detailed Description
Definition at line 20 of file cb_explore_adf_greedy.cc.
Constructor & Destructor Documentation
cb_explore_adf_greedy()
VW::cb_explore_adf::greedy::cb_explore_adf_greedy::cb_explore_adf_greedy (float epsilon, bool first_only)
Definition at line 39 of file cb_explore_adf_greedy.cc.
     : _epsilon(epsilon), _first_only(first_only)
 {
 }
~cb_explore_adf_greedy()
VW::cb_explore_adf::greedy::cb_explore_adf_greedy::~cb_explore_adf_greedy () default
Member Function Documentation
learn()
void VW::cb_explore_adf::greedy::cb_explore_adf_greedy::learn (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 32 of file cb_explore_adf_greedy.cc.
References predict_or_learn_impl().
 { predict_or_learn_impl<true>(base, examples); }
predict()
void VW::cb_explore_adf::greedy::cb_explore_adf_greedy::predict (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 31 of file cb_explore_adf_greedy.cc.
 { predict_or_learn_impl<false>(base, examples); }
predict_or_learn_impl()
template<bool is_learn> void VW::cb_explore_adf::greedy::cb_explore_adf_greedy::predict_or_learn_impl (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 45 of file cb_explore_adf_greedy.cc.
References _epsilon, _first_only, f, VW::cb_explore_adf::fill_tied(), prediction_type::prob, and v_array< T >::size().
Referenced by learn().
 {
   // Explore uniform random an epsilon fraction of the time.
   LEARNER::multiline_learn_or_predict<is_learn>(base, examples, examples[0]->ft_offset);
   ACTION_SCORE::action_scores& preds = examples[0]->pred.a_s;
   uint32_t num_actions = (uint32_t)preds.size();
   size_t tied_actions = fill_tied(preds);
   const float prob = _epsilon / num_actions;
   for (size_t i = 0; i < num_actions; i++) preds[i].score = prob;
   if (!_first_only)
   {
     for (size_t i = 0; i < tied_actions; ++i) preds[i].score += (1.f - _epsilon) / tied_actions;
   }
   else
     preds[0].score += 1.f - _epsilon;
 }
Member Data Documentation
_epsilon
float VW::cb_explore_adf::greedy::cb_explore_adf_greedy::_epsilon private
Definition at line 23 of file cb_explore_adf_greedy.cc.
Referenced by predict_or_learn_impl().
_first_only
bool VW::cb_explore_adf::greedy::cb_explore_adf_greedy::_first_only private
Definition at line 24 of file cb_explore_adf_greedy.cc.
Referenced by predict_or_learn_impl().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/cb_explore_adf_greedy.cc