Vowpal Wabbit: VW::cb_sample_data Struct Reference
VW::cb_sample_data Struct Reference
Public Member Functions
cb_sample_data (std::shared_ptr< rand_state > &random_state)
cb_sample_data (std::shared_ptr< rand_state > &&random_state)
template<bool is_learn>
void learn_or_predict (multi_learner &base, multi_ex &examples)
Private Attributes
std::shared_ptr< rand_state > _random_state
Detailed Description
Definition at line 14 of file cb_sample.cc.
Constructor & Destructor Documentation
cb_sample_data() [1/2]
VW::cb_sample_data::cb_sample_data (std::shared_ptr< rand_state > & random_state) inline explicit
Definition at line 16 of file cb_sample.cc.
 : _random_state(random_state) {}
cb_sample_data() [2/2]
VW::cb_sample_data::cb_sample_data (std::shared_ptr< rand_state > && random_state) inline explicit
Definition at line 17 of file cb_sample.cc.
 : _random_state(random_state) {}
Member Function Documentation
learn_or_predict()
template<bool is_learn> void VW::cb_sample_data::learn_or_predict (multi_learner & base, multi_ex & examples) inline
Definition at line 20 of file cb_sample.cc.
References _UNUSED, substring::begin, ACTION_SCORE::begin_scores(), ACTION_SCORE::end_scores(), S_EXPLORATION_OK, exploration::sample_after_normalizing(), substring_len(), exploration::swap_chosen(), and uniform_hash().
Referenced by learn_or_predict().
   {
     multiline_learn_or_predict<is_learn>(base, examples, examples[0]->ft_offset);
     auto action_scores = examples[0]->pred.a_s;
     uint32_t chosen_action = -1;
     int labelled_action = -1;
     // Find that chosen action in the learning case, skip the shared example.
     auto it = std::find_if(examples.begin(), examples.end(), [](example *item) { return !item->l.cb.costs.empty(); });
     if (it != examples.end())
     {
       labelled_action = std::distance(examples.begin(), it);
     }
     // If we are learning and have a label, then take that action as the chosen action. Otherwise sample the
     // distribution.
     if (is_learn && labelled_action != -1)
     {
       // Find where the labelled action is in the final prediction to determine if swapping needs to occur.
       // This only matters if the prediction decided to explore, but the same output should happen for the learn case.
       for (size_t i = 0; i < action_scores.size(); i++)
       {
         auto &a_s = action_scores[i];
         if (a_s.action == static_cast<uint32_t>(labelled_action))
         {
           chosen_action = static_cast<uint32_t>(i);
           break;
         }
       }
     }
     else
     {
       bool tag_provided_seed = false;
       uint64_t seed = _random_state->get_current_state();
       if (!examples[0]->tag.empty())
       {
         const std::string SEED_IDENTIFIER = "seed=";
         if (strncmp(examples[0]->tag.begin(), SEED_IDENTIFIER.c_str(), SEED_IDENTIFIER.size()) == 0 &&
             examples[0]->tag.size() > SEED_IDENTIFIER.size())
         {
           substring tag_seed{examples[0]->tag.begin() + 5, examples[0]->tag.begin() + examples[0]->tag.size()};
           seed = uniform_hash(tag_seed.begin, substring_len(tag_seed), 0);
           tag_provided_seed = true;
         }
       }
       // Sampling is done after the base learner has generated a pdf.
       auto result = exploration::sample_after_normalizing(
           seed, ACTION_SCORE::begin_scores(action_scores), ACTION_SCORE::end_scores(action_scores), chosen_action);
       assert(result == S_EXPLORATION_OK);
       _UNUSED(result);
       // Update the seed state in place if it was used for this example.
       if (!tag_provided_seed)
       {
         _random_state->get_and_update_random();
       }
     }
     auto result = exploration::swap_chosen(action_scores.begin(), action_scores.end(), chosen_action);
     assert(result == S_EXPLORATION_OK);
     _UNUSED(result);
   }
Member Data Documentation
_random_state
std::shared_ptr<rand_state> VW::cb_sample_data::_random_state private
Definition at line 87 of file cb_sample.cc.
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/cb_sample.cc