Vowpal Wabbit: VW::config::options_i Struct Reference
VW::config::options_i Struct Reference abstract
#include <options.h>
Public Member Functions
virtual void add_and_parse (const option_group_definition &group)=0
virtual bool was_supplied (const std::string &key)=0
virtual std::string help ()=0
virtual std::vector< std::shared_ptr< base_option > > get_all_options ()=0
virtual std::shared_ptr< base_option > get_option (const std::string &key)=0
virtual void insert (const std::string &key, const std::string &value)=0
virtual void replace (const std::string &key, const std::string &value)=0
template<typename T >
typed_option< T > & get_typed_option (const std::string &key)
virtual void check_unregistered ()=0
virtual ~options_i ()=default
Detailed Description
Definition at line 107 of file options.h.
Constructor & Destructor Documentation
~options_i()
virtual VW::config::options_i::~options_i () virtual default
Member Function Documentation
add_and_parse()
virtual void VW::config::options_i::add_and_parse (const option_group_definition & group) pure virtual
Implemented in VW::config::options_boost_po.
Referenced by active_cover_setup(), active_setup(), audit_regressor_setup(), autolink_setup(), baseline_setup(), bfgs_setup(), binary_setup(), boosting_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_explore_setup(), cb_sample_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), classweight_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), CSOAA::csoaa_setup(), ect_setup(), explore_eval_setup(), ExpReplay::expreplay_setup(), ftrl_setup(), gd_mf_setup(), Search::handle_condition_options(), EntityRelationTask::initialize(), SelectiveBranchingMT::initialize(), DepParserTask::initialize(), GraphTask::initialize(), SequenceSpanTask::initialize(), ArgmaxTask::initialize(), interact_setup(), kernel_svm_setup(), lda_setup(), log_multi_setup(), lrq_setup(), lrqfa_setup(), marginal_setup(), memory_tree_setup(), mf_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), noop_setup(), oaa_setup(), OjaNewton_setup(), parse_args(), parse_diagnostics(), parse_example_tweaks(), parse_feature_tweaks(), parse_modules(), parse_output_model(), parse_output_preds(), parse_source(), print_setup(), recall_tree_setup(), scorer_setup(), sender_setup(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), GD::setup(), Search::setup(), stagewise_poly_setup(), svrg_setup(), topk_setup(), and warm_cb_setup().
check_unregistered()
virtual void VW::config::options_i::check_unregistered () pure virtual
Implemented in VW::config::options_boost_po.
Referenced by VW::initialize().
get_all_options()
virtual std::vector<std::shared_ptr<base_option> > VW::config::options_i::get_all_options () pure virtual
Implemented in VW::config::options_boost_po.
Referenced by save_load_header(), and VW::seed_vw_model().
get_option()
virtual std::shared_ptr<base_option> VW::config::options_i::get_option (const std::string & key) pure virtual
Implemented in VW::config::options_boost_po.
get_typed_option()
template<typename T > typed_option<T>& VW::config::options_i::get_typed_option (const std::string & key) inline
Definition at line 120 of file options.h.
References VW::config::base_option::m_type_hash.
Referenced by bfgs_setup(), Search::end_examples(), GD::end_pass(), Search::end_pass(), ftrl_setup(), gd_mf_setup(), get_best_constant(), init_driver(), VW::initialize(), GD::setup(), and Search::setup().
   {
     base_option& base = *get_option(key);
     if (base.m_type_hash != typed_option<T>::type_hash())
     {
       throw std::bad_cast();
     }
     return dynamic_cast<typed_option<T>&>(base);
   }
help()
virtual std::string VW::config::options_i::help () pure virtual
Implemented in VW::config::options_boost_po.
Referenced by VW::initialize().
insert()
virtual void VW::config::options_i::insert (const std::string & key, const std::string & value) pure virtual
Implemented in VW::config::options_boost_po.
Referenced by cb_adf_setup(), cb_algs_setup(), cb_explore_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), explore_eval_setup(), load_header_merge_options(), mwt_setup(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), Search::setup(), and warm_cb_setup().
replace()
virtual void VW::config::options_i::replace (const std::string & key, const std::string & value) pure virtual
Implemented in VW::config::options_boost_po.
Referenced by Search::end_examples(), GD::end_pass(), Search::end_pass(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), and Search::setup().
was_supplied()
virtual bool VW::config::options_i::was_supplied (const std::string & key) pure virtual
Implemented in VW::config::options_boost_po.
Referenced by active_cover_setup(), active_setup(), audit_regressor_setup(), autolink_setup(), boosting_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_explore_setup(), cb_sample_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), check_interaction_settings_collision(), classweight_setup(), cs_active_setup(), CSOAA::csldf_setup(), CSOAA::csoaa_setup(), ect_setup(), enable_sources(), explore_eval_setup(), ExpReplay::expreplay_setup(), VW::finish(), ftrl_setup(), gd_mf_setup(), get_best_constant(), init_driver(), VW::initialize(), interact_setup(), kernel_svm_setup(), lda_setup(), log_multi_setup(), lrq_setup(), lrqfa_setup(), marginal_setup(), mf_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), oaa_setup(), OjaNewton_setup(), parse_args(), parse_diagnostics(), parse_example_tweaks(), parse_feature_tweaks(), parse_output_model(), parse_output_preds(), parse_source(), recall_tree_setup(), save_load_header(), VW::seed_vw_model(), sender_setup(), setup(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), GD::setup(), Search::setup(), topk_setup(), VW::shared_feature_merger::use_reduction(), and warm_cb_setup().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/options.h