Vowpal Wabbit: SlotsState< audit > Struct Template Reference
SlotsState< audit > Struct Template Reference
#include <parse_example_json.h>
Public Member Functions
SlotsState ()
BaseState< audit > * StartArray (Context< audit > &ctx) override
BaseState< audit > * StartObject (Context< audit > &ctx) override
BaseState< audit > * EndArray (Context< audit > &ctx, rapidjson::SizeType) override
Public Member Functions inherited from BaseState< audit >
BaseState (const char *pname)
virtual BaseState< audit > * Null (Context< audit > &ctx)
virtual BaseState< audit > * Bool (Context< audit > &ctx, bool b)
virtual BaseState< audit > * Float (Context< audit > &ctx, float v)
virtual BaseState< audit > * Uint (Context< audit > &ctx, unsigned v)
virtual BaseState< audit > * String (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * Key (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * EndObject (Context< audit > &ctx, rapidjson::SizeType)
Public Attributes
BaseState< audit > * saved
BaseState< audit > * saved_root_state
Public Attributes inherited from BaseState< audit >
const char * name
Detailed Description
template<bool audit>
struct SlotsState< audit >
Definition at line 488 of file parse_example_json.h.
Constructor & Destructor Documentation
SlotsState()
template<bool audit> SlotsState< audit >::SlotsState () inline
Definition at line 490 of file parse_example_json.h.
 : BaseState<audit>("Slots") {}
Member Function Documentation
EndArray()
template<bool audit> BaseState<audit>* SlotsState< audit >::EndArray (Context< audit > & ctx, rapidjson::SizeType) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 522 of file parse_example_json.h.
References Context< audit >::default_state, Context< audit >::ex, Context< audit >::examples, Context< audit >::PushNamespace(), and Context< audit >::root_state.
   {
     // return to shared example
     ctx.ex = (*ctx.examples)[0];
     ctx.PushNamespace(" ", saved);
     ctx.root_state = saved_root_state;
     return &ctx.default_state;
   }
StartArray()
template<bool audit> BaseState<audit>* SlotsState< audit >::StartArray (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 494 of file parse_example_json.h.
References Context< audit >::PopNamespace(), and Context< audit >::root_state.
   {
     // drain existing added namespace
     // todo check bounds
     saved = ctx.PopNamespace();
     saved_root_state = ctx.root_state;
     ctx.root_state = this;
     return this;
   }
StartObject()
template<bool audit> BaseState<audit>* SlotsState< audit >::StartObject (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 504 of file parse_example_json.h.
References Context< audit >::all, polylabel::conditional_contextual_bandit, label_parser::default_label, Context< audit >::default_state, Context< audit >::ex, Context< audit >::example_factory, Context< audit >::example_factory_context, Context< audit >::examples, example::l, Context< audit >::label_index_state, parser::lp, vw::p, v_array< T >::push_back(), Context< audit >::PushNamespace(), v_array< T >::size(), CCB::slot, and CCB::label::type.
   {
     // allocate new example
     ctx.ex = &(*ctx.example_factory)(ctx.example_factory_context);
     ctx.all->p->lp.default_label(&ctx.ex->l);
     ctx.ex->l.conditional_contextual_bandit.type = CCB::example_type::slot;
     ctx.examples->push_back(ctx.ex);
     // The end object logic assumes shared example so we need to take an extra one here.
     ctx.label_index_state.index = static_cast<int>(ctx.examples->size()) - 2;
     // setup default namespace
     ctx.PushNamespace(" ", this);
     return &ctx.default_state;
   }
Member Data Documentation
saved
template<bool audit> BaseState<audit>* SlotsState< audit >::saved
Definition at line 491 of file parse_example_json.h.
saved_root_state
template<bool audit> BaseState<audit>* SlotsState< audit >::saved_root_state
Definition at line 492 of file parse_example_json.h.
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/parse_example_json.h