Vowpal Wabbit: VW::cb_explore_adf::softmax::cb_explore_adf_softmax Struct Reference
VW::cb_explore_adf::softmax::cb_explore_adf_softmax Struct Reference
Public Member Functions
cb_explore_adf_softmax (float epsilon, float lambda)
~cb_explore_adf_softmax ()=default
void predict (LEARNER::multi_learner &base, multi_ex &examples)
void learn (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void predict_or_learn_impl (LEARNER::multi_learner &base, multi_ex &examples)
Private Attributes
float _epsilon
float _lambda
Detailed Description
Definition at line 19 of file cb_explore_adf_softmax.cc.
Constructor & Destructor Documentation
cb_explore_adf_softmax()
VW::cb_explore_adf::softmax::cb_explore_adf_softmax::cb_explore_adf_softmax (float epsilon, float lambda)
Definition at line 38 of file cb_explore_adf_softmax.cc.
 : _epsilon(epsilon), _lambda(lambda) {}
~cb_explore_adf_softmax()
VW::cb_explore_adf::softmax::cb_explore_adf_softmax::~cb_explore_adf_softmax () default
Member Function Documentation
learn()
void VW::cb_explore_adf::softmax::cb_explore_adf_softmax::learn (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 31 of file cb_explore_adf_softmax.cc.
References predict_or_learn_impl().
 { predict_or_learn_impl<true>(base, examples); }
predict()
void VW::cb_explore_adf::softmax::cb_explore_adf_softmax::predict (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 30 of file cb_explore_adf_softmax.cc.
 { predict_or_learn_impl<false>(base, examples); }
predict_or_learn_impl()
template<bool is_learn> void VW::cb_explore_adf::softmax::cb_explore_adf_softmax::predict_or_learn_impl (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 41 of file cb_explore_adf_softmax.cc.
References _epsilon, _lambda, ACTION_SCORE::begin_scores(), ACTION_SCORE::end_scores(), exploration::enforce_minimum_probability(), and exploration::generate_softmax().
Referenced by learn().
 {
   LEARNER::multiline_learn_or_predict<is_learn>(base, examples, examples[0]->ft_offset);
   v_array<ACTION_SCORE::action_score>& preds = examples[0]->pred.a_s;
   exploration::generate_softmax(
       -_lambda, begin_scores(preds), end_scores(preds), begin_scores(preds), end_scores(preds));
   exploration::enforce_minimum_probability(_epsilon, true, begin_scores(preds), end_scores(preds));
 }
Member Data Documentation
_epsilon
float VW::cb_explore_adf::softmax::cb_explore_adf_softmax::_epsilon private
Definition at line 22 of file cb_explore_adf_softmax.cc.
Referenced by predict_or_learn_impl().
_lambda
float VW::cb_explore_adf::softmax::cb_explore_adf_softmax::_lambda private
Definition at line 23 of file cb_explore_adf_softmax.cc.
Referenced by predict_or_learn_impl().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/cb_explore_adf_softmax.cc