Vowpal Wabbit: label_parser Struct Reference
label_parser Struct Reference
#include <label_parser.h>
Public Attributes
void(* default_label)(void *)
void(* parse_label)(parser *, shared_data *, void *, v_array< substring > &)
void(* cache_label)(void *, io_buf &cache)
size_t(* read_cached_label)(shared_data *, void *, io_buf &cache)
void(* delete_label)(void *)
float(* get_weight)(void *)
void(* copy_label)(void *, void *)
bool(* test_label)(void *)
size_t label_size
Detailed Description
Definition at line 10 of file label_parser.h.
Member Data Documentation
cache_label
void(* label_parser::cache_label) (void *, io_buf &cache)
Definition at line 14 of file label_parser.h.
Referenced by learn(), and VW::setup_example().
copy_label
void(* label_parser::copy_label) (void *, void *)
Definition at line 18 of file label_parser.h.
Referenced by Search::search_predict(), and ezexample::train().
default_label
void(* label_parser::default_label) (void *)
Definition at line 12 of file label_parser.h.
Referenced by copy_example_to_adf(), end_pass_example(), DefaultState< audit >::EndObject(), ezexample::get_new_example(), VW::import_example(), VWReaderHandler< audit >::init(), init_adf_data(), SequenceTask_DemoLDF::initialize(), VW::new_unused_example(), parse_dispatch(), Search::search_initialize(), Search::setup(), Search::single_prediction_LDF(), LabelObjectState< audit >::StartObject(), MultiState< audit >::StartObject(), SlotsState< audit >::StartObject(), and substring_to_example().
delete_label
void(* label_parser::delete_label) (void *)
Definition at line 16 of file label_parser.h.
Referenced by free_parser(), memory_tree_setup(), multilabel_oaa_setup(), parse_dictionary_argument(), Search::train_single_example(), baseline::~baseline(), CB_ALGS::cb::~cb(), CB_EXPLORE::cb_explore::~cb_explore(), cbify::~cbify(), Search::search::~search(), and warm_cb::~warm_cb().
get_weight
float(* label_parser::get_weight) (void *)
Definition at line 17 of file label_parser.h.
Referenced by ezexample::mini_setup_example(), and VW::setup_example().
label_size
size_t label_parser::label_size
Definition at line 23 of file label_parser.h.
Referenced by baseline_setup(), parse_dictionary_argument(), and ezexample::train().
parse_label
void(* label_parser::parse_label) (parser *, shared_data *, void *, v_array< substring > &)
Definition at line 13 of file label_parser.h.
Referenced by VW::parse_example_label(), and substring_to_example().
read_cached_label
size_t(* label_parser::read_cached_label) (shared_data *, void *, io_buf &cache)
Definition at line 15 of file label_parser.h.
Referenced by read_cached_features().
test_label
bool(* label_parser::test_label) (void *)
Definition at line 22 of file label_parser.h.
Referenced by copy_example_to_adf(), Search::mc_label_is_test(), CB_ALGS::output_example(), Search::search::set_label_parser(), VW::setup_example(), and CSOAA::test_ldf_sequence().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/label_parser.h