Vowpal Wabbit: VW::cb_explore_adf::first::cb_explore_adf_first Struct Reference
VW::cb_explore_adf::first::cb_explore_adf_first Struct Reference
Public Member Functions
cb_explore_adf_first (size_t tau, float epsilon)
~cb_explore_adf_first ()=default
void predict (LEARNER::multi_learner &base, multi_ex &examples)
void learn (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void predict_or_learn_impl (LEARNER::multi_learner &base, multi_ex &examples)
Private Attributes
size_t _tau
float _epsilon
Detailed Description
Definition at line 21 of file cb_explore_adf_first.cc.
Constructor & Destructor Documentation
cb_explore_adf_first()
VW::cb_explore_adf::first::cb_explore_adf_first::cb_explore_adf_first (size_t tau, float epsilon)
Definition at line 40 of file cb_explore_adf_first.cc.
 : _tau(tau), _epsilon(epsilon) {}
~cb_explore_adf_first()
VW::cb_explore_adf::first::cb_explore_adf_first::~cb_explore_adf_first () default
Member Function Documentation
learn()
void VW::cb_explore_adf::first::cb_explore_adf_first::learn (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 33 of file cb_explore_adf_first.cc.
References predict_or_learn_impl().
 { predict_or_learn_impl<true>(base, examples); }
predict()
void VW::cb_explore_adf::first::cb_explore_adf_first::predict (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 32 of file cb_explore_adf_first.cc.
 { predict_or_learn_impl<false>(base, examples); }
predict_or_learn_impl()
template<bool is_learn> void VW::cb_explore_adf::first::cb_explore_adf_first::predict_or_learn_impl (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 43 of file cb_explore_adf_first.cc.
References _epsilon, _tau, ACTION_SCORE::begin_scores(), ACTION_SCORE::end_scores(), exploration::enforce_minimum_probability(), prediction_type::prob, and v_array< T >::size().
Referenced by learn().
 {
   // Explore tau times, then act according to optimal.
   if (is_learn)
     LEARNER::multiline_learn_or_predict<true>(base, examples, examples[0]->ft_offset);
   else
     LEARNER::multiline_learn_or_predict<false>(base, examples, examples[0]->ft_offset);
   v_array<ACTION_SCORE::action_score>& preds = examples[0]->pred.a_s;
   uint32_t num_actions = (uint32_t)preds.size();
   if (_tau)
   {
     float prob = 1.f / (float)num_actions;
     for (size_t i = 0; i < num_actions; i++) preds[i].score = prob;
     if (is_learn)
       _tau--;
   }
   else
   {
     for (size_t i = 1; i < num_actions; i++) preds[i].score = 0.;
     preds[0].score = 1.0;
   }
   exploration::enforce_minimum_probability(_epsilon, true, begin_scores(preds), end_scores(preds));
 }
Member Data Documentation
_epsilon
float VW::cb_explore_adf::first::cb_explore_adf_first::_epsilon private
Definition at line 25 of file cb_explore_adf_first.cc.
Referenced by predict_or_learn_impl().
_tau
size_t VW::cb_explore_adf::first::cb_explore_adf_first::_tau private
Definition at line 24 of file cb_explore_adf_first.cc.
Referenced by predict_or_learn_impl().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/cb_explore_adf_first.cc