Vowpal Wabbit: VW::autolink Struct Reference
VW::autolink Struct Reference
Public Member Functions
autolink (uint32_t d, uint32_t stride_shift)
void predict (LEARNER::single_learner &base, example &ec)
void learn (LEARNER::single_learner &base, example &ec)
Private Member Functions
void prepare_example (LEARNER::single_learner &base, example &ec)
void reset_example (example &ec)
Private Attributes
const uint32_t _poly_degree
const uint32_t _stride_shift
Static Private Attributes
static constexpr int AUTOCONSTANT = 524267083
Detailed Description
Definition at line 13 of file autolink.cc.
Constructor & Destructor Documentation
autolink()
VW::autolink::autolink (uint32_t d, uint32_t stride_shift)
Definition at line 30 of file autolink.cc.
     : _poly_degree(poly_degree), _stride_shift(stride_shift)
 {
 }
Member Function Documentation
learn()
void VW::autolink::learn (LEARNER::single_learner & base, example & ec)
Definition at line 42 of file autolink.cc.
References LEARNER::learner< T, E >::learn(), prepare_example(), and reset_example().
Referenced by predict_or_learn().
 {
   prepare_example(base, ec);
   base.learn(ec);
   reset_example(ec);
 }
predict()
void VW::autolink::predict (LEARNER::single_learner & base, example & ec)
Definition at line 35 of file autolink.cc.
References LEARNER::learner< T, E >::predict(), prepare_example(), and reset_example().
Referenced by predict_or_learn().
 {
   prepare_example(base, ec);
   base.predict(ec);
   reset_example(ec);
 }
prepare_example()
void VW::autolink::prepare_example (LEARNER::single_learner & base, example & ec) private
Definition at line 49 of file autolink.cc.
References _poly_degree, _stride_shift, AUTOCONSTANT, autolink_namespace, example_predict::feature_space, example_predict::indices, example::pred, LEARNER::learner< T, E >::predict(), v_array< T >::push_back(), features::push_back(), polyprediction::scalar, features::sum_feat_sq, and example::total_sum_feat_sq.
Referenced by learn(), and predict().
 {
   base.predict(ec);
   float base_pred = ec.pred.scalar;
   // Add features of label.
   ec.indices.push_back(autolink_namespace);
   features& fs = ec.feature_space[autolink_namespace];
   for (size_t i = 0; i < _poly_degree; i++)
   {
     if (base_pred != 0.)
     {
       fs.push_back(base_pred, AUTOCONSTANT + (i << _stride_shift));
       base_pred *= ec.pred.scalar;
     }
   }
   ec.total_sum_feat_sq += fs.sum_feat_sq;
 }
reset_example()
void VW::autolink::reset_example (example & ec) private
Definition at line 68 of file autolink.cc.
References autolink_namespace, features::clear(), example_predict::feature_space, example_predict::indices, v_array< T >::pop(), features::sum_feat_sq, and example::total_sum_feat_sq.
Referenced by learn(), and predict().
 {
   features& fs = ec.feature_space[autolink_namespace];
   ec.total_sum_feat_sq -= fs.sum_feat_sq;
   fs.clear();
   ec.indices.pop();
 }
Member Data Documentation
_poly_degree
const uint32_t VW::autolink::_poly_degree private
Definition at line 24 of file autolink.cc.
Referenced by prepare_example().
_stride_shift
const uint32_t VW::autolink::_stride_shift private
Definition at line 25 of file autolink.cc.
Referenced by prepare_example().
AUTOCONSTANT
constexpr int VW::autolink::AUTOCONSTANT = 524267083 static private
Definition at line 26 of file autolink.cc.
Referenced by prepare_example().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/autolink.cc