Vowpal Wabbit: VW::config::option_group_definition Struct Reference
VW::config::option_group_definition Struct Reference
#include <options.h>
Public Member Functions
option_group_definition (const std::string &name)
template<typename T >
option_group_definition & add (T &&op)
template<typename T >
option_group_definition & operator() (T &&op)
Public Attributes
std::string m_name
std::vector< std::shared_ptr< base_option > > m_options
Detailed Description
Definition at line 85 of file options.h.
Constructor & Destructor Documentation
option_group_definition()
VW::config::option_group_definition::option_group_definition (const std::string & name) inline
Definition at line 87 of file options.h.
 : m_name(name) {}
Member Function Documentation
add()
template<typename T > option_group_definition& VW::config::option_group_definition::add (T && op) inline
Definition at line 90 of file options.h.
Referenced by active_setup(), audit_regressor_setup(), autolink_setup(), baseline_setup(), bfgs_setup(), binary_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_sample_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), ect_setup(), explore_eval_setup(), ftrl_setup(), gd_mf_setup(), Search::handle_condition_options(), SelectiveBranchingMT::initialize(), GraphTask::initialize(), SequenceSpanTask::initialize(), ArgmaxTask::initialize(), interact_setup(), kernel_svm_setup(), lrq_setup(), lrqfa_setup(), main(), marginal_setup(), mwt_setup(), nn_setup(), noop_setup(), oaa_setup(), OjaNewton_setup(), parse_args(), parse_diagnostics(), parse_example_tweaks(), parse_feature_tweaks(), parse_modules(), parse_output_model(), parse_output_preds(), parse_source(), print_setup(), scorer_setup(), sender_setup(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), VW::cb_explore_adf::regcb::setup(), GD::setup(), Search::setup(), stagewise_poly_setup(), svrg_setup(), topk_setup(), and warm_cb_setup().
   {
     m_options.push_back(std::make_shared<typename std::decay<T>::type>(op));
     return *this;
   }
operator()()
template<typename T > option_group_definition& VW::config::option_group_definition::operator() (T && op) inline
Definition at line 97 of file options.h.
References add().
   {
     add(std::forward<T>(op));
     return *this;
   }
Member Data Documentation
m_name
std::string VW::config::option_group_definition::m_name
Definition at line 103 of file options.h.
Referenced by VW::config::options_boost_po::add_and_parse().
m_options
std::vector<std::shared_ptr<base_option> > VW::config::option_group_definition::m_options
Definition at line 104 of file options.h.
Referenced by VW::config::options_boost_po::add_and_parse().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/options.h