Vowpal Wabbit: MultiState< audit > Struct Template Reference
MultiState< audit > Struct Template Reference
#include <parse_example_json.h>
Public Member Functions
MultiState ()
BaseState< audit > * StartArray (Context< audit > &ctx) override
BaseState< audit > * StartObject (Context< audit > &ctx) override
BaseState< audit > * EndArray (Context< audit > &ctx, rapidjson::SizeType) override
Public Member Functions inherited from BaseState< audit >
BaseState (const char *pname)
virtual BaseState< audit > * Null (Context< audit > &ctx)
virtual BaseState< audit > * Bool (Context< audit > &ctx, bool b)
virtual BaseState< audit > * Float (Context< audit > &ctx, float v)
virtual BaseState< audit > * Uint (Context< audit > &ctx, unsigned v)
virtual BaseState< audit > * String (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * Key (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * EndObject (Context< audit > &ctx, rapidjson::SizeType)
Additional Inherited Members
Public Attributes inherited from BaseState< audit >
const char * name
Detailed Description
template<bool audit>
struct MultiState< audit >
Definition at line 429 of file parse_example_json.h.
Constructor & Destructor Documentation
MultiState()
template<bool audit> MultiState< audit >::MultiState () inline
Definition at line 431 of file parse_example_json.h.
 : BaseState<audit>("Multi") {}
Member Function Documentation
EndArray()
template<bool audit> BaseState<audit>* MultiState< audit >::EndArray (Context< audit > & ctx, rapidjson::SizeType) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 477 of file parse_example_json.h.
References Context< audit >::default_state, Context< audit >::ex, and Context< audit >::examples.
   {
     // return to shared example
     ctx.ex = (*ctx.examples)[0];
     return &ctx.default_state;
   }
StartArray()
template<bool audit> BaseState<audit>* MultiState< audit >::StartArray (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 433 of file parse_example_json.h.
References CB::cb_class::action, Context< audit >::all, polylabel::cb, label_type::cb, label_type::ccb, polylabel::conditional_contextual_bandit, CB::cb_class::cost, CB::label::costs, Context< audit >::ex, f, example::l, vw::label_type, CB::cb_class::partial_prediction, CB::cb_class::probability, CCB::shared, THROW, CCB::label::type, and uniform_hash().
   {
     // mark shared example
     if (ctx.all->label_type == label_type::cb)
     {
       CB::label* ld = &ctx.ex->l.cb;
       CB::cb_class f;
       f.partial_prediction = 0.;
       f.action = (uint32_t)uniform_hash("shared", 6, 0);
       f.cost = FLT_MAX;
       f.probability = -1.f;
       ld->costs.push_back(f);
     }
     else if (ctx.all->label_type == label_type::ccb)
     {
       CCB::label* ld = &ctx.ex->l.conditional_contextual_bandit;
       ld->type = CCB::example_type::shared;
     }
     else
       THROW("label type is not CB or CCB")
     return this;
   }
StartObject()
template<bool audit> BaseState<audit>* MultiState< audit >::StartObject (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 459 of file parse_example_json.h.
References Context< audit >::all, label_type::ccb, polylabel::conditional_contextual_bandit, label_parser::default_label, Context< audit >::default_state, Context< audit >::ex, Context< audit >::example_factory, Context< audit >::example_factory_context, Context< audit >::examples, example::l, vw::label_type, parser::lp, vw::p, v_array< T >::push_back(), Context< audit >::PushNamespace(), and CCB::label::type.
   {
     // allocate new example
     ctx.ex = &(*ctx.example_factory)(ctx.example_factory_context);
     ctx.all->p->lp.default_label(&ctx.ex->l);
     if (ctx.all->label_type == label_type::ccb)
     {
       ctx.ex->l.conditional_contextual_bandit.type = CCB::example_type::action;
     }
     ctx.examples->push_back(ctx.ex);
     // setup default namespace
     ctx.PushNamespace(" ", this);
     return &ctx.default_state;
   }
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/parse_example_json.h