Vowpal Wabbit: Search::search Struct Reference
Search::search Struct Reference
#include <search.h>
Public Member Functions
template<class T >
void set_task_data (T *data)
template<class T >
T * get_task_data ()
template<class T >
void set_metatask_data (T *data)
template<class T >
T * get_metatask_data ()
void set_options (uint32_t opts)
void set_label_parser (label_parser &lp, bool(*is_test)(polylabel &))
void loss (float incr_loss)
action predict (example &ec, ptag my_tag, const action *oracle_actions, size_t oracle_actions_cnt=1, const ptag *condition_on=nullptr, const char *condition_on_names=nullptr, const action *allowed_actions=nullptr, size_t allowed_actions_cnt=0, const float *allowed_actions_cost=nullptr, size_t learner_id=0, float weight=0.)
action predictLDF (example *ecs, size_t ec_cnt, ptag my_tag, const action *oracle_actions, size_t oracle_actions_cnt=1, const ptag *condition_on=nullptr, const char *condition_on_names=nullptr, size_t learner_id=0, float weight=0.)
bool predictNeedsExample ()
uint32_t get_history_length ()
bool is_ldf ()
std::stringstream & output ()
void set_num_learners (size_t num_learners)
void get_test_action_sequence (std::vector< action > &)
uint64_t get_mask ()
size_t get_stride_shift ()
std::string pretty_label (action a)
BaseTask base_task (multi_ex &ec)
vw & get_vw_pointer_unsafe ()
void set_force_oracle (bool force)
search ()
~search ()
Public Attributes
search_private * priv
void * task_data
void * metatask_data
const char * task_name
const char * metatask_name
Detailed Description
Definition at line 80 of file search.h.
Constructor & Destructor Documentation
search()
Search::search::search ()
Definition at line 295 of file search.cc.
 { priv = &calloc_or_throw<search_private>(); }
~search()
Search::search::~search ()
Definition at line 297 of file search.cc.
References Search::search_private::_random_state, Search::search_private::active_known, Search::search_private::active_uncertainty, Search::search_private::allowed_actions_cache, Search::audit_feature_space(), Search::search_private::bad_string_stream, Search::search_private::cache_hash_map, polylabel::cb, Search::search_private::cb_learner, cdbg, Search::clear_cache_hash_map(), Search::clear_memo_foreach_action(), Search::search_private::condition_on_actions, CB::label::costs, COST_SENSITIVE::label::costs, polylabel::cs, COST_SENSITIVE::cs_label, Search::search_private::dat_new_feature_audit_ss, VW::dealloc_example(), label_parser::delete_label, CB::delete_label(), v_array< T >::delete_v(), features::delete_v(), Search::search_private::examples_dont_change, Search::search_private::gte_label, Search::search_private::is_ldf, Search::search_private::last_action_repr, Search::search_private::ldf_test_label, Search::search_private::learn_allowed_actions, Search::search_private::learn_condition_on, Search::search_private::learn_condition_on_act, Search::search_private::learn_condition_on_names, Search::search_private::learn_ec_copy, Search::search_private::learn_losses, MULTICLASS::mc_label, Search::search_private::memo_foreach_action, Search::search_private::neighbor_features, Search::search_private::pred_string, Search::search_private::ptag_to_action, Search::search_private::rawOutputString, Search::search_private::rawOutputStringStream, Search::action_repr::repr, Search::search_private::test_action_sequence, Search::search_private::timesteps, Search::search_private::train_trajectory, and Search::search_private::truth_string.
 {
   if (this->priv && this->priv->all)
   {
     search_private& priv = *this->priv;
     clear_cache_hash_map(priv);
     priv._random_state.~shared_ptr<rand_state>();
     delete priv.truth_string;
     delete priv.pred_string;
     delete priv.bad_string_stream;
     priv.cache_hash_map.~v_hashmap<unsigned char*, scored_action>();
     priv.rawOutputString.~basic_string();
     priv.test_action_sequence.~vector<action>();
     priv.dat_new_feature_audit_ss.~basic_stringstream();
     priv.neighbor_features.delete_v();
     priv.timesteps.delete_v();
     if (priv.cb_learner)
       priv.learn_losses.cb.costs.delete_v();
     else
       priv.learn_losses.cs.costs.delete_v();
     if (priv.cb_learner)
       priv.gte_label.cb.costs.delete_v();
     else
       priv.gte_label.cs.costs.delete_v();
     priv.condition_on_actions.delete_v();
     priv.learn_allowed_actions.delete_v();
     priv.ldf_test_label.costs.delete_v();
     priv.last_action_repr.delete_v();
     priv.active_uncertainty.delete_v();
     for (size_t i = 0; i < priv.active_known.size(); i++) priv.active_known[i].delete_v();
     priv.active_known.delete_v();
     if (priv.cb_learner)
       priv.allowed_actions_cache->cb.costs.delete_v();
     else
       priv.allowed_actions_cache->cs.costs.delete_v();
     priv.train_trajectory.delete_v();
     for (Search::action_repr& ar : priv.ptag_to_action)
     {
       if (ar.repr != nullptr)
       {
         ar.repr->delete_v();
         delete ar.repr;
         cdbg << "delete_v" << endl;
       }
     }
     priv.ptag_to_action.delete_v();
     clear_memo_foreach_action(priv);
     priv.memo_foreach_action.delete_v();
     // destroy copied examples if we needed them
     if (!priv.examples_dont_change)
     {
       void (*delete_label)(void*) = priv.is_ldf ? CS::cs_label.delete_label : MC::mc_label.delete_label;
       for (example& ec : priv.learn_ec_copy) VW::dealloc_example(delete_label, ec);
       priv.learn_ec_copy.delete_v();
     }
     priv.learn_condition_on_names.delete_v();
     priv.learn_condition_on.delete_v();
     priv.learn_condition_on_act.delete_v();
     free(priv.allowed_actions_cache);
     delete priv.rawOutputStringStream;
   }
   free(this->priv);
 }
Member Function Documentation
base_task()
BaseTask Search::search::base_task (multi_ex & ec) inline
Definition at line 213 of file search.h.
References Search::BaseTask::BaseTask().
Referenced by DebugMT::run(), and SelectiveBranchingMT::run().
 { return BaseTask(this, ec); }
get_history_length()
uint32_t Search::search::get_history_length ()
Definition at line 3098 of file search.cc.
References Search::search_private::history_length.
Referenced by SequenceTask::run(), SequenceSpanTask::run(), SequenceTaskCostToGo::run(), SequenceTask_DemoLDF::run(), and DepParserTask::run().
 { return (uint32_t)this->priv->history_length; }
get_mask()
uint64_t Search::search::get_mask ()
Definition at line 3096 of file search.cc.
References Search::search_private::all, parameters::mask(), and vw::weights.
Referenced by DepParserTask::extract_features().
 { return this->priv->all->weights.mask(); }
get_metatask_data()
template<class T > T* Search::search::get_metatask_data () inline
Definition at line 101 of file search.h.
References a, Search::BaseTask::ec, loss(), and predict().
Referenced by SelectiveBranchingMT::finish(), and SelectiveBranchingMT::run().
   {
     return (T*)metatask_data;
   }
get_stride_shift()
size_t Search::search::get_stride_shift ()
Definition at line 3097 of file search.cc.
References Search::search_private::all, parameters::stride_shift(), and vw::weights.
Referenced by SequenceTask_DemoLDF::my_update_example_indicies().
 { return this->priv->all->weights.stride_shift(); }
get_task_data()
template<class T > T* Search::search::get_task_data () inline
Definition at line 89 of file search.h.
Referenced by DepParserTask::convert_to_onelearner_actions(), EntityRelationTask::er_allow_skip_decoding(), DepParserTask::extract_features(), HookTask::finish(), MulticlassTask::finish(), EntityRelationTask::finish(), DepParserTask::finish(), GraphTask::finish(), SequenceSpanTask::finish(), ArgmaxTask::finish(), SequenceTask_DemoLDF::finish(), DepParserTask::get_cost_to_go_losses(), DepParserTask::get_eager_action_cost(), DepParserTask::get_gold_actions(), DepParserTask::get_hybrid_action_cost(), DepParserTask::get_valid_actions(), EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), MulticlassTask::run(), HookTask::run(), SequenceSpanTask::run(), SequenceTaskCostToGo::run(), ArgmaxTask::run(), GraphTask::run(), EntityRelationTask::run(), SequenceTask_DemoLDF::run(), DepParserTask::run(), HookTask::run_setup(), HookTask::run_takedown(), GraphTask::setup(), SequenceSpanTask::setup(), DepParserTask::setup(), SequenceSpanTask::takedown(), GraphTask::takedown(), DepParserTask::transition_eager(), and DepParserTask::transition_hybrid().
   {
     return (T*)task_data;
   }
get_test_action_sequence()
void Search::search::get_test_action_sequence (std::vector< action > & V)
Definition at line 3088 of file search.cc.
References Search::search_private::test_action_sequence.
 {
   V.clear();
   for (size_t i = 0; i < this->priv->test_action_sequence.size(); i++) V.push_back(this->priv->test_action_sequence[i]);
 }
get_vw_pointer_unsafe()
vw & Search::search::get_vw_pointer_unsafe ()
Definition at line 3115 of file search.cc.
References Search::search_private::all.
Referenced by GraphTask::add_edge_features(), DepParserTask::extract_features(), EntityRelationTask::initialize(), DepParserTask::initialize(), SequenceTask_DemoLDF::initialize(), and GraphTask::setup().
 { return *this->priv->all; }
is_ldf()
bool Search::search::is_ldf ()
Definition at line 2965 of file search.cc.
References Search::search_private::is_ldf.
 { return priv->is_ldf; }
loss()
void Search::search::loss (float incr_loss)
Definition at line 3039 of file search.cc.
References Search::search_declare_loss().
Referenced by EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), MulticlassTask::run(), ArgmaxTask::run(), GraphTask::run(), DepParserTask::run(), DepParserTask::transition_eager(), and DepParserTask::transition_hybrid().
 { search_declare_loss(*this->priv, loss); }
output()
std::stringstream & Search::search::output ()
Definition at line 3043 of file search.cc.
References Search::search_private::bad_string_stream, Search::GET_TRUTH_STRING, Search::search_private::pred_string, Search::search_private::should_produce_string, Search::search_private::state, and Search::search_private::truth_string.
Referenced by MulticlassTask::run(), SequenceTask::run(), SequenceSpanTask::run(), SequenceTaskCostToGo::run(), ArgmaxTask::run(), GraphTask::run(), EntityRelationTask::run(), SequenceTask_DemoLDF::run(), and DepParserTask::run().
 {
   if (!this->priv->should_produce_string)
     return *(this->priv->bad_string_stream);
   else if (this->priv->state == GET_TRUTH_STRING)
     return *(this->priv->truth_string);
   else
     return *(this->priv->pred_string);
 }
predict()
action Search::search::predict (example & ec, ptag my_tag, const action * oracle_actions, size_t oracle_actions_cnt = 1, const ptag * condition_on = nullptr, const char * condition_on_names = nullptr, const action * allowed_actions = nullptr, size_t allowed_actions_cnt = 0, const float * allowed_actions_cost = nullptr, size_t learner_id = 0, float weight = 0.)
Definition at line 2967 of file search.cc.
References a, Search::search_private::acset, Search::action_cost_loss(), Search::action_hamming_loss(), Search::search_private::auto_hamming_loss, cdbg, Search::INIT_TEST, Search::search_private::last_action_repr, loss(), Search::search_private::ptag_to_action, Search::push_at(), Search::search_predict(), Search::search_private::state, Search::search_private::test_action_sequence, Search::search_private::use_action_costs, and Search::auto_condition_settings::use_passthrough_repr.
Referenced by Search::predictor::predict(), MulticlassTask::run(), and ArgmaxTask::run().
 {
   float a_cost = 0.;
   action a = search_predict(*priv, &ec, 1, mytag, oracle_actions, oracle_actions_cnt, condition_on, condition_on_names,
       allowed_actions, allowed_actions_cnt, allowed_actions_cost, learner_id, a_cost, weight);
   if (priv->state == INIT_TEST)
     priv->test_action_sequence.push_back(a);
   if (mytag != 0)
   {
     if (mytag < priv->ptag_to_action.size())
     {
       cdbg << "delete_v at " << mytag << endl;
       if (priv->ptag_to_action[mytag].repr != nullptr)
       {
         priv->ptag_to_action[mytag].repr->delete_v();
         delete priv->ptag_to_action[mytag].repr;
       }
     }
     if (priv->acset.use_passthrough_repr)
     {
       assert((mytag >= priv->ptag_to_action.size()) || (priv->ptag_to_action[mytag].repr == nullptr));
       push_at(priv->ptag_to_action, action_repr(a, &(priv->last_action_repr)), mytag);
     }
     else
       push_at(priv->ptag_to_action, action_repr(a, (features*)nullptr), mytag);
     cdbg << "push_at " << mytag << endl;
   }
   if (priv->auto_hamming_loss)
     loss(priv->use_action_costs ? action_cost_loss(a, allowed_actions, allowed_actions_cost, allowed_actions_cnt)
                                 : action_hamming_loss(a, oracle_actions, oracle_actions_cnt));
   cdbg << "predict returning " << a << endl;
   return a;
 }
predictLDF()
action Search::search::predictLDF (example * ecs, size_t ec_cnt, ptag my_tag, const action * oracle_actions, size_t oracle_actions_cnt = 1, const ptag * condition_on = nullptr, const char * condition_on_names = nullptr, size_t learner_id = 0, float weight = 0.)
Definition at line 3003 of file search.cc.
References a, Search::action_hamming_loss(), Search::search_private::auto_hamming_loss, cdbg, COST_SENSITIVE::ec_is_example_header(), Search::INIT_TEST, Search::search_private::last_action_repr, loss(), Search::search_private::ptag_to_action, Search::push_at(), Search::search_predict(), Search::search_private::state, and Search::search_private::test_action_sequence.
Referenced by Search::predictor::predict().
 {
   float a_cost = 0.;
   // TODO: action costs for ldf
   action a = search_predict(*priv, ecs, ec_cnt, mytag, oracle_actions, oracle_actions_cnt, condition_on,
       condition_on_names, nullptr, 0, nullptr, learner_id, a_cost, weight);
   if (priv->state == INIT_TEST)
     priv->test_action_sequence.push_back(a);
   // If there is a shared example (example header), then action "1" is at index 1, but otherwise
   // action "1" is at index 0. Map action to its appropriate index. In particular, this fixes an
   // issue where the predicted action is the last, and there is no example header, causing an index
   // beyond the end of the array (usually resulting in a segfault at some point.)
   size_t action_index = a - COST_SENSITIVE::ec_is_example_header(ecs[0]) ? 0 : 1;
   if ((mytag != 0) && ecs[action_index].l.cs.costs.size() > 0)
   {
     if (mytag < priv->ptag_to_action.size())
     {
       cdbg << "delete_v at " << mytag << endl;
       if (priv->ptag_to_action[mytag].repr != nullptr)
       {
         priv->ptag_to_action[mytag].repr->delete_v();
         delete priv->ptag_to_action[mytag].repr;
       }
     }
     push_at(priv->ptag_to_action, action_repr(ecs[a].l.cs.costs[0].class_index, &(priv->last_action_repr)), mytag);
   }
   if (priv->auto_hamming_loss)
     loss(action_hamming_loss(a, oracle_actions, oracle_actions_cnt));  // TODO: action costs
   cdbg << "predict returning " << a << endl;
   return a;
 }
predictNeedsExample()
bool Search::search::predictNeedsExample ()
Definition at line 3041 of file search.cc.
References Search::search_predictNeedsExample().
Referenced by GraphTask::run(), SequenceTask_DemoLDF::run(), and DepParserTask::run().
 { return search_predictNeedsExample(*this->priv); }
pretty_label()
std::string Search::search::pretty_label (action a)
Definition at line 3100 of file search.cc.
References a, Search::search_private::all, substring::begin, substring::end, namedlabels::get(), shared_data::ldict, and vw::sd.
Referenced by SequenceTask::run(), and SequenceTaskCostToGo::run().
 {
   if (this->priv->all->sd->ldict)
   {
     substring ss = this->priv->all->sd->ldict->get(a);
     return std::string(ss.begin, ss.end - ss.begin);
   }
   else
   {
     std::ostringstream os;
     os << a;
     return os.str();
   }
 }
set_force_oracle()
void Search::search::set_force_oracle (bool force)
Definition at line 3116 of file search.cc.
References Search::search_private::force_oracle.
 { this->priv->force_oracle = force; }
set_label_parser()
void Search::search::set_label_parser (label_parser & lp, bool(*)(polylabel &) is_test)
Definition at line 3079 of file search.cc.
References Search::search_private::all, Search::INITIALIZE, Search::search_private::label_is_test, parser::lp, vw::p, label_parser::test_label, and vw::vw_is_main.
Referenced by DepParserTask::initialize(), and GraphTask::initialize().
 {
   if (this->priv->all->vw_is_main && (this->priv->state != INITIALIZE))
     std::cerr << "warning: task should not set label parser except in initialize function!" << endl;
   this->priv->all->p->lp = lp;
   this->priv->all->p->lp.test_label = (bool (*)(void*))is_test;
   this->priv->label_is_test = is_test;
 }
set_metatask_data()
template<class T > void Search::search::set_metatask_data (T * data) inline
Definition at line 96 of file search.h.
Referenced by SelectiveBranchingMT::initialize().
   {
     metatask_data = data;
   }
set_num_learners()
void Search::search::set_num_learners (size_t num_learners)
Definition at line 3094 of file search.cc.
References Search::search_private::num_learners.
Referenced by MulticlassTask::initialize(), EntityRelationTask::initialize(), DepParserTask::initialize(), GraphTask::initialize(), and SequenceSpanTask::initialize().
 { this->priv->num_learners = num_learners; }
set_options()
void Search::search::set_options (uint32_t opts)
Definition at line 3053 of file search.cc.
References Search::ACTION_COSTS, Search::search_private::all, Search::search_private::auto_condition_features, Search::AUTO_HAMMING_LOSS, Search::search_private::auto_hamming_loss, Search::EXAMPLES_DONT_CHANGE, Search::search_private::examples_dont_change, Search::INITIALIZE, Search::IS_LDF, Search::search_private::is_ldf, Search::NO_CACHING, Search::search_private::no_caching, Search::NO_ROLLOUT, THROW, Search::search_private::use_action_costs, and vw::vw_is_main.
Referenced by MulticlassTask::initialize(), SequenceTask::initialize(), EntityRelationTask::initialize(), DepParserTask::initialize(), GraphTask::initialize(), SequenceSpanTask::initialize(), SequenceTaskCostToGo::initialize(), ArgmaxTask::initialize(), and SequenceTask_DemoLDF::initialize().
 {
   if (this->priv->all->vw_is_main && (this->priv->state != INITIALIZE))
     std::cerr << "warning: task should not set options except in initialize function!" << endl;
   if ((opts & AUTO_CONDITION_FEATURES) != 0)
     this->priv->auto_condition_features = true;
   if ((opts & AUTO_HAMMING_LOSS) != 0)
     this->priv->auto_hamming_loss = true;
   if ((opts & EXAMPLES_DONT_CHANGE) != 0)
     this->priv->examples_dont_change = true;
   if ((opts & IS_LDF) != 0)
     this->priv->is_ldf = true;
   if ((opts & NO_CACHING) != 0)
     this->priv->no_caching = true;
   if ((opts & ACTION_COSTS) != 0)
     this->priv->use_action_costs = true;
   if (this->priv->is_ldf && this->priv->use_action_costs)
     THROW("using LDF and actions costs is not yet implemented; turn off action costs");  // TODO fix
   if (this->priv->use_action_costs && (this->priv->rollout_method != NO_ROLLOUT))
     std::cerr
         << "warning: task is designed to use rollout costs, but this only works when --search_rollout none is specified"
         << endl;
 }
set_task_data()
template<class T > void Search::search::set_task_data (T * data) inline
Definition at line 84 of file search.h.
Referenced by HookTask::initialize(), MulticlassTask::initialize(), EntityRelationTask::initialize(), DepParserTask::initialize(), GraphTask::initialize(), SequenceSpanTask::initialize(), SequenceTaskCostToGo::initialize(), ArgmaxTask::initialize(), and SequenceTask_DemoLDF::initialize().
   {
     task_data = data;
   }
Member Data Documentation
metatask_data
void* Search::search::metatask_data
Definition at line 218 of file search.h.
metatask_name
const char* Search::search::metatask_name
Definition at line 220 of file search.h.
priv
search_private* Search::search::priv
Definition at line 216 of file search.h.
Referenced by Search::do_actual_learning(), Search::end_examples(), Search::end_pass(), Search::finish_multiline_example(), Search::parse_neighbor_features(), Search::run_task(), Search::search_finish(), Search::search_initialize(), and Search::train_single_example().
task_data
void* Search::search::task_data
Definition at line 217 of file search.h.
Referenced by Search::search_initialize().
task_name
const char* Search::search::task_name
Definition at line 219 of file search.h.
The documentation for this struct was generated from the following files:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/search.h
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/search.cc