Vowpal Wabbit: svm_example Struct Reference
svm_example Struct Reference
Public Member Functions
~svm_example ()
void init_svm_example (flat_example *fec)
int compute_kernels (svm_params &params)
int clear_kernels ()
Public Attributes
v_array< float > krow
flat_example ex
Detailed Description
Definition at line 47 of file kernel_svm.cc.
Constructor & Destructor Documentation
~svm_example()
svm_example::~svm_example ()
Definition at line 155 of file kernel_svm.cc.
References free_flatten_example(), and kernel_function().
Referenced by predict(), and remove().
 {
   krow.delete_v();
   // free flatten example contents
   flat_example* fec = &calloc_or_throw<flat_example>();
   *fec = ex;
   free_flatten_example(fec);  // free contents of flat example and frees fec.
 }
Member Function Documentation
clear_kernels()
int svm_example::clear_kernels ()
Definition at line 194 of file kernel_svm.cc.
Referenced by trim_cache().
 {
   int rowsize = (int)krow.size();
   krow.end() = krow.begin();
   krow.resize(0);
   return -rowsize;
 }
compute_kernels()
int svm_example::compute_kernels (svm_params & params)
Definition at line 166 of file kernel_svm.cc.
References ex, kernel_function(), svm_params::kernel_params, svm_params::kernel_type, svm_params::model, num_cache_evals, num_kernel_evals, svm_model::num_support, and svm_model::support_vec.
Referenced by make_hot_sv(), predict(), and update().
 {
   int alloc = 0;
   svm_model* model = params.model;
   size_t n = model->num_support;
   if (krow.size() < n)
   {
     // computing new kernel values and caching them
     // if(params->curcache + n > params->maxcache)
     // trim_cache(params);
     num_kernel_evals += krow.size();
     // std::cerr<<"Kernels ";
     for (size_t i = krow.size(); i < n; i++)
     {
       svm_example* sec = model->support_vec[i];
       float kv = kernel_function(&ex, &(sec->ex), params.kernel_params, params.kernel_type);
       krow.push_back(kv);
       alloc += 1;
       // std::cerr<<kv<<" ";
     }
     // std::cerr<< endl;
   }
   else
     num_cache_evals += n;
   return alloc;
 }
init_svm_example()
void svm_example::init_svm_example (flat_example * fec)
Definition at line 149 of file kernel_svm.cc.
Referenced by learn(), predict(), save_load_svm_model(), and sync_queries().
 {
   ex = *fec;
   free(fec);
 }
Member Data Documentation
ex
flat_example svm_example::ex
Definition at line 50 of file kernel_svm.cc.
Referenced by compute_kernels(), sync_queries(), train(), and update().
krow
v_array<float> svm_example::krow
Definition at line 49 of file kernel_svm.cc.
Referenced by make_hot_sv(), remove(), trim_cache(), and update().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/kernel_svm.cc