Vowpal Wabbit: VW::LEARNER::learner< T, E > Struct Template Reference
VW::LEARNER::learner< T, E > Struct Template Reference
#include <learner.h>
Public Types
using end_fptr_type = void(*)(vw &, void *, void *)
using finish_fptr_type = void(*)(void *)
Public Member Functions
void learn (E &ec, size_t i=0)
void predict (E &ec, size_t i=0)
void multipredict (E &ec, size_t lo, size_t count, polyprediction *pred, bool finalize_predictions)
template<class L >
void set_predict (void(*u)(T &, L &, E &))
template<class L >
void set_learn (void(*u)(T &, L &, E &))
template<class L >
void set_multipredict (void(*u)(T &, L &, E &, size_t, size_t, polyprediction *, bool))
void update (E &ec, size_t i=0)
template<class L >
void set_update (void(*u)(T &data, L &base, E &))
void set_sensitivity (float(*u)(T &data, base_learner &base, example &))
float sensitivity (example &ec, size_t i=0)
void save_load (io_buf &io, const bool read, const bool text)
void set_save_load (void(*sl)(T &, io_buf &, bool, bool))
void set_finish (void(*f)(T &))
void finish ()
void end_pass ()
void set_end_pass (void(*f)(T &))
void end_examples ()
void set_end_examples (void(*f)(T &))
void init_driver ()
void set_init_driver (void(*f)(T &))
void finish_example (vw &all, E &ec)
void set_finish_example (void(*f)(vw &all, T &, E &))
Static Public Member Functions
template<class L >
static learner< T, E > & init_learner (T *dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws, prediction_type_t pred_type)
Public Attributes
prediction_type_t pred_type
size_t weights
size_t increment
bool is_multiline
Private Member Functions
learner ()
Private Attributes
func_data init_fd
learn_data learn_fd
sensitivity_data sensitivity_fd
finish_example_data finish_example_fd
save_load_data save_load_fd
func_data end_pass_fd
func_data end_examples_fd
func_data finisher_fd
std::shared_ptr< void > learner_data
Detailed Description
template<class T, class E>
struct VW::LEARNER::learner< T, E >
Definition at line 35 of file learner.h.
Member Typedef Documentation
end_fptr_type
template<class T, class E> using VW::LEARNER::learner< T, E >::end_fptr_type = void (*)(vw&, void*, void*)
Definition at line 154 of file learner.h.
finish_fptr_type
template<class T, class E> using VW::LEARNER::learner< T, E >::finish_fptr_type = void (*)(void*)
Definition at line 155 of file learner.h.
Constructor & Destructor Documentation
learner()
template<class T, class E> VW::LEARNER::learner< T, E >::learner () inline private
Definition at line 147 of file learner.h.
 {};  // Should only be able to construct a learner through init_learner function
Member Function Documentation
end_examples()
template<class T, class E> void VW::LEARNER::learner< T, E >::end_examples () inline
Definition at line 287 of file learner.h.
References VW::LEARNER::func_data::base, VW::LEARNER::func_data::data, VW::LEARNER::learner< T, E >::end_examples(), and VW::LEARNER::func_data::func.
Referenced by VW::LEARNER::learner< T, E >::end_examples().
   {
     end_examples_fd.func(end_examples_fd.data);
     if (end_examples_fd.base)
       end_examples_fd.base->end_examples();
   }
end_pass()
template<class T, class E> void VW::LEARNER::learner< T, E >::end_pass () inline
Definition at line 278 of file learner.h.
References VW::LEARNER::func_data::base, VW::LEARNER::func_data::data, VW::LEARNER::learner< T, E >::end_pass(), and VW::LEARNER::func_data::func.
Referenced by VW::LEARNER::learner< T, E >::end_pass().
   {
     end_pass_fd.func(end_pass_fd.data);
     if (end_pass_fd.base)
       end_pass_fd.base->end_pass();
   }  // autorecursive
finish()
template<class T, class E> void VW::LEARNER::learner< T, E >::finish () inline
Definition at line 264 of file learner.h.
References VW::LEARNER::func_data::base, VW::LEARNER::func_data::data, VW::LEARNER::learner< T, E >::finish(), and VW::LEARNER::func_data::func.
Referenced by VW::LEARNER::learner< T, E >::finish().
   {
     if (finisher_fd.data)
     {
       finisher_fd.func(finisher_fd.data);
     }
     learner_data.~shared_ptr<void>();
     if (finisher_fd.base)
     {
       finisher_fd.base->finish();
       free(finisher_fd.base);
     }
   }
finish_example()
template<class T, class E> void VW::LEARNER::learner< T, E >::finish_example (vw & all, E & ec) inline
Definition at line 300 of file learner.h.
References VW::LEARNER::finish_example_data::data, and VW::LEARNER::finish_example_data::finish_example_f.
   {
     finish_example_fd.finish_example_f(all, finish_example_fd.data, (void*)&ec);
   }
init_driver()
template<class T, class E> void VW::LEARNER::learner< T, E >::init_driver () inline
Definition at line 296 of file learner.h.
References VW::LEARNER::func_data::data, and VW::LEARNER::func_data::func.
 { init_fd.func(init_fd.data); }
init_learner()
template<class T, class E> template<class L > static learner<T, E>& VW::LEARNER::learner< T, E >::init_learner (T * dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t ws, prediction_type_t pred_type) inline static
Definition at line 312 of file learner.h.
References VW::LEARNER::learner< T, E >::end_examples_fd, VW::LEARNER::learner< T, E >::end_pass_fd, VW::LEARNER::learner< T, E >::finish_example_fd, VW::LEARNER::learner< T, E >::finisher_fd, VW::LEARNER::learner< T, E >::increment, VW::LEARNER::learner< T, E >::init_fd, VW::LEARNER::learner< T, E >::is_multiline, VW::LEARNER::learner< T, E >::learn_fd, VW::LEARNER::learner< T, E >::learner_data, VW::LEARNER::make_base(), VW::LEARNER::noop(), VW::LEARNER::noop_sensitivity(), VW::LEARNER::noop_sl(), VW::LEARNER::learner< T, E >::pred_type, return_simple_example(), VW::LEARNER::learner< T, E >::save_load_fd, VW::LEARNER::learner< T, E >::sensitivity_fd, and VW::LEARNER::learner< T, E >::weights.
   {
     learner<T, E>& ret = calloc_or_throw<learner<T, E> >();
     if (base != nullptr)
     {  // a reduction
       // This is a copy assignment into the current object. The purpose is to copy all of the
       // function data objects so that if this reduction does not define a function such as
       // save_load then calling save_load on this object will essentially result in forwarding the
       // call the next reduction that actually implements it.
       ret = *(learner<T, E>*)(base);
       ret.learn_fd.base = make_base(*base);
       ret.sensitivity_fd.sensitivity_f = (sensitivity_data::fn)recur_sensitivity;
       ret.finisher_fd.data = dat;
       ret.finisher_fd.base = make_base(*base);
       ret.finisher_fd.func = (func_data::fn)noop;
       ret.weights = ws;
       ret.increment = base->increment * ret.weights;
     }
     else  // a base learner
     {
       ret.weights = 1;
       ret.increment = ws;
       ret.end_pass_fd.func = (func_data::fn)noop;
       ret.end_examples_fd.func = (func_data::fn)noop;
       ret.init_fd.func = (func_data::fn)noop;
       ret.save_load_fd.save_load_f = (save_load_data::fn)noop_sl;
       ret.finisher_fd.data = dat;
       ret.finisher_fd.func = (func_data::fn)noop;
       ret.sensitivity_fd.sensitivity_f = (sensitivity_data::fn)noop_sensitivity;
       ret.finish_example_fd.data = dat;
       ret.finish_example_fd.finish_example_f = (finish_example_data::fn)return_simple_example;
     }
     ret.learner_data = std::shared_ptr<T>(dat, [](T* ptr) {
       ptr->~T();
       free(ptr);
     });
     ret.learn_fd.data = dat;
     ret.learn_fd.learn_f = (learn_data::fn)learn;
     ret.learn_fd.update_f = (learn_data::fn)learn;
     ret.learn_fd.predict_f = (learn_data::fn)predict;
     ret.learn_fd.multipredict_f = nullptr;
     ret.pred_type = pred_type;
     ret.is_multiline = std::is_same<multi_ex, E>::value;
     return ret;
   }
learn()
template<class T, class E> void VW::LEARNER::learner< T, E >::learn (E & ec, size_t i = 0) inline
Definition at line 158 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, VW::LEARNER::decrement_offset(), VW::LEARNER::increment_offset(), and VW::LEARNER::learn_data::learn_f.
Referenced by GEN_CS::call_cs_ldf(), ExpReplay::end_pass(), CB_ALGS::get_cost_pred(), VW::LEARNER::multiline_learn_or_predict(), and ExpReplay::predict_or_learn().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     increment_offset(ec, increment, i);
     learn_fd.learn_f(learn_fd.data, *learn_fd.base, (void*)&ec);
     decrement_offset(ec, increment, i);
   }
multipredict()
template<class T, class E> void VW::LEARNER::learner< T, E >::multipredict (E & ec, size_t lo, size_t count, polyprediction * pred, bool finalize_predictions) inline
Definition at line 176 of file learner.h.
References VW::LEARNER::learn_data::base, exploration::c, VW::LEARNER::learn_data::data, VW::LEARNER::decrement_offset(), VW::LEARNER::increment_offset(), VW::LEARNER::learn_data::multipredict_f, VW::LEARNER::learn_data::predict_f, and polyprediction::scalar.
Referenced by ExpReplay::multipredict().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     if (learn_fd.multipredict_f == NULL)
     {
       increment_offset(ec, increment, lo);
       for (size_t c = 0; c < count; c++)
       {
         learn_fd.predict_f(learn_fd.data, *learn_fd.base, (void*)&ec);
         if (finalize_predictions)
           pred[c] = ec.pred;  // TODO: this breaks for complex labels because = doesn't do deep copy!
         else
           pred[c].scalar = ec.partial_prediction;
         // pred[c].scalar = finalize_prediction ec.partial_prediction; // TODO: this breaks for complex labels because =
         // doesn't do deep copy! // note works if ec.partial_prediction, but only if finalize_prediction is run????
         increment_offset(ec, increment, 1);
       }
       decrement_offset(ec, increment, lo + count);
     }
     else
     {
       increment_offset(ec, increment, lo);
       learn_fd.multipredict_f(learn_fd.data, *learn_fd.base, (void*)&ec, count, increment, pred, finalize_predictions);
       decrement_offset(ec, increment, lo);
     }
   }
predict()
template<class T, class E> void VW::LEARNER::learner< T, E >::predict (E & ec, size_t i = 0) inline
Definition at line 167 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, VW::LEARNER::decrement_offset(), VW::LEARNER::increment_offset(), and VW::LEARNER::learn_data::predict_f.
Referenced by GEN_CS::call_cs_ldf(), CB_ALGS::get_cost_pred(), VW::LEARNER::multiline_learn_or_predict(), and ExpReplay::predict_or_learn().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     increment_offset(ec, increment, i);
     learn_fd.predict_f(learn_fd.data, *learn_fd.base, (void*)&ec);
     decrement_offset(ec, increment, i);
   }
save_load()
template<class T, class E> void VW::LEARNER::learner< T, E >::save_load (io_buf & io, const bool read, const bool text) inline
Definition at line 249 of file learner.h.
References VW::LEARNER::save_load_data::base, VW::LEARNER::save_load_data::data, VW::LEARNER::learner< T, E >::save_load(), and VW::LEARNER::save_load_data::save_load_f.
Referenced by VW::LEARNER::learner< T, E >::save_load().
   {
     save_load_fd.save_load_f(save_load_fd.data, io, read, text);
     if (save_load_fd.base)
       save_load_fd.base->save_load(io, read, text);
   }
sensitivity()
template<class T, class E> float VW::LEARNER::learner< T, E >::sensitivity (example & ec, size_t i = 0) inline
Definition at line 240 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::sensitivity_data::data, VW::LEARNER::decrement_offset(), VW::LEARNER::increment_offset(), and VW::LEARNER::sensitivity_data::sensitivity_f.
   {
     increment_offset(ec, increment, i);
     const float ret = sensitivity_fd.sensitivity_f(sensitivity_fd.data, *learn_fd.base, ec);
     decrement_offset(ec, increment, i);
     return ret;
   }
set_end_examples()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_end_examples (void(*)(T &) f) inline
Definition at line 293 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, and VW::LEARNER::tuple_dbf().
 { end_examples_fd = tuple_dbf(learn_fd.data, learn_fd.base, (func_data::fn)f); }
set_end_pass()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_end_pass (void(*)(T &) f) inline
Definition at line 284 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, and VW::LEARNER::tuple_dbf().
Referenced by ExpReplay::expreplay_setup().
 { end_pass_fd = tuple_dbf(learn_fd.data, learn_fd.base, (func_data::fn)f); }
set_finish()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_finish (void(*)(T &) f) inline
Definition at line 263 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, and VW::LEARNER::tuple_dbf().
 { finisher_fd = tuple_dbf(learn_fd.data, learn_fd.base, (finish_fptr_type)(f)); }
set_finish_example()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_finish_example (void(*)(vw &all, T &, E &) f) inline
Definition at line 305 of file learner.h.
References VW::LEARNER::learn_data::data, VW::LEARNER::finish_example_data::data, and VW::LEARNER::finish_example_data::finish_example_f.
Referenced by VW::LEARNER::init_cost_sensitive_learner(), and VW::LEARNER::init_multiclass_learner().
   {
     finish_example_fd.data = learn_fd.data;
     finish_example_fd.finish_example_f = (end_fptr_type)(f);
   }
set_init_driver()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_init_driver (void(*)(T &) f) inline
Definition at line 297 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, and VW::LEARNER::tuple_dbf().
 { init_fd = tuple_dbf(learn_fd.data, learn_fd.base, (func_data::fn)f); }
set_learn()
template<class T, class E> template<class L > void VW::LEARNER::learner< T, E >::set_learn (void(*)(T &, L &, E &) u) inline
Definition at line 210 of file learner.h.
References VW::LEARNER::learn_data::learn_f.
   {
     learn_fd.learn_f = (learn_data::fn)u;
   }
set_multipredict()
template<class T, class E> template<class L > void VW::LEARNER::learner< T, E >::set_multipredict (void(*)(T &, L &, E &, size_t, size_t, polyprediction *, bool) u) inline
Definition at line 215 of file learner.h.
References VW::LEARNER::learn_data::multipredict_f.
   {
     learn_fd.multipredict_f = (learn_data::multi_fn)u;
   }
set_predict()
template<class T, class E> template<class L > void VW::LEARNER::learner< T, E >::set_predict (void(*)(T &, L &, E &) u) inline
Definition at line 205 of file learner.h.
References VW::LEARNER::learn_data::predict_f.
   {
     learn_fd.predict_f = (learn_data::fn)u;
   }
set_save_load()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_save_load (void(*)(T &, io_buf &, bool, bool) sl) inline
Definition at line 255 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::save_load_data::base, VW::LEARNER::learn_data::data, VW::LEARNER::save_load_data::data, and VW::LEARNER::save_load_data::save_load_f.
   {
     save_load_fd.save_load_f = (save_load_data::fn)sl;
     save_load_fd.data = learn_fd.data;
     save_load_fd.base = learn_fd.base;
   }
set_sensitivity()
template<class T, class E> void VW::LEARNER::learner< T, E >::set_sensitivity (float(*)(T &data, base_learner< T, E > &base, example &) u) inline
Definition at line 235 of file learner.h.
References VW::LEARNER::learn_data::data, VW::LEARNER::sensitivity_data::data, and VW::LEARNER::sensitivity_data::sensitivity_f.
   {
     sensitivity_fd.data = learn_fd.data;
     sensitivity_fd.sensitivity_f = (sensitivity_data::fn)u;
   }
set_update()
template<class T, class E> template<class L > void VW::LEARNER::learner< T, E >::set_update (void(*)(T &data, L &base, E &) u) inline
Definition at line 229 of file learner.h.
References VW::LEARNER::learn_data::update_f.
   {
     learn_fd.update_f = (learn_data::fn)u;
   }
update()
template<class T, class E> void VW::LEARNER::learner< T, E >::update (E & ec, size_t i = 0) inline
Definition at line 220 of file learner.h.
References VW::LEARNER::learn_data::base, VW::LEARNER::learn_data::data, VW::LEARNER::decrement_offset(), VW::LEARNER::increment_offset(), and VW::LEARNER::learn_data::update_f.
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     increment_offset(ec, increment, i);
     learn_fd.update_f(learn_fd.data, *learn_fd.base, (void*)&ec);
     decrement_offset(ec, increment, i);
   }
Member Data Documentation
end_examples_fd
template<class T, class E> func_data VW::LEARNER::learner< T, E >::end_examples_fd private
Definition at line 143 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
end_pass_fd
template<class T, class E> func_data VW::LEARNER::learner< T, E >::end_pass_fd private
Definition at line 142 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
finish_example_fd
template<class T, class E> finish_example_data VW::LEARNER::learner< T, E >::finish_example_fd private
Definition at line 140 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
finisher_fd
template<class T, class E> func_data VW::LEARNER::learner< T, E >::finisher_fd private
Definition at line 144 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
increment
template<class T, class E> size_t VW::LEARNER::learner< T, E >::increment
Definition at line 151 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
init_fd
template<class T, class E> func_data VW::LEARNER::learner< T, E >::init_fd private
Definition at line 137 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
is_multiline
template<class T, class E> bool VW::LEARNER::learner< T, E >::is_multiline
Definition at line 152 of file learner.h.
Referenced by VW::LEARNER::as_multiline(), VW::LEARNER::as_singleline(), and VW::LEARNER::learner< T, E >::init_learner().
learn_fd
template<class T, class E> learn_data VW::LEARNER::learner< T, E >::learn_fd private
Definition at line 138 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
learner_data
template<class T, class E> std::shared_ptr<void> VW::LEARNER::learner< T, E >::learner_data private
Definition at line 146 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
pred_type
template<class T, class E> prediction_type_t VW::LEARNER::learner< T, E >::pred_type
Definition at line 147 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
save_load_fd
template<class T, class E> save_load_data VW::LEARNER::learner< T, E >::save_load_fd private
Definition at line 141 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
sensitivity_fd
template<class T, class E> sensitivity_data VW::LEARNER::learner< T, E >::sensitivity_fd private
Definition at line 139 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
weights
template<class T, class E> size_t VW::LEARNER::learner< T, E >::weights
Definition at line 150 of file learner.h.
Referenced by VW::LEARNER::learner< T, E >::init_learner().
The documentation for this struct was generated from the following file:
/mnt/c/w/linux/vowpal_wabbit/vowpalwabbit/learner.h