Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/active.h File Reference
active.h File Reference
Classes
struct active
Functions
float query_decision (active &a, example &ec, float k)
LEARNER::base_learner * active_setup (VW::config::options_i &options, vw &all)
Function Documentation
active_setup()
LEARNER::base_learner* active_setup (VW::config::options_i & options, vw & all)
Definition at line 140 of file active.cc.
References vw::active, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), return_active_example(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<active>();
   bool active_option = false;
   bool simulation = false;
   option_group_definition new_options("Active Learning");
   new_options.add(make_option("active", active_option).keep().help("enable active learning"))
       .add(make_option("simulation", simulation).help("active learning simulation mode"))
       .add(make_option("mellowness", data->active_c0)
                .default_value(8.f)
                .help("active learning mellowness parameter c_0. Default 8"));
   options.add_and_parse(new_options);
   if (!active_option)
     return nullptr;
   data->all = &all;
   if (options.was_supplied("lda"))
     THROW("error: you can't combine lda and active learning");
   auto base = as_singleline(setup_base(options, all));
   // Create new learner
   learner<active, example>* l;
   if (options.was_supplied("simulation"))
     l = &init_learner(data, base, predict_or_learn_simulation<true>, predict_or_learn_simulation<false>);
   else
   {
     all.active = true;
     l = &init_learner(data, base, predict_or_learn_active<true>, predict_or_learn_active<false>);
     l->set_finish_example(return_active_example);
   }
   return make_base(*l);
 }
query_decision()
float query_decision (active & a, example & ec, float k)