Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/autolink.h File Reference
autolink.h File Reference
Functions
LEARNER::base_learner * autolink_setup (VW::config::options_i &options, vw &all)
Function Documentation
autolink_setup()
LEARNER::base_learner* autolink_setup (VW::config::options_i & options, vw & all)
Definition at line 39 of file autolink.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), setup_base(), parameters::stride_shift(), VW::config::options_i::was_supplied(), and vw::weights.
Referenced by parse_reductions().
 {
   free_ptr<autolink> data = scoped_calloc_or_throw<autolink>();
   option_group_definition new_options("Autolink");
   new_options.add(make_option("autolink", data->d).keep().help("create link function with polynomial d"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("autolink"))
     return nullptr;
   data->stride_shift = all.weights.stride_shift();
   LEARNER::learner<autolink, example>& ret =
       init_learner(data, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>);
   return make_base(ret);
 }