Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/autolink.cc File Reference
autolink.cc File Reference
#include "reductions.h"
Classes
struct autolink
Functions
template<bool is_learn>
void predict_or_learn (autolink &b, LEARNER::single_learner &base, example &ec)
LEARNER::base_learner * autolink_setup (options_i &options, vw &all)
Variables
constexpr int autoconstant = 524267083
Function Documentation
autolink_setup()
LEARNER::base_learner* autolink_setup (options_i & options, vw & all)
Definition at line 39 of file autolink.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), setup_base(), parameters::stride_shift(), VW::config::options_i::was_supplied(), and vw::weights.
Referenced by parse_reductions().
 {
   free_ptr<autolink> data = scoped_calloc_or_throw<autolink>();
   option_group_definition new_options("Autolink");
   new_options.add(make_option("autolink", data->d).keep().help("create link function with polynomial d"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("autolink"))
     return nullptr;
   data->stride_shift = all.weights.stride_shift();
   LEARNER::learner<autolink, example>& ret =
       init_learner(data, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>);
   return make_base(ret);
 }
predict_or_learn()
template<bool is_learn> void predict_or_learn (autolink & b, LEARNER::single_learner & base, example & ec)
Definition at line 14 of file autolink.cc.
References autoconstant, autolink_namespace, features::clear(), autolink::d, example_predict::feature_space, example_predict::indices, LEARNER::learner< T, E >::learn(), v_array< T >::pop(), example::pred, LEARNER::learner< T, E >::predict(), v_array< T >::push_back(), features::push_back(), polyprediction::scalar, autolink::stride_shift, features::sum_feat_sq, and example::total_sum_feat_sq.
 {
   base.predict(ec);
   float base_pred = ec.pred.scalar;
   // add features of label
   ec.indices.push_back(autolink_namespace);
   features& fs = ec.feature_space[autolink_namespace];
   for (size_t i = 0; i < b.d; i++)
     if (base_pred != 0.)
     {
       fs.push_back(base_pred, autoconstant + (i << b.stride_shift));
       base_pred *= ec.pred.scalar;
     }
   ec.total_sum_feat_sq += fs.sum_feat_sq;
   if (is_learn)
     base.learn(ec);
   else
     base.predict(ec);
   ec.total_sum_feat_sq -= fs.sum_feat_sq;
   fs.clear();
   ec.indices.pop();
 }
Variable Documentation
autoconstant
constexpr int autoconstant = 524267083
Definition at line 5 of file autolink.cc.
Referenced by predict_or_learn().