Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/binary.h File Reference
binary.h File Reference
Functions
LEARNER::base_learner * binary_setup (VW::config::options_i &options, vw &all)
Function Documentation
binary_setup()
LEARNER::base_learner* binary_setup (VW::config::options_i & options, vw & all)
Definition at line 31 of file binary.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), and setup_base().
Referenced by parse_reductions().
 {
   bool binary = false;
   option_group_definition new_options("Binary loss");
   new_options.add(make_option("binary", binary).keep().help("report loss as binary classification on -1,1"));
   options.add_and_parse(new_options);
   if (!binary)
     return nullptr;
   LEARNER::learner<char, example>& ret =
       LEARNER::init_learner(as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>);
   return make_base(ret);
 }