Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/cb_algs.h File Reference
cb_algs.h File Reference
#include "baseline.h"
Namespaces
CB_ALGS
Macros
#define CB_TYPE_DR 0
#define CB_TYPE_DM 1
#define CB_TYPE_IPS 2
#define CB_TYPE_MTR 3
#define CB_TYPE_SM 4
Functions
LEARNER::base_learner * cb_algs_setup (VW::config::options_i &options, vw &all)
template<bool is_learn>
float CB_ALGS::get_cost_pred (LEARNER::single_learner *scorer, CB::cb_class *known_cost, example &ec, uint32_t index, uint32_t base)
float CB_ALGS::get_cost_estimate (CB::cb_class *observation, uint32_t action, float offset=0.)
float CB_ALGS::get_cost_estimate (CB::cb_class *observation, COST_SENSITIVE::label &scores, uint32_t action)
float CB_ALGS::get_cost_estimate (ACTION_SCORE::action_score &a_s, float cost, uint32_t action, float offset=0.)
bool CB_ALGS::example_is_newline_not_header (example &ec)
Macro Definition Documentation
CB_TYPE_DM
#define CB_TYPE_DM 1
Definition at line 14 of file cb_algs.h.
Referenced by cb_adf_setup(), cb_algs_setup(), CB_ADF::do_actual_learning(), GEN_CS::gen_cs_example(), and CB_ALGS::predict_or_learn().
CB_TYPE_DR
#define CB_TYPE_DR 0
Definition at line 13 of file cb_algs.h.
Referenced by cb_adf_setup(), cb_algs_setup(), cb_explore_adf_setup(), cb_explore_setup(), CB_ADF::do_actual_learning(), and GEN_CS::gen_cs_example().
CB_TYPE_IPS
#define CB_TYPE_IPS 2
Definition at line 15 of file cb_algs.h.
Referenced by cb_adf_setup(), cb_algs_setup(), cb_explore_adf_setup(), CB_ADF::do_actual_learning(), and GEN_CS::gen_cs_example().
CB_TYPE_MTR
#define CB_TYPE_MTR 3
Definition at line 16 of file cb_algs.h.
Referenced by cb_adf_setup(), cb_explore_adf_setup(), CB_ADF::do_actual_learning(), GEN_CS::gen_cs_example(), and CB_EXPLORE_ADF::predict_or_learn_cover().
CB_TYPE_SM
#define CB_TYPE_SM 4
Definition at line 17 of file cb_algs.h.
Referenced by cb_adf_setup(), and CB_ADF::do_actual_learning().
Function Documentation
cb_algs_setup()
LEARNER::base_learner* cb_algs_setup (VW::config::options_i & options, vw & all)
Definition at line 134 of file cb_algs.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), c, label_type::cb, CB_EVAL::cb_eval, label_type::cb_eval, CB::cb_label, GEN_CS::cb_to_cs::cb_type, CB_TYPE_DM, CB_TYPE_DR, CB_TYPE_IPS, CB_ALGS::eval_finish_example(), CB_ALGS::finish(), CB_ALGS::finish_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, CB_ALGS::learn_eval(), parser::lp, LEARNER::make_base(), VW::config::make_option(), prediction_type::multiclass, vw::p, CB_ALGS::predict_eval(), GEN_CS::cb_to_cs::scorer, vw::scorer, LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<cb>();
   std::string type_string = "dr";
   bool eval = false;
   option_group_definition new_options("Contextual Bandit Options");
   new_options
       .add(make_option("cb", data->cbcs.num_actions).keep().help("Use contextual bandit learning with <k> costs"))
       .add(make_option("cb_type", type_string).keep().help("contextual bandit method to use in {ips,dm,dr}"))
       .add(make_option("eval", eval).help("Evaluate a policy rather than optimizing."));
   options.add_and_parse(new_options);
   if (!options.was_supplied("cb"))
     return nullptr;
   // Ensure serialization of this option in all cases.
   if (!options.was_supplied("cb_type"))
   {
     options.insert("cb_type", type_string);
     options.add_and_parse(new_options);
   }
   cb_to_cs& c = data->cbcs;
   size_t problem_multiplier = 2;  // default for DR
   if (type_string.compare("dr") == 0)
     c.cb_type = CB_TYPE_DR;
   else if (type_string.compare("dm") == 0)
   {
     if (eval)
       THROW("direct method can not be used for evaluation --- it is biased.");
     c.cb_type = CB_TYPE_DM;
     problem_multiplier = 1;
   }
   else if (type_string.compare("ips") == 0)
   {
     c.cb_type = CB_TYPE_IPS;
     problem_multiplier = 1;
   }
   else
   {
     std::cerr << "warning: cb_type must be in {'ips','dm','dr'}; resetting to dr." << std::endl;
     c.cb_type = CB_TYPE_DR;
   }
   if (!options.was_supplied("csoaa"))
   {
     stringstream ss;
     ss << data->cbcs.num_actions;
     options.insert("csoaa", ss.str());
   }
   auto base = as_singleline(setup_base(options, all));
   if (eval)
   {
     all.p->lp = CB_EVAL::cb_eval;
     all.label_type = label_type::cb_eval;
   }
   else
   {
     all.p->lp = CB::cb_label;
     all.label_type = label_type::cb;
   }
   learner<cb, example>* l;
   if (eval)
   {
     l = &init_learner(data, base, learn_eval, predict_eval, problem_multiplier, prediction_type::multiclass);
     l->set_finish_example(eval_finish_example);
   }
   else
   {
     l = &init_learner(
         data, base, predict_or_learn<true>, predict_or_learn<false>, problem_multiplier, prediction_type::multiclass);
     l->set_finish_example(finish_example);
   }
   c.scorer = all.scorer;
   l->set_finish(finish);
   return make_base(*l);
 }