Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/cb_explore_adf.cc File Reference
cb_explore_adf.cc File Reference
#include "reductions.h"
#include "cb_adf.h"
#include "rand48.h"
#include "bs.h"
#include "gen_cs_example.h"
#include "cb_explore.h"
#include "explore.h"
#include <vector>
#include <algorithm>
#include <cmath>
Classes
struct CB_EXPLORE_ADF::cb_explore_adf
Namespaces
CB_EXPLORE_ADF
Macros
#define EXPLORE_FIRST 0
#define EPS_GREEDY 1
#define BAG_EXPLORE 2
#define SOFTMAX 3
#define COVER 4
#define REGCB 5
#define B_SEARCH_MAX_ITER 20
Functions
float CB_EXPLORE_ADF::binary_search (float fhat, float delta, float sens, float tol=1e-6)
void CB_EXPLORE_ADF::get_cost_ranges (std::vector< float > &min_costs, std::vector< float > &max_costs, float delta, cb_explore_adf &data, multi_learner &base, multi_ex &examples, bool min_only)
size_t CB_EXPLORE_ADF::fill_tied (cb_explore_adf &, v_array< action_score > &preds)
template<bool is_learn>
void CB_EXPLORE_ADF::predict_or_learn_first (cb_explore_adf &data, multi_learner &base, multi_ex &examples)
template<bool is_learn>
void CB_EXPLORE_ADF::predict_or_learn_greedy (cb_explore_adf &data, multi_learner &base, multi_ex &examples)
template<bool is_learn>
void CB_EXPLORE_ADF::predict_or_learn_regcb (cb_explore_adf &data, multi_learner &base, multi_ex &examples)
void CB_EXPLORE_ADF::do_sort (cb_explore_adf &data)
template<bool is_learn>
void CB_EXPLORE_ADF::predict_or_learn_bag (cb_explore_adf &data, multi_learner &base, multi_ex &examples)
template<bool is_learn>
void CB_EXPLORE_ADF::predict_or_learn_cover (cb_explore_adf &data, multi_learner &base, multi_ex &examples)
template<bool is_learn>
void CB_EXPLORE_ADF::predict_or_learn_softmax (cb_explore_adf &data, multi_learner &base, multi_ex &examples)
void CB_EXPLORE_ADF::finish (cb_explore_adf &data)
void CB_EXPLORE_ADF::output_example (vw &all, cb_explore_adf &c, multi_ex &ec_seq)
void CB_EXPLORE_ADF::output_example_seq (vw &all, cb_explore_adf &data, multi_ex &ec_seq)
void CB_EXPLORE_ADF::finish_multiline_example (vw &all, cb_explore_adf &data, multi_ex &ec_seq)
template<bool is_learn>
void CB_EXPLORE_ADF::do_actual_learning (cb_explore_adf &data, multi_learner &base, multi_ex &ec_seq)
base_learner * cb_explore_adf_setup (options_i &options, vw &all)
Macro Definition Documentation
B_SEARCH_MAX_ITER
#define B_SEARCH_MAX_ITER 20
Definition at line 35 of file cb_explore_adf.cc.
Referenced by CB_EXPLORE_ADF::binary_search().
BAG_EXPLORE
#define BAG_EXPLORE 2
Definition at line 27 of file cb_explore_adf.cc.
Referenced by cb_explore_adf_setup(), and CB_EXPLORE_ADF::do_actual_learning().
COVER
#define COVER 4
Definition at line 31 of file cb_explore_adf.cc.
Referenced by cb_explore_adf_setup(), and CB_EXPLORE_ADF::do_actual_learning().
EPS_GREEDY
#define EPS_GREEDY 1
Definition at line 25 of file cb_explore_adf.cc.
Referenced by cb_explore_adf_setup(), and CB_EXPLORE_ADF::do_actual_learning().
EXPLORE_FIRST
#define EXPLORE_FIRST 0
Definition at line 23 of file cb_explore_adf.cc.
Referenced by cb_explore_adf_setup(), and CB_EXPLORE_ADF::do_actual_learning().
REGCB
#define REGCB 5
Definition at line 33 of file cb_explore_adf.cc.
Referenced by cb_explore_adf_setup(), and CB_EXPLORE_ADF::do_actual_learning().
SOFTMAX
#define SOFTMAX 3
Definition at line 29 of file cb_explore_adf.cc.
Referenced by cb_explore_adf_setup(), and CB_EXPLORE_ADF::do_actual_learning().
Function Documentation
cb_explore_adf_setup()
base_learner* cb_explore_adf_setup (options_i & options, vw & all)
Definition at line 679 of file cb_explore_adf.cc.
References prediction_type::action_probs, VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), BAG_EXPLORE, label_type::cb, CB::cb_label, CB_TYPE_DR, CB_TYPE_IPS, CB_TYPE_MTR, vw::cost_sensitive, COVER, ACTION_SCORE::delete_action_scores(), vw::delete_prediction, EPS_GREEDY, EXPLORE_FIRST, f, CB_EXPLORE_ADF::finish(), CB_EXPLORE_ADF::finish_multiline_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, REGCB, VW::config::options_i::replace(), vw::scorer, LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), SOFTMAX, vw::trace_message, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<cb_explore_adf>();
   bool cb_explore_adf_option = false;
   bool softmax = false;
   bool regcb = false;
   std::string type_string = "mtr";
   option_group_definition new_options("Contextual Bandit Exploration with Action Dependent Features");
   new_options
       .add(make_option("cb_explore_adf", cb_explore_adf_option)
                .keep()
                .help("Online explore-exploit for a contextual bandit problem with multiline action dependent features"))
       .add(make_option("first", data->tau).keep().help("tau-first exploration"))
       .add(make_option("epsilon", data->epsilon).keep().help("epsilon-greedy exploration"))
       .add(make_option("bag", data->bag_size).keep().help("bagging-based exploration"))
       .add(make_option("cover", data->cover_size).keep().help("Online cover based exploration"))
       .add(make_option("psi", data->psi).keep().default_value(1.0f).help("disagreement parameter for cover"))
       .add(make_option("nounif", data->nounif)
                .keep()
                .help("do not explore uniformly on zero-probability actions in cover"))
       .add(make_option("softmax", softmax).keep().help("softmax exploration"))
       .add(make_option("regcb", regcb).keep().help("RegCB-elim exploration"))
       .add(make_option("regcbopt", data->regcbopt).keep().help("RegCB optimistic exploration"))
       .add(make_option("mellowness", data->c0)
                .keep()
                .default_value(0.1f)
                .help("RegCB mellowness parameter c_0. Default 0.1"))
       .add(make_option("greedify", data->greedify).keep().help("always update first policy once in bagging"))
       .add(make_option("cb_min_cost", data->min_cb_cost).keep().default_value(0.f).help("lower bound on cost"))
       .add(make_option("cb_max_cost", data->max_cb_cost).keep().default_value(1.f).help("upper bound on cost"))
       .add(make_option("first_only", data->first_only)
                .keep()
                .help("Only explore the first action in a tie-breaking event"))
       .add(make_option("lambda", data->lambda).keep().default_value(1.f).help("parameter for softmax"))
       .add(make_option("cb_type", type_string)
                .keep()
                .help("contextual bandit method to use in {ips,dr,mtr}. Default: mtr"));
   options.add_and_parse(new_options);
   if (!cb_explore_adf_option)
     return nullptr;
   // Ensure serialization of cb_type in all cases.
   if (!options.was_supplied("cb_type"))
   {
     options.insert("cb_type", type_string);
     options.add_and_parse(new_options);
   }
   data->all = &all;
   if (data->lambda < 0)  // Lambda should always be positive because we are using a cost basis.
     data->lambda = -data->lambda;
   // Ensure serialization of cb_adf in all cases.
   if (!options.was_supplied("cb_adf"))
   {
     options.insert("cb_adf", "");
   }
   all.delete_prediction = delete_action_scores;
   // Set cb_type
   if (type_string.compare("dr") == 0)
     data->gen_cs.cb_type = CB_TYPE_DR;
   else if (type_string.compare("ips") == 0)
     data->gen_cs.cb_type = CB_TYPE_IPS;
   else if (type_string.compare("mtr") == 0)
   {
     if (options.was_supplied("cover"))
       all.trace_message << "warning: currently, mtr is only used for the first policy in cover, other policies use dr"
                         << endl;
     data->gen_cs.cb_type = CB_TYPE_MTR;
   }
   else
   {
     all.trace_message << "warning: cb_type must be in {'ips','dr','mtr'}; resetting to mtr." << std::endl;
     options.replace("cb_type", "mtr");
     data->gen_cs.cb_type = CB_TYPE_MTR;
   }
   // Set explore_type
   size_t problem_multiplier = 1;
   if (options.was_supplied("cover"))
   {
     data->explore_type = COVER;
     problem_multiplier = data->cover_size + 1;
   }
   else if (options.was_supplied("bag"))
   {
     data->explore_type = BAG_EXPLORE;
     problem_multiplier = data->bag_size;
   }
   else if (options.was_supplied("first"))
     data->explore_type = EXPLORE_FIRST;
   else if (softmax)
     data->explore_type = SOFTMAX;
   else if (regcb || (options.was_supplied("regcbopt") && data->regcbopt))
   {
     data->explore_type = REGCB;
     if (data->gen_cs.cb_type != CB_TYPE_MTR)
     {
       all.trace_message << "warning: bad cb_type, RegCB only supports mtr; resetting to mtr." << std::endl;
       options.replace("cb_type", "mtr");
       data->gen_cs.cb_type = CB_TYPE_MTR;
     }
   }
   else
   {
     if (!options.was_supplied("epsilon"))
       data->epsilon = 0.05f;
     data->explore_type = EPS_GREEDY;
   }
   multi_learner* base = as_multiline(setup_base(options, all));
   all.p->lp = CB::cb_label;
   all.label_type = label_type::cb;
   // Extract from lower level reductions.
   data->gen_cs.scorer = all.scorer;
   data->cs_ldf_learner = as_multiline(all.cost_sensitive);
   learner<cb_explore_adf, multi_ex>& l = init_learner(data, base, CB_EXPLORE_ADF::do_actual_learning<true>,
       CB_EXPLORE_ADF::do_actual_learning<false>, problem_multiplier, prediction_type::action_probs);
   l.set_finish_example(CB_EXPLORE_ADF::finish_multiline_example);
   l.set_finish(CB_EXPLORE_ADF::finish);
   return make_base(l);
 }