Vowpal Wabbit: namedlabels Class Reference
namedlabels Class Reference
#include <global_data.h>
Public Member Functions
namedlabels (std::string label_list)
~namedlabels ()
uint32_t getK ()
uint64_t get (substring &s)
substring get (uint32_t v)
Private Attributes
std::vector< substring > id2name
v_hashmap< substring, uint64_t > name2id
uint32_t K
Detailed Description
Definition at line 60 of file global_data.h.
Constructor & Destructor Documentation
namedlabels()
namedlabels::namedlabels (std::string label_list) inline
Definition at line 68 of file global_data.h.
References substring::begin, v_hashmap< K, V >::delete_v(), substring::end, v_hashmap< K, V >::get(), v_hashmap< K, V >::init(), v_hashmap< K, V >::put(), substring_equal(), THROW, tokenize(), and uniform_hash().
   {
     char* temp = calloc_or_throw<char>(1 + label_list.length());
     memcpy(temp, label_list.c_str(), strlen(label_list.c_str()));
     substring ss = {temp, nullptr};
     ss.end = ss.begin + label_list.length();
     tokenize(',', ss, id2name);
     K = (uint32_t)id2name.size();
     name2id.delete_v();  // delete automatically allocated vector.
     name2id.init(4 * K + 1, 0, substring_equal);
     for (size_t k = 0; k < K; k++)
     {
       substring& l = id2name[k];
       uint64_t hash = uniform_hash((unsigned char*)l.begin, l.end - l.begin, 378401);
       uint64_t id = name2id.get(l, hash);
       if (id != 0)  // TODO: memory leak: char* temp
         THROW("error: label dictionary initialized with multiple occurances of: " << l);
       size_t len = l.end - l.begin;
       substring l_copy = {calloc_or_throw<char>(len), nullptr};
       memcpy(l_copy.begin, l.begin, len * sizeof(char));
       l_copy.end = l_copy.begin + len;
       name2id.put(l_copy, hash, k + 1);
     }
   }
~namedlabels()
namedlabels::~namedlabels () inline
Definition at line 94 of file global_data.h.
References v_hashmap< K, V >::delete_v(), deleter(), and v_hashmap< K, V >::iter().
Referenced by VW::finish().
   {
     if (id2name.size() > 0)
       free(id2name[0].begin);
     name2id.iter(deleter);
     name2id.delete_v();
   }
Member Function Documentation
get() [1/2]
uint64_t namedlabels::get (substring & s) inline
Definition at line 104 of file global_data.h.
References c, v_hashmap< K, V >::get(), and uniform_hash().
Referenced by MULTICLASS::finish_example(), finish_example_scores(), COST_SENSITIVE::output_example(), MULTICLASS::parse_label(), COST_SENSITIVE::parse_label(), Search::search::pretty_label(), MULTICLASS::print_label_pred(), and COST_SENSITIVE::print_update().
   {
     uint64_t hash = uniform_hash((unsigned char*)s.begin, s.end - s.begin, 378401);
     uint64_t v = name2id.get(s, hash);
     if (v == 0)
     {
       std::cerr << "warning: missing named label '";
       for (char* c = s.begin; c != s.end; c++) std::cerr << *c;
       std::cerr << '\'' << std::endl;
     }
     return v;
   }
get() [2/2]
substring namedlabels::get (uint32_t v) inline
Definition at line 117 of file global_data.h.
   {
     if ((v == 0) || (v > K))
     {
       substring ss = {nullptr, nullptr};
       return ss;
     }
     else
       return id2name[v - 1];
   }
getK()
uint32_t namedlabels::getK () inline
Definition at line 102 of file global_data.h.
Referenced by oaa_setup(), and parse_example_tweaks().
 { return K; }
Member Data Documentation
id2name
std::vector<substring> namedlabels::id2name private
Definition at line 63 of file global_data.h.
K
uint32_t namedlabels::K private
Definition at line 65 of file global_data.h.
name2id
v_hashmap<substring, uint64_t> namedlabels::name2id private
Definition at line 64 of file global_data.h.
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/global_data.h