Vowpal Wabbit: Search::predictor Class Reference
Search::predictor Class Reference
#include <search.h>
Public Member Functions
predictor (search &sch, ptag my_tag)
~predictor ()
predictor & set_input (example &input_example)
predictor & set_input (example *input_example, size_t input_length)
void set_input_length (size_t input_length)
void set_input_at (size_t posn, example &input_example)
predictor & erase_oracles ()
predictor & reset ()
predictor & add_oracle (action a)
predictor & add_oracle (action *a, size_t action_count)
predictor & add_oracle (v_array< action > &a)
predictor & set_oracle (action a)
predictor & set_oracle (action *a, size_t action_count)
predictor & set_oracle (v_array< action > &a)
predictor & set_weight (float w)
predictor & erase_alloweds ()
predictor & add_allowed (action a)
predictor & add_allowed (action *a, size_t action_count)
predictor & add_allowed (v_array< action > &a)
predictor & set_allowed (action a)
predictor & set_allowed (action *a, size_t action_count)
predictor & set_allowed (v_array< action > &a)
predictor & add_allowed (action a, float cost)
predictor & add_allowed (action *a, float *costs, size_t action_count)
predictor & add_allowed (v_array< std::pair< action, float > > &a)
predictor & add_allowed (std::vector< std::pair< action, float > > &a)
predictor & set_allowed (action a, float cost)
predictor & set_allowed (action *a, float *costs, size_t action_count)
predictor & set_allowed (v_array< std::pair< action, float > > &a)
predictor & set_allowed (std::vector< std::pair< action, float > > &a)
predictor & add_condition (ptag tag, char name)
predictor & set_condition (ptag tag, char name)
predictor & add_condition_range (ptag hi, ptag count, char name0)
predictor & set_condition_range (ptag hi, ptag count, char name0)
predictor & set_learner_id (size_t id)
predictor & set_tag (ptag tag)
action predict ()
Private Member Functions
template<class T >
void make_new_pointer (v_array< T > &A, size_t new_size)
template<class T >
predictor & add_to (v_array< T > &A, bool &A_is_ptr, T a, bool clear_first)
template<class T >
predictor & add_to (v_array< T > &A, bool &A_is_ptr, T *a, size_t count, bool clear_first)
void free_ec ()
Private Attributes
bool is_ldf
ptag my_tag
example * ec
size_t ec_cnt
bool ec_alloced
float weight
v_array< action > oracle_actions
bool oracle_is_pointer
v_array< ptag > condition_on_tags
v_array< char > condition_on_names
v_array< action > allowed_actions
bool allowed_is_pointer
v_array< float > allowed_actions_cost
bool allowed_cost_is_pointer
size_t learner_id
search & sch
Detailed Description
Definition at line 256 of file search.h.
Constructor & Destructor Documentation
predictor()
Search::predictor::predictor (search & sch, ptag my_tag)
Definition at line 3101 of file search.cc.
References allowed_actions, allowed_actions_cost, condition_on_names, condition_on_tags, and oracle_actions.
     : is_ldf(false)
     , my_tag(my_tag)
     , ec(nullptr)
     , ec_cnt(0)
     , ec_alloced(false)
     , weight(1.)
     , oracle_is_pointer(false)
     , allowed_is_pointer(false)
     , allowed_cost_is_pointer(false)
     , learner_id(0)
     , sch(sch)
 {
   oracle_actions = v_init<action>();
   condition_on_tags = v_init<ptag>();
   condition_on_names = v_init<char>();
   allowed_actions = v_init<action>();
   allowed_actions_cost = v_init<float>();
 }
~predictor()
Search::predictor::~predictor ()
Definition at line 3133 of file search.cc.
References allowed_actions, allowed_actions_cost, allowed_cost_is_pointer, allowed_is_pointer, condition_on_names, condition_on_tags, v_array< T >::delete_v(), free_ec(), oracle_actions, and oracle_is_pointer.
 {
   if (!oracle_is_pointer)
     oracle_actions.delete_v();
   if (!allowed_is_pointer)
     allowed_actions.delete_v();
   if (!allowed_cost_is_pointer)
     allowed_actions_cost.delete_v();
   free_ec();
   condition_on_tags.delete_v();
   condition_on_names.delete_v();
 }
Member Function Documentation
add_allowed() [1/7]
predictor & Search::predictor::add_allowed (action a)
Definition at line 3324 of file search.cc.
References add_to(), allowed_actions, and allowed_is_pointer.
Referenced by add_allowed(), SequenceSpanTask::run(), and set_allowed().
 { return add_to(allowed_actions, allowed_is_pointer, a, false); }
add_allowed() [2/7]
predictor & Search::predictor::add_allowed (action * a, size_t action_count)
Definition at line 3325 of file search.cc.
References add_to(), allowed_actions, and allowed_is_pointer.
 {
   return add_to(allowed_actions, allowed_is_pointer, a, action_count, false);
 }
add_allowed() [3/7]
predictor & Search::predictor::add_allowed (v_array< action > & a)
Definition at line 3329 of file search.cc.
References add_to(), allowed_actions, allowed_is_pointer, v_array< T >::begin(), and v_array< T >::size().
 {
   return add_to(allowed_actions, allowed_is_pointer, a.begin(), a.size(), false);
 }
add_allowed() [4/7]
predictor & Search::predictor::add_allowed (action a, float cost)
Definition at line 3344 of file search.cc.
References add_to(), allowed_actions, allowed_actions_cost, allowed_cost_is_pointer, and allowed_is_pointer.
 {
   add_to(allowed_actions_cost, allowed_cost_is_pointer, cost, false);
   return add_to(allowed_actions, allowed_is_pointer, a, false);
 }
add_allowed() [5/7]
predictor & Search::predictor::add_allowed (action * a, float * costs, size_t action_count)
Definition at line 3350 of file search.cc.
References a, add_allowed(), add_to(), allowed_actions, allowed_actions_cost, allowed_cost_is_pointer, and allowed_is_pointer.
 {
   add_to(allowed_actions_cost, allowed_cost_is_pointer, costs, action_count, false);
   return add_to(allowed_actions, allowed_is_pointer, a, action_count, false);
 }
add_allowed() [6/7]
predictor& Search::predictor::add_allowed (v_array< std::pair< action, float > > & a)
add_allowed() [7/7]
predictor& Search::predictor::add_allowed (std::vector< std::pair< action, float > > & a)
add_condition()
predictor & Search::predictor::add_condition (ptag tag, char name)
Definition at line 3396 of file search.cc.
References condition_on_names, condition_on_tags, and v_array< T >::push_back().
Referenced by EntityRelationTask::predict_relation(), GraphTask::run(), and set_condition().
 {
   condition_on_tags.push_back(tag);
   condition_on_names.push_back(name);
   return *this;
 }
add_condition_range()
predictor & Search::predictor::add_condition_range (ptag hi, ptag count, char name0)
Definition at line 3409 of file search.cc.
References condition_on_names, condition_on_tags, and v_array< T >::push_back().
Referenced by SequenceSpanTask::run(), and set_condition_range().
 {
   if (count == 0)
     return *this;
   for (ptag i = 0; i < count; i++)
   {
     if (i > hi)
       break;
     char name = name0 + i;
     condition_on_tags.push_back(hi - i);
     condition_on_names.push_back(name);
   }
   return *this;
 }
add_oracle() [1/3]
predictor & Search::predictor::add_oracle (action a)
Definition at line 3286 of file search.cc.
References add_to(), oracle_actions, and oracle_is_pointer.
 { return add_to(oracle_actions, oracle_is_pointer, a, false); }
add_oracle() [2/3]
predictor & Search::predictor::add_oracle (action * a, size_t action_count)
Definition at line 3287 of file search.cc.
References add_to(), oracle_actions, and oracle_is_pointer.
 {
   return add_to(oracle_actions, oracle_is_pointer, a, action_count, false);
 }
add_oracle() [3/3]
predictor & Search::predictor::add_oracle (v_array< action > & a)
Definition at line 3291 of file search.cc.
References add_to(), v_array< T >::begin(), oracle_actions, oracle_is_pointer, and v_array< T >::size().
 {
   return add_to(oracle_actions, oracle_is_pointer, a.begin(), a.size(), false);
 }
add_to() [1/2]
template<class T > predictor & Search::predictor::add_to (v_array< T > & A, bool & A_is_ptr, T a, bool clear_first) private
Definition at line 3215 of file search.cc.
References a, v_array< T >::begin(), v_array< T >::clear(), v_array< T >::end(), v_array< T >::push_back(), and v_array< T >::size().
Referenced by add_allowed(), add_oracle(), set_allowed(), and set_oracle().
 {
   if (A_is_ptr)  // we need to make our own memory
   {
     if (clear_first)
       A.end() = A.begin();
     size_t new_size = clear_first ? 1 : (A.size() + 1);
     make_new_pointer<T>(A, new_size);
     A_is_ptr = false;
     A[new_size - 1] = a;
   }
   else  // we've already allocated our own memory
   {
     if (clear_first)
       A.clear();
     A.push_back(a);
   }
   return *this;
 }
add_to() [2/2]
template<class T > predictor & Search::predictor::add_to (v_array< T > & A, bool & A_is_ptr, T * a, size_t count, bool clear_first) private
Definition at line 3236 of file search.cc.
References a, v_array< T >::begin(), v_array< T >::clear(), v_array< T >::delete_v(), v_array< T >::end(), v_array< T >::end_array, and v_array< T >::size().
 {
   size_t old_size = A.size();
   if (old_size > 0)
   {
     if (A_is_ptr)  // we need to make our own memory
     {
       if (clear_first)
       {
         A.end() = A.begin();
         old_size = 0;
       }
       size_t new_size = old_size + count;
       make_new_pointer<T>(A, new_size);
       A_is_ptr = false;
       if (a != nullptr)
         memcpy(A.begin() + old_size, a, count * sizeof(T));
     }
     else  // we already have our own memory
     {
       if (clear_first)
         A.clear();
       if (a != nullptr)
         push_many<T>(A, a, count);
     }
   }
   else  // old_size == 0, clear_first is irrelevant
   {
     if (!A_is_ptr)
       A.delete_v();  // avoid memory leak
     A.begin() = a;
     if (a != nullptr)  // a is not nullptr
       A.end() = a + count;
     else
       A.end() = a;
     A.end_array = A.end();
     A_is_ptr = true;
   }
   return *this;
 }
erase_alloweds()
predictor & Search::predictor::erase_alloweds ()
Definition at line 3312 of file search.cc.
References allowed_actions, allowed_actions_cost, allowed_cost_is_pointer, allowed_is_pointer, v_array< T >::begin(), v_array< T >::clear(), and v_array< T >::end().
Referenced by reset(), DepParserTask::run(), and set_allowed().
 {
   if (allowed_is_pointer)
     allowed_actions.end() = allowed_actions.begin();
   else
     allowed_actions.clear();
   if (allowed_cost_is_pointer)
     allowed_actions_cost.end() = allowed_actions_cost.begin();
   else
     allowed_actions_cost.clear();
   return *this;
 }
erase_oracles()
predictor & Search::predictor::erase_oracles ()
Definition at line 3278 of file search.cc.
References v_array< T >::begin(), v_array< T >::clear(), v_array< T >::end(), oracle_actions, and oracle_is_pointer.
Referenced by reset().
 {
   if (oracle_is_pointer)
     oracle_actions.end() = oracle_actions.begin();
   else
     oracle_actions.clear();
   return *this;
 }
free_ec()
void Search::predictor::free_ec () private
Definition at line 3121 of file search.cc.
References COST_SENSITIVE::cs_label, VW::dealloc_example(), CB::delete_label(), ec, ec_alloced, ec_cnt, and is_ldf.
Referenced by reset(), set_input(), and ~predictor().
 {
   if (ec_alloced)
   {
     if (is_ldf)
       for (size_t i = 0; i < ec_cnt; i++) VW::dealloc_example(CS::cs_label.delete_label, ec[i]);
     else
       VW::dealloc_example(nullptr, *ec);
     free(ec);
   }
 }
make_new_pointer()
template<class T > void Search::predictor::make_new_pointer (v_array< T > & A, size_t new_size) private
Definition at line 3204 of file search.cc.
References v_array< T >::begin(), v_array< T >::end(), v_array< T >::end_array, and v_array< T >::size().
 {
   size_t old_size = A.size();
   T* old_pointer = A.begin();
   A.begin() = calloc_or_throw<T>(new_size);
   A.end() = A.begin() + new_size;
   A.end_array = A.end();
   memcpy(A.begin(), old_pointer, old_size * sizeof(T));
 }
predict()
action Search::predictor::predict ()
Definition at line 3442 of file search.cc.
References allowed_actions, allowed_actions_cost, v_array< T >::begin(), condition_on_names, condition_on_tags, ec, ec_cnt, is_ldf, learner_id, max(), my_tag, oracle_actions, v_array< T >::pop(), Search::search::predict(), Search::search::predictLDF(), v_array< T >::push_back(), sch, v_array< T >::size(), and weight.
Referenced by EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), SequenceSpanTask::run(), GraphTask::run(), and DepParserTask::run().
 {
   const action* orA = oracle_actions.size() == 0 ? nullptr : oracle_actions.begin();
   const ptag* cOn = condition_on_names.size() == 0 ? nullptr : condition_on_tags.begin();
   const char* cNa = nullptr;
   if (condition_on_names.size() > 0)
   {
     condition_on_names.push_back((char)0);  // null terminate
     cNa = condition_on_names.begin();
   }
   const action* alA = (allowed_actions.size() == 0) ? nullptr : allowed_actions.begin();
   const float* alAcosts = (allowed_actions_cost.size() == 0) ? nullptr : allowed_actions_cost.begin();
   size_t numAlA = max(allowed_actions.size(), allowed_actions_cost.size());
   action p = is_ldf
       ? sch.predictLDF(ec, ec_cnt, my_tag, orA, oracle_actions.size(), cOn, cNa, learner_id, weight)
       : sch.predict(*ec, my_tag, orA, oracle_actions.size(), cOn, cNa, alA, numAlA, alAcosts, learner_id, weight);
   if (condition_on_names.size() > 0)
     condition_on_names.pop();  // un-null-terminate
   return p;
 }
reset()
predictor & Search::predictor::reset ()
Definition at line 3145 of file search.cc.
References v_array< T >::clear(), condition_on_names, condition_on_tags, erase_alloweds(), erase_oracles(), and free_ec().
 {
   this->erase_oracles();
   this->erase_alloweds();
   condition_on_tags.clear();
   condition_on_names.clear();
   free_ec();
   return *this;
 }
set_allowed() [1/7]
predictor & Search::predictor::set_allowed (action a)
Definition at line 3334 of file search.cc.
References add_to(), allowed_actions, and allowed_is_pointer.
Referenced by EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), SequenceSpanTask::run(), DepParserTask::run(), and set_allowed().
 { return add_to(allowed_actions, allowed_is_pointer, a, true); }
set_allowed() [2/7]
predictor & Search::predictor::set_allowed (action * a, size_t action_count)
Definition at line 3335 of file search.cc.
References add_to(), allowed_actions, and allowed_is_pointer.
 {
   return add_to(allowed_actions, allowed_is_pointer, a, action_count, true);
 }
set_allowed() [3/7]
predictor & Search::predictor::set_allowed (v_array< action > & a)
Definition at line 3339 of file search.cc.
References add_to(), allowed_actions, allowed_is_pointer, v_array< T >::begin(), and v_array< T >::size().
 {
   return add_to(allowed_actions, allowed_is_pointer, a.begin(), a.size(), true);
 }
set_allowed() [4/7]
predictor & Search::predictor::set_allowed (action a, float cost)
Definition at line 3374 of file search.cc.
References add_to(), allowed_actions, allowed_actions_cost, allowed_cost_is_pointer, and allowed_is_pointer.
 {
   add_to(allowed_actions_cost, allowed_cost_is_pointer, cost, true);
   return add_to(allowed_actions, allowed_is_pointer, a, true);
 }
set_allowed() [5/7]
predictor & Search::predictor::set_allowed (action * a, float * costs, size_t action_count)
Definition at line 3380 of file search.cc.
References a, add_allowed(), add_to(), allowed_actions, allowed_actions_cost, allowed_cost_is_pointer, allowed_is_pointer, erase_alloweds(), and set_allowed().
 {
   add_to(allowed_actions_cost, allowed_cost_is_pointer, costs, action_count, true);
   return add_to(allowed_actions, allowed_is_pointer, a, action_count, true);
 }
set_allowed() [6/7]
predictor& Search::predictor::set_allowed (v_array< std::pair< action, float > > & a)
set_allowed() [7/7]
predictor& Search::predictor::set_allowed (std::vector< std::pair< action, float > > & a)
set_condition()
predictor & Search::predictor::set_condition (ptag tag, char name)
Definition at line 3402 of file search.cc.
References add_condition(), v_array< T >::clear(), condition_on_names, and condition_on_tags.
 {
   condition_on_tags.clear();
   condition_on_names.clear();
   return add_condition(tag, name);
 }
set_condition_range()
predictor & Search::predictor::set_condition_range (ptag hi, ptag count, char name0)
Definition at line 3423 of file search.cc.
References add_condition_range(), v_array< T >::clear(), condition_on_names, and condition_on_tags.
Referenced by SequenceTask::run(), SequenceSpanTask::run(), and DepParserTask::run().
 {
   condition_on_tags.clear();
   condition_on_names.clear();
   return add_condition_range(hi, count, name0);
 }
set_input() [1/2]
predictor & Search::predictor::set_input (example & input_example)
Definition at line 3155 of file search.cc.
References ec, ec_alloced, ec_cnt, free_ec(), and is_ldf.
Referenced by EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), SequenceTask::run(), SequenceSpanTask::run(), GraphTask::run(), and DepParserTask::run().
 {
   free_ec();
   is_ldf = false;
   ec = &input_example;
   ec_cnt = 1;
   ec_alloced = false;
   return *this;
 }
set_input() [2/2]
predictor & Search::predictor::set_input (example * input_example, size_t input_length)
Definition at line 3165 of file search.cc.
References ec, ec_alloced, ec_cnt, free_ec(), and is_ldf.
 {
   free_ec();
   is_ldf = true;
   ec = input_example;
   ec_cnt = input_length;
   ec_alloced = false;
   return *this;
 }
set_input_at()
void Search::predictor::set_input_at (size_t posn, example & input_example)
Definition at line 3191 of file search.cc.
References VW::copy_example_data(), CB::copy_label(), COST_SENSITIVE::cs_label, ec, ec_alloced, ec_cnt, and THROW.
 {
   if (!ec_alloced)
     THROW("call to set_input_at without previous call to set_input_length");
   if (posn >= ec_cnt)
     THROW("call to set_input_at with too large a position: posn (" << posn << ") >= ec_cnt(" << ec_cnt << ")");
   VW::copy_example_data(
       false, ec + posn, &ex, CS::cs_label.label_size, CS::cs_label.copy_label);  // TODO: the false is "audit"
 }
set_input_length()
void Search::predictor::set_input_length (size_t input_length)
Definition at line 3175 of file search.cc.
References ec, ec_alloced, ec_cnt, is_ldf, and THROW.
 {
   is_ldf = true;
   if (ec_alloced)
   {
     example* temp = (example*)realloc(ec, input_length * sizeof(example));
     if (temp != nullptr)
       ec = temp;
     else
       THROW("realloc failed in search.cc");
   }
   else
     ec = calloc_or_throw<example>(input_length);
   ec_cnt = input_length;
   ec_alloced = true;
 }
set_learner_id()
predictor & Search::predictor::set_learner_id (size_t id)
Definition at line 3430 of file search.cc.
References id(), and learner_id.
Referenced by EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), SequenceSpanTask::run(), and GraphTask::run().
 {
   learner_id = id;
   return *this;
 }
set_oracle() [1/3]
predictor & Search::predictor::set_oracle (action a)
Definition at line 3296 of file search.cc.
References add_to(), oracle_actions, and oracle_is_pointer.
Referenced by EntityRelationTask::predict_entity(), EntityRelationTask::predict_relation(), SequenceTask::run(), SequenceSpanTask::run(), GraphTask::run(), and DepParserTask::run().
 { return add_to(oracle_actions, oracle_is_pointer, a, true); }
set_oracle() [2/3]
predictor & Search::predictor::set_oracle (action * a, size_t action_count)
Definition at line 3297 of file search.cc.
References add_to(), oracle_actions, and oracle_is_pointer.
 {
   return add_to(oracle_actions, oracle_is_pointer, a, action_count, true);
 }
set_oracle() [3/3]
predictor & Search::predictor::set_oracle (v_array< action > & a)
Definition at line 3301 of file search.cc.
References add_to(), v_array< T >::begin(), oracle_actions, oracle_is_pointer, and v_array< T >::size().
 {
   return add_to(oracle_actions, oracle_is_pointer, a.begin(), a.size(), true);
 }
set_tag()
predictor & Search::predictor::set_tag (ptag tag)
Definition at line 3436 of file search.cc.
References my_tag.
Referenced by SequenceTask::run(), SequenceSpanTask::run(), and DepParserTask::run().
 {
   my_tag = tag;
   return *this;
 }
set_weight()
predictor & Search::predictor::set_weight (float w)
Definition at line 3306 of file search.cc.
Referenced by GraphTask::run().
 {
   weight = w;
   return *this;
 }
Member Data Documentation
allowed_actions
v_array<action> Search::predictor::allowed_actions private
Definition at line 343 of file search.h.
Referenced by add_allowed(), erase_alloweds(), predict(), predictor(), set_allowed(), and ~predictor().
allowed_actions_cost
v_array<float> Search::predictor::allowed_actions_cost private
Definition at line 345 of file search.h.
Referenced by add_allowed(), erase_alloweds(), predict(), predictor(), set_allowed(), and ~predictor().
allowed_cost_is_pointer
bool Search::predictor::allowed_cost_is_pointer private
Definition at line 346 of file search.h.
Referenced by add_allowed(), erase_alloweds(), set_allowed(), and ~predictor().
allowed_is_pointer
bool Search::predictor::allowed_is_pointer private
Definition at line 344 of file search.h.
Referenced by add_allowed(), erase_alloweds(), set_allowed(), and ~predictor().
condition_on_names
v_array<char> Search::predictor::condition_on_names private
Definition at line 342 of file search.h.
Referenced by add_condition(), add_condition_range(), predict(), predictor(), reset(), set_condition(), set_condition_range(), and ~predictor().
condition_on_tags
v_array<ptag> Search::predictor::condition_on_tags private
Definition at line 341 of file search.h.
Referenced by add_condition(), add_condition_range(), predict(), predictor(), reset(), set_condition(), set_condition_range(), and ~predictor().
ec
example* Search::predictor::ec private
Definition at line 335 of file search.h.
Referenced by free_ec(), predict(), set_input(), set_input_at(), and set_input_length().
ec_alloced
bool Search::predictor::ec_alloced private
Definition at line 337 of file search.h.
Referenced by free_ec(), set_input(), set_input_at(), and set_input_length().
ec_cnt
size_t Search::predictor::ec_cnt private
Definition at line 336 of file search.h.
Referenced by free_ec(), predict(), set_input(), set_input_at(), and set_input_length().
is_ldf
bool Search::predictor::is_ldf private
Definition at line 333 of file search.h.
Referenced by free_ec(), predict(), set_input(), and set_input_length().
learner_id
size_t Search::predictor::learner_id private
Definition at line 347 of file search.h.
Referenced by predict(), and set_learner_id().
my_tag
ptag Search::predictor::my_tag private
Definition at line 334 of file search.h.
Referenced by predict(), and set_tag().
oracle_actions
v_array<action> Search::predictor::oracle_actions private
Definition at line 339 of file search.h.
Referenced by add_oracle(), erase_oracles(), predict(), predictor(), set_oracle(), and ~predictor().
oracle_is_pointer
bool Search::predictor::oracle_is_pointer private
Definition at line 340 of file search.h.
Referenced by add_oracle(), erase_oracles(), set_oracle(), and ~predictor().
sch
search& Search::predictor::sch private
Definition at line 348 of file search.h.
Referenced by predict().
weight
float Search::predictor::weight private
Definition at line 338 of file search.h.
Referenced by predict().
The documentation for this class was generated from the following files:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/search.h
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/search.cc