Vowpal Wabbit: features_value_index_iterator Class Reference
features_value_index_iterator Class Reference
iterator over values and indicies
#include <feature_group.h>
Public Member Functions
features_value_index_iterator (feature_value *begin, feature_index *begin_index)
features_value_index_iterator (const features_value_index_iterator &other)
features_value_index_iterator & operator++ ()
feature_index & index ()
template<typename T >
features_value_index_iterator & operator+= (T index)
template<typename T >
features_value_index_iterator operator+ (T index)
template<typename T >
features_value_index_iterator & operator-= (T index)
features_value_index_iterator & operator= (const features_value_index_iterator &other)
features_value_index_iterator & operator* ()
Public Member Functions inherited from features_value_iterator
features_value_iterator (feature_value *begin)
features_value_iterator (const features_value_iterator &other)
features_value_iterator & operator++ ()
feature_value & value ()
template<typename T >
features_value_iterator operator+ (T index)
template<typename T >
features_value_iterator & operator+= (T index)
template<typename T >
features_value_iterator & operator-= (T index)
features_value_iterator & operator= (const features_value_iterator &other)
features_value_iterator & operator* ()
bool operator== (const features_value_iterator &rhs)
bool operator!= (const features_value_iterator &rhs)
Protected Attributes
feature_index * _begin_index
Protected Attributes inherited from features_value_iterator
feature_value * _begin
Friends
void swap (features_value_index_iterator &lhs, features_value_index_iterator &rhs)
Detailed Description
iterator over values and indicies
Definition at line 112 of file feature_group.h.
Constructor & Destructor Documentation
features_value_index_iterator() [1/2]
features_value_index_iterator::features_value_index_iterator (feature_value * begin, feature_index * begin_index) inline
Definition at line 118 of file feature_group.h.
       : features_value_iterator(begin), _begin_index(begin_index)
   {
   }
features_value_index_iterator() [2/2]
features_value_index_iterator::features_value_index_iterator (const features_value_index_iterator & other) inline
Definition at line 123 of file feature_group.h.
       : features_value_iterator(other), _begin_index(other._begin_index)
   {
   }
Member Function Documentation
index()
feature_index& features_value_index_iterator::index () inline
Definition at line 135 of file feature_group.h.
Referenced by collision_cleanup(), INTERACTIONS::inner_kernel(), and unique_features().
 { return *_begin_index; }
operator*()
features_value_index_iterator& features_value_index_iterator::operator* () inline
Definition at line 166 of file feature_group.h.
 { return *this; }
operator+()
template<typename T > features_value_index_iterator features_value_index_iterator::operator+ (T index) inline
Definition at line 146 of file feature_group.h.
   {
     return features_value_index_iterator(_begin + index, _begin_index + index);
   }
operator++()
features_value_index_iterator& features_value_index_iterator::operator++ () inline
Definition at line 128 of file feature_group.h.
References features_value_iterator::operator++().
Referenced by features_value_index_audit_iterator::operator++().
   {
     features_value_iterator::operator++();
     _begin_index++;
     return *this;
   }
operator+=()
template<typename T > features_value_index_iterator& features_value_index_iterator::operator+= (T index) inline
Definition at line 138 of file feature_group.h.
References features_value_iterator::operator+=().
Referenced by features_value_index_audit_iterator::operator+=().
   {
     features_value_iterator::operator+=(index);
     _begin_index += index;
     return *this;
   }
operator-=()
template<typename T > features_value_index_iterator& features_value_index_iterator::operator-= (T index) inline
Definition at line 152 of file feature_group.h.
References features_value_iterator::operator-=().
Referenced by features_value_index_audit_iterator::operator-=().
   {
     features_value_iterator::operator-=(index);
     _begin_index -= index;
     return *this;
   }
operator=()
features_value_index_iterator& features_value_index_iterator::operator= (const features_value_index_iterator & other) inline
Definition at line 159 of file feature_group.h.
References _begin_index, and features_value_iterator::operator=().
Referenced by features_value_index_audit_iterator::operator=().
   {
     features_value_iterator::operator=(other);
     _begin_index = other._begin_index;
     return *this;
   }
Friends And Related Function Documentation
swap
void swap (features_value_index_iterator & lhs, features_value_index_iterator & rhs) friend
Definition at line 168 of file feature_group.h.
   {
     swap(static_cast<features_value_iterator&>(lhs), static_cast<features_value_iterator&>(rhs));
     std::swap(lhs._begin_index, rhs._begin_index);
   }
Member Data Documentation
_begin_index
feature_index* features_value_index_iterator::_begin_index protected
Definition at line 115 of file feature_group.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/feature_group.h