Vowpal Wabbit: dense_parameters Class Reference
dense_parameters Class Reference
#include <array_parameters_dense.h>
Public Types
typedef dense_iterator< weight > iterator
typedef dense_iterator< const weight > const_iterator
Public Member Functions
dense_parameters (size_t length, uint32_t stride_shift=0)
dense_parameters ()
bool not_null ()
dense_parameters (const dense_parameters &other)
dense_parameters (dense_parameters &&)=delete
weight * first ()
iterator begin ()
iterator end ()
const_iterator cbegin ()
const_iterator cend ()
weight & operator[] (size_t i) const
void shallow_copy (const dense_parameters &input)
weight & strided_index (size_t index)
template<class R , class T >
void set_default (R &info)
template<class T >
void set_default ()
void set_zero (size_t offset)
uint64_t mask () const
uint64_t seeded () const
uint32_t stride () const
uint32_t stride_shift () const
void stride_shift (uint32_t stride_shift)
void share (size_t length)
~dense_parameters ()
Private Attributes
weight * _begin
uint64_t _weight_mask
uint32_t _stride_shift
bool _seeded
Detailed Description
Definition at line 39 of file array_parameters_dense.h.
Member Typedef Documentation
const_iterator
typedef dense_iterator<const weight> dense_parameters::const_iterator
Definition at line 49 of file array_parameters_dense.h.
iterator
typedef dense_iterator<weight> dense_parameters::iterator
Definition at line 48 of file array_parameters_dense.h.
Constructor & Destructor Documentation
dense_parameters() [1/4]
dense_parameters::dense_parameters (size_t length, uint32_t stride_shift = 0) inline
Definition at line 50 of file array_parameters_dense.h.
       : _begin(calloc_mergable_or_throw<weight>(length << stride_shift))
       , _weight_mask((length << stride_shift) - 1)
       , _stride_shift(stride_shift)
       , _seeded(false)
   {
   }
dense_parameters() [2/4]
dense_parameters::dense_parameters () inline
Definition at line 58 of file array_parameters_dense.h.
 : _begin(nullptr), _weight_mask(0), _stride_shift(0), _seeded(false) {}
dense_parameters() [3/4]
dense_parameters::dense_parameters (const dense_parameters & other) inline
Definition at line 62 of file array_parameters_dense.h.
 { shallow_copy(other); }
dense_parameters() [4/4]
dense_parameters::dense_parameters (dense_parameters &&) delete
~dense_parameters()
dense_parameters::~dense_parameters () inline
Definition at line 132 of file array_parameters_dense.h.
   {
     if (_begin != nullptr && !_seeded)  // don't free weight vector if it is shared with another instance
     {
       free(_begin);
       _begin = nullptr;
     }
   }
Member Function Documentation
begin()
iterator dense_parameters::begin () inline
Definition at line 68 of file array_parameters_dense.h.
 { return iterator(_begin, _begin, stride()); }
cbegin()
const_iterator dense_parameters::cbegin () inline
Definition at line 72 of file array_parameters_dense.h.
 { return const_iterator(_begin, _begin, stride()); }
cend()
const_iterator dense_parameters::cend () inline
Definition at line 73 of file array_parameters_dense.h.
 { return const_iterator(_begin + _weight_mask + 1, _begin, stride()); }
end()
iterator dense_parameters::end () inline
Definition at line 69 of file array_parameters_dense.h.
 { return iterator(_begin + _weight_mask + 1, _begin, stride()); }
first()
weight* dense_parameters::first () inline
Definition at line 65 of file array_parameters_dense.h.
References dense_iterator< T >::_begin.
Referenced by accumulate_weighted_avg().
 { return _begin; }  // TODO: Temporary fix for allreduce.
mask()
uint64_t dense_parameters::mask () const inline
Definition at line 107 of file array_parameters_dense.h.
Referenced by parameters::mask().
 { return _weight_mask; }
not_null()
bool dense_parameters::not_null () inline
Definition at line 60 of file array_parameters_dense.h.
Referenced by parameters::not_null().
 { return (_weight_mask > 0 && _begin != nullptr); }
operator[]()
weight& dense_parameters::operator[] (size_t i) const inline
Definition at line 75 of file array_parameters_dense.h.
 { return _begin[i & _weight_mask]; }
seeded()
uint64_t dense_parameters::seeded () const inline
Definition at line 109 of file array_parameters_dense.h.
Referenced by parameters::seeded().
 { return _seeded; }
set_default() [1/2]
template<class R , class T > void dense_parameters::set_default (R & info) inline
Definition at line 89 of file array_parameters_dense.h.
References dense_iterator< T >::index().
Referenced by save_load(), and GD::save_load().
   {
     iterator iter = begin();
     for (size_t i = 0; iter != end(); ++iter, i += stride()) T::func(*iter, info, iter.index());
   }
set_default() [2/2]
template<class T > void dense_parameters::set_default () inline
Definition at line 96 of file array_parameters_dense.h.
References dense_iterator< T >::index().
   {
     iterator iter = begin();
     for (size_t i = 0; iter != end(); ++iter, i += stride()) T::func(*iter, iter.index());
   }
set_zero()
void dense_parameters::set_zero (size_t offset) inline
Definition at line 102 of file array_parameters_dense.h.
Referenced by parameters::set_zero().
   {
     for (iterator iter = begin(); iter != end(); ++iter) (&(*iter))[offset] = 0;
   }
shallow_copy()
void dense_parameters::shallow_copy (const dense_parameters & input) inline
Definition at line 76 of file array_parameters_dense.h.
References _begin, _stride_shift, and _weight_mask.
Referenced by parameters::shallow_copy().
   {
     if (!_seeded)
       free(_begin);
     _begin = input._begin;
     _weight_mask = input._weight_mask;
     _stride_shift = input._stride_shift;
     _seeded = true;
   }
share()
void dense_parameters::share (size_t length) inline
Definition at line 119 of file array_parameters_dense.h.
References MAP_ANONYMOUS.
Referenced by parameters::share().
   {
     float* shared_weights = (float*)mmap(
         0, (length << _stride_shift) * sizeof(float), PROT_READ | PROT_WRITE, MAP_SHARED | MAP_ANONYMOUS, -1, 0);
     size_t float_count = length << _stride_shift;
     weight* dest = shared_weights;
     memcpy(dest, _begin, float_count * sizeof(float));
     free(_begin);
     _begin = dest;
   }
stride()
uint32_t dense_parameters::stride () const inline
Definition at line 111 of file array_parameters_dense.h.
Referenced by parameters::stride().
 { return 1 << _stride_shift; }
stride_shift() [1/2]
uint32_t dense_parameters::stride_shift () const inline
Definition at line 113 of file array_parameters_dense.h.
Referenced by accumulate(), accumulate_avg(), accumulate_weighted_avg(), and parameters::stride_shift().
 { return _stride_shift; }
stride_shift() [2/2]
void dense_parameters::stride_shift (uint32_t stride_shift) inline
Definition at line 115 of file array_parameters_dense.h.
References stride_shift().
Referenced by stride_shift().
 { _stride_shift = stride_shift; }
strided_index()
weight& dense_parameters::strided_index (size_t index) inline
Definition at line 86 of file array_parameters_dense.h.
Referenced by parameters::strided_index().
 { return operator[](index << _stride_shift); }
Member Data Documentation
_begin
weight* dense_parameters::_begin private
Definition at line 42 of file array_parameters_dense.h.
Referenced by shallow_copy().
_seeded
bool dense_parameters::_seeded private
Definition at line 45 of file array_parameters_dense.h.
_stride_shift
uint32_t dense_parameters::_stride_shift private
Definition at line 44 of file array_parameters_dense.h.
Referenced by shallow_copy().
_weight_mask
uint64_t dense_parameters::_weight_mask private
Definition at line 43 of file array_parameters_dense.h.
Referenced by shallow_copy().
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/array_parameters_dense.h