Vowpal Wabbit: ezexample Class Reference
ezexample Class Reference
#include <ezexample.h>
Public Member Functions
ezexample (vw *this_vw, bool multiline=false, vw *this_vw_parser=nullptr)
ezexample (vw *this_vw, example *this_ec, bool multiline=false, vw *this_vw_parser=nullptr)
~ezexample ()
bool ensure_ns_exists (char c)
void addns (char c)
void remns ()
fid addf (char to_ns, fid fint, float v)
fid addf (fid fint, float v)
void add_other_example_ns (example &other, char other_ns, char to_ns)
void add_other_example_ns (example &other, char ns)
void add_other_example_ns (ezexample &other, char other_ns, char to_ns)
void add_other_example_ns (ezexample &other, char ns)
ezexample & set_label (std::string label)
void mini_setup_example ()
size_t get_num_features ()
example * get ()
float predict ()
float predict_partial ()
void train ()
void clear_features ()
void finish ()
fid hash (std::string fstr)
fid hash (char *fstr)
fid hash (char c, std::string fstr)
fid hash (char c, char *fstr)
fid addf (fid fint)
fid addf (std::string fstr, float val)
fid addf (std::string fstr)
fid addf (char ns, fid fint)
fid addf (char ns, std::string fstr, float val)
fid addf (char ns, std::string fstr)
ezexample & operator() (const vw_namespace &n)
ezexample & operator() (fid fint)
ezexample & operator() (std::string fstr)
ezexample & operator() (const char *fstr)
ezexample & operator() (fid fint, float val)
ezexample & operator() (std::string fstr, float val)
ezexample & operator() (const char *fstr, float val)
ezexample & operator() (char ns, fid fint)
ezexample & operator() (char ns, std::string fstr)
ezexample & operator() (char ns, const char *fstr)
ezexample & operator() (char ns, fid fint, float val)
ezexample & operator() (char ns, std::string fstr, float val)
ezexample & operator() (char ns, const char *fstr, float val)
ezexample & operator() (example &other, char other_ns, char to_ns)
ezexample & operator() (example &other, char ns)
ezexample & operator() (ezexample &other, char other_ns, char to_ns)
ezexample & operator() (ezexample &other, char ns)
ezexample & operator-- ()
float operator() ()
Private Member Functions
ezexample (const ezexample &ex)
ezexample & operator= (const ezexample &ex)
example * get_new_example ()
void setup_new_ezexample (vw *this_vw, bool multiline, vw *this_vw_parser)
void setup_for_predict ()
Private Attributes
vw * vw_ref
vw * vw_par_ref
bool is_multiline
char str [2]
example * ec
bool we_create_ec
std::vector< fid > past_seeds
fid current_seed
size_t quadratic_features_num
float quadratic_features_sqr
char current_ns
bool ns_exists [256]
bool example_changed_since_prediction
v_array< example * > example_copies
Detailed Description
Definition at line 16 of file ezexample.h.
Constructor & Destructor Documentation
ezexample() [1/3]
ezexample::ezexample (const ezexample & ex) private
ezexample() [2/3]
ezexample::ezexample (vw * this_vw, bool multiline = false, vw * this_vw_parser = nullptr) inline
Definition at line 93 of file ezexample.h.
References vw::add_constant, and VW::add_constant_feature().
   {
     setup_new_ezexample(this_vw, multiline, this_vw_parser);
     example_copies = v_init<example*>();
     ec = get_new_example();
     we_create_ec = true;
     if (vw_ref->add_constant)
       VW::add_constant_feature(*vw_ref, ec);
   }
ezexample() [3/3]
ezexample::ezexample (vw * this_vw, example * this_ec, bool multiline = false, vw * this_vw_parser = nullptr) inline
Definition at line 107 of file ezexample.h.
References VW::hash_space(), and example_predict::indices.
   {
     setup_new_ezexample(this_vw, multiline, this_vw_parser);
     ec = this_ec;
     we_create_ec = false;
     for (auto ns : ec->indices) ns_exists[ns] = true;
     if (current_ns != 0)
     {
       str[0] = current_ns;
       current_seed = VW::hash_space(*vw_ref, str);
     }
   }
~ezexample()
ezexample::~ezexample () inline
Definition at line 122 of file ezexample.h.
References VW::finish_example(), example::in_use, and VW::is_ring_example().
   {
     if (ec->in_use && VW::is_ring_example(*vw_par_ref, ec))
       VW::finish_example(*vw_par_ref, *ec);
     for (auto ecc : example_copies)
       if (ecc->in_use && VW::is_ring_example(*vw_par_ref, ec))
         VW::finish_example(*vw_par_ref, *ecc);
     example_copies.clear();
     free(example_copies.begin());
   }
Member Function Documentation
add_other_example_ns() [1/4]
void ezexample::add_other_example_ns (example & other, char other_ns, char to_ns) inline
Definition at line 198 of file ezexample.h.
References example_predict::feature_space, features::indicies, example::num_features, features::push_back(), features::size(), features::sum_feat_sq, example::total_sum_feat_sq, and features::values.
   {
     if (ensure_ns_exists(to_ns))
       return;
     features& fs = other.feature_space[(int)other_ns];
     for (size_t i = 0; i < fs.size(); i++) ec->feature_space[(int)to_ns].push_back(fs.values[i], fs.indicies[i]);
     ec->total_sum_feat_sq += fs.sum_feat_sq;
     ec->num_features += fs.size();
     example_changed_since_prediction = true;
   }
add_other_example_ns() [2/4]
void ezexample::add_other_example_ns (example & other, char ns) inline
Definition at line 208 of file ezexample.h.
   {
     add_other_example_ns(other, ns, ns);
   }
add_other_example_ns() [3/4]
void ezexample::add_other_example_ns (ezexample & other, char other_ns, char to_ns) inline
Definition at line 213 of file ezexample.h.
References ec.
   {
     add_other_example_ns(*other.ec, other_ns, to_ns);
   }
add_other_example_ns() [4/4]
void ezexample::add_other_example_ns (ezexample & other, char ns) inline
Definition at line 217 of file ezexample.h.
References add_other_example_ns(), and ec.
Referenced by add_other_example_ns().
 { add_other_example_ns(*other.ec, ns); }
addf() [1/8]
fid ezexample::addf (char to_ns, fid fint, float v) inline
Definition at line 181 of file ezexample.h.
References example_predict::feature_space, example::num_features, parameters::stride_shift(), example::total_sum_feat_sq, and vw::weights.
   {
     if (to_ns == 0)
       return 0;
     if (ensure_ns_exists(to_ns))
       return 0;
     ec->feature_space[(int)to_ns].push_back(v, fint << vw_ref->weights.stride_shift());
     ec->total_sum_feat_sq += v * v;
     ec->num_features++;
     example_changed_since_prediction = true;
     return fint;
   }
addf() [2/8]
fid ezexample::addf (fid fint, float v) inline
Definition at line 195 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(current_ns, fint, v); }
addf() [3/8]
fid ezexample::addf (fid fint) inline
Definition at line 329 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(fint, 1.0); }
addf() [4/8]
fid ezexample::addf (std::string fstr, float val) inline
Definition at line 330 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(hash(fstr), val); }
addf() [5/8]
fid ezexample::addf (std::string fstr) inline
Definition at line 331 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(hash(fstr), 1.0); }
addf() [6/8]
fid ezexample::addf (char ns, fid fint) inline
Definition at line 333 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(ns, fint, 1.0); }
addf() [7/8]
fid ezexample::addf (char ns, std::string fstr, float val) inline
Definition at line 334 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(ns, hash(ns, fstr), val); }
addf() [8/8]
fid ezexample::addf (char ns, std::string fstr) inline
Definition at line 335 of file ezexample.h.
References addf().
Referenced by addf().
 { return addf(ns, hash(ns, fstr), 1.0); }
addns()
void ezexample::addns (char c) inline
Definition at line 144 of file ezexample.h.
References c, example_predict::feature_space, VW::hash_space(), and features::push_back().
   {
     if (ensure_ns_exists(c))
       return;
     ec->feature_space[(int)c].clear();
     past_seeds.push_back(current_seed);
     current_ns = c;
     str[0] = c;
     current_seed = VW::hash_space(*vw_ref, str);
   }
clear_features()
void ezexample::clear_features () inline
Definition at line 291 of file ezexample.h.
   {
     for (size_t i = 0; i < 256; i++)
     {
       if (current_ns == 0)
         break;
       remns();
     }
   }
ensure_ns_exists()
bool ezexample::ensure_ns_exists (char c) inline
Definition at line 133 of file ezexample.h.
References vw::ignore, vw::ignore_some, example_predict::indices, and v_array< T >::push_back().
   {
     if (vw_ref->ignore_some && vw_ref->ignore[(int)c])
       return true;
     if (ns_exists[(int)c])
       return false;
     ec->indices.push_back((size_t)c);
     ns_exists[(int)c] = true;
     return false;
   }
finish()
void ezexample::finish () inline
Definition at line 301 of file ezexample.h.
References VW::empty_example(), VW::finish_example(), vw::learn(), and VW::read_example().
   {
     static example* empty_example = is_multiline ? VW::read_example(*vw_par_ref, (char*)"") : nullptr;
     if (is_multiline)
     {
       vw_ref->learn(*empty_example);
       for (auto ecc : example_copies)
         if (ecc->in_use)
           VW::finish_example(*vw_par_ref, *ecc);
       example_copies.clear();
     }
   }
get()
example* ezexample::get () inline
Definition at line 249 of file ezexample.h.
   {
     if (example_changed_since_prediction)
       mini_setup_example();
     return ec;
   }
get_new_example()
example* ezexample::get_new_example () inline private
Definition at line 39 of file ezexample.h.
References v_array< T >::clear(), features::clear(), example::confidence, label_parser::default_label, example_predict::feature_space, example_predict::ft_offset, example_predict::indices, example::l, example::loss, parser::lp, VW::new_unused_example(), example::num_features, vw::p, example::partial_prediction, example::passthrough, example::tag, example::total_sum_feat_sq, and example::updated_prediction.
   {
     example* new_ec = VW::new_unused_example(*vw_par_ref);
     vw_par_ref->p->lp.default_label(&new_ec->l);
     new_ec->tag.clear();
     new_ec->indices.clear();
     for (size_t i = 0; i < 256; i++) new_ec->feature_space[i].clear();
     new_ec->ft_offset = 0;
     new_ec->num_features = 0;
     new_ec->partial_prediction = 0.;
     new_ec->updated_prediction = 0.;
     new_ec->passthrough = nullptr;
     new_ec->loss = 0.;
     new_ec->total_sum_feat_sq = 0.;
     new_ec->confidence = 0.;
     return new_ec;
   }
get_num_features()
size_t ezexample::get_num_features () inline
Definition at line 247 of file ezexample.h.
References example::num_features.
 { return ec->num_features; }
hash() [1/4]
fid ezexample::hash (std::string fstr) inline
Definition at line 316 of file ezexample.h.
References VW::hash_feature().
 { return VW::hash_feature(*vw_ref, fstr, current_seed); }
hash() [2/4]
fid ezexample::hash (char * fstr) inline
Definition at line 317 of file ezexample.h.
References VW::hash_feature_cstr().
 { return VW::hash_feature_cstr(*vw_ref, fstr, current_seed); }
hash() [3/4]
fid ezexample::hash (char c, std::string fstr) inline
Definition at line 318 of file ezexample.h.
References c, VW::hash_feature(), and VW::hash_space().
   {
     str[0] = c;
     return VW::hash_feature(*vw_ref, fstr, VW::hash_space(*vw_ref, str));
   }
hash() [4/4]
fid ezexample::hash (char c, char * fstr) inline
Definition at line 323 of file ezexample.h.
References c, VW::hash_feature_cstr(), and VW::hash_space().
   {
     str[0] = c;
     return VW::hash_feature_cstr(*vw_ref, fstr, VW::hash_space(*vw_ref, str));
   }
mini_setup_example()
void ezexample::mini_setup_example () inline
Definition at line 226 of file ezexample.h.
References example_predict::feature_space, label_parser::get_weight, example::l, parser::lp, example::num_features, vw::p, vw::pairs, example::partial_prediction, features::size(), features::sum_feat_sq, example::total_sum_feat_sq, and example::weight.
   {
     ec->partial_prediction = 0.;
     ec->weight = vw_par_ref->p->lp.get_weight(&ec->l);
     ec->num_features -= quadratic_features_num;
     ec->total_sum_feat_sq -= quadratic_features_sqr;
     quadratic_features_num = 0;
     quadratic_features_sqr = 0.;
     for (std::vector<std::string>::iterator i = vw_ref->pairs.begin(); i != vw_ref->pairs.end(); i++)
     {
       quadratic_features_num += ec->feature_space[(int)(*i)[0]].size() * ec->feature_space[(int)(*i)[1]].size();
       quadratic_features_sqr +=
           ec->feature_space[(int)(*i)[0]].sum_feat_sq * ec->feature_space[(int)(*i)[1]].sum_feat_sq;
     }
     ec->num_features += quadratic_features_num;
     ec->total_sum_feat_sq += quadratic_features_sqr;
   }
operator()() [1/18]
ezexample& ezexample::operator() (const vw_namespace & n) inline
Definition at line 337 of file ezexample.h.
References vw_namespace::namespace_letter.
   {
     addns(n.namespace_letter);
     return *this;
   }
operator()() [2/18]
ezexample& ezexample::operator() (fid fint) inline
Definition at line 343 of file ezexample.h.
   {
     addf(fint, 1.0);
     return *this;
   }
operator()() [3/18]
ezexample& ezexample::operator() (std::string fstr) inline
Definition at line 348 of file ezexample.h.
   {
     addf(fstr, 1.0);
     return *this;
   }
operator()() [4/18]
ezexample& ezexample::operator() (const char * fstr) inline
Definition at line 353 of file ezexample.h.
   {
     addf(fstr, 1.0);
     return *this;
   }
operator()() [5/18]
ezexample& ezexample::operator() (fid fint, float val) inline
Definition at line 358 of file ezexample.h.
   {
     addf(fint, val);
     return *this;
   }
operator()() [6/18]
ezexample& ezexample::operator() (std::string fstr, float val) inline
Definition at line 363 of file ezexample.h.
   {
     addf(fstr, val);
     return *this;
   }
operator()() [7/18]
ezexample& ezexample::operator() (const char * fstr, float val) inline
Definition at line 368 of file ezexample.h.
   {
     addf(fstr, val);
     return *this;
   }
operator()() [8/18]
ezexample& ezexample::operator() (char ns, fid fint) inline
Definition at line 374 of file ezexample.h.
   {
     addf(ns, fint, 1.0);
     return *this;
   }
operator()() [9/18]
ezexample& ezexample::operator() (char ns, std::string fstr) inline
Definition at line 379 of file ezexample.h.
   {
     addf(ns, fstr, 1.0);
     return *this;
   }
operator()() [10/18]
ezexample& ezexample::operator() (char ns, const char * fstr) inline
Definition at line 384 of file ezexample.h.
   {
     addf(ns, fstr, 1.0);
     return *this;
   }
operator()() [11/18]
ezexample& ezexample::operator() (char ns, fid fint, float val) inline
Definition at line 389 of file ezexample.h.
   {
     addf(ns, fint, val);
     return *this;
   }
operator()() [12/18]
ezexample& ezexample::operator() (char ns, std::string fstr, float val) inline
Definition at line 394 of file ezexample.h.
   {
     addf(ns, fstr, val);
     return *this;
   }
operator()() [13/18]
ezexample& ezexample::operator() (char ns, const char * fstr, float val) inline
Definition at line 399 of file ezexample.h.
   {
     addf(ns, fstr, val);
     return *this;
   }
operator()() [14/18]
ezexample& ezexample::operator() (example & other, char other_ns, char to_ns) inline
Definition at line 405 of file ezexample.h.
   {
     add_other_example_ns(other, other_ns, to_ns);
     return *this;
   }
operator()() [15/18]
ezexample& ezexample::operator() (example & other, char ns) inline
Definition at line 410 of file ezexample.h.
   {
     add_other_example_ns(other, ns);
     return *this;
   }
operator()() [16/18]
ezexample& ezexample::operator() (ezexample & other, char other_ns, char to_ns) inline
Definition at line 415 of file ezexample.h.
   {
     add_other_example_ns(other, other_ns, to_ns);
     return *this;
   }
operator()() [17/18]
ezexample& ezexample::operator() (ezexample & other, char ns) inline
Definition at line 420 of file ezexample.h.
   {
     add_other_example_ns(other, ns);
     return *this;
   }
operator()() [18/18]
float ezexample::operator() () inline
Definition at line 432 of file ezexample.h.
References predict().
 { return predict(); }
operator--()
ezexample& ezexample::operator-- () inline
Definition at line 426 of file ezexample.h.
   {
     remns();
     return *this;
   }
operator=()
ezexample& ezexample::operator= (const ezexample & ex) private
predict()
float ezexample::predict () inline
Definition at line 256 of file ezexample.h.
References example::pred, and polyprediction::scalar.
   {
     setup_for_predict();
     return ec->pred.scalar;
   }
predict_partial()
float ezexample::predict_partial () inline
Definition at line 262 of file ezexample.h.
References example::partial_prediction.
   {
     setup_for_predict();
     return ec->partial_prediction;
   }
remns()
void ezexample::remns () inline
Definition at line 156 of file ezexample.h.
References example_predict::feature_space, example_predict::indices, example::num_features, v_array< T >::pop(), v_array< T >::size(), and example::total_sum_feat_sq.
   {
     if (ec->indices.size() == 0)
     {
       current_seed = 0;
       current_ns = 0;
     }
     else
     {
       if (ns_exists[(int)current_ns])
       {
         ec->total_sum_feat_sq -= ec->feature_space[(int)current_ns].sum_feat_sq;
         ec->feature_space[(int)current_ns].clear();
         ec->num_features -= ec->feature_space[(int)current_ns].size();
         ns_exists[(int)current_ns] = false;
       }
       current_seed = past_seeds.back();
       past_seeds.pop_back();
       ec->indices.pop();
       example_changed_since_prediction = true;
     }
   }
set_label()
ezexample& ezexample::set_label (std::string label) inline
Definition at line 219 of file ezexample.h.
References VW::parse_example_label().
   {
     VW::parse_example_label(*vw_par_ref, *ec, label);
     example_changed_since_prediction = true;
     return *this;
   }
setup_for_predict()
void ezexample::setup_for_predict () inline private
Definition at line 77 of file ezexample.h.
References VW::empty_example(), vw::learn(), and VW::read_example().
   {
     static example* empty_example = is_multiline ? VW::read_example(*vw_par_ref, (char*)"") : nullptr;
     if (example_changed_since_prediction)
     {
       mini_setup_example();
       vw_ref->learn(*ec);
       if (is_multiline)
         vw_ref->learn(*empty_example);
       example_changed_since_prediction = false;
     }
   }
setup_new_ezexample()
void ezexample::setup_new_ezexample (vw * this_vw, bool multiline, vw * this_vw_parser) inline private
Definition at line 58 of file ezexample.h.
   {
     vw_ref = this_vw;
     vw_par_ref = (this_vw_parser == nullptr) ? this_vw : this_vw_parser;
     is_multiline = multiline;
     str[0] = 0;
     str[1] = 0;
     current_seed = 0;
     current_ns = 0;
     quadratic_features_num = 0;
     quadratic_features_sqr = 0.;
     for (size_t i = 0; i < 256; i++) ns_exists[i] = false;
     example_changed_since_prediction = true;
   }
train()
void ezexample::train () inline
Definition at line 268 of file ezexample.h.
References vw::audit, VW::copy_example_data(), label_parser::copy_label, example::in_use, label_parser::label_size, vw::learn(), parser::lp, vw::p, and v_array< T >::push_back().
   {
     if (example_changed_since_prediction)
     {
       mini_setup_example();
       example_changed_since_prediction = false;
     }
     if (!is_multiline)
     {
       vw_ref->learn(*ec);
     }
     else  // is multiline
     {     // we need to make a copy
       example* copy = get_new_example();
       assert(ec->in_use);
       VW::copy_example_data(vw_ref->audit, copy, ec, vw_par_ref->p->lp.label_size, vw_par_ref->p->lp.copy_label);
       assert(copy->in_use);
       vw_ref->learn(*copy);
       example_copies.push_back(copy);
     }
   }
Member Data Documentation
current_ns
char ezexample::current_ns private
Definition at line 30 of file ezexample.h.
current_seed
fid ezexample::current_seed private
Definition at line 27 of file ezexample.h.
ec
example* ezexample::ec private
Definition at line 24 of file ezexample.h.
Referenced by add_other_example_ns().
example_changed_since_prediction
bool ezexample::example_changed_since_prediction private
Definition at line 32 of file ezexample.h.
example_copies
v_array<example*> ezexample::example_copies private
Definition at line 34 of file ezexample.h.
is_multiline
bool ezexample::is_multiline private
Definition at line 21 of file ezexample.h.
ns_exists
bool ezexample::ns_exists[256] private
Definition at line 31 of file ezexample.h.
past_seeds
std::vector<fid> ezexample::past_seeds private
Definition at line 26 of file ezexample.h.
quadratic_features_num
size_t ezexample::quadratic_features_num private
Definition at line 28 of file ezexample.h.
quadratic_features_sqr
float ezexample::quadratic_features_sqr private
Definition at line 29 of file ezexample.h.
str
char ezexample::str[2] private
Definition at line 23 of file ezexample.h.
vw_par_ref
vw* ezexample::vw_par_ref private
Definition at line 20 of file ezexample.h.
vw_ref
vw* ezexample::vw_ref private
Definition at line 19 of file ezexample.h.
we_create_ec
bool ezexample::we_create_ec private
Definition at line 25 of file ezexample.h.
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/ezexample.h