Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/classweight.cc File Reference
classweight.cc File Reference
#include <unordered_map>
#include "reductions.h"
Classes
struct CLASSWEIGHTS::classweights
Namespaces
CLASSWEIGHTS
Functions
template<bool is_learn, int pred_type>
static void CLASSWEIGHTS::predict_or_learn (classweights &cweights, LEARNER::single_learner &base, example &ec)
void CLASSWEIGHTS::finish (classweights &data)
LEARNER::base_learner * classweight_setup (options_i &options, vw &all)
Function Documentation
classweight_setup()
LEARNER::base_learner* classweight_setup (options_i & options, vw & all)
Definition at line 74 of file classweight.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), CLASSWEIGHTS::finish(), LEARNER::make_base(), VW::config::make_option(), prediction_type::multiclass, LEARNER::learner< T, E >::pred_type, vw::quiet, prediction_type::scalar, LEARNER::learner< T, E >::set_finish(), setup_base(), THROW, vw::trace_message, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   vector<string> classweight_array;
   auto cweights = scoped_calloc_or_throw<classweights>();
   option_group_definition new_options("importance weight classes");
   new_options.add(make_option("classweight", classweight_array).help("importance weight multiplier for class"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("classweight"))
     return nullptr;
   for (auto& s : classweight_array) cweights->load_string(s);
   if (!all.quiet)
     all.trace_message << "parsed " << cweights->weights.size() << " class weights" << endl;
   LEARNER::single_learner* base = as_singleline(setup_base(options, all));
   LEARNER::learner<classweights, example>* ret;
   if (base->pred_type == prediction_type::scalar)
     ret = &LEARNER::init_learner<classweights>(cweights, base, predict_or_learn<true, prediction_type::scalar>,
         predict_or_learn<false, prediction_type::scalar>);
   else if (base->pred_type == prediction_type::multiclass)
     ret = &LEARNER::init_learner<classweights>(cweights, base, predict_or_learn<true, prediction_type::multiclass>,
         predict_or_learn<false, prediction_type::multiclass>);
   else
     THROW("--classweight not implemented for this type of prediction");
   ret->set_finish(finish);
   return make_base(*ret);
 }