Vowpal Wabbit: features_value_iterator Class Reference
features_value_iterator Class Reference
iterator over feature values only
#include <feature_group.h>
Public Member Functions
features_value_iterator (feature_value *begin)
features_value_iterator (const features_value_iterator &other)
features_value_iterator & operator++ ()
feature_value & value ()
template<typename T >
features_value_iterator operator+ (T index)
template<typename T >
features_value_iterator & operator+= (T index)
template<typename T >
features_value_iterator & operator-= (T index)
features_value_iterator & operator= (const features_value_iterator &other)
features_value_iterator & operator* ()
bool operator== (const features_value_iterator &rhs)
bool operator!= (const features_value_iterator &rhs)
Protected Attributes
feature_value * _begin
Friends
struct features
void swap (features_value_iterator &lhs, features_value_iterator &rhs)
Detailed Description
iterator over feature values only
Definition at line 54 of file feature_group.h.
Constructor & Destructor Documentation
features_value_iterator() [1/2]
features_value_iterator::features_value_iterator (feature_value * begin) inline
Definition at line 60 of file feature_group.h.
 : _begin(begin) {}
features_value_iterator() [2/2]
features_value_iterator::features_value_iterator (const features_value_iterator & other) inline
Definition at line 62 of file feature_group.h.
 : _begin(other._begin) {}
Member Function Documentation
operator!=()
bool features_value_iterator::operator!= (const features_value_iterator & rhs) inline
Definition at line 104 of file feature_group.h.
References _begin.
 { return _begin != rhs._begin; }
operator*()
features_value_iterator& features_value_iterator::operator* () inline
Definition at line 101 of file feature_group.h.
 { return *this; }
operator+()
template<typename T > features_value_iterator features_value_iterator::operator+ (T index) inline
creates a new iterator advanced by index
Remarks
template<typename T> used to avoid warnings or tons of overloads for int, size_t, ...
Definition at line 76 of file feature_group.h.
   {
     return features_value_iterator(_begin + index);
   }
operator++()
features_value_iterator& features_value_iterator::operator++ () inline
Definition at line 64 of file feature_group.h.
Referenced by features_value_index_iterator::operator++().
   {
     _begin++;
     return *this;
   }
operator+=()
template<typename T > features_value_iterator& features_value_iterator::operator+= (T index) inline
Definition at line 82 of file feature_group.h.
Referenced by features_value_index_iterator::operator+=().
   {
     _begin += index;
     return *this;
   }
operator-=()
template<typename T > features_value_iterator& features_value_iterator::operator-= (T index) inline
Definition at line 89 of file feature_group.h.
Referenced by features_value_index_iterator::operator-=().
   {
     _begin -= index;
     return *this;
   }
operator=()
features_value_iterator& features_value_iterator::operator= (const features_value_iterator & other) inline
Definition at line 95 of file feature_group.h.
References _begin.
Referenced by features_value_index_iterator::operator=().
   {
     _begin = other._begin;
     return *this;
   }
operator==()
bool features_value_iterator::operator== (const features_value_iterator & rhs) inline
Definition at line 103 of file feature_group.h.
References _begin.
 { return _begin == rhs._begin; }
value()
feature_value& features_value_iterator::value () inline
Returns
reference to the current value
Definition at line 71 of file feature_group.h.
Referenced by collision_cleanup(), INTERACTIONS::inner_kernel(), and unique_features().
 { return *_begin; }
Friends And Related Function Documentation
features
friend struct features friend
Definition at line 108 of file feature_group.h.
swap
void swap (features_value_iterator & lhs, features_value_iterator & rhs) friend
Definition at line 106 of file feature_group.h.
 { std::swap(lhs._begin, rhs._begin); }
Member Data Documentation
_begin
feature_value* features_value_iterator::_begin protected
Definition at line 57 of file feature_group.h.
Referenced by operator!=(), operator=(), operator==(), and features::truncate_to().
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/feature_group.h