Vowpal Wabbit: comp_io_buf Class Reference
comp_io_buf Class Reference
#include <comp_io.h>
Public Member Functions
virtual int open_file (const char *name, bool stdin_off, int flag=READ)
virtual void reset_file (int f)
virtual ssize_t read_file (int f, void *buf, size_t nbytes)
virtual size_t num_files ()
virtual ssize_t write_file (int file, const void *buf, size_t nbytes)
virtual bool compressed ()
virtual void flush ()
virtual bool close_file ()
Public Member Functions inherited from io_buf
void init ()
void verify_hash (bool verify)
uint32_t hash ()
io_buf ()
virtual ~io_buf ()
void set (char *p)
ssize_t fill (int f)
void close_files ()
void buf_write (char *&pointer, size_t n)
size_t buf_read (char *&pointer, size_t n)
size_t bin_read_fixed (char *data, size_t len, const char *read_message)
size_t bin_write_fixed (const char *data, size_t len)
Public Attributes
std::vector< gzFile > gz_files
Public Attributes inherited from io_buf
v_array< char > space
v_array< int > files
size_t count
size_t current
char * head
v_array< char > currentname
v_array< char > finalname
Additional Inherited Members
Static Public Member Functions inherited from io_buf
static ssize_t read_file_or_socket (int f, void *buf, size_t nbytes)
static ssize_t write_file_or_socket (int f, const void *buf, size_t nbytes)
static void close_file_or_socket (int f)
static bool is_socket (int f)
Static Public Attributes inherited from io_buf
static constexpr int READ = 1
static constexpr int WRITE = 2
Detailed Description
Definition at line 19 of file comp_io.h.
Member Function Documentation
close_file()
bool comp_io_buf::close_file () virtual
Reimplemented from io_buf.
Definition at line 75 of file comp_io.cc.
References io_buf::files, gz_files, v_array< T >::pop(), and v_array< T >::size().
 {
   if (gz_files.size() > 0)
   {
     gzclose(gz_files.back());
     gz_files.pop_back();
     if (files.size() > 0)
       files.pop();
     return true;
   }
   return false;
 }
compressed()
bool comp_io_buf::compressed () virtual
Reimplemented from io_buf.
Definition at line 66 of file comp_io.cc.
 { return true; }
flush()
void comp_io_buf::flush () virtual
Reimplemented from io_buf.
Definition at line 68 of file comp_io.cc.
References v_array< T >::begin(), v_array< T >::end(), io_buf::head, io_buf::space, and write_file().
 {
   if (write_file(0, space.begin(), head - space.end()) != (int)((head - space.end())))
     std::cerr << "error, failed to write to cache\n";
   head = space.begin();
 }
num_files()
size_t comp_io_buf::num_files () virtual
Reimplemented from io_buf.
Definition at line 58 of file comp_io.cc.
References gz_files.
 { return gz_files.size(); }
open_file()
int comp_io_buf::open_file (const char * name, bool stdin_off, int flag = READ) virtual
Reimplemented from io_buf.
Definition at line 4 of file comp_io.cc.
References io_buf::files, gz_files, v_array< T >::push_back(), io_buf::READ, and io_buf::WRITE.
 {
   gzFile fil = nullptr;
   int ret = -1;
   switch (flag)
   {
     case READ:
       if (*name != '\0')
         fil = gzopen(name, "rb");
       else if (!stdin_off)
 #ifdef _WIN32
         fil = gzdopen(_fileno(stdin), "rb");
 #else
         fil = gzdopen(fileno(stdin), "rb");
 #endif
       if (fil != nullptr)
       {
         gz_files.push_back(fil);
         ret = (int)gz_files.size() - 1;
         files.push_back(ret);
       }
       break;
     case WRITE:
       fil = gzopen(name, "wb");
       if (fil != nullptr)
       {
         gz_files.push_back(fil);
         ret = (int)gz_files.size() - 1;
         files.push_back(ret);
       }
       break;
     default:
       std::cerr << "Unknown file operation. Something other than READ/WRITE specified" << std::endl;
   }
   return ret;
 }
read_file()
ssize_t comp_io_buf::read_file (int f, void * buf, size_t nbytes) virtual
Reimplemented from io_buf.
Definition at line 51 of file comp_io.cc.
References f, and gz_files.
 {
   gzFile fil = gz_files[f];
   int num_read = gzread(fil, buf, (unsigned int)nbytes);
   return (num_read > 0) ? num_read : 0;
 }
reset_file()
void comp_io_buf::reset_file (int f) virtual
Reimplemented from io_buf.
Definition at line 43 of file comp_io.cc.
References v_array< T >::begin(), v_array< T >::end(), f, gz_files, io_buf::head, and io_buf::space.
 {
   gzFile fil = gz_files[f];
   gzseek(fil, 0, SEEK_SET);
   space.end() = space.begin();
   head = space.begin();
 }
write_file()
ssize_t comp_io_buf::write_file (int file, const void * buf, size_t nbytes) virtual
Reimplemented from io_buf.
Definition at line 60 of file comp_io.cc.
References gz_files.
Referenced by flush().
 {
   int num_written = gzwrite(gz_files[file], buf, (unsigned int)nbytes);
   return (num_written > 0) ? num_written : 0;
 }
Member Data Documentation
gz_files
std::vector<gzFile> comp_io_buf::gz_files
Definition at line 22 of file comp_io.h.
Referenced by close_file(), num_files(), open_file(), read_file(), reset_file(), and write_file().
The documentation for this class was generated from the following files:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/comp_io.h
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/comp_io.cc