Vowpal Wabbit: ArrayState< audit > Class Template Reference
ArrayState< audit > Class Template Reference
#include <parse_example_json.h>
Public Member Functions
ArrayState ()
BaseState< audit > * StartArray (Context< audit > &ctx) override
BaseState< audit > * Float (Context< audit > &ctx, float f) override
BaseState< audit > * Uint (Context< audit > &ctx, unsigned f) override
BaseState< audit > * Null (Context< audit > &) override
BaseState< audit > * StartObject (Context< audit > &ctx) override
BaseState< audit > * EndArray (Context< audit > &ctx, rapidjson::SizeType) override
Public Member Functions inherited from BaseState< audit >
BaseState (const char *pname)
virtual BaseState< audit > * Bool (Context< audit > &ctx, bool b)
virtual BaseState< audit > * String (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * Key (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * EndObject (Context< audit > &ctx, rapidjson::SizeType)
Private Attributes
feature_index array_hash
Additional Inherited Members
Public Attributes inherited from BaseState< audit >
const char * name
Detailed Description
template<bool audit>
class ArrayState< audit >
Definition at line 537 of file parse_example_json.h.
Constructor & Destructor Documentation
ArrayState()
template<bool audit> ArrayState< audit >::ArrayState () inline
Definition at line 542 of file parse_example_json.h.
 : BaseState<audit>("Array") {}
Member Function Documentation
EndArray()
template<bool audit> BaseState<audit>* ArrayState< audit >::EndArray (Context< audit > & ctx, rapidjson::SizeType) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 591 of file parse_example_json.h.
References Context< audit >::PopNamespace().
   {
     return ctx.PopNamespace();
   }
Float()
template<bool audit> BaseState<audit>* ArrayState< audit >::Float (Context< audit > & ctx, float f) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 559 of file parse_example_json.h.
References Context< audit >::CurrentNamespace().
   {
     if (audit)
     {
       stringstream str;
       str << '[' << (array_hash - ctx.CurrentNamespace().namespace_hash) << ']';
       ctx.CurrentNamespace().AddFeature(f, array_hash, str.str().c_str());
     }
     else
       ctx.CurrentNamespace().AddFeature(f, array_hash, nullptr);
     array_hash++;
     return this;
   }
Null()
template<bool audit> BaseState<audit>* ArrayState< audit >::Null (Context< audit > &) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 577 of file parse_example_json.h.
   {
     // ignore null values and stay in current state
     return this;
   }
StartArray()
template<bool audit> BaseState<audit>* ArrayState< audit >::StartArray (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 544 of file parse_example_json.h.
References Context< audit >::CurrentNamespace(), Context< audit >::error(), Context< audit >::key, Context< audit >::previous_state, and Context< audit >::PushNamespace().
   {
     if (ctx.previous_state == this)
     {
       ctx.error() << "Nested arrays are not supported";
       return nullptr;
     }
     ctx.PushNamespace(ctx.key, ctx.previous_state);
     array_hash = ctx.CurrentNamespace().namespace_hash;
     return this;
   }
StartObject()
template<bool audit> BaseState<audit>* ArrayState< audit >::StartObject (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 583 of file parse_example_json.h.
References Context< audit >::CurrentNamespace(), Context< audit >::default_state, Context< audit >::namespace_path, and Context< audit >::PushNamespace().
   {
     // parse properties
     ctx.PushNamespace(ctx.namespace_path.size() > 0 ? ctx.CurrentNamespace().name : " ", this);
     return &ctx.default_state;
   }
Uint()
template<bool audit> BaseState<audit>* ArrayState< audit >::Uint (Context< audit > & ctx, unsigned f) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 575 of file parse_example_json.h.
 { return Float(ctx, (float)f); }
Member Data Documentation
array_hash
template<bool audit> feature_index ArrayState< audit >::array_hash private
Definition at line 539 of file parse_example_json.h.
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/parse_example_json.h