Vowpal Wabbit: Search::BaseTask Class Reference
Search::BaseTask Class Reference
#include <search.h>
Public Member Functions
BaseTask (search *_sch, multi_ex &_ec)
BaseTask & foreach_action (void(*f)(search &, size_t, float, action, bool, float))
BaseTask & post_prediction (void(*f)(search &, size_t, action, float))
BaseTask & maybe_override_prediction (bool(*f)(search &, size_t, action &, float &))
BaseTask & with_output_string (void(*f)(search &, std::stringstream &))
BaseTask & final_run ()
void Run ()
Public Attributes
search * sch
multi_ex & ec
bool _final_run
void(* _foreach_action)(search &, size_t, float, action, bool, float)
void(* _post_prediction)(search &, size_t, action, float)
bool(* _maybe_override_prediction)(search &, size_t, action &, float &)
void(* _with_output_string)(search &, std::stringstream &)
Detailed Description
Definition at line 31 of file search.h.
Constructor & Destructor Documentation
BaseTask()
Search::BaseTask::BaseTask (search * _sch, multi_ex & _ec) inline
Definition at line 34 of file search.h.
References _final_run, _foreach_action, _maybe_override_prediction, _post_prediction, and _with_output_string.
Referenced by Search::search::base_task().
                                         : sch(_sch), ec(_ec)
   {
     _foreach_action = nullptr;
     _post_prediction = nullptr;
     _maybe_override_prediction = nullptr;
     _with_output_string = nullptr;
     _final_run = false;
   }
Member Function Documentation
final_run()
BaseTask& Search::BaseTask::final_run () inline
Definition at line 62 of file search.h.
References _final_run, and Run().
   {
     _final_run = true;
     return *this;
   }
foreach_action()
BaseTask& Search::BaseTask::foreach_action (void(*)(search &, size_t, float, action, bool, float) f) inline
Definition at line 42 of file search.h.
References _foreach_action, and f.
Referenced by DebugMT::run(), and SelectiveBranchingMT::run().
   {
     _foreach_action = f;
     return *this;
   }
maybe_override_prediction()
BaseTask& Search::BaseTask::maybe_override_prediction (bool(*)(search &, size_t, action &, float &) f) inline
Definition at line 52 of file search.h.
References _maybe_override_prediction, and f.
   {
     _maybe_override_prediction = f;
     return *this;
   }
post_prediction()
BaseTask& Search::BaseTask::post_prediction (void(*)(search &, size_t, action, float) f) inline
Definition at line 47 of file search.h.
References _post_prediction, and f.
   {
     _post_prediction = f;
     return *this;
   }
Run()
void Search::BaseTask::Run ()
Definition at line 1991 of file search.cc.
References Search::search_private::learn_loss, Search::search_private::meta_t, Search::search_private::metaoverride, Search::search_private::pred_string, Search::search_task::run, Search::search_private::should_produce_string, Search::search_private::t, Search::search_private::task, Search::search_private::test_loss, and Search::search_private::train_loss.
Referenced by final_run(), DebugMT::run(), and SelectiveBranchingMT::run().
 {
   search_private& priv = *sch->priv;
   // make sure output is correct
   bool old_should_produce_string = priv.should_produce_string;
   if (!_final_run && !_with_output_string)
     priv.should_produce_string = false;
   // if this isn't a final run, it shouldn't count for loss
   float old_test_loss = priv.test_loss;
   // float old_learn_loss = priv.learn_loss;
   priv.learn_loss *= 0.5;
   float old_train_loss = priv.train_loss;
   if (priv.should_produce_string)
     priv.pred_string->str("");
   priv.t = 0;
   priv.metaoverride = this;
   priv.task->run(*sch, ec);
   priv.metaoverride = nullptr;
   priv.meta_t += priv.t;
   // restore
   if (_with_output_string && old_should_produce_string)
     _with_output_string(*sch, *priv.pred_string);
   priv.should_produce_string = old_should_produce_string;
   if (!_final_run)
   {
     priv.test_loss = old_test_loss;
     // priv.learn_loss = old_learn_loss;
     priv.train_loss = old_train_loss;
   }
 }
with_output_string()
BaseTask& Search::BaseTask::with_output_string (void(*)(search &, std::stringstream &) f) inline
Definition at line 57 of file search.h.
References _with_output_string, and f.
   {
     _with_output_string = f;
     return *this;
   }
Member Data Documentation
_final_run
bool Search::BaseTask::_final_run
Definition at line 73 of file search.h.
Referenced by BaseTask(), and final_run().
_foreach_action
void(* Search::BaseTask::_foreach_action) (search &, size_t, float, action, bool, float)
Definition at line 74 of file search.h.
Referenced by BaseTask(), foreach_action(), Search::foreach_action_from_cache(), Search::search_predict(), Search::single_prediction_LDF(), and Search::single_prediction_notLDF().
_maybe_override_prediction
bool(* Search::BaseTask::_maybe_override_prediction) (search &, size_t, action &, float &)
Definition at line 76 of file search.h.
Referenced by BaseTask(), maybe_override_prediction(), and Search::search_predict().
_post_prediction
void(* Search::BaseTask::_post_prediction) (search &, size_t, action, float)
Definition at line 75 of file search.h.
Referenced by BaseTask(), post_prediction(), and Search::search_predict().
_with_output_string
void(* Search::BaseTask::_with_output_string) (search &, std::stringstream &)
Definition at line 77 of file search.h.
Referenced by BaseTask(), and with_output_string().
ec
multi_ex& Search::BaseTask::ec
Definition at line 72 of file search.h.
Referenced by Search::search::get_metatask_data().
sch
search* Search::BaseTask::sch
Definition at line 71 of file search.h.
Referenced by Search::foreach_action_from_cache(), Search::search_predict(), Search::single_prediction_LDF(), and Search::single_prediction_notLDF().
The documentation for this class was generated from the following files:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/search.h
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/search.cc