Vowpal Wabbit: features_value_index_audit_iterator Class Reference
features_value_index_audit_iterator Class Reference
iterator over values, indicies and audit space names
#include <feature_group.h>
Public Member Functions
features_value_index_audit_iterator (feature_value *begin, feature_index *begin_index, audit_strings_ptr *begin_audit)
features_value_index_audit_iterator (const features_value_index_audit_iterator &other)
features_value_index_audit_iterator & operator++ ()
audit_strings_ptr & audit ()
template<typename T >
features_value_index_audit_iterator & operator+= (T index)
template<typename T >
features_value_index_audit_iterator operator+ (T index)
template<typename T >
features_value_index_audit_iterator & operator-= (T index)
features_value_index_audit_iterator & operator= (const features_value_index_audit_iterator &other)
features_value_index_audit_iterator & operator* ()
Public Member Functions inherited from features_value_index_iterator
features_value_index_iterator (feature_value *begin, feature_index *begin_index)
features_value_index_iterator (const features_value_index_iterator &other)
features_value_index_iterator & operator++ ()
feature_index & index ()
template<typename T >
features_value_index_iterator & operator+= (T index)
template<typename T >
features_value_index_iterator operator+ (T index)
template<typename T >
features_value_index_iterator & operator-= (T index)
features_value_index_iterator & operator= (const features_value_index_iterator &other)
features_value_index_iterator & operator* ()
Public Member Functions inherited from features_value_iterator
features_value_iterator (feature_value *begin)
features_value_iterator (const features_value_iterator &other)
features_value_iterator & operator++ ()
feature_value & value ()
template<typename T >
features_value_iterator operator+ (T index)
template<typename T >
features_value_iterator & operator+= (T index)
template<typename T >
features_value_iterator & operator-= (T index)
features_value_iterator & operator= (const features_value_iterator &other)
features_value_iterator & operator* ()
bool operator== (const features_value_iterator &rhs)
bool operator!= (const features_value_iterator &rhs)
Protected Attributes
audit_strings_ptr * _begin_audit
Protected Attributes inherited from features_value_index_iterator
feature_index * _begin_index
Protected Attributes inherited from features_value_iterator
feature_value * _begin
Friends
void swap (features_value_index_audit_iterator &lhs, features_value_index_audit_iterator &rhs)
Detailed Description
iterator over values, indicies and audit space names
Definition at line 176 of file feature_group.h.
Constructor & Destructor Documentation
features_value_index_audit_iterator() [1/2]
features_value_index_audit_iterator::features_value_index_audit_iterator (feature_value * begin, feature_index * begin_index, audit_strings_ptr * begin_audit) inline
Definition at line 182 of file feature_group.h.
       : features_value_index_iterator(begin, begin_index), _begin_audit(begin_audit)
   {
   }
features_value_index_audit_iterator() [2/2]
features_value_index_audit_iterator::features_value_index_audit_iterator (const features_value_index_audit_iterator & other) inline
Definition at line 187 of file feature_group.h.
       : features_value_index_iterator(other), _begin_audit(other._begin_audit)
   {
   }
Member Function Documentation
audit()
audit_strings_ptr& features_value_index_audit_iterator::audit () inline
Definition at line 200 of file feature_group.h.
Referenced by INTERACTIONS::inner_kernel(), and unique_features().
 { return *_begin_audit; }
operator*()
features_value_index_audit_iterator& features_value_index_audit_iterator::operator* () inline
Definition at line 231 of file feature_group.h.
 { return *this; }
operator+()
template<typename T > features_value_index_audit_iterator features_value_index_audit_iterator::operator+ (T index) inline
Definition at line 211 of file feature_group.h.
   {
     return features_value_index_audit_iterator(_begin + index, _begin_index + index, _begin_audit + index);
   }
operator++()
features_value_index_audit_iterator& features_value_index_audit_iterator::operator++ () inline
Definition at line 193 of file feature_group.h.
References features_value_index_iterator::operator++().
   {
     features_value_index_iterator::operator++();
     _begin_audit++;
     return *this;
   }
operator+=()
template<typename T > features_value_index_audit_iterator& features_value_index_audit_iterator::operator+= (T index) inline
Definition at line 203 of file feature_group.h.
References features_value_index_iterator::operator+=().
   {
     features_value_index_iterator::operator+=(index);
     _begin_audit += index;
     return *this;
   }
operator-=()
template<typename T > features_value_index_audit_iterator& features_value_index_audit_iterator::operator-= (T index) inline
Definition at line 217 of file feature_group.h.
References features_value_index_iterator::operator-=().
   {
     features_value_index_iterator::operator-=(index);
     _begin_audit += index;
     return *this;
   }
operator=()
features_value_index_audit_iterator& features_value_index_audit_iterator::operator= (const features_value_index_audit_iterator & other) inline
Definition at line 224 of file feature_group.h.
References _begin_audit, and features_value_index_iterator::operator=().
   {
     features_value_index_iterator::operator=(other);
     _begin_audit = other._begin_audit;
     return *this;
   }
Friends And Related Function Documentation
swap
void swap (features_value_index_audit_iterator & lhs, features_value_index_audit_iterator & rhs) friend
Definition at line 233 of file feature_group.h.
   {
     swap(static_cast<features_value_index_iterator&>(lhs), static_cast<features_value_index_iterator&>(rhs));
     swap(lhs._begin_audit, rhs._begin_audit);
   }
Member Data Documentation
_begin_audit
audit_strings_ptr* features_value_index_audit_iterator::_begin_audit protected
Definition at line 179 of file feature_group.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/feature_group.h