Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/cs_active.h File Reference
cs_active.h File Reference
Functions
LEARNER::base_learner * cs_active_setup (VW::config::options_i &options, vw &all)
Function Documentation
cs_active_setup()
LEARNER::base_learner* cs_active_setup (VW::config::options_i & options, vw & all)
Definition at line 307 of file cs_active.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), vw::cost_sensitive, COST_SENSITIVE::cs_label, f, finish(), finish_example(), loss_function::getType(), LEARNER::init_learner(), vw::loss, parser::lp, LEARNER::make_base(), VW::config::make_option(), prediction_type::multilabels, vw::p, vw::sd, LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), vw::set_minmax, setup_base(), THROW, vw::trace_message, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<cs_active>();
   bool simulation = false;
   int domination;
   option_group_definition new_options("Cost-sensitive Active Learning");
   new_options
       .add(make_option("cs_active", data->num_classes).keep().help("Cost-sensitive active learning with <k> costs"))
       .add(make_option("simulation", simulation).help("cost-sensitive active learning simulation mode"))
       .add(make_option("baseline", data->is_baseline).help("cost-sensitive active learning baseline"))
       .add(make_option("domination", domination)
                .default_value(1)
                .help("cost-sensitive active learning use domination. Default 1"))
       .add(make_option("mellowness", data->c0).default_value(0.1f).help("mellowness parameter c_0. Default 0.1."))
       .add(make_option("range_c", data->c1)
                .default_value(0.5f)
                .help("parameter controlling the threshold for per-label cost uncertainty. Default 0.5."))
       .add(make_option("max_labels", data->max_labels).default_value(-1).help("maximum number of label queries."))
       .add(make_option("min_labels", data->min_labels).default_value(-1).help("minimum number of label queries."))
       .add(make_option("cost_max", data->cost_max).default_value(1.f).help("cost upper bound. Default 1."))
       .add(make_option("cost_min", data->cost_min).default_value(0.f).help("cost lower bound. Default 0."))
       // TODO replace with trace and quiet
       .add(make_option("csa_debug", data->print_debug_stuff).help("print debug stuff for cs_active"));
   options.add_and_parse(new_options);
   data->use_domination = true;
   if (options.was_supplied("domination") && !domination)
     data->use_domination = false;
   if (!options.was_supplied("cs_active"))
     return nullptr;
   data->all = &all;
   data->t = 1;
   auto loss_function_type = all.loss->getType();
   if (loss_function_type != "squared")
     THROW("error: you can't use non-squared loss with cs_active");
   if (options.was_supplied("lda"))
     THROW("error: you can't combine lda and active learning");
   if (options.was_supplied("active"))
     THROW("error: you can't use --cs_active and --active at the same time");
   if (options.was_supplied("active_cover"))
     THROW("error: you can't use --cs_active and --active_cover at the same time");
   if (options.was_supplied("csoaa"))
     THROW("error: you can't use --cs_active and --csoaa at the same time");
   if (!options.was_supplied("adax"))
     all.trace_message << "WARNING: --cs_active should be used with --adax" << endl;
   all.p->lp = cs_label;  // assigning the label parser
   all.set_minmax(all.sd, data->cost_max);
   all.set_minmax(all.sd, data->cost_min);
   for (uint32_t i = 0; i < data->num_classes + 1; i++) data->examples_by_queries.push_back(0);
   learner<cs_active, example>& l = simulation
       ? init_learner(data, as_singleline(setup_base(options, all)), predict_or_learn<true, true>,
             predict_or_learn<false, true>, data->num_classes, prediction_type::multilabels)
       : init_learner(data, as_singleline(setup_base(options, all)), predict_or_learn<true, false>,
             predict_or_learn<false, false>, data->num_classes, prediction_type::multilabels);
   l.set_finish_example(finish_example);
   l.set_finish(finish);
   base_learner* b = make_base(l);
   all.cost_sensitive = b;
   return b;
 }