Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/example.h File Reference
example.h File Reference
#include <stdint.h>
#include "v_array.h"
#include "no_label.h"
#include "simple_label.h"
#include "multiclass.h"
#include "multilabel.h"
#include "cost_sensitive.h"
#include "cb.h"
#include "constant.h"
#include "feature_group.h"
#include "action_score.h"
#include "example_predict.h"
#include "conditional_contextual_bandit.h"
#include "ccb_label.h"
#include <vector>
Classes
union polylabel
union polyprediction
struct example
struct flat_example
Namespaces
VW
Macros
#define add_passthrough_feature(ec, i, x) add_passthrough_feature_magic(ec, __FILE__[0] * 483901 + __FILE__[1] * 3417 + __FILE__[2] * 8490177, i, x);
Typedefs
typedef std::vector< example * > multi_ex
Functions
void delete_scalars (void *v)
flat_example * flatten_example (vw &all, example *ec)
flat_example * flatten_sort_example (vw &all, example *ec)
void free_flatten_example (flat_example *fec)
int example_is_newline (example &ec)
bool valid_ns (char c)
void add_passthrough_feature_magic (example &ec, uint64_t magic, uint64_t i, float x)
void VW::clear_seq_and_finish_examples (vw &all, multi_ex &ec_seq)
void VW::return_multiple_example (vw &all, v_array< example *> &examples)
Variables
constexpr unsigned char default_namespace = 32
constexpr unsigned char wap_ldf_namespace = 126
constexpr unsigned char history_namespace = 127
constexpr unsigned char constant_namespace = 128
constexpr unsigned char nn_output_namespace = 129
constexpr unsigned char autolink_namespace = 130
constexpr unsigned char neighbor_namespace
constexpr unsigned char affix_namespace = 132
constexpr unsigned char spelling_namespace = 133
constexpr unsigned char conditioning_namespace = 134
constexpr unsigned char dictionary_namespace = 135
constexpr unsigned char node_id_namespace = 136
constexpr unsigned char message_namespace = 137
constexpr unsigned char ccb_slot_namespace = 139
constexpr unsigned char ccb_id_namespace = 140
Macro Definition Documentation
add_passthrough_feature
#define add_passthrough_feature (ec, i, x) add_passthrough_feature_magic(ec, __FILE__[0] * 483901 + __FILE__[1] * 3417 + __FILE__[2] * 8490177, i, x);
Definition at line 134 of file example.h.
Referenced by CSOAA::inner_loop(), inner_loop(), CSOAA::predict_or_learn(), predict_or_learn(), and predict_or_learn_multi().
Typedef Documentation
multi_ex
typedef std::vector<example*> multi_ex
Definition at line 137 of file example.h.
Function Documentation
add_passthrough_feature_magic()
void add_passthrough_feature_magic (example & ec, uint64_t magic, uint64_t i, float x) inline
Definition at line 128 of file example.h.
References FNV_prime, example::passthrough, and features::push_back().
 {
   if (ec.passthrough)
     ec.passthrough->push_back(x, (FNV_prime * magic) ^ i);
 }
delete_scalars()
void delete_scalars (void * v) inline
Definition at line 53 of file example.h.
References v_array< T >::delete_v().
Referenced by lda_setup(), mwt_setup(), and oaa_setup().
 {
   v_array<float>* preds = (v_array<float>*)v;
   preds->delete_v();
 }
example_is_newline()
int example_is_newline (example & ec) inline
Definition at line 119 of file example.h.
References constant_namespace, example_predict::indices, v_array< T >::last(), v_array< T >::size(), and example::tag.
Referenced by CB_ALGS::example_is_newline_not_header(), LEARNER::example_is_newline_not_header(), output_example(), CSOAA::output_example(), CSOAA::output_rank_example(), and VW::setup_example().
 {  // if only index is constant namespace or no index
   if (ec.tag.size() > 0)
     return false;
   return ((ec.indices.size() == 0) || ((ec.indices.size() == 1) && (ec.indices.last() == constant_namespace)));
 }
flatten_example()
flat_example* flatten_example (vw & all, example * ec)
Definition at line 152 of file example.cc.
References v_array< T >::begin(), example::example_counter, flat_example::example_counter, flat_example::fs, full_features_and_source::fs, example_predict::ft_offset, flat_example::ft_offset, example::l, flat_example::l, full_features_and_source::mask, parameters::mask(), parameters::not_null(), example::num_features, flat_example::num_features, polylabel::simple, v_array< T >::size(), full_features_and_source::stride_shift, parameters::stride_shift(), example::tag, flat_example::tag, flat_example::tag_len, label_data::weight, example::weight, and vw::weights.
Referenced by flatten_sort_example().
 {
   flat_example& fec = calloc_or_throw<flat_example>();
   fec.l = ec->l;
   fec.l.simple.weight = ec->weight;
   fec.tag_len = ec->tag.size();
   if (fec.tag_len > 0)
   {
     fec.tag = calloc_or_throw<char>(fec.tag_len + 1);
     memcpy(fec.tag, ec->tag.begin(), fec.tag_len);
   }
   fec.example_counter = ec->example_counter;
   fec.ft_offset = ec->ft_offset;
   fec.num_features = ec->num_features;
   full_features_and_source ffs;
   ffs.stride_shift = all.weights.stride_shift();
   if (all.weights.not_null())  // TODO:temporary fix. all.weights is not initialized at this point in some cases.
     ffs.mask = (uint64_t)all.weights.mask() >> all.weights.stride_shift();
   else
     ffs.mask = (uint64_t)LONG_MAX >> all.weights.stride_shift();
   GD::foreach_feature<full_features_and_source, uint64_t, vec_ffs_store>(all, *ec, ffs);
   fec.fs = ffs.fs;
   return &fec;
 }
flatten_sort_example()
flat_example* flatten_sort_example (vw & all, example * ec)
Definition at line 182 of file example.cc.
References collision_cleanup(), flatten_example(), flat_example::fs, vw::parse_mask, features::sort(), and flat_example::total_sum_feat_sq.
Referenced by learn(), memory_tree_ns::normalized_linear_prod(), and predict().
 {
   flat_example* fec = flatten_example(all, ec);
   fec->fs.sort(all.parse_mask);
   fec->total_sum_feat_sq = collision_cleanup(fec->fs);
   return fec;
 }
free_flatten_example()
void free_flatten_example (flat_example * fec)
Definition at line 190 of file example.cc.
References features::delete_v(), flat_example::fs, flat_example::tag, and flat_example::tag_len.
Referenced by memory_tree_ns::normalized_linear_prod(), and svm_example::~svm_example().
 {
   // note: The label memory should be freed by by freeing the original example.
   if (fec)
   {
     fec->fs.delete_v();
     if (fec->tag_len > 0)
       free(fec->tag);
     free(fec);
   }
 }
valid_ns()
bool valid_ns (char c) inline
Definition at line 126 of file example.h.
Referenced by INTERACTIONS::expand_namespaces_with_recursion(), and parse_affix_argument().
 { return !(c == '|' || c == ':'); }
Variable Documentation
affix_namespace
constexpr unsigned char affix_namespace = 132
Definition at line 33 of file example.h.
Referenced by TC_parser< audit >::maybeFeature().
autolink_namespace
constexpr unsigned char autolink_namespace = 130
Definition at line 30 of file example.h.
Referenced by predict_or_learn().
ccb_id_namespace
constexpr unsigned char ccb_id_namespace = 140
Definition at line 40 of file example.h.
Referenced by CCB::calculate_and_insert_interactions(), CCB::ccb_explore_adf_setup(), CCB::inject_slot_id(), and CCB::remove_slot_id().
ccb_slot_namespace
constexpr unsigned char ccb_slot_namespace = 139
Definition at line 39 of file example.h.
Referenced by CCB::inject_slot_features(), and CCB::remove_slot_features().
conditioning_namespace
constexpr unsigned char conditioning_namespace = 134
Definition at line 35 of file example.h.
Referenced by Search::add_example_conditioning(), and Search::del_example_conditioning().
constant_namespace
constexpr unsigned char constant_namespace = 128
Definition at line 28 of file example.h.
Referenced by DepParserTask::add_all_features(), VW::add_constant_feature(), LabelDict::add_example_namespaces_from_example(), LabelDict::del_example_namespaces_from_example(), example_is_newline(), finish_setup(), init_global(), DepParserTask::initialize(), CCB::inject_slot_features(), predict_or_learn(), CCB::remove_slot_features(), and send_features().
default_namespace
constexpr unsigned char default_namespace = 32
Definition at line 25 of file example.h.
Referenced by CCB::inject_slot_features(), and CCB::remove_slot_features().
dictionary_namespace
constexpr unsigned char dictionary_namespace = 135
Definition at line 36 of file example.h.
Referenced by TC_parser< audit >::maybeFeature().
history_namespace
constexpr unsigned char history_namespace = 127
Definition at line 27 of file example.h.
message_namespace
constexpr unsigned char message_namespace = 137
Definition at line 38 of file example.h.
Referenced by BASELINE::baseline_enabled(), BASELINE::reset_baseline_disabled(), and BASELINE::set_baseline_enabled().
neighbor_namespace
constexpr unsigned char neighbor_namespace
Initial value:
=
    131
Definition at line 31 of file example.h.
Referenced by GraphTask::add_edge_features(), GraphTask::add_edge_features_group_fn(), GraphTask::add_edge_features_single_fn(), Search::add_neighbor_features(), GraphTask::del_edge_features(), and Search::del_neighbor_features().
nn_output_namespace
constexpr unsigned char nn_output_namespace = 129
Definition at line 29 of file example.h.
Referenced by finish_setup(), and predict_or_learn_multi().
node_id_namespace
constexpr unsigned char node_id_namespace = 136
Definition at line 37 of file example.h.
Referenced by recall_tree_ns::add_node_id_feature(), and recall_tree_ns::remove_node_id_feature().
spelling_namespace
constexpr unsigned char spelling_namespace = 133
Definition at line 34 of file example.h.
Referenced by TC_parser< audit >::maybeFeature().
wap_ldf_namespace
constexpr unsigned char wap_ldf_namespace = 126
Definition at line 26 of file example.h.
Referenced by CSOAA::subtract_example(), CSOAA::subtract_feature(), and CSOAA::unsubtract_example().