Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/example.cc File Reference
example.cc File Reference
#include <stdint.h>
#include <algorithm>
#include "gd.h"
Classes
struct features_and_source
struct full_features_and_source
Namespaces
VW
Functions
float collision_cleanup (features &fs)
void VW::copy_example_label (example *dst, example *src, size_t, void(*copy_label)(void *, void *))
void VW::copy_example_metadata (bool, example *dst, example *src)
void VW::copy_example_data (bool audit, example *dst, example *src)
void VW::copy_example_data (bool audit, example *dst, example *src, size_t label_size, void(*copy_label)(void *, void *))
void VW::move_feature_namespace (example *dst, example *src, namespace_index c)
void vec_store (features_and_source &p, float fx, uint64_t fi)
feature * VW::get_features (vw &all, example *ec, size_t &feature_map_len)
void VW::return_features (feature *f)
void vec_ffs_store (full_features_and_source &p, float fx, uint64_t fi)
flat_example * flatten_example (vw &all, example *ec)
flat_example * flatten_sort_example (vw &all, example *ec)
void free_flatten_example (flat_example *fec)
example * VW::alloc_examples (size_t, size_t count=1)
void VW::dealloc_example (void(*delete_label)(void *), example &ec, void(*delete_prediction)(void *))
void VW::finish_example (vw &, example &)
void VW::clean_example (vw &, example &, bool rewind)
void VW::clear_seq_and_finish_examples (vw &all, multi_ex &ec_seq)
void VW::return_multiple_example (vw &all, v_array< example *> &examples)
Function Documentation
collision_cleanup()
float collision_cleanup (features & fs)
Definition at line 11 of file example.cc.
References features::begin(), f, features_value_index_iterator::index(), and features_value_iterator::value().
Referenced by flatten_sort_example().
 {
   uint64_t last_index = (uint64_t)-1;
   float sum_sq = 0.f;
   features::iterator pos = fs.begin();
   for (features::iterator& f : fs)
   {
     if (last_index == f.index())
       pos.value() += f.value();
     else
     {
       sum_sq += pos.value() * pos.value();
       ++pos;
       pos.value() = f.value();
       pos.index() = f.index();
       last_index = f.index();
     }
   }
   sum_sq += pos.value() * pos.value();
   fs.sum_feat_sq = sum_sq;
   ++pos;
   fs.truncate_to(pos);
   return sum_sq;
 }
flatten_example()
flat_example* flatten_example (vw & all, example * ec)
Definition at line 152 of file example.cc.
References v_array< T >::begin(), example::example_counter, flat_example::example_counter, flat_example::fs, full_features_and_source::fs, example_predict::ft_offset, flat_example::ft_offset, example::l, flat_example::l, full_features_and_source::mask, parameters::mask(), parameters::not_null(), example::num_features, flat_example::num_features, polylabel::simple, v_array< T >::size(), full_features_and_source::stride_shift, parameters::stride_shift(), example::tag, flat_example::tag, flat_example::tag_len, label_data::weight, example::weight, and vw::weights.
Referenced by flatten_sort_example().
 {
   flat_example& fec = calloc_or_throw<flat_example>();
   fec.l = ec->l;
   fec.l.simple.weight = ec->weight;
   fec.tag_len = ec->tag.size();
   if (fec.tag_len > 0)
   {
     fec.tag = calloc_or_throw<char>(fec.tag_len + 1);
     memcpy(fec.tag, ec->tag.begin(), fec.tag_len);
   }
   fec.example_counter = ec->example_counter;
   fec.ft_offset = ec->ft_offset;
   fec.num_features = ec->num_features;
   full_features_and_source ffs;
   ffs.stride_shift = all.weights.stride_shift();
   if (all.weights.not_null())  // TODO:temporary fix. all.weights is not initialized at this point in some cases.
     ffs.mask = (uint64_t)all.weights.mask() >> all.weights.stride_shift();
   else
     ffs.mask = (uint64_t)LONG_MAX >> all.weights.stride_shift();
   GD::foreach_feature<full_features_and_source, uint64_t, vec_ffs_store>(all, *ec, ffs);
   fec.fs = ffs.fs;
   return &fec;
 }
flatten_sort_example()
flat_example* flatten_sort_example (vw & all, example * ec)
Definition at line 182 of file example.cc.
References collision_cleanup(), flatten_example(), flat_example::fs, vw::parse_mask, features::sort(), and flat_example::total_sum_feat_sq.
Referenced by learn(), memory_tree_ns::normalized_linear_prod(), and predict().
 {
   flat_example* fec = flatten_example(all, ec);
   fec->fs.sort(all.parse_mask);
   fec->total_sum_feat_sq = collision_cleanup(fec->fs);
   return fec;
 }
free_flatten_example()
void free_flatten_example (flat_example * fec)
Definition at line 190 of file example.cc.
References features::delete_v(), flat_example::fs, flat_example::tag, and flat_example::tag_len.
Referenced by memory_tree_ns::normalized_linear_prod(), and svm_example::~svm_example().
 {
   // note: The label memory should be freed by by freeing the original example.
   if (fec)
   {
     fec->fs.delete_v();
     if (fec->tag_len > 0)
       free(fec->tag);
     free(fec);
   }
 }
vec_ffs_store()
void vec_ffs_store (full_features_and_source & p, float fx, uint64_t fi)
Definition at line 147 of file example.cc.
References full_features_and_source::fs, full_features_and_source::mask, features::push_back(), and full_features_and_source::stride_shift.
 {
   p.fs.push_back(fx, (uint64_t)(fi >> p.stride_shift) & p.mask);
 }
vec_store()
void vec_store (features_and_source & p, float fx, uint64_t fi)
Definition at line 118 of file example.cc.
References features_and_source::feature_map, features_and_source::mask, v_array< T >::push_back(), and features_and_source::stride_shift.
 {
   p.feature_map.push_back(feature(fx, (uint64_t)(fi >> p.stride_shift) & p.mask));
 }