Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/explore/hash.h File Reference
hash.h File Reference
#include <sys/types.h>
#include <stdint.h>
Namespaces
MURMUR_HASH_3
Macros
#define ROTL32(x, y) rotl32(x,y)
#define BIG_CONSTANT(x) (x##LLU)
Functions
constexpr uint32_t rotl32 (uint32_t x, int8_t r) noexcept
static uint32_t MURMUR_HASH_3::fmix (uint32_t h) noexcept
static constexpr uint32_t MURMUR_HASH_3::getblock (const uint32_t *p, int i) noexcept
uint64_t uniform_hash (const void *key, size_t len, uint64_t seed)
Macro Definition Documentation
BIG_CONSTANT
#define BIG_CONSTANT (x) (x##LLU)
Definition at line 50 of file hash.h.
ROTL32
#define ROTL32 (x, y) rotl32(x,y)
Definition at line 49 of file hash.h.
Referenced by uniform_hash().
Function Documentation
rotl32()
constexpr uint32_t rotl32 (uint32_t x, int8_t r) inline noexcept
Definition at line 45 of file hash.h.
 { return (x << r) | (x >> (32 - r));
 }
uniform_hash()
uint64_t uniform_hash (const void * key, size_t len, uint64_t seed) inline
Definition at line 82 of file hash.h.
References MURMUR_HASH_3::fmix(), MURMUR_HASH_3::getblock(), and ROTL32.
Referenced by io_buf::bin_read_fixed(), io_buf::bin_write_fixed(), Search::cached_action_store_or_find(), cbify_setup(), cbifyldf_setup(), namedlabels::get(), hashall(), hashstring(), learn_or_predict(), TC_parser< audit >::maybeFeature(), namedlabels::namedlabels(), TC_parser< audit >::nameSpace(), parse_dictionary_argument(), exploration::sample_after_normalizing(), save_load_header(), MultiState< audit >::StartArray(), and warm_cb_setup().
 {
   const uint8_t * data = (const uint8_t*)key;
   const int nblocks = (int)len / 4;
   uint32_t h1 = (uint32_t)seed;
   const uint32_t c1 = 0xcc9e2d51;
   const uint32_t c2 = 0x1b873593;
   // --- body
   const uint32_t * blocks = (const uint32_t *)(data + nblocks * 4);
   for (int i = -nblocks; i; i++)
   {
     uint32_t k1 = MURMUR_HASH_3::getblock(blocks, i);
     k1 *= c1;
     k1 = ROTL32(k1, 15);
     k1 *= c2;
     h1 ^= k1;
     h1 = ROTL32(h1, 13);
     h1 = h1 * 5 + 0xe6546b64;
   }
   // --- tail
   const uint8_t * tail = (const uint8_t*)(data + nblocks * 4);
   uint32_t k1 = 0;
   // The 'fall through' comments below silence the implicit-fallthrough warning introduced in GCC 7.
   // Once we move to C++17 these should be replaced with the [[fallthrough]] attribute.
   switch (len & 3)
   {
   case 3:
     k1 ^= tail[2] << 16;
     // fall through
   case 2:
     k1 ^= tail[1] << 8;
     // fall through
   case 1: k1 ^= tail[0];
     k1 *= c1;
     k1 = ROTL32(k1, 15);
     k1 *= c2; h1 ^= k1;
   }
   // --- finalization
   h1 ^= len;
   return MURMUR_HASH_3::fmix(h1);
 }