Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/interact.h File Reference
interact.h File Reference
Functions
LEARNER::base_learner * interact_setup (VW::config::options_i &options, vw &all)
Function Documentation
interact_setup()
LEARNER::base_learner* interact_setup (VW::config::options_i & options, vw & all)
Definition at line 155 of file interact.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), finish(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), vw::quiet, LEARNER::learner< T, E >::set_finish(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   string s;
   option_group_definition new_options("Interact via elementwise multiplication");
   new_options.add(
       make_option("interact", s).keep().help("Put weights on feature products from namespaces <n1> and <n2>"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("interact"))
     return nullptr;
   if (s.length() != 2)
   {
     cerr << "Need two namespace arguments to interact: " << s << " won't do EXITING\n";
     return nullptr;
   }
   auto data = scoped_calloc_or_throw<interact>();
   data->n1 = (unsigned char)s[0];
   data->n2 = (unsigned char)s[1];
   if (!all.quiet)
     cerr << "Interacting namespaces " << data->n1 << " and " << data->n2 << endl;
   data->all = &all;
   LEARNER::learner<interact, example>* l;
   l = &LEARNER::init_learner(
       data, as_singleline(setup_base(options, all)), predict_or_learn<true, true>, predict_or_learn<false, true>, 1);
   l->set_finish(finish);
   return make_base(*l);
 }