Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/io_buf.cc File Reference
io_buf.cc File Reference
#include "io_buf.h"
#include <stdio.h>
Functions
bool isbinary (io_buf &i)
size_t readto (io_buf &i, char *&pointer, char terminal)
Function Documentation
isbinary()
bool isbinary (io_buf & i)
Definition at line 45 of file io_buf.cc.
References io_buf::current, v_array< T >::end(), io_buf::files, io_buf::fill(), io_buf::head, and io_buf::space.
Referenced by io_buf::bin_write_fixed(), enable_sources(), and reset_source().
 {
   if (i.space.end() == i.head)
     if (i.fill(i.files[i.current]) <= 0)
       return false;
   bool ret = (*i.head == 0);
   if (ret)
     i.head++;
   return ret;
 }
readto()
size_t readto (io_buf & i, char *& pointer, char terminal)
Definition at line 58 of file io_buf.cc.
References v_array< T >::begin(), io_buf::current, v_array< T >::end(), v_array< T >::end_array, io_buf::files, io_buf::fill(), io_buf::head, readto(), v_array< T >::size(), and io_buf::space.
Referenced by io_buf::bin_write_fixed(), read_features(), and readto().
 {
   // Return a pointer to the bytes before the terminal.  Must be less than the buffer size.
   pointer = i.head;
   while (pointer < i.space.end() && *pointer != terminal) pointer++;
   if (pointer != i.space.end())
   {
     size_t n = pointer - i.head;
     i.head = pointer + 1;
     pointer -= n;
     return n + 1;
   }
   else
   {
     if (i.space.end() == i.space.end_array)
     {
       size_t left = i.space.end() - i.head;
       memmove(i.space.begin(), i.head, left);
       i.head = i.space.begin();
       i.space.end() = i.space.begin() + left;
       pointer = i.space.end();
     }
     if (i.current < i.files.size() && i.fill(i.files[i.current]) > 0)  // more bytes are read.
       return readto(i, pointer, terminal);
     else if (++i.current < i.files.size())  // no more bytes, so go to next file.
       return readto(i, pointer, terminal);
     else  // no more bytes to read, return everything we have.
     {
       size_t n = pointer - i.head;
       i.head = pointer;
       pointer -= n;
       return n;
     }
   }
 }