Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/lrq.h File Reference
lrq.h File Reference
Functions
LEARNER::base_learner * lrq_setup (VW::config::options_i &options, vw &all)
Function Documentation
lrq_setup()
LEARNER::base_learner* lrq_setup (VW::config::options_i & options, vw & all)
Definition at line 162 of file lrq.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), finish(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), max(), vw::quiet, vw::random_seed, reset_seed(), LEARNER::learner< T, E >::set_end_pass(), LEARNER::learner< T, E >::set_finish(), setup_base(), spoof_hex_encoded_namespaces(), THROW, vw::trace_message, valid_int(), VW::config::options_i::was_supplied(), and vw::wpp.
Referenced by parse_reductions().
 {
   auto lrq = scoped_calloc_or_throw<LRQstate>();
   vector<string> lrq_names;
   option_group_definition new_options("Low Rank Quadratics");
   new_options.add(make_option("lrq", lrq_names).keep().help("use low rank quadratic features"))
       .add(make_option("lrqdropout", lrq->dropout).keep().help("use dropout training for low rank quadratic features"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("lrq"))
     return nullptr;
   uint32_t maxk = 0;
   lrq->all = &all;
   for (size_t i = 0; i < lrq_names.size(); i++) lrq_names[i] = spoof_hex_encoded_namespaces(lrq_names[i]);
   new (&lrq->lrpairs) std::set<std::string>(lrq_names.begin(), lrq_names.end());
   lrq->initial_seed = lrq->seed = all.random_seed | 8675309;
   if (!all.quiet)
   {
     all.trace_message << "creating low rank quadratic features for pairs: ";
     if (lrq->dropout)
       all.trace_message << "(using dropout) ";
   }
   for (string const& i : lrq->lrpairs)
   {
     if (!all.quiet)
     {
       if ((i.length() < 3) || !valid_int(i.c_str() + 2))
         THROW("error, low-rank quadratic features must involve two sets and a rank.");
       all.trace_message << i << " ";
     }
     // TODO: colon-syntax
     unsigned int k = atoi(i.c_str() + 2);
     lrq->lrindices[(int)i[0]] = 1;
     lrq->lrindices[(int)i[1]] = 1;
     maxk = max(maxk, k);
   }
   if (!all.quiet)
     all.trace_message << endl;
   all.wpp = all.wpp * (uint64_t)(1 + maxk);
   learner<LRQstate, example>& l = init_learner(
       lrq, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>, 1 + maxk);
   l.set_end_pass(reset_seed);
   l.set_finish(finish);
   // TODO: leaks memory ?
   return make_base(l);
 }