Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/multilabel_oaa.h File Reference
multilabel_oaa.h File Reference
Functions
LEARNER::base_learner * multilabel_oaa_setup (VW::config::options_i &options, vw &all)
Function Documentation
multilabel_oaa_setup()
LEARNER::base_learner* multilabel_oaa_setup (VW::config::options_i & options, vw & all)
Definition at line 59 of file multilabel_oaa.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), label_parser::delete_label, vw::delete_prediction, finish_example(), LEARNER::init_learner(), vw::label_type, parser::lp, LEARNER::make_base(), VW::config::make_option(), label_type::multi, MULTILABEL::multilabel, prediction_type::multilabels, vw::p, LEARNER::learner< T, E >::set_finish_example(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<multi_oaa>();
   option_group_definition new_options("Multilabel One Against All");
   new_options.add(make_option("multilabel_oaa", data->k).keep().help("One-against-all multilabel with <k> labels"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("multilabel_oaa"))
     return nullptr;
   LEARNER::learner<multi_oaa, example>& l = LEARNER::init_learner(data, as_singleline(setup_base(options, all)),
       predict_or_learn<true>, predict_or_learn<false>, data->k, prediction_type::multilabels);
   l.set_finish_example(finish_example);
   all.p->lp = MULTILABEL::multilabel;
   all.label_type = label_type::multi;
   all.delete_prediction = MULTILABEL::multilabel.delete_label;
   return make_base(l);
 }