Vowpal Wabbit: LabelDict Namespace Reference
LabelDict Namespace Reference
Typedefs
typedef v_hashmap< size_t, features > label_feature_map
Functions
constexpr size_t hash_lab (size_t lab) noexcept
void del_example_namespace (example &ec, namespace_index ns, features &fs)
void add_example_namespace (example &ec, namespace_index ns, features &fs)
void add_example_namespaces_from_example (example &target, example &source)
void del_example_namespaces_from_example (example &target, example &source)
void add_example_namespace_from_memory (label_feature_map &lfm, example &ec, size_t lab)
void del_example_namespace_from_memory (label_feature_map &lfm, example &ec, size_t lab)
void set_label_features (label_feature_map &lfm, size_t lab, features &fs)
void free_label_features (label_feature_map &lfm)
bool size_t_eq (const size_t &a, const size_t &b)
Typedef Documentation
label_feature_map
typedef v_hashmap<size_t, features> LabelDict::label_feature_map
Definition at line 8 of file label_dictionary.h.
Function Documentation
add_example_namespace()
void LabelDict::add_example_namespace (example & ec, namespace_index ns, features & fs)
Definition at line 26 of file label_dictionary.cc.
References example_predict::feature_space, example_predict::indices, features::indicies, example::num_features, v_array< T >::push_back(), features::push_back(), v_array< T >::size(), features::size(), features::space_names, features::sum_feat_sq, example::total_sum_feat_sq, and features::values.
Referenced by add_example_namespace_from_memory(), add_example_namespaces_from_example(), CCB::inject_slot_features(), and size_t_eq().
 {
   bool has_ns = false;
   for (size_t i = 0; i < ec.indices.size(); i++)
     if (ec.indices[i] == (size_t)ns)
     {
       has_ns = true;
       break;
     }
   if (!has_ns)
     ec.indices.push_back((size_t)ns);
   bool audit = fs.space_names.size() > 0;
   features& add_fs = ec.feature_space[(size_t)ns];
   for (size_t i = 0; i < fs.size(); ++i)
   {
     add_fs.push_back(fs.values[i], fs.indicies[i]);
     if (audit)
       add_fs.space_names.push_back(fs.space_names[i]);
   }
   ec.total_sum_feat_sq += fs.sum_feat_sq;
   ec.num_features += fs.size();
 }
add_example_namespace_from_memory()
void LabelDict::add_example_namespace_from_memory (label_feature_map & lfm, example & ec, size_t lab)
Definition at line 76 of file label_dictionary.cc.
References add_example_namespace(), v_hashmap< K, V >::get(), hash_lab(), and features::size().
Referenced by CSOAA::do_actual_learning_oaa(), CSOAA::do_actual_learning_wap(), CSOAA::make_single_prediction(), and size_t_eq().
 {
   size_t lab_hash = hash_lab(lab);
   features& res = lfm.get(lab, lab_hash);
   if (res.size() == 0)
     return;
   add_example_namespace(ec, static_cast<unsigned char>('l'), res);
 }
add_example_namespaces_from_example()
void LabelDict::add_example_namespaces_from_example (example & target, example & source)
Definition at line 52 of file label_dictionary.cc.
References add_example_namespace(), constant_namespace, example_predict::feature_space, and example_predict::indices.
Referenced by VW::shared_feature_merger::predict_or_learn(), Search::single_prediction_LDF(), and size_t_eq().
 {
   for (namespace_index idx : source.indices)
   {
     if (idx == constant_namespace)
       continue;
     add_example_namespace(target, idx, source.feature_space[idx]);
   }
 }
del_example_namespace()
void LabelDict::del_example_namespace (example & ec, namespace_index ns, features & fs)
Definition at line 9 of file label_dictionary.cc.
References example_predict::feature_space, example_predict::indices, v_array< T >::last(), example::num_features, v_array< T >::pop(), v_array< T >::size(), features::size(), features::sum_feat_sq, example::total_sum_feat_sq, and features::truncate_to().
Referenced by del_example_namespace_from_memory(), del_example_namespaces_from_example(), CCB::remove_slot_features(), and size_t_eq().
 {
   // print_update is called after this del_example_namespace,
   // so we need to keep the ec.num_features correct,
   // so shared features are included in the reported number of "current features"
   // ec.num_features -= numf;
   features& del_target = ec.feature_space[(size_t)ns];
   assert(del_target.size() >= fs.size());
   assert(ec.indices.size() > 0);
   if (ec.indices.last() == ns && ec.feature_space[(size_t)ns].size() == fs.size())
     ec.indices.pop();
   ec.total_sum_feat_sq -= fs.sum_feat_sq;
   ec.num_features -= fs.size();
   del_target.truncate_to(del_target.size() - fs.size());
   del_target.sum_feat_sq -= fs.sum_feat_sq;
 }
del_example_namespace_from_memory()
void LabelDict::del_example_namespace_from_memory (label_feature_map & lfm, example & ec, size_t lab)
Definition at line 85 of file label_dictionary.cc.
References del_example_namespace(), v_hashmap< K, V >::get(), hash_lab(), and features::size().
Referenced by CSOAA::do_actual_learning_oaa(), CSOAA::do_actual_learning_wap(), CSOAA::make_single_prediction(), and size_t_eq().
 {
   size_t lab_hash = hash_lab(lab);
   features& res = lfm.get(lab, lab_hash);
   if (res.size() == 0)
     return;
   del_example_namespace(ec, static_cast<unsigned char>('l'), res);
 }
del_example_namespaces_from_example()
void LabelDict::del_example_namespaces_from_example (example & target, example & source)
Definition at line 62 of file label_dictionary.cc.
References v_array< T >::begin(), constant_namespace, del_example_namespace(), v_array< T >::end(), example_predict::feature_space, example_predict::indices, and v_array< T >::size().
Referenced by VW::shared_feature_merger::predict_or_learn(), Search::single_prediction_LDF(), and size_t_eq().
 {
   if (source.indices.size() == 0)  // making sure we can deal with empty shared example
     return;
   namespace_index* idx = source.indices.end();
   idx--;
   for (; idx >= source.indices.begin(); idx--)
   {
     if (*idx == constant_namespace)
       continue;
     del_example_namespace(target, *idx, source.feature_space[*idx]);
   }
 }
free_label_features()
void LabelDict::free_label_features (label_feature_map & lfm)
Definition at line 102 of file label_dictionary.cc.
References v_hashmap< K, V >::clear(), v_array< T >::delete_v(), v_hashmap< K, V >::delete_v(), features::indicies, v_hashmap< K, V >::iterator(), v_hashmap< K, V >::iterator_get_value(), v_hashmap< K, V >::iterator_next(), features::space_names, and features::values.
Referenced by CSOAA::finish(), and size_t_eq().
 {
   void* label_iter = lfm.iterator();
   while (label_iter != nullptr)
   {
     features* res = lfm.iterator_get_value(label_iter);
     res->values.delete_v();
     res->indicies.delete_v();
     res->space_names.delete_v();
     label_iter = lfm.iterator_next(label_iter);
   }
   lfm.clear();
   lfm.delete_v();
 }
hash_lab()
constexpr size_t LabelDict::hash_lab (size_t lab) noexcept
Definition at line 7 of file label_dictionary.cc.
Referenced by add_example_namespace_from_memory(), del_example_namespace_from_memory(), and set_label_features().
 { return 328051 + 94389193 * lab; }
set_label_features()
void LabelDict::set_label_features (label_feature_map & lfm, size_t lab, features & fs)
Definition at line 94 of file label_dictionary.cc.
References v_hashmap< K, V >::contains(), hash_lab(), and v_hashmap< K, V >::put_after_get().
Referenced by CSOAA::process_label(), and size_t_eq().
 {
   size_t lab_hash = hash_lab(lab);
   if (lfm.contains(lab, lab_hash))
     return;
   lfm.put_after_get(lab, lab_hash, fs);
 }
size_t_eq()
bool LabelDict::size_t_eq (const size_t & a, const size_t & b) inline
Definition at line 9 of file label_dictionary.h.
References add_example_namespace(), add_example_namespace_from_memory(), add_example_namespaces_from_example(), del_example_namespace(), del_example_namespace_from_memory(), del_example_namespaces_from_example(), free_label_features(), and set_label_features().
Referenced by CSOAA::csldf_setup().
 { return (a == b); }