Vowpal Wabbit: SequenceTaskCostToGo Namespace Reference
SequenceTaskCostToGo Namespace Reference
Functions
void initialize (Search::search &sch, size_t &num_actions, options_i &)
void run (Search::search &sch, multi_ex &ec)
Variables
Search::search_task task = {"sequence_ctg", run, initialize, nullptr, nullptr, nullptr}
Function Documentation
initialize()
void SequenceTaskCostToGo::initialize (Search::search & sch, size_t & num_actions, options_i &)
Definition at line 275 of file search_sequencetask.cc.
References Search::ACTION_COSTS, Search::AUTO_CONDITION_FEATURES, Search::AUTO_HAMMING_LOSS, Search::EXAMPLES_DONT_CHANGE, Search::search::set_options(), and Search::search::set_task_data().
 {
   sch.set_options(Search::AUTO_CONDITION_FEATURES |  // automatically add history features to our examples, please
       Search::AUTO_HAMMING_LOSS |     // please just use hamming loss on individual predictions -- we won't declare loss
       Search::EXAMPLES_DONT_CHANGE |  // we don't do any internal example munging
       Search::ACTION_COSTS |          // we'll provide cost-per-action (rather than oracle)
       0);
   sch.set_task_data<size_t>(&num_actions);
 }
run()
void SequenceTaskCostToGo::run (Search::search & sch, multi_ex & ec)
Definition at line 285 of file search_sequencetask.cc.
References Search::search::get_history_length(), Search::search::get_task_data(), Search::search::output(), predict(), and Search::search::pretty_label().
 {
   size_t K = *sch.get_task_data<size_t>();
   float* costs = calloc_or_throw<float>(K);
   Search::predictor P(sch, (ptag)0);
   for (size_t i = 0; i < ec.size(); i++)
   {
     action oracle = ec[i]->l.multi.label;
     for (size_t k = 0; k < K; k++) costs[k] = 1.;
     costs[oracle - 1] = 0.;
     size_t prediction = P.set_tag((ptag)i + 1)
                             .set_input(*ec[i])
                             .set_allowed(nullptr, costs, K)
                             .set_condition_range((ptag)i, sch.get_history_length(), 'p')
                             .predict();
     if (sch.output().good())
       sch.output() << sch.pretty_label((uint32_t)prediction) << ' ';
   }
   free(costs);
 }
Variable Documentation
task
Search::search_task SequenceTaskCostToGo::task = {"sequence_ctg", run, initialize, nullptr, nullptr, nullptr}
Definition at line 22 of file search_sequencetask.cc.