Vowpal Wabbit: CB_ADF Namespace Reference
CB_ADF Namespace Reference
Classes
struct cb_adf
Functions
CB::cb_class get_observed_cost (multi_ex &examples)
void learn_IPS (cb_adf &mydata, multi_learner &base, multi_ex &examples)
void learn_SM (cb_adf &mydata, multi_learner &base, multi_ex &examples)
void learn_DR (cb_adf &mydata, multi_learner &base, multi_ex &examples)
void learn_DM (cb_adf &mydata, multi_learner &base, multi_ex &examples)
template<bool predict>
void learn_MTR (cb_adf &mydata, multi_learner &base, multi_ex &examples)
example * test_adf_sequence (multi_ex &ec_seq)
template<bool is_learn>
void do_actual_learning (cb_adf &data, multi_learner &base, multi_ex &ec_seq)
void global_print_newline (vw &all)
bool update_statistics (vw &all, cb_adf &c, example &ec, multi_ex *ec_seq)
void output_example (vw &all, cb_adf &c, example &ec, multi_ex *ec_seq)
void output_rank_example (vw &all, cb_adf &c, example &ec, multi_ex *ec_seq)
void output_example_seq (vw &all, cb_adf &data, multi_ex &ec_seq)
void finish_multiline_example (vw &all, cb_adf &data, multi_ex &ec_seq)
void finish (cb_adf &data)
void save_load (cb_adf &c, io_buf &model_file, bool read, bool text)
Function Documentation
do_actual_learning()
template<bool is_learn> void CB_ADF::do_actual_learning (cb_adf & data, multi_learner & base, multi_ex & ec_seq)
Definition at line 250 of file cb_adf.cc.
References CB_ADF::cb_adf::cb_labels, GEN_CS::cb_to_cs_adf::cb_type, CB_TYPE_DM, CB_TYPE_DR, CB_TYPE_IPS, CB_TYPE_MTR, CB_TYPE_SM, CB_ADF::cb_adf::cs_labels, CB_ADF::cb_adf::gen_cs, GEN_CS::gen_cs_test_example(), get_observed_cost(), GEN_CS::cb_to_cs_adf::known_cost, learn_DM(), learn_DR(), learn_IPS(), learn_SM(), CB_ADF::cb_adf::no_predict, CB_ADF::cb_adf::offset, CB_ADF::cb_adf::prepped_cs_labels, test_adf_sequence(), and THROW.
 {
   data.offset = ec_seq[0]->ft_offset;
   data.gen_cs.known_cost = get_observed_cost(ec_seq);  // need to set for test case
   if (is_learn && test_adf_sequence(ec_seq) != nullptr)
   {
     /*  v_array<float> temp_scores;
     temp_scores = v_init<float>();
     do_actual_learning<false>(data,base);
     for (size_t i = 0; i < data.ec_seq[0]->pred.a_s.size(); i++)
     temp_scores.push_back(data.ec_seq[0]->pred.a_s[i].score);*/
     switch (data.gen_cs.cb_type)
     {
       case CB_TYPE_IPS:
         learn_IPS(data, base, ec_seq);
         break;
       case CB_TYPE_DR:
         learn_DR(data, base, ec_seq);
         break;
       case CB_TYPE_DM:
         learn_DM(data, base, ec_seq);
         break;
       case CB_TYPE_MTR:
         if (data.no_predict)
           learn_MTR<false>(data, base, ec_seq);
         else
           learn_MTR<true>(data, base, ec_seq);
         break;
       case CB_TYPE_SM:
         learn_SM(data, base, ec_seq);
         break;
       default:
         THROW("Unknown cb_type specified for contextual bandit learning: " << data.gen_cs.cb_type);
     }
     /*      for (size_t i = 0; i < temp_scores.size(); i++)
     if (temp_scores[i] != data.ec_seq[0]->pred.a_s[i].score)
       cout << "problem! " << temp_scores[i] << " != " << data.ec_seq[0]->pred.a_s[i].score << " for " <<
     data.ec_seq[0]->pred.a_s[i].action << endl; temp_scores.delete_v();*/
   }
   else
   {
     gen_cs_test_example(ec_seq, data.cs_labels);  // create test labels.
     call_cs_ldf<false>(base, ec_seq, data.cb_labels, data.cs_labels, data.prepped_cs_labels, data.offset);
   }
 }
finish()
void CB_ADF::finish (cb_adf & data)
Definition at line 417 of file cb_adf.cc.
References CB_ADF::cb_adf::a_s, CB_ADF::cb_adf::backup_nf, CB_ADF::cb_adf::backup_weights, CB_ADF::cb_adf::cb_labels, COST_SENSITIVE::label::costs, CB_ADF::cb_adf::cs_labels, v_array< T >::delete_v(), CB_ADF::cb_adf::gen_cs, GEN_CS::cb_to_cs_adf::mtr_ec_seq, GEN_CS::cb_to_cs_adf::pred_scores, CB_ADF::cb_adf::prepped_cs_labels, CB_ADF::cb_adf::prob_s, and v_array< T >::size().
Referenced by cb_adf_setup().
 {
   data.gen_cs.mtr_ec_seq.~multi_ex();
   data.cb_labels.delete_v();
   for (size_t i = 0; i < data.prepped_cs_labels.size(); i++) data.prepped_cs_labels[i].costs.delete_v();
   data.prepped_cs_labels.delete_v();
   data.cs_labels.costs.delete_v();
   data.backup_weights.delete_v();
   data.backup_nf.delete_v();
   data.prob_s.delete_v();
   data.a_s.delete_v();
   data.gen_cs.pred_scores.costs.delete_v();
 }
finish_multiline_example()
void CB_ADF::finish_multiline_example (vw & all, cb_adf & data, multi_ex & ec_seq)
Definition at line 407 of file cb_adf.cc.
References VW::clear_seq_and_finish_examples(), global_print_newline(), and output_example_seq().
Referenced by cb_adf_setup().
 {
   if (ec_seq.size() > 0)
   {
     output_example_seq(all, data, ec_seq);
     global_print_newline(all);
   }
   VW::clear_seq_and_finish_examples(all, ec_seq);
 }
get_observed_cost()
CB::cb_class CB_ADF::get_observed_cost (multi_ex & examples)
Definition at line 51 of file cb_adf.cc.
References CB::cb_class::action, CB::label::costs, and CB::cb_class::probability.
Referenced by EXPLORE_EVAL::do_actual_learning(), do_actual_learning(), CB_EXPLORE_ADF::do_actual_learning(), CB_ALGS::learn_eval(), CB_EXPLORE::output_example(), CB_ALGS::predict_or_learn(), and CB_EXPLORE::predict_or_learn_cover().
 {
   CB::label ld;
   ld.costs = v_init<cb_class>();
   int index = -1;
   CB::cb_class known_cost;
   size_t i = 0;
   for (example*& ec : examples)
   {
     if (ec->l.cb.costs.size() == 1 && ec->l.cb.costs[0].cost != FLT_MAX && ec->l.cb.costs[0].probability > 0)
     {
       ld = ec->l.cb;
       index = (int)i;
     }
     ++i;
   }
   // handle -1 case.
   if (index == -1)
   {
     known_cost.probability = -1;
     return known_cost;
     // std::cerr << "None of the examples has known cost. Exiting." << endl;
     // throw exception();
   }
   known_cost = ld.costs[0];
   known_cost.action = index;
   return known_cost;
 }
global_print_newline()
void CB_ADF::global_print_newline (vw & all)
Definition at line 297 of file cb_adf.cc.
References f, vw::final_prediction_sink, v_array< T >::size(), and io_buf::write_file_or_socket().
Referenced by EXPLORE_EVAL::finish_multiline_example(), finish_multiline_example(), CB_EXPLORE_ADF::finish_multiline_example(), and CCB::finish_multiline_example().
 {
   char temp[1];
   temp[0] = '\n';
   for (size_t i = 0; i < all.final_prediction_sink.size(); i++)
   {
     int f = all.final_prediction_sink[i];
     ssize_t t;
     t = io_buf::write_file_or_socket(f, temp, 1);
     if (t != 1)
       cerr << "write error: " << strerror(errno) << endl;
   }
 }
learn_DM()
void CB_ADF::learn_DM (cb_adf & mydata, multi_learner & base, multi_ex & examples)
Definition at line 186 of file cb_adf.cc.
References CB_ADF::cb_adf::cb_labels, CB_ADF::cb_adf::cs_labels, GEN_CS::gen_cs_example_dm(), CB_ADF::cb_adf::offset, and CB_ADF::cb_adf::prepped_cs_labels.
Referenced by do_actual_learning().
 {
   gen_cs_example_dm(examples, mydata.cs_labels);
   call_cs_ldf<true>(base, examples, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
 }
learn_DR()
void CB_ADF::learn_DR (cb_adf & mydata, multi_learner & base, multi_ex & examples)
Definition at line 180 of file cb_adf.cc.
References CB_ADF::cb_adf::cb_labels, CB_ADF::cb_adf::clip_p, CB_ADF::cb_adf::cs_labels, CB_ADF::cb_adf::gen_cs, CB_ADF::cb_adf::offset, and CB_ADF::cb_adf::prepped_cs_labels.
Referenced by do_actual_learning().
 {
   gen_cs_example_dr<true>(mydata.gen_cs, examples, mydata.cs_labels, mydata.clip_p);
   call_cs_ldf<true>(base, examples, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
 }
learn_IPS()
void CB_ADF::learn_IPS (cb_adf & mydata, multi_learner & base, multi_ex & examples)
Definition at line 83 of file cb_adf.cc.
References CB_ADF::cb_adf::cb_labels, CB_ADF::cb_adf::clip_p, CB_ADF::cb_adf::cs_labels, GEN_CS::gen_cs_example_ips(), CB_ADF::cb_adf::offset, and CB_ADF::cb_adf::prepped_cs_labels.
Referenced by do_actual_learning().
 {
   gen_cs_example_ips(examples, mydata.cs_labels, mydata.clip_p);
   call_cs_ldf<true>(base, examples, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
 }
learn_MTR()
template<bool predict> void CB_ADF::learn_MTR (cb_adf & mydata, multi_learner & base, multi_ex & examples)
Definition at line 193 of file cb_adf.cc.
References CB_ADF::cb_adf::a_s, GEN_CS::cb_to_cs_adf::action_sum, CB_ADF::cb_adf::cb_labels, CB_ADF::cb_adf::clip_p, CB_ADF::cb_adf::cs_labels, GEN_CS::cb_to_cs_adf::event_sum, CB_ADF::cb_adf::gen_cs, GEN_CS::gen_cs_example_ips(), GEN_CS::gen_cs_example_mtr(), max(), GEN_CS::cb_to_cs_adf::mtr_ec_seq, GEN_CS::cb_to_cs_adf::mtr_example, CB_ADF::cb_adf::offset, predict(), and CB_ADF::cb_adf::prepped_cs_labels.
 {
   // uint32_t action = 0;
   if (predict)  // first get the prediction to return
   {
     gen_cs_example_ips(examples, mydata.cs_labels);
     call_cs_ldf<false>(base, examples, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
     swap(examples[0]->pred.a_s, mydata.a_s);
   }
   // second train on _one_ action (which requires up to 3 examples).
   // We must go through the cost sensitive classifier layer to get
   // proper feature handling.
   gen_cs_example_mtr(mydata.gen_cs, examples, mydata.cs_labels);
   uint32_t nf = (uint32_t)examples[mydata.gen_cs.mtr_example]->num_features;
   float old_weight = examples[mydata.gen_cs.mtr_example]->weight;
   const float clipped_p = (std::max)(examples[mydata.gen_cs.mtr_example]->l.cb.costs[0].probability, mydata.clip_p);
   examples[mydata.gen_cs.mtr_example]->weight *= 1.f / clipped_p *
       ((float)mydata.gen_cs.event_sum / (float)mydata.gen_cs.action_sum);
   // TODO!!! mydata.cb_labels are not getting properly restored (empty costs are dropped)
   GEN_CS::call_cs_ldf<true>(
       base, mydata.gen_cs.mtr_ec_seq, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
   examples[mydata.gen_cs.mtr_example]->num_features = nf;
   examples[mydata.gen_cs.mtr_example]->weight = old_weight;
   swap(examples[0]->pred.a_s, mydata.a_s);
 }
learn_SM()
void CB_ADF::learn_SM (cb_adf & mydata, multi_learner & base, multi_ex & examples)
Definition at line 89 of file cb_adf.cc.
References CB_ADF::cb_adf::a_s, CB_ADF::cb_adf::backup_nf, CB_ADF::cb_adf::backup_weights, ACTION_SCORE::begin_scores(), CB_ADF::cb_adf::cb_labels, v_array< T >::clear(), CB::label::costs, CB_ADF::cb_adf::cs_labels, ACTION_SCORE::end_scores(), GEN_CS::gen_cs_example_sm(), GEN_CS::gen_cs_test_example(), exploration::generate_softmax(), CB_ADF::cb_adf::offset, CB_ADF::cb_adf::prepped_cs_labels, CB_ADF::cb_adf::prob_s, v_array< T >::push_back(), GEN_CS::safe_probability(), and v_array< T >::size().
Referenced by do_actual_learning().
 {
   gen_cs_test_example(examples, mydata.cs_labels);  // create test labels.
   call_cs_ldf<false>(base, examples, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
   // Can probably do this more efficiently than 6 loops over the examples...
   //[1: initialize temporary storage;
   // 2: find chosen action;
   // 3: create cs_labels (gen_cs_example_sm);
   // 4: get probability of chosen action;
   // 5: backup example wts;
   // 6: restore example wts]
   mydata.a_s.clear();
   mydata.prob_s.clear();
   // TODO: Check that predicted scores are always stored with the first example
   for (uint32_t i = 0; i < examples[0]->pred.a_s.size(); i++)
   {
     mydata.a_s.push_back({examples[0]->pred.a_s[i].action, examples[0]->pred.a_s[i].score});
     mydata.prob_s.push_back({examples[0]->pred.a_s[i].action, 0.0});
   }
   float sign_offset = 1.0;  // To account for negative rewards/costs
   uint32_t chosen_action = 0;
   float example_weight = 1.0;
   for (uint32_t i = 0; i < examples.size(); i++)
   {
     CB::label ld = examples[i]->l.cb;
     if (ld.costs.size() == 1 && ld.costs[0].cost != FLT_MAX)
     {
       chosen_action = i;
       example_weight = ld.costs[0].cost / safe_probability(ld.costs[0].probability);
       // Importance weights of examples cannot be negative.
       // So we use a trick: set |w| as weight, and use sign(w) as an offset in the regression target.
       if (ld.costs[0].cost < 0.0)
       {
         sign_offset = -1.0;
         example_weight = -example_weight;
       }
       break;
     }
   }
   gen_cs_example_sm(examples, chosen_action, sign_offset, mydata.a_s, mydata.cs_labels);
   // Lambda is -1 in the call to generate_softmax because in vw, lower score is better; for softmax higher score is
   // better.
   generate_softmax(
       -1.0, begin_scores(mydata.a_s), end_scores(mydata.a_s), begin_scores(mydata.prob_s), end_scores(mydata.prob_s));
   // TODO: Check Marco's example that causes VW to report prob > 1.
   for (uint32_t i = 0; i < mydata.prob_s.size(); i++)  // Scale example_wt by prob of chosen action
   {
     if (mydata.prob_s[i].action == chosen_action)
     {
       example_weight *= mydata.prob_s[i].score;
       break;
     }
   }
   mydata.backup_weights.clear();
   mydata.backup_nf.clear();
   for (uint32_t i = 0; i < mydata.prob_s.size(); i++)
   {
     uint32_t current_action = mydata.prob_s[i].action;
     mydata.backup_weights.push_back(examples[current_action]->weight);
     mydata.backup_nf.push_back((uint32_t)examples[current_action]->num_features);
     if (current_action == chosen_action)
       examples[current_action]->weight = example_weight * (1.0f - mydata.prob_s[i].score);
     else
       examples[current_action]->weight = example_weight * mydata.prob_s[i].score;
     if (examples[current_action]->weight <= 1e-15)
       examples[current_action]->weight = 0;
   }
   // Do actual training
   call_cs_ldf<true>(base, examples, mydata.cb_labels, mydata.cs_labels, mydata.prepped_cs_labels, mydata.offset);
   // Restore example weights and numFeatures
   for (uint32_t i = 0; i < mydata.prob_s.size(); i++)
   {
     uint32_t current_action = mydata.prob_s[i].action;
     examples[current_action]->weight = mydata.backup_weights[i];
     examples[current_action]->num_features = mydata.backup_nf[i];
   }
 }
output_example()
void CB_ADF::output_example (vw & all, cb_adf & c, example & ec, multi_ex * ec_seq)
Definition at line 335 of file cb_adf.cc.
References polyprediction::a_s, polylabel::cb, CB::label::costs, CB_ALGS::example_is_newline_not_header(), vw::final_prediction_sink, example::l, example::pred, vw::print, vw::print_text, CB::print_update(), vw::raw_prediction, v_array< T >::size(), example::tag, and update_statistics().
Referenced by output_example_seq().
 {
   if (example_is_newline_not_header(ec))
     return;
   bool labeled_example = update_statistics(all, c, ec, ec_seq);
   uint32_t action = ec.pred.a_s[0].action;
   for (int sink : all.final_prediction_sink) all.print(sink, (float)action, 0, ec.tag);
   if (all.raw_prediction > 0)
   {
     string outputString;
     stringstream outputStringStream(outputString);
     v_array<CB::cb_class> costs = ec.l.cb.costs;
     for (size_t i = 0; i < costs.size(); i++)
     {
       if (i > 0)
         outputStringStream << ' ';
       outputStringStream << costs[i].action << ':' << costs[i].partial_prediction;
     }
     all.print_text(all.raw_prediction, outputStringStream.str(), ec.tag);
   }
   CB::print_update(all, !labeled_example, ec, ec_seq, true);
 }
output_example_seq()
void CB_ADF::output_example_seq (vw & all, cb_adf & data, multi_ex & ec_seq)
Definition at line 391 of file cb_adf.cc.
References output_example(), output_rank_example(), vw::print_text, CB_ADF::cb_adf::rank_all, and vw::raw_prediction.
 {
   if (ec_seq.size() > 0)
   {
     if (data.rank_all)
       output_rank_example(all, data, **(ec_seq.begin()), &(ec_seq));
     else
     {
       output_example(all, data, **(ec_seq.begin()), &(ec_seq));
       if (all.raw_prediction > 0)
         all.print_text(all.raw_prediction, "", ec_seq[0]->tag);
     }
   }
 }
output_rank_example()
void CB_ADF::output_rank_example (vw & all, cb_adf & c, example & ec, multi_ex * ec_seq)
Definition at line 363 of file cb_adf.cc.
References polyprediction::a_s, polylabel::cb, CB::label::costs, CB_ALGS::example_is_newline_not_header(), vw::final_prediction_sink, example::l, example::pred, ACTION_SCORE::print_action_score(), vw::print_text, CB::print_update(), vw::raw_prediction, v_array< T >::size(), example::tag, and update_statistics().
Referenced by output_example_seq().
 {
   label& ld = ec.l.cb;
   v_array<CB::cb_class> costs = ld.costs;
   if (example_is_newline_not_header(ec))
     return;
   bool labeled_example = update_statistics(all, c, ec, ec_seq);
   for (int sink : all.final_prediction_sink) print_action_score(sink, ec.pred.a_s, ec.tag);
   if (all.raw_prediction > 0)
   {
     string outputString;
     stringstream outputStringStream(outputString);
     for (size_t i = 0; i < costs.size(); i++)
     {
       if (i > 0)
         outputStringStream << ' ';
       outputStringStream << costs[i].action << ':' << costs[i].partial_prediction;
     }
     all.print_text(all.raw_prediction, outputStringStream.str(), ec.tag);
   }
   CB::print_update(all, !labeled_example, ec, ec_seq, true);
 }
save_load()
void CB_ADF::save_load (cb_adf & c, io_buf & model_file, bool read, bool text)
Definition at line 432 of file cb_adf.cc.
References GEN_CS::cb_to_cs_adf::action_sum, CB_ADF::cb_adf::all, bin_text_read_write_fixed(), GEN_CS::cb_to_cs_adf::event_sum, CB_ADF::cb_adf::gen_cs, vw::model_file_ver, and VERSION_FILE_WITH_CB_ADF_SAVE.
Referenced by cb_adf_setup().
 {
   if (c.all->model_file_ver < VERSION_FILE_WITH_CB_ADF_SAVE)
     return;
   stringstream msg;
   msg << "event_sum " << c.gen_cs.event_sum << "\n";
   bin_text_read_write_fixed(model_file, (char*)&c.gen_cs.event_sum, sizeof(c.gen_cs.event_sum), "", read, msg, text);
   msg << "action_sum " << c.gen_cs.action_sum << "\n";
   bin_text_read_write_fixed(model_file, (char*)&c.gen_cs.action_sum, sizeof(c.gen_cs.action_sum), "", read, msg, text);
 }
test_adf_sequence()
example * CB_ADF::test_adf_sequence (multi_ex & ec_seq)
Definition at line 221 of file cb_adf.cc.
References polylabel::cb, CB::label::costs, example::l, and THROW.
Referenced by EXPLORE_EVAL::do_actual_learning(), do_actual_learning(), CB_EXPLORE_ADF::do_actual_learning(), CB_EXPLORE_ADF::predict_or_learn_bag(), CB_EXPLORE_ADF::predict_or_learn_first(), CB_EXPLORE_ADF::predict_or_learn_greedy(), CB_EXPLORE_ADF::predict_or_learn_regcb(), and CB_EXPLORE_ADF::predict_or_learn_softmax().
 {
   if (ec_seq.size() == 0)
     THROW("cb_adf: At least one action must be provided for an example to be valid.");
   uint32_t count = 0;
   example* ret = nullptr;
   for (size_t k = 0; k < ec_seq.size(); k++)
   {
     example* ec = ec_seq[k];
     // Check if there is more than one cost for this example.
     if (ec->l.cb.costs.size() > 1)
       THROW("cb_adf: badly formatted example, only one cost can be known.");
     // Check whether the cost was initialized to a value.
     if (ec->l.cb.costs.size() == 1 && ec->l.cb.costs[0].cost != FLT_MAX)
     {
       ret = ec;
       count += 1;
       if (count > 1)
         THROW("cb_adf: badly formatted example, only one line can have a cost");
     }
   }
   return ret;
 }
update_statistics()
bool CB_ADF::update_statistics (vw & all, cb_adf & c, example & ec, multi_ex * ec_seq)
Definition at line 313 of file cb_adf.cc.
References polyprediction::a_s, CB_ADF::cb_adf::gen_cs, CB_ALGS::get_cost_estimate(), GEN_CS::cb_to_cs_adf::known_cost, loss(), example::num_features, example::pred, GEN_CS::cb_to_cs_adf::pred_scores, CB::cb_class::probability, vw::sd, shared_data::update(), and example::weight.
Referenced by output_example(), and output_rank_example().
 {
   size_t num_features = 0;
   uint32_t action = ec.pred.a_s[0].action;
   for (const auto& example : *ec_seq) num_features += example->num_features;
   float loss = 0.;
   bool labeled_example = true;
   if (c.gen_cs.known_cost.probability > 0)
     loss = get_cost_estimate(&(c.gen_cs.known_cost), c.gen_cs.pred_scores, action);
   else
     labeled_example = false;
   bool holdout_example = labeled_example;
   for (size_t i = 0; i < ec_seq->size(); i++) holdout_example &= (*ec_seq)[i]->test_only;
   all.sd->update(holdout_example, labeled_example, loss, ec.weight, num_features);
   return labeled_example;
 }