Vowpal Wabbit: ArgmaxTask Namespace Reference
ArgmaxTask Namespace Reference
Classes
struct task_data
Functions
void initialize (Search::search &sch, size_t &, options_i &options)
void finish (Search::search &sch)
void run (Search::search &sch, multi_ex &ec)
Variables
Search::search_task task = {"argmax", run, initialize, finish, nullptr, nullptr}
Function Documentation
finish()
void ArgmaxTask::finish (Search::search & sch)
Definition at line 337 of file search_sequencetask.cc.
References Search::search::get_task_data().
 {
   task_data* D = sch.get_task_data<task_data>();
   delete D;
 }
initialize()
void ArgmaxTask::initialize (Search::search & sch, size_t & , options_i & options)
Definition at line 316 of file search_sequencetask.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), Search::AUTO_CONDITION_FEATURES, Search::EXAMPLES_DONT_CHANGE, f, ArgmaxTask::task_data::false_negative_cost, VW::config::make_option(), ArgmaxTask::task_data::negative_weight, ArgmaxTask::task_data::predict_max, Search::search::set_options(), and Search::search::set_task_data().
 {
   task_data* D = new task_data();
   option_group_definition new_options("argmax options");
   new_options.add(make_option("cost", D->false_negative_cost).default_value(10.0f).help("False Negative Cost"))
       .add(make_option("negative_weight", D->negative_weight)
                .default_value(1.f)
                .help("Relative weight of negative examples"))
       .add(make_option("max", D->predict_max).help("Disable structure: just predict the max"));
   options.add_and_parse(new_options);
   sch.set_task_data(D);
   if (D->predict_max)
     sch.set_options(Search::EXAMPLES_DONT_CHANGE);  // we don't do any internal example munging
   else
     sch.set_options(Search::AUTO_CONDITION_FEATURES |  // automatically add history features to our examples, please
         Search::EXAMPLES_DONT_CHANGE);                 // we don't do any internal example munging
 }
run()
void ArgmaxTask::run (Search::search & sch, multi_ex & ec)
Definition at line 343 of file search_sequencetask.cc.
References ArgmaxTask::task_data::false_negative_cost, Search::search::get_task_data(), loss(), Search::search::loss(), max(), ArgmaxTask::task_data::negative_weight, Search::search::output(), Search::search::predict(), and ArgmaxTask::task_data::predict_max.
 {
   task_data& D = *sch.get_task_data<task_data>();
   uint32_t max_prediction = 1;
   uint32_t max_label = 1;
   for (size_t i = 0; i < ec.size(); i++) max_label = max(ec[i]->l.multi.label, max_label);
   for (ptag i = 0; i < ec.size(); i++)
   {
     // labels should be 1 or 2, and our output is MAX of all predicted values
     uint32_t oracle = D.predict_max ? max_label : ec[i]->l.multi.label;
     uint32_t prediction = sch.predict(*ec[i], i + 1, &oracle, 1, &i, "p");
     max_prediction = max(prediction, max_prediction);
   }
   float loss = 0.;
   if (max_label > max_prediction)
     loss = D.false_negative_cost / D.negative_weight;
   else if (max_prediction > max_label)
     loss = 1.;
   sch.loss(loss);
   if (sch.output().good())
     sch.output() << max_prediction;
 }
Variable Documentation
task
Search::search_task ArgmaxTask::task = {"argmax", run, initialize, finish, nullptr, nullptr}
Definition at line 26 of file search_sequencetask.cc.