Vowpal Wabbit: LEARNER Namespace Reference
LEARNER Namespace Reference
Classes
struct finish_example_data
struct func_data
struct learn_data
struct learner
struct save_load_data
struct sensitivity_data
Typedefs
using base_learner = learner< char, char >
using single_learner = learner< char, example >
using multi_learner = learner< char, multi_ex >
Functions
void dispatch_end_pass (vw &all, example &ec)
void save (vw &all, example *ec)
bool is_save_cmd (example *ec)
void process_example (vw &all, example *ec)
void process_multi_ex (vw &all, multi_ex &ec_seq)
bool example_is_newline_not_header (example &ec, vw &all)
bool complete_multi_ex (example *ec, multi_ex &ec_seq, vw &all)
template<void(*)(vw &, multi_ex &) f>
void dispatch_multi_ex (vw &all, multi_ex &ec_seq)
template<void(*)(vw &, multi_ex &) f>
void dispatch_multi_ex (vw &all, example *ec, multi_ex &ec_seq)
template<void(*)(vw &, multi_ex &) f>
void on_new_partial_ex (example *ec, multi_ex &ec_seq, vw &all)
template<void(*)(vw &, multi_ex &) f>
void multi_ex_generic_driver (vw &all)
template<class T , void(*)(T, example *) f>
void generic_driver (vw &all, T context)
void process_multiple (vector< vw *> alls, example *ec)
void generic_driver (vector< vw *> alls)
void generic_driver (vw &all)
void dispatch (vw &all, v_array< example *> examples)
void generic_driver_onethread (vw &all)
float recur_sensitivity (void *, base_learner &base, example &ec)
func_data tuple_dbf (void *data, base_learner *base, void(*func)(void *))
void generic_driver (std::vector< vw *> alls)
void noop_sl (void *, io_buf &, bool, bool)
void noop (void *)
float noop_sensitivity (void *, base_learner &, example &)
void increment_offset (example &ex, const size_t increment, const size_t i)
void increment_offset (multi_ex &ec_seq, const size_t increment, const size_t i)
void decrement_offset (example &ex, const size_t increment, const size_t i)
void decrement_offset (multi_ex &ec_seq, const size_t increment, const size_t i)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws, prediction_type::prediction_type_t pred_type)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t params_per_weight)
template<class T , class E , class L >
learner< T, E > & init_learner (void(*predict)(T &, L &, E &), size_t params_per_weight)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t params_per_weight, prediction_type::prediction_type_t pred_type)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws)
template<class T , class E , class L >
learner< T, E > & init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &))
template<class T , class E , class L >
learner< T, E > & init_learner (L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &))
template<class T , class E , class L >
learner< T, E > & init_multiclass_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), parser *p, size_t ws, prediction_type::prediction_type_t pred_type=prediction_type::multiclass)
template<class T , class E , class L >
learner< T, E > & init_cost_sensitive_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), parser *p, size_t ws, prediction_type::prediction_type_t pred_type=prediction_type::multiclass)
template<class T , class E >
base_learner * make_base (learner< T, E > &base)
template<class T , class E >
multi_learner * as_multiline (learner< T, E > *l)
template<class T , class E >
single_learner * as_singleline (learner< T, E > *l)
template<bool is_learn>
void multiline_learn_or_predict (multi_learner &base, multi_ex &examples, const uint64_t offset, const uint32_t id=0)
Typedef Documentation
base_learner
typedef learner< char, char > LEARNER::base_learner
Definition at line 14 of file conditional_contextual_bandit.h.
multi_learner
using LEARNER::multi_learner = typedef learner<char, multi_ex>
Definition at line 39 of file learner.h.
single_learner
using LEARNER::single_learner = typedef learner<char, example>
Definition at line 38 of file learner.h.
Function Documentation
as_multiline()
template<class T , class E > multi_learner* LEARNER::as_multiline (learner< T, E > * l)
Definition at line 460 of file learner.h.
References LEARNER::learner< T, E >::is_multiline, and THROW.
Referenced by cb_adf_setup(), cb_explore_adf_setup(), cb_sample_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), explore_eval_setup(), vw::finish_example(), Search::generate_training_example(), vw::learn(), learn_sup_adf(), vw::predict(), process_multi_ex(), VW::shared_feature_merger::shared_feature_merger_setup(), Search::single_prediction_LDF(), and warm_cb_setup().
 {
   if (l->is_multiline)  // Tried to use a singleline reduction as a multiline reduction
     return (multi_learner*)(l);
   THROW("Tried to use a singleline reduction as a multiline reduction");
 }
as_singleline()
template<class T , class E > single_learner* LEARNER::as_singleline (learner< T, E > * l)
Definition at line 468 of file learner.h.
References LEARNER::learner< T, E >::is_multiline, and THROW.
Referenced by active_cover_setup(), active_setup(), audit_regressor_setup(), autolink_setup(), baseline_setup(), binary_setup(), boosting_setup(), bs_setup(), cb_algs_setup(), cb_explore_setup(), cbify_setup(), classweight_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), CSOAA::csoaa_setup(), dispatch_example(), ect_setup(), ExpReplay::expreplay_setup(), vw::finish_example(), Search::generate_training_example(), interact_setup(), vw::learn(), log_multi_setup(), lrq_setup(), lrqfa_setup(), marginal_setup(), memory_tree_setup(), mf_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), oaa_setup(), vw::predict(), recall_tree_setup(), scorer_setup(), sensitivity(), Search::single_prediction_notLDF(), stagewise_poly_setup(), topk_setup(), VW_Predict(), and VW_PredictCostSensitive().
 {
   if (!l->is_multiline)  // Tried to use a multiline reduction as a singleline reduction
     return (single_learner*)(l);
   THROW("Tried to use a multiline reduction as a singleline reduction");
 }
complete_multi_ex()
bool LEARNER::complete_multi_ex (example * ec, multi_ex & ec_seq, vw & all)
Definition at line 104 of file learner.cc.
References example_is_newline_not_header(), VW::finish_example(), example::l, parser::lp, vw::p, and label_parser::test_label.
Referenced by dispatch_multi_ex().
 {
   const bool is_test_ec = all.p->lp.test_label(&ec->l);
   if (example_is_newline_not_header(*ec, all) && is_test_ec)
   {
     VW::finish_example(all, *ec);
     if (ec_seq.size() == 0)
     {
       cout << "Something is wrong---an example with no choice.  Do you have all 0 features? Or multiple empty lines?"
            << endl;
       return false;
     }
     return true;  // example complete
   }
   ec_seq.push_back(ec);
   return false;
 }
decrement_offset() [1/2]
void LEARNER::decrement_offset (example & ex, const size_t increment, const size_t i) inline
Definition at line 118 of file learner.h.
References example_predict::ft_offset.
 {
   assert(ex.ft_offset >= increment * i);
   ex.ft_offset -= static_cast<uint32_t>(increment * i);
 }
decrement_offset() [2/2]
void LEARNER::decrement_offset (multi_ex & ec_seq, const size_t increment, const size_t i) inline
Definition at line 124 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::learn(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::multipredict(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::predict(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::sensitivity(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::update().
 {
   for (auto ec : ec_seq)
   {
     assert(ec->ft_offset >= increment * i);
     ec->ft_offset -= static_cast<uint32_t>(increment * i);
   }
 }
dispatch()
void LEARNER::dispatch (vw & all, v_array< example *> examples)
Definition at line 217 of file learner.cc.
References parser::end_parsed_examples, vw::p, process_example(), and v_array< T >::size().
Referenced by generic_driver_onethread(), and parse_dispatch().
 {
   all.p->end_parsed_examples += examples.size();  // divergence: lock & signal
   for (size_t i = 0; i < examples.size(); ++i) process_example(all, examples[i]);
 }
dispatch_end_pass()
void LEARNER::dispatch_end_pass (vw & all, example & ec)
Definition at line 39 of file learner.cc.
References vw::current_pass, LEARNER::learner< T, E >::end_pass(), VW::finish_example(), and vw::l.
Referenced by on_new_partial_ex(), and process_example().
 {
   all.current_pass++;
   all.l->end_pass();
   VW::finish_example(all, ec);
 }
dispatch_multi_ex() [1/2]
template<void(*)(vw &, multi_ex &) f> void LEARNER::dispatch_multi_ex (vw & all, multi_ex & ec_seq)
Definition at line 124 of file learner.cc.
References f, and VW::finish_example().
 {
   f(all, ec_seq);                   // call learn or predict
   VW::finish_example(all, ec_seq);  // clean up
 }
dispatch_multi_ex() [2/2]
template<void(*)(vw &, multi_ex &) f> void LEARNER::dispatch_multi_ex (vw & all, example * ec, multi_ex & ec_seq)
Definition at line 131 of file learner.cc.
References complete_multi_ex().
 {
   if (complete_multi_ex(ec, ec_seq, all))
   {
     dispatch_multi_ex<f>(all, ec_seq);
   }
 }
example_is_newline_not_header()
bool LEARNER::example_is_newline_not_header (example & ec, vw & all) inline
Definition at line 85 of file learner.cc.
References label_type::ccb, CB::ec_is_example_header(), CCB::ec_is_example_header(), example_is_newline(), and vw::label_type.
Referenced by complete_multi_ex(), and EXPLORE_EVAL::output_example().
 {
   // If we are using CCB, test against CCB implementation otherwise fallback to previous behavior.
   bool is_header = false;
   if (all.label_type == label_type::ccb)
   {
     is_header = CCB::ec_is_example_header(ec);
   }
   else
   {
     is_header = CB::ec_is_example_header(ec);
   }
   return example_is_newline(ec) && !is_header;
 }
generic_driver() [1/4]
void LEARNER::generic_driver (std::vector< vw *> alls)
generic_driver() [2/4]
template<class T , void(*)(T, example *) f> void LEARNER::generic_driver (vw & all, T context)
Definition at line 180 of file learner.cc.
References vw::early_terminate, LEARNER::learner< T, E >::end_examples(), f, VW::finish_example(), VW::get_example(), vw::l, and vw::p.
Referenced by main(), and VW_Finish_Passes().
 {
   example* ec = nullptr;
   while (all.early_terminate == false)
     if ((ec = VW::get_example(all.p)) != nullptr)
       f(context, ec);
     else
       break;
   if (all.early_terminate)  // drain any extra examples from parser.
     while ((ec = VW::get_example(all.p)) != nullptr) VW::finish_example(all, *ec);
   all.l->end_examples();
 }
generic_driver() [3/4]
void LEARNER::generic_driver (vector< vw *> alls)
Definition at line 200 of file learner.cc.
References process_multiple().
 {
   generic_driver<vector<vw*>, process_multiple>(**alls.begin(), alls);
   // skip first as it already called end_examples()
   auto it = alls.begin();
   for (it++; it != alls.end(); it++) (*it)->l->end_examples();
 }
generic_driver() [4/4]
void LEARNER::generic_driver (vw & all)
Definition at line 209 of file learner.cc.
References LEARNER::learner< T, E >::is_multiline, and vw::l.
 {
   if (all.l->is_multiline)
     multi_ex_generic_driver<process_multi_ex>(all);
   else
     generic_driver<vw&, process_example>(all, all);
 }
generic_driver_onethread()
void LEARNER::generic_driver_onethread (vw & all)
Definition at line 223 of file learner.cc.
References dispatch(), LEARNER::learner< T, E >::end_examples(), parser::end_parsed_examples, LEARNER::learner< T, E >::is_multiline, vw::l, vw::p, and parse_dispatch().
Referenced by main().
 {
   if (all.l->is_multiline)
   {
     multi_ex ctxt;
     auto multi_ex_fptr = [&ctxt](vw& all, v_array<example*> examples) {
       all.p->end_parsed_examples += examples.size();  // divergence: lock & signal
       for (size_t i = 0; i < examples.size(); ++i) on_new_partial_ex<process_multi_ex>(examples[i], ctxt, all);
     };
     parse_dispatch(all, multi_ex_fptr);
     // flush accumulated examples if there is no newline
     // at the end of the file
     on_new_partial_ex<process_multi_ex>(nullptr, ctxt, all);
   }
   else
     parse_dispatch(all, dispatch);
   all.l->end_examples();
 }
increment_offset() [1/2]
void LEARNER::increment_offset (example & ex, const size_t increment, const size_t i) inline
Definition at line 108 of file learner.h.
References example_predict::ft_offset.
 {
   ex.ft_offset += static_cast<uint32_t>(increment * i);
 }
increment_offset() [2/2]
void LEARNER::increment_offset (multi_ex & ec_seq, const size_t increment, const size_t i) inline
Definition at line 113 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::learn(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::multipredict(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::predict(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::sensitivity(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::update().
 {
   for (auto ec : ec_seq) ec->ft_offset += static_cast<uint32_t>(increment * i);
 }
init_cost_sensitive_learner()
template<class T , class E , class L > learner<T, E>& LEARNER::init_cost_sensitive_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, parser * p, size_t ws, prediction_type::prediction_type_t pred_type = prediction_type::multiclass)
Definition at line 442 of file learner.h.
References COST_SENSITIVE::cs_label, COST_SENSITIVE::finish_example(), init_learner(), learn(), parser::lp, predict(), and LEARNER::learner< T, E >::set_finish_example().
Referenced by cbify_setup(), and warm_cb_setup().
 {
   learner<T, E>& l = learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, pred_type);
   dat.release();
   l.set_finish_example(COST_SENSITIVE::finish_example);
   p->lp = COST_SENSITIVE::cs_label;
   return l;
 }
init_learner() [1/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t ws, prediction_type::prediction_type_t pred_type)
Definition at line 361 of file learner.h.
References init_learner(), learn(), and predict().
Referenced by active_cover_setup(), active_setup(), audit_regressor_setup(), autolink_setup(), baseline_setup(), bfgs_setup(), binary_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_explore_adf_setup(), cb_explore_setup(), cb_sample_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), CSOAA::csoaa_setup(), explore_eval_setup(), ExpReplay::expreplay_setup(), ftrl_setup(), gd_mf_setup(), interact_setup(), kernel_svm_setup(), lda_setup(), lrq_setup(), lrqfa_setup(), marginal_setup(), memory_tree_setup(), mf_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), noop_setup(), OjaNewton_setup(), print_setup(), scorer_setup(), sender_setup(), GD::setup(), Search::setup(), VW::shared_feature_merger::shared_feature_merger_setup(), stagewise_poly_setup(), svrg_setup(), and topk_setup().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, pred_type);
   dat.release();
   return *ret;
 }
init_learner() [2/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (free_ptr< T > & dat, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t params_per_weight)
Definition at line 372 of file learner.h.
References init_learner(), learn(), predict(), and prediction_type::scalar.
 {
   auto ret =
       &learner<T, E>::init_learner(dat.get(), (L*)nullptr, learn, predict, params_per_weight, prediction_type::scalar);
   dat.release();
   return *ret;
 }
init_learner() [3/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (void(*)(T &, L &, E &) predict, size_t params_per_weight)
Definition at line 384 of file learner.h.
References init_learner(), predict(), and prediction_type::scalar.
 {
   return learner<T, E>::init_learner(
       nullptr, (L*)nullptr, predict, predict, params_per_weight, prediction_type::scalar);
 }
init_learner() [4/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (free_ptr< T > & dat, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t params_per_weight, prediction_type::prediction_type_t pred_type)
Definition at line 391 of file learner.h.
References init_learner(), learn(), and predict().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), (L*)nullptr, learn, predict, params_per_weight, pred_type);
   dat.release();
   return *ret;
 }
init_learner() [5/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t ws)
Definition at line 401 of file learner.h.
References init_learner(), learn(), and predict().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, base->pred_type);
   dat.release();
   return *ret;
 }
init_learner() [6/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict)
Definition at line 412 of file learner.h.
References init_learner(), learn(), and predict().
 {
   auto ret = &learner<T, E>::init_learner(dat.get(), base, learn, predict, 1, base->pred_type);
   dat.release();
   return *ret;
 }
init_learner() [7/7]
template<class T , class E , class L > learner<T, E>& LEARNER::init_learner (L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict)
Definition at line 422 of file learner.h.
References learn(), and predict().
Referenced by init_cost_sensitive_learner(), init_learner(), and init_multiclass_learner().
 {
   return learner<T, E>::init_learner(nullptr, base, learn, predict, 1, base->pred_type);
 }
init_multiclass_learner()
template<class T , class E , class L > learner<T, E>& LEARNER::init_multiclass_learner (free_ptr< T > & dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, parser * p, size_t ws, prediction_type::prediction_type_t pred_type = prediction_type::multiclass)
Definition at line 429 of file learner.h.
References init_learner(), learn(), parser::lp, MULTICLASS::mc_label, predict(), and LEARNER::learner< T, E >::set_finish_example().
Referenced by cbify_setup(), ect_setup(), log_multi_setup(), memory_tree_setup(), oaa_setup(), recall_tree_setup(), and warm_cb_setup().
 {
   learner<T, E>& l = learner<T, E>::init_learner(dat.get(), base, learn, predict, ws, pred_type);
   dat.release();
   l.set_finish_example(MULTICLASS::finish_example<T>);
   p->lp = MULTICLASS::mc_label;
   return l;
 }
is_save_cmd()
bool LEARNER::is_save_cmd (example * ec) inline
Definition at line 61 of file learner.cc.
References v_array< T >::begin(), v_array< T >::size(), and example::tag.
Referenced by on_new_partial_ex(), and process_example().
 {
   return (ec->tag.size() >= 4) && (0 == strncmp((const char*)ec->tag.begin(), "save", 4));
 }
make_base()
template<class T , class E > base_learner* LEARNER::make_base (learner< T, E > & base)
Definition at line 454 of file learner.h.
Referenced by active_cover_setup(), active_setup(), autolink_setup(), baseline_setup(), bfgs_setup(), binary_setup(), boosting_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_explore_adf_setup(), cb_explore_setup(), cb_sample_setup(), cbify_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), classweight_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), CSOAA::csoaa_setup(), ect_setup(), explore_eval_setup(), ExpReplay::expreplay_setup(), ftrl_setup(), gd_mf_setup(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner(), interact_setup(), kernel_svm_setup(), lda_setup(), log_multi_setup(), lrq_setup(), lrqfa_setup(), marginal_setup(), memory_tree_setup(), mf_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), noop_setup(), oaa_setup(), OjaNewton_setup(), print_setup(), recall_tree_setup(), scorer_setup(), sender_setup(), GD::setup(), Search::setup(), VW::shared_feature_merger::shared_feature_merger_setup(), stagewise_poly_setup(), svrg_setup(), topk_setup(), and warm_cb_setup().
 {
   return (base_learner*)(&base);
 }
multi_ex_generic_driver()
template<void(*)(vw &, multi_ex &) f> void LEARNER::multi_ex_generic_driver (vw & all)
Definition at line 161 of file learner.cc.
References vw::early_terminate, LEARNER::learner< T, E >::end_examples(), VW::finish_example(), VW::get_example(), vw::l, and vw::p.
 {
   multi_ex ec_seq;
   example* ec = nullptr;
   while (all.early_terminate == false)
   {
     ec = VW::get_example(all.p);
     on_new_partial_ex<f>(ec, ec_seq, all);
     if (ec == nullptr)
       break;
   }
   if (all.early_terminate)  // drain any extra examples from parser.
     while ((ec = VW::get_example(all.p)) != nullptr) VW::finish_example(all, *ec);
   all.l->end_examples();
 }
multiline_learn_or_predict()
template<bool is_learn> void LEARNER::multiline_learn_or_predict (multi_learner & base, multi_ex & examples, const uint64_t offset, const uint32_t id = 0)
Definition at line 476 of file learner.h.
References LEARNER::learner< T, E >::learn(), and LEARNER::learner< T, E >::predict().
 {
   std::vector<uint64_t> saved_offsets;
   for (auto ec : examples)
   {
     saved_offsets.push_back(ec->ft_offset);
     ec->ft_offset = offset;
   }
   if (is_learn)
     base.learn(examples, id);
   else
     base.predict(examples, id);
   for (size_t i = 0; i < examples.size(); i++) examples[i]->ft_offset = saved_offsets[i];
 }
noop()
void LEARNER::noop (void *) inline
Definition at line 100 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner(), and noop_setup().
 {}
noop_sensitivity()
float LEARNER::noop_sensitivity (void * , base_learner & , example &) inline
Definition at line 101 of file learner.h.
References recur_sensitivity().
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
 {
   std::cout << std::endl;
   return 0.;
 }
noop_sl()
void LEARNER::noop_sl (void * , io_buf & , bool , bool) inline
Definition at line 99 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
 {}
on_new_partial_ex()
template<void(*)(vw &, multi_ex &) f> void LEARNER::on_new_partial_ex (example * ec, multi_ex & ec_seq, vw & all)
Definition at line 140 of file learner.cc.
References dispatch_end_pass(), example::end_pass, example_predict::indices, is_save_cmd(), save(), and v_array< T >::size().
 {
   if (ec != nullptr)
   {
     if (ec->indices.size() > 1)  // 1+ nonconstant feature. (most common case first)
       dispatch_multi_ex<f>(all, ec, ec_seq);
     else if (ec->end_pass)
       dispatch_end_pass(all, *ec);
     else if (is_save_cmd(ec))
       save(all, ec);
     else
       dispatch_multi_ex<f>(all, ec, ec_seq);
   }
   else
   {
     if (ec_seq.size() > 0)
       dispatch_multi_ex<f>(all, ec_seq);
   }
 }
process_example()
void LEARNER::process_example (vw & all, example * ec)
Definition at line 66 of file learner.cc.
References dispatch_end_pass(), dispatch_example(), example::end_pass, example_predict::indices, is_save_cmd(), save(), and v_array< T >::size().
 {
   if (ec->indices.size() > 1)  // 1+ nonconstant feature. (most common case first)
     dispatch_example(all, *ec);
   else if (ec->end_pass)
     dispatch_end_pass(all, *ec);
   else if (is_save_cmd(ec))
     save(all, ec);
   else
     dispatch_example(all, *ec);
 }
process_multi_ex()
void LEARNER::process_multi_ex (vw & all, multi_ex & ec_seq)
Definition at line 78 of file learner.cc.
References as_multiline(), LEARNER::learner< T, E >::finish_example(), vw::l, and vw::learn().
 {
   all.learn(ec_seq);
   as_multiline(all.l)->finish_example(all, ec_seq);
 }
process_multiple()
void LEARNER::process_multiple (vector< vw *> alls, example * ec)
Definition at line 194 of file learner.cc.
References process_example().
Referenced by generic_driver().
 {
   // start with last as the first instance will free the example as it is the owner
   for (auto it = alls.rbegin(); it != alls.rend(); ++it) process_example(**it, ec);
 }
recur_sensitivity()
float LEARNER::recur_sensitivity (void * , base_learner & base, example & ec)
Definition at line 245 of file learner.cc.
References LEARNER::learner< T, E >::sensitivity().
Referenced by noop_sensitivity().
 { return base.sensitivity(ec); }
save()
void LEARNER::save (vw & all, example * ec)
Definition at line 46 of file learner.cc.
References v_array< T >::begin(), vw::final_regressor_name, VW::finish_example(), vw::quiet, save_predictor(), example::tag, and vw::trace_message.
Referenced by on_new_partial_ex(), and process_example().
 {
   // save state command
   string final_regressor_name = all.final_regressor_name;
   if ((ec->tag).size() >= 6 && (ec->tag)[4] == '_')
     final_regressor_name = string(ec->tag.begin() + 5, (ec->tag).size() - 5);
   if (!all.quiet)
     all.trace_message << "saving regressor to " << final_regressor_name << endl;
   save_predictor(all, final_regressor_name, 0);
   VW::finish_example(all, *ec);
 }
tuple_dbf()
func_data LEARNER::tuple_dbf (void * data, base_learner * base, void(*)(void *) func) inline
Definition at line 49 of file learner.h.
References LEARNER::func_data::base, LEARNER::func_data::data, and LEARNER::func_data::func.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::set_end_examples(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::set_end_pass(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::set_finish(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::set_init_driver().
 {
   func_data foo;
   foo.data = data;
   foo.base = base;
   foo.func = func;
   return foo;
 }