Vowpal Wabbit: CB_ALGS Namespace Reference
CB_ALGS Namespace Reference
Classes
struct cb
Functions
bool know_all_cost_example (CB::label &ld)
template<bool is_learn>
void predict_or_learn (cb &data, single_learner &base, example &ec)
void predict_eval (cb &, single_learner &, example &)
void learn_eval (cb &data, single_learner &, example &ec)
void output_example (vw &all, cb &data, example &ec, CB::label &ld)
void finish (cb &data)
void finish_example (vw &all, cb &c, example &ec)
void eval_finish_example (vw &all, cb &c, example &ec)
template<bool is_learn>
float get_cost_pred (LEARNER::single_learner *scorer, CB::cb_class *known_cost, example &ec, uint32_t index, uint32_t base)
float get_cost_estimate (CB::cb_class *observation, uint32_t action, float offset=0.)
float get_cost_estimate (CB::cb_class *observation, COST_SENSITIVE::label &scores, uint32_t action)
float get_cost_estimate (ACTION_SCORE::action_score &a_s, float cost, uint32_t action, float offset=0.)
bool example_is_newline_not_header (example &ec)
Function Documentation
eval_finish_example()
void CB_ALGS::eval_finish_example (vw & all, cb & c, example & ec)
Definition at line 127 of file cb_algs.cc.
References polylabel::cb_eval, CB_EVAL::label::event, VW::finish_example(), example::l, and output_example().
Referenced by cb_algs_setup().
 {
   output_example(all, c, ec, ec.l.cb_eval.event);
   VW::finish_example(all, ec);
 }
example_is_newline_not_header()
bool CB_ALGS::example_is_newline_not_header (example & ec) inline
Definition at line 80 of file cb_algs.h.
References CB::ec_is_example_header(), and example_is_newline().
Referenced by copy_example_to_adf(), GEN_CS::gen_cs_example_dr(), CB_ADF::output_example(), and CB_ADF::output_rank_example().
 {
   return (example_is_newline(ec) && !CB::ec_is_example_header(ec));
 }
finish()
void CB_ALGS::finish (cb & data)
Definition at line 114 of file cb_algs.cc.
References c, CB_ALGS::cb::cb_cs_ld, CB_ALGS::cb::cbcs, COST_SENSITIVE::label::costs, COST_SENSITIVE::cs_label, label_parser::delete_label, and GEN_CS::cb_to_cs::pred_scores.
Referenced by cb_algs_setup().
 {
   cb_to_cs& c = data.cbcs;
   data.cb_cs_ld.costs.delete_v();
   COST_SENSITIVE::cs_label.delete_label(&c.pred_scores);
 }
finish_example()
void CB_ALGS::finish_example (vw & all, cb & c, example & ec)
Definition at line 121 of file cb_algs.cc.
References polylabel::cb, VW::finish_example(), example::l, and output_example().
Referenced by cb_algs_setup().
 {
   output_example(all, c, ec, ec.l.cb);
   VW::finish_example(all, ec);
 }
get_cost_estimate() [1/3]
float CB_ALGS::get_cost_estimate (CB::cb_class * observation, uint32_t action, float offset = 0.) inline
Definition at line 58 of file cb_algs.h.
References CB::cb_class::action, CB::cb_class::cost, and CB::cb_class::probability.
Referenced by MWT::finish_example(), get_cost_estimate(), EXPLORE_EVAL::output_example(), output_example(), CB_EXPLORE::output_example(), CB_EXPLORE_ADF::output_example(), CCB::output_example(), MWT::predict_or_learn(), and CB_ADF::update_statistics().
 {
   if (action == observation->action)
     return (observation->cost - offset) / observation->probability;
   return 0.;
 }
get_cost_estimate() [2/3]
float CB_ALGS::get_cost_estimate (CB::cb_class * observation, COST_SENSITIVE::label & scores, uint32_t action) inline
Definition at line 65 of file cb_algs.h.
References COST_SENSITIVE::label::costs, and get_cost_estimate().
 {
   for (auto& cl : scores.costs)
     if (cl.class_index == action)
       return get_cost_estimate(observation, action, cl.x) + cl.x;
   return get_cost_estimate(observation, action);
 }
get_cost_estimate() [3/3]
float CB_ALGS::get_cost_estimate (ACTION_SCORE::action_score & a_s, float cost, uint32_t action, float offset = 0.) inline
Definition at line 73 of file cb_algs.h.
References ACTION_SCORE::action_score::action, and ACTION_SCORE::action_score::score.
 {
   if (action == a_s.action)
     return (cost - offset) / a_s.score;
   return 0.;
 }
get_cost_pred()
template<bool is_learn> float CB_ALGS::get_cost_pred (LEARNER::single_learner * scorer, CB::cb_class * known_cost, example & ec, uint32_t index, uint32_t base)
Definition at line 22 of file cb_algs.h.
References CB::cb_class::action, BASELINE::baseline_enabled(), polylabel::cb, CB::cb_class::cost, label_data::initial, example::l, label_data::label, LEARNER::learner< T, E >::learn(), example::pred, LEARNER::learner< T, E >::predict(), CB::cb_class::probability, BASELINE::reset_baseline_disabled(), polyprediction::scalar, BASELINE::set_baseline_enabled(), polylabel::simple, and example::weight.
 {
   CB::label ld = ec.l.cb;
   label_data simple_temp;
   simple_temp.initial = 0.;
   if (known_cost != nullptr && index == known_cost->action)
     simple_temp.label = known_cost->cost;
   else
     simple_temp.label = FLT_MAX;
   const bool baseline_enabled_old = BASELINE::baseline_enabled(&ec);
   BASELINE::set_baseline_enabled(&ec);
   ec.l.simple = simple_temp;
   polyprediction p = ec.pred;
   if (is_learn && known_cost != nullptr && index == known_cost->action)
   {
     float old_weight = ec.weight;
     ec.weight /= known_cost->probability;
     scorer->learn(ec, index - 1 + base);
     ec.weight = old_weight;
   }
   else
     scorer->predict(ec, index - 1 + base);
   if (!baseline_enabled_old)
     BASELINE::reset_baseline_disabled(&ec);
   float pred = ec.pred.scalar;
   ec.pred = p;
   ec.l.cb = ld;
   return pred;
 }
know_all_cost_example()
bool CB_ALGS::know_all_cost_example (CB::label & ld)
Definition at line 28 of file cb_algs.cc.
References CB::label::costs.
 {
   if (ld.costs.size() <= 1)  // this means we specified an example where all actions are possible but only specified the
                              // cost for the observed action
     return false;
   // if we specified more than 1 action for this example, i.e. either we have a limited set of possible actions, or all
   // actions are specified than check if all actions have a specified cost
   for (auto& cl : ld.costs)
     if (cl.cost == FLT_MAX)
       return false;
   return true;
 }
learn_eval()
void CB_ALGS::learn_eval (cb & data, single_learner & , example & ec)
Definition at line 72 of file cb_algs.cc.
References c, CB_ALGS::cb::cb_cs_ld, polylabel::cb_eval, CB_ALGS::cb::cbcs, CB::label::costs, COST_SENSITIVE::label::costs, CB_EVAL::label::event, CB_ADF::get_observed_cost(), GEN_CS::cb_to_cs::known_cost, and example::l.
Referenced by cb_algs_setup().
 {
   CB_EVAL::label ld = ec.l.cb_eval;
   cb_to_cs& c = data.cbcs;
   c.known_cost = get_observed_cost(ld.event);
   gen_cs_example<true>(c, ec, ld.event, data.cb_cs_ld);
   for (size_t i = 0; i < ld.event.costs.size(); i++)
     ld.event.costs[i].partial_prediction = data.cb_cs_ld.costs[i].partial_prediction;
   ec.pred.multiclass = ec.l.cb_eval.action;
 }
output_example()
void CB_ALGS::output_example (vw & all, cb & data, example & ec, CB::label & ld)
Definition at line 86 of file cb_algs.cc.
References CB::cb_class::action, c, CB::cb_label, CB_ALGS::cb::cbcs, CB::label::costs, vw::final_prediction_sink, get_cost_estimate(), GEN_CS::cb_to_cs::known_cost, loss(), polyprediction::multiclass, example::num_features, CB::cb_class::partial_prediction, example::pred, GEN_CS::cb_to_cs::pred_scores, vw::print, vw::print_text, CB::print_update(), vw::raw_prediction, vw::sd, example::tag, label_parser::test_label, test_label(), example::test_only, and shared_data::update().
Referenced by eval_finish_example(), and finish_example().
 {
   float loss = 0.;
   cb_to_cs& c = data.cbcs;
   if (!CB::cb_label.test_label(&ld))
     loss = get_cost_estimate(c.known_cost, c.pred_scores, ec.pred.multiclass);
   all.sd->update(ec.test_only, !CB::cb_label.test_label(&ld), loss, 1.f, ec.num_features);
   for (int sink : all.final_prediction_sink) all.print(sink, (float)ec.pred.multiclass, 0, ec.tag);
   if (all.raw_prediction > 0)
   {
     stringstream outputStringStream;
     for (unsigned int i = 0; i < ld.costs.size(); i++)
     {
       cb_class cl = ld.costs[i];
       if (i > 0)
         outputStringStream << ' ';
       outputStringStream << cl.action << ':' << cl.partial_prediction;
     }
     all.print_text(all.raw_prediction, outputStringStream.str(), ec.tag);
   }
   print_update(all, CB::cb_label.test_label(&ld), ec, nullptr, false);
 }
predict_eval()
void CB_ALGS::predict_eval (cb & , single_learner & , example &)
Definition at line 70 of file cb_algs.cc.
References THROW.
Referenced by cb_algs_setup().
 { THROW("can not use a test label for evaluation"); }
predict_or_learn()
template<bool is_learn> void CB_ALGS::predict_or_learn (cb & data, single_learner & base, example & ec)
Definition at line 44 of file cb_algs.cc.
References CB::cb_class::action, c, polylabel::cb, CB_ALGS::cb::cb_cs_ld, CB_TYPE_DM, CB_ALGS::cb::cbcs, COST_SENSITIVE::label::costs, CB_ADF::get_observed_cost(), GEN_CS::cb_to_cs::known_cost, example::l, LEARNER::learner< T, E >::learn(), GEN_CS::cb_to_cs::num_actions, and LEARNER::learner< T, E >::predict().
 {
   CB::label ld = ec.l.cb;
   cb_to_cs& c = data.cbcs;
   c.known_cost = get_observed_cost(ld);
   if (c.known_cost != nullptr && (c.known_cost->action < 1 || c.known_cost->action > c.num_actions))
     cerr << "invalid action: " << c.known_cost->action << endl;
   // generate a cost-sensitive example to update classifiers
   gen_cs_example<is_learn>(c, ec, ld, data.cb_cs_ld);
   if (c.cb_type != CB_TYPE_DM)
   {
     ec.l.cs = data.cb_cs_ld;
     if (is_learn)
       base.learn(ec);
     else
       base.predict(ec);
     for (size_t i = 0; i < ld.costs.size(); i++)
       ld.costs[i].partial_prediction = data.cb_cs_ld.costs[i].partial_prediction;
     ec.l.cb = ld;
   }
 }