Vowpal Wabbit: no_label Namespace Reference
no_label Namespace Reference
Typedefs
typedef char no_label
Functions
char * bufread_no_label (shared_data *, label_data *, char *c)
size_t read_cached_no_label (shared_data *, void *, io_buf &)
float get_weight (void *)
char * bufcache_no_label (label_data *, char *c)
void cache_no_label (void *, io_buf &)
void default_no_label (void *)
bool test_label (void *)
void delete_no_label (void *)
void parse_no_label (parser *, shared_data *, void *, v_array< substring > &words)
void print_no_label_update (vw &all, example &ec)
void output_and_account_no_label_example (vw &all, example &ec)
void return_no_label_example (vw &all, void *, example &ec)
Variables
label_parser no_label_parser
Typedef Documentation
no_label
typedef char no_label::no_label
Definition at line 14 of file no_label.h.
Function Documentation
bufcache_no_label()
char* no_label::bufcache_no_label (label_data * , char * c)
Definition at line 20 of file no_label.cc.
References c.
 { return c; }
bufread_no_label()
char* no_label::bufread_no_label (shared_data * , label_data * , char * c)
Definition at line 14 of file no_label.cc.
References c.
 { return c; }
cache_no_label()
void no_label::cache_no_label (void * , io_buf &)
Definition at line 22 of file no_label.cc.
 {}
default_no_label()
void no_label::default_no_label (void *)
Definition at line 24 of file no_label.cc.
 {}
delete_no_label()
void no_label::delete_no_label (void *)
Definition at line 28 of file no_label.cc.
 {}
get_weight()
float no_label::get_weight (void *)
Definition at line 18 of file no_label.cc.
 { return 1.; }
output_and_account_no_label_example()
void no_label::output_and_account_no_label_example (vw & all, example & ec)
Definition at line 56 of file no_label.cc.
References f, vw::final_prediction_sink, example::loss, example::num_features, example::partial_prediction, example::pred, vw::print, print_no_label_update(), vw::raw_prediction, polyprediction::scalar, vw::sd, v_array< T >::size(), example::tag, example::test_only, shared_data::update(), and example::weight.
 {
   all.sd->update(ec.test_only, false, ec.loss, ec.weight, ec.num_features);
   all.print(all.raw_prediction, ec.partial_prediction, -1, ec.tag);
   for (size_t i = 0; i < all.final_prediction_sink.size(); i++)
   {
     int f = (int)all.final_prediction_sink[i];
     all.print(f, ec.pred.scalar, 0, ec.tag);
   }
   print_no_label_update(all, ec);
 }
parse_no_label()
void no_label::parse_no_label (parser * , shared_data * , void * , v_array< substring > & words)
Definition at line 30 of file no_label.cc.
References print_substring(), and v_array< T >::size().
 {
   switch (words.size())
   {
     case 0:
       break;
     default:
       cout << "Error: " << words.size() << " is too many tokens for a simple label: ";
       for (unsigned int i = 0; i < words.size(); ++i) print_substring(words[i]);
       cout << endl;
   }
 }
print_no_label_update()
void no_label::print_no_label_update (vw & all, example & ec)
Definition at line 46 of file no_label.cc.
References vw::bfgs, vw::current_pass, shared_data::dump_interval, vw::holdout_set_off, example::num_features, example::pred, shared_data::print_update(), vw::progress_add, vw::progress_arg, vw::quiet, polyprediction::scalar, vw::sd, shared_data::weighted_labeled_examples, and shared_data::weighted_unlabeled_examples.
Referenced by output_and_account_no_label_example().
 {
   if (all.sd->weighted_labeled_examples + all.sd->weighted_unlabeled_examples >= all.sd->dump_interval && !all.quiet &&
       !all.bfgs)
   {
     all.sd->print_update(all.holdout_set_off, all.current_pass, 0.f, ec.pred.scalar, ec.num_features, all.progress_add,
         all.progress_arg);
   }
 }
read_cached_no_label()
size_t no_label::read_cached_no_label (shared_data * , void * , io_buf &)
Definition at line 16 of file no_label.cc.
 { return 1; }
return_no_label_example()
void no_label::return_no_label_example (vw & all, void * , example & ec)
Definition at line 70 of file no_label.cc.
References VW::finish_example(), and output_and_account_example().
 {
   output_and_account_example(all, ec);
   VW::finish_example(all, ec);
 }
test_label()
bool no_label::test_label (void *)
Definition at line 26 of file no_label.cc.
 { return false; }
Variable Documentation
no_label_parser
label_parser no_label::no_label_parser
Initial value:
= {default_no_label, parse_no_label, cache_no_label, read_cached_no_label, delete_no_label,
    get_weight, nullptr, test_label, sizeof(nullptr)}
Definition at line 43 of file no_label.cc.
Referenced by lda_setup().