Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/parse_primitives.cc File Reference
parse_primitives.cc File Reference
#include <iostream>
#include <strings.h>
#include <stdexcept>
#include <sstream>
#include "parse_primitives.h"
#include "hash.h"
#include "vw_exception.h"
Functions
bool substring_equal (const substring &a, const substring &b)
bool substring_equal (const substring &ss, const char *str)
size_t substring_len (substring &s)
uint64_t hashstring (substring s, uint64_t h)
uint64_t hashall (substring s, uint64_t h)
hash_func_t getHasher (const std::string &s)
std::ostream & operator<< (std::ostream &os, const substring &ss)
std::ostream & operator<< (std::ostream &os, const v_array< substring > &ss)
Function Documentation
getHasher()
hash_func_t getHasher (const std::string & s)
Definition at line 58 of file parse_primitives.cc.
References hashall(), hashstring(), and THROW.
Referenced by VW::hash_feature_static(), VW::hash_space_static(), and parse_feature_tweaks().
 {
   if (s == "strings")
     return hashstring;
   else if (s == "all")
     return hashall;
   else
     THROW("Unknown hash function: " << s);
 }
hashall()
uint64_t hashall (substring s, uint64_t h)
Definition at line 56 of file parse_primitives.cc.
References substring::begin, substring::end, and uniform_hash().
Referenced by getHasher().
 { return uniform_hash((unsigned char*)s.begin, s.end - s.begin, h); }
hashstring()
uint64_t hashstring (substring s, uint64_t h)
Definition at line 36 of file parse_primitives.cc.
References substring::begin, substring::end, and uniform_hash().
Referenced by getHasher(), TC_parser< audit >::maybeFeature(), CB::parse_label(), COST_SENSITIVE::parse_label(), and CB_EVAL::parse_label().
 {
   // trim leading whitespace but not UTF-8
   for (; s.begin < s.end && *(s.begin) <= 0x20 && (int)*(s.begin) >= 0; s.begin++)
     ;
   // trim trailing white space but not UTF-8
   for (; s.end > s.begin && *(s.end - 1) <= 0x20 && (int)*(s.end - 1) >= 0; s.end--)
     ;
   size_t ret = 0;
   char* p = s.begin;
   while (p != s.end)
     if (*p >= '0' && *p <= '9')
       ret = 10 * ret + *(p++) - '0';
     else
       return uniform_hash((unsigned char*)s.begin, s.end - s.begin, h);
   return ret + h;
 }
operator<<() [1/2]
std::ostream& operator<< (std::ostream & os, const substring & ss)
Definition at line 68 of file parse_primitives.cc.
References substring::begin, and substring::end.
 {
   std::string s(ss.begin, ss.end - ss.begin);
   return os << s;
 }
operator<<() [2/2]
std::ostream& operator<< (std::ostream & os, const v_array< substring > & ss)
Definition at line 74 of file parse_primitives.cc.
 {
   substring* it = ss.cbegin();
   if (it == ss.cend())
   {
     return os;
   }
   os << *it;
   for (it++; it != ss.cend(); it++)
   {
     os << ",";
     os << *it;
   }
   return os;
 }
substring_equal() [1/2]
bool substring_equal (const substring & a, const substring & b)
Definition at line 19 of file parse_primitives.cc.
References substring::begin, and substring::end.
Referenced by namedlabels::namedlabels(), parse_dictionary_argument(), CB::parse_label(), COST_SENSITIVE::parse_label(), CCB::parse_label(), and tokenize().
 {
   return (a.end - a.begin == b.end - b.begin)  // same length
       && (strncmp(a.begin, b.begin, a.end - a.begin) == 0);
 }
substring_equal() [2/2]
bool substring_equal (const substring & ss, const char * str)
Definition at line 25 of file parse_primitives.cc.
References substring::begin, and substring::end.
 {
   size_t len_ss = ss.end - ss.begin;
   size_t len_str = strlen(str);
   if (len_ss != len_str)
     return false;
   return (strncmp(ss.begin, str, len_ss) == 0);
 }
substring_len()
size_t substring_len (substring & s)
Definition at line 34 of file parse_primitives.cc.
References substring::begin, and substring::end.
Referenced by learn_or_predict(), and tokenize().
 { return s.end - s.begin; }