Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/rand48.h File Reference
rand48.h File Reference
Functions
float merand48 (uint64_t &initial)
float merand48_noadvance (uint64_t v)
Function Documentation
merand48()
float merand48 (uint64_t & initial)
Definition at line 16 of file rand48.cc.
References a, bias, and c.
Referenced by cheesyrand(), cheesyrbit(), Search::choose_oracle_action(), corrupt_action(), EXPLORE_EVAL::do_actual_learning(), random_positive_wrapper< T >::func(), random_weights_wrapper< T >::func(), polar_normal_weights_wrapper< T >::func(), set_rand_wrapper< T >::func(), set_initial_lda_wrapper< T >::func(), generate_uar_action(), Search::get_training_timesteps(), OjaNewton::initialize_Z(), recall_tree_ns::learn(), memory_tree_ns::learn_at_leaf_random(), learn_or_predict(), merand48_noadvance(), oaa_setup(), ExpReplay::predict_or_learn(), predict_or_learn_adaptive(), predict_or_learn_multi(), query_decision(), Search::random(), Search::random_policy(), memory_tree_ns::random_sample_example_pop(), memory_tree_ns::single_query_and_learn(), train(), and BS::weight_gen().
 {
   static_assert(sizeof(int) == sizeof(float), "Floats and ints are converted between, they must be the same size.");
   initial = a * initial + c;
   int32_t temp = ((initial >> 25) & 0x7FFFFF) | bias;
   return reinterpret_cast<float&>(temp) - 1;
 }
merand48_noadvance()
float merand48_noadvance (uint64_t v)
Definition at line 24 of file rand48.cc.
References merand48().
Referenced by Search::random_policy().
 { return merand48(v); }