Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/recall_tree.h File Reference
recall_tree.h File Reference
Functions
LEARNER::base_learner * recall_tree_setup (VW::config::options_i &options, vw &all)
Function Documentation
recall_tree_setup()
LEARNER::base_learner* recall_tree_setup (VW::config::options_i & options, vw & all)
Definition at line 502 of file recall_tree.cc.
References add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), f, recall_tree_ns::finish(), LEARNER::init_multiclass_learner(), init_tree(), recall_tree_ns::learn(), LEARNER::make_base(), VW::config::make_option(), min(), vw::p, recall_tree_ns::predict(), vw::quiet, save_load_tree(), LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_save_load(), setup_base(), vw::trace_message, vw::training, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto tree = scoped_calloc_or_throw<recall_tree>();
   option_group_definition new_options("Recall Tree");
   new_options.add(make_option("recall_tree", tree->k).keep().help("Use online tree for multiclass"))
       .add(make_option("max_candidates", tree->max_candidates)
                .keep()
                .help("maximum number of labels per leaf in the tree"))
       .add(make_option("bern_hyper", tree->bern_hyper).default_value(1.f).help("recall tree depth penalty"))
       .add(make_option("max_depth", tree->max_depth).keep().help("maximum depth of the tree, default log_2 (#classes)"))
       .add(make_option("node_only", tree->node_only).keep().help("only use node features, not full path features"))
       .add(make_option("randomized_routing", tree->randomized_routing).keep().help("randomized routing"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("recall_tree"))
     return nullptr;
   tree->all = &all;
   tree->max_candidates = options.was_supplied("max_candidates")
       ? tree->max_candidates
       : (std::min)(tree->k, 4 * (uint32_t)(ceil(log(tree->k) / log(2.0))));
   tree->max_depth =
       options.was_supplied("max_depth") ? tree->max_depth : (uint32_t)std::ceil(std::log(tree->k) / std::log(2.0));
   init_tree(*tree.get());
   if (!all.quiet)
     all.trace_message << "recall_tree:"
                       << " node_only = " << tree->node_only << " bern_hyper = " << tree->bern_hyper
                       << " max_depth = " << tree->max_depth << " routing = "
                       << (all.training ? (tree->randomized_routing ? "randomized" : "deterministic") : "n/a testonly")
                       << std::endl;
   learner<recall_tree, example>& l = init_multiclass_learner(
       tree, as_singleline(setup_base(options, all)), learn, predict, all.p, tree->max_routers + tree->k);
   l.set_save_load(save_load_tree);
   l.set_finish(finish);
   return make_base(l);
 }