Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/scorer.cc File Reference
scorer.cc File Reference
#include <float.h>
#include "correctedMath.h"
#include "reductions.h"
#include "vw_exception.h"
Classes
struct scorer
Functions
template<bool is_learn, float(*)(float in) link>
void predict_or_learn (scorer &s, LEARNER::single_learner &base, example &ec)
template<float(*)(float in) link>
void multipredict (scorer &, LEARNER::single_learner &base, example &ec, size_t count, size_t, polyprediction *pred, bool finalize_predictions)
void update (scorer &s, LEARNER::single_learner &base, example &ec)
float logistic (float in)
float glf1 (float in)
float id (float in)
LEARNER::base_learner * scorer_setup (options_i &options, vw &all)
Function Documentation
glf1()
float glf1 (float in) inline
Definition at line 50 of file scorer.cc.
References correctedExp, and f.
 { return 2.f / (1.f + correctedExp(-in)) - 1.f; }
id()
float id (float in) inline
Definition at line 52 of file scorer.cc.
Referenced by create_circuit(), ect_predict(), ect_train(), Search::foreach_action_from_cache(), CCB::inject_slot_id(), TC_parser< audit >::maybeFeature(), parse_feature_tweaks(), VW::SpanningTree::Run(), GraphTask::run_bfs(), and Search::predictor::set_learner_id().
 { return in; }
logistic()
float logistic (float in) inline
Definition at line 44 of file scorer.cc.
References correctedExp.
 { return 1.f / (1.f + correctedExp(-in)); }
multipredict()
template<float(*)(float in) link> void multipredict (scorer & , LEARNER::single_learner & base, example & ec, size_t count, size_t , polyprediction * pred, bool finalize_predictions) inline
Definition at line 30 of file scorer.cc.
References c, LEARNER::learner< T, E >::multipredict(), and prediction_type::scalar.
 {
   base.multipredict(ec, 0, count, pred, finalize_predictions);  // TODO: need to thread step through???
   for (size_t c = 0; c < count; c++) pred[c].scalar = link(pred[c].scalar);
 }
predict_or_learn()
template<bool is_learn, float(*)(float in) link> void predict_or_learn (scorer & s, LEARNER::single_learner & base, example & ec)
Definition at line 15 of file scorer.cc.
References scorer::all, loss_function::getLoss(), example::l, label_data::label, LEARNER::learner< T, E >::learn(), example::loss, vw::loss, example::pred, LEARNER::learner< T, E >::predict(), polyprediction::scalar, vw::sd, vw::set_minmax, polylabel::simple, and example::weight.
 {
   s.all->set_minmax(s.all->sd, ec.l.simple.label);
   if (is_learn && ec.l.simple.label != FLT_MAX && ec.weight > 0)
     base.learn(ec);
   else
     base.predict(ec);
   if (ec.weight > 0 && ec.l.simple.label != FLT_MAX)
     ec.loss = s.all->loss->getLoss(s.all->sd, ec.pred.scalar, ec.l.simple.label) * ec.weight;
   ec.pred.scalar = link(ec.pred.scalar);
 }
scorer_setup()
LEARNER::base_learner* scorer_setup (options_i & options, vw & all)
Definition at line 54 of file scorer.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), vw::scorer, LEARNER::learner< T, E >::set_multipredict(), LEARNER::learner< T, E >::set_update(), setup_base(), THROW, and update().
Referenced by parse_reductions().
 {
   auto s = scoped_calloc_or_throw<scorer>();
   string link;
   option_group_definition new_options("scorer options");
   new_options.add(make_option("link", link)
                       .default_value("identity")
                       .keep()
                       .help("Specify the link function: identity, logistic, glf1 or poisson"));
   options.add_and_parse(new_options);
   // This always returns a base_learner.
   s->all = &all;
   auto base = as_singleline(setup_base(options, all));
   LEARNER::learner<scorer, example>* l;
   void (*multipredict_f)(scorer&, LEARNER::single_learner&, example&, size_t, size_t, polyprediction*, bool) =
       multipredict<id>;
   if (link.compare("identity") == 0)
     l = &init_learner(s, base, predict_or_learn<true, id>, predict_or_learn<false, id>);
   else if (link.compare("logistic") == 0)
   {
     l = &init_learner(s, base, predict_or_learn<true, logistic>, predict_or_learn<false, logistic>);
     multipredict_f = multipredict<logistic>;
   }
   else if (link.compare("glf1") == 0)
   {
     l = &init_learner(s, base, predict_or_learn<true, glf1>, predict_or_learn<false, glf1>);
     multipredict_f = multipredict<glf1>;
   }
   else if (link.compare("poisson") == 0)
   {
     l = &init_learner(s, base, predict_or_learn<true, expf>, predict_or_learn<false, expf>);
     multipredict_f = multipredict<expf>;
   }
   else
     THROW("Unknown link function: " << link);
   l->set_multipredict(multipredict_f);
   l->set_update(update);
   all.scorer = LEARNER::as_singleline(l);
   return make_base(*all.scorer);
 }
update()
void update (scorer & s, LEARNER::single_learner & base, example & ec)
Definition at line 37 of file scorer.cc.
References scorer::all, example::l, label_data::label, vw::sd, vw::set_minmax, polylabel::simple, and LEARNER::learner< T, E >::update().
Referenced by scorer_setup().
 {
   s.all->set_minmax(s.all->sd, ec.l.simple.label);
   base.update(ec);
 }