Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/scorer.h File Reference
scorer.h File Reference
Functions
LEARNER::base_learner * scorer_setup (VW::config::options_i &options, vw &all)
Function Documentation
scorer_setup()
LEARNER::base_learner* scorer_setup (VW::config::options_i & options, vw & all)
Definition at line 54 of file scorer.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), vw::scorer, LEARNER::learner< T, E >::set_multipredict(), LEARNER::learner< T, E >::set_update(), setup_base(), THROW, and update().
Referenced by parse_reductions().
 {
   auto s = scoped_calloc_or_throw<scorer>();
   string link;
   option_group_definition new_options("scorer options");
   new_options.add(make_option("link", link)
                       .default_value("identity")
                       .keep()
                       .help("Specify the link function: identity, logistic, glf1 or poisson"));
   options.add_and_parse(new_options);
   // This always returns a base_learner.
   s->all = &all;
   auto base = as_singleline(setup_base(options, all));
   LEARNER::learner<scorer, example>* l;
   void (*multipredict_f)(scorer&, LEARNER::single_learner&, example&, size_t, size_t, polyprediction*, bool) =
       multipredict<id>;
   if (link.compare("identity") == 0)
     l = &init_learner(s, base, predict_or_learn<true, id>, predict_or_learn<false, id>);
   else if (link.compare("logistic") == 0)
   {
     l = &init_learner(s, base, predict_or_learn<true, logistic>, predict_or_learn<false, logistic>);
     multipredict_f = multipredict<logistic>;
   }
   else if (link.compare("glf1") == 0)
   {
     l = &init_learner(s, base, predict_or_learn<true, glf1>, predict_or_learn<false, glf1>);
     multipredict_f = multipredict<glf1>;
   }
   else if (link.compare("poisson") == 0)
   {
     l = &init_learner(s, base, predict_or_learn<true, expf>, predict_or_learn<false, expf>);
     multipredict_f = multipredict<expf>;
   }
   else
     THROW("Unknown link function: " << link);
   l->set_multipredict(multipredict_f);
   l->set_update(update);
   all.scorer = LEARNER::as_singleline(l);
   return make_base(*all.scorer);
 }