Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/stagewise_poly.h File Reference
stagewise_poly.h File Reference
Functions
LEARNER::base_learner * stagewise_poly_setup (VW::config::options_i &options, vw &all)
Function Documentation
stagewise_poly_setup()
LEARNER::base_learner* stagewise_poly_setup (VW::config::options_i & options, vw & all)
Definition at line 661 of file stagewise_poly.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), depthsbits_create(), end_pass(), finish(), finish_example(), LEARNER::init_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), predict(), save_load(), LEARNER::learner< T, E >::set_end_pass(), LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_save_load(), setup_base(), and sort_data_create().
Referenced by parse_reductions().
 {
   auto poly = scoped_calloc_or_throw<stagewise_poly>();
   bool stage_poly = false;
   option_group_definition new_options("Stagewise polynomial options");
   new_options.add(make_option("stage_poly", stage_poly).keep().help("use stagewise polynomial feature learning"))
       .add(make_option("sched_exponent", poly->sched_exponent)
                .default_value(1.f)
                .help("exponent controlling quantity of included features"))
       .add(make_option("batch_sz", poly->batch_sz)
                .default_value(1000)
                .help("multiplier on batch size before including more features"))
       .add(make_option("batch_sz_no_doubling", poly->batch_sz_double).help("batch_sz does not double"));
 #ifdef MAGIC_ARGUMENT
   new_options.add(
       make_typed_option("magic_argument", poly->magic_argument).default_value(0.).help("magical feature flag"));
 #endif  // MAGIC_ARGUMENT
   options.add_and_parse(new_options);
   if (!stage_poly)
     return nullptr;
   poly->all = &all;
   depthsbits_create(*poly.get());
   sort_data_create(*poly.get());
   poly->batch_sz_double = !poly->batch_sz_double;
   poly->sum_sparsity = 0;
   poly->sum_input_sparsity = 0;
   poly->num_examples = 0;
   poly->sum_sparsity_sync = 0;
   poly->sum_input_sparsity_sync = 0;
   poly->num_examples_sync = 0;
   poly->last_example_counter = -1;
   poly->numpasses = 1;
   poly->update_support = false;
   poly->original_ec = nullptr;
   poly->next_batch_sz = poly->batch_sz;
   learner<stagewise_poly, example> &l = init_learner(poly, as_singleline(setup_base(options, all)), learn, predict);
   l.set_finish(finish);
   l.set_save_load(save_load);
   l.set_finish_example(finish_example);
   l.set_end_pass(end_pass);
   return make_base(l);
 }