Vowpal Wabbit: HookTask::task_data Struct Reference
HookTask::task_data Struct Reference
#include <search_hooktask.h>
Public Attributes
void(* run_f)(Search::search &)
void(* run_setup_f)(Search::search &)
void(* run_takedown_f)(Search::search &)
void * run_object
void * setup_object
void * takedown_object
void(* delete_run_object)(void *)
void(* delete_extra_data)(task_data &)
VW::config::options_i * arg
const void * extra_data
const void * extra_data2
size_t num_actions
Detailed Description
Definition at line 18 of file search_hooktask.h.
Member Data Documentation
arg
VW::config::options_i* HookTask::task_data::arg
Definition at line 32 of file search_hooktask.h.
Referenced by HookTask::initialize().
delete_extra_data
void(* HookTask::task_data::delete_extra_data) (task_data &)
Definition at line 31 of file search_hooktask.h.
Referenced by HookTask::finish(), and HookTask::initialize().
delete_run_object
void(* HookTask::task_data::delete_run_object) (void *)
Definition at line 29 of file search_hooktask.h.
Referenced by HookTask::finish(), and HookTask::initialize().
extra_data
const void* HookTask::task_data::extra_data
Definition at line 33 of file search_hooktask.h.
extra_data2
const void* HookTask::task_data::extra_data2
Definition at line 34 of file search_hooktask.h.
num_actions
size_t HookTask::task_data::num_actions
Definition at line 35 of file search_hooktask.h.
Referenced by HookTask::initialize().
run_f
void(* HookTask::task_data::run_f) (Search::search &)
Definition at line 20 of file search_hooktask.h.
Referenced by HookTask::initialize(), and HookTask::run().
run_object
void* HookTask::task_data::run_object
Definition at line 23 of file search_hooktask.h.
Referenced by HookTask::finish(), and HookTask::initialize().
run_setup_f
void(* HookTask::task_data::run_setup_f) (Search::search &)
Definition at line 21 of file search_hooktask.h.
Referenced by HookTask::initialize(), and HookTask::run_setup().
run_takedown_f
void(* HookTask::task_data::run_takedown_f) (Search::search &)
Definition at line 22 of file search_hooktask.h.
Referenced by HookTask::initialize(), and HookTask::run_takedown().
setup_object
void* HookTask::task_data::setup_object
Definition at line 25 of file search_hooktask.h.
Referenced by HookTask::finish(), and HookTask::initialize().
takedown_object
void* HookTask::task_data::takedown_object
Definition at line 27 of file search_hooktask.h.
Referenced by HookTask::finish(), and HookTask::initialize().
The documentation for this struct was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/search_hooktask.h