Vowpal Wabbit: VWReaderHandler< audit > Struct Template Reference
VWReaderHandler< audit > Struct Template Reference
#include <parse_example_json.h>
Public Member Functions
void init (vw *all, v_array< example *> *examples, rapidjson::InsituStringStream *stream, const char *stream_end, VW::example_factory_t example_factory, void *example_factory_context)
bool Bool (bool v)
bool Int (int v)
bool Uint (unsigned v)
bool Int64 (int64_t v)
bool Uint64 (uint64_t v)
bool Double (double v)
bool String (const char *str, SizeType len, bool copy)
bool StartObject ()
bool Key (const char *str, SizeType len, bool copy)
bool EndObject (SizeType count)
bool StartArray ()
bool EndArray (SizeType count)
bool Null ()
bool VWReaderHandlerNull ()
bool VWReaderHandlerDefault ()
bool RawNumber (const char *, rapidjson::SizeType, bool)
std::stringstream & error ()
BaseState< audit > * current_state ()
Public Attributes
Context< audit > ctx
Detailed Description
template<bool audit>
struct VWReaderHandler< audit >
Definition at line 1289 of file parse_example_json.h.
Member Function Documentation
Bool()
template<bool audit> bool VWReaderHandler< audit >::Bool (bool v) inline
Definition at line 1308 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Bool(ctx, v)); }
current_state()
template<bool audit> BaseState<audit>* VWReaderHandler< audit >::current_state () inline
Definition at line 1336 of file parse_example_json.h.
References Context< audit >::current_state.
Referenced by VW::read_line_decision_service_json(), and VW::read_line_json().
 { return ctx.current_state; }
Double()
template<bool audit> bool VWReaderHandler< audit >::Double (double v) inline
Definition at line 1313 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Float(ctx, (float)v)); }
EndArray()
template<bool audit> bool VWReaderHandler< audit >::EndArray (SizeType count) inline
Definition at line 1325 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->EndArray(ctx, count)); }
EndObject()
template<bool audit> bool VWReaderHandler< audit >::EndObject (SizeType count) inline
Definition at line 1323 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->EndObject(ctx, count)); }
error()
template<bool audit> std::stringstream& VWReaderHandler< audit >::error () inline
Definition at line 1334 of file parse_example_json.h.
References Context< audit >::error().
Referenced by VW::read_line_decision_service_json(), and VW::read_line_json().
 { return ctx.error(); }
init()
template<bool audit> void VWReaderHandler< audit >::init (vw * all, v_array< example *> * examples, rapidjson::InsituStringStream * stream, const char * stream_end, VW::example_factory_t example_factory, void * example_factory_context) inline
Definition at line 1293 of file parse_example_json.h.
References label_parser::default_label, Context< audit >::ex, Context< audit >::example_factory, Context< audit >::example_factory_context, Context< audit >::examples, Context< audit >::init(), example::l, parser::lp, vw::p, Context< audit >::stream, and Context< audit >::stream_end.
Referenced by VW::read_line_decision_service_json(), and VW::read_line_json().
   {
     ctx.init(all);
     ctx.examples = examples;
     ctx.ex = (*examples)[0];
     all->p->lp.default_label(&ctx.ex->l);
     ctx.stream = stream;
     ctx.stream_end = stream_end;
     ctx.example_factory = example_factory;
     ctx.example_factory_context = example_factory_context;
   }
Int()
template<bool audit> bool VWReaderHandler< audit >::Int (int v) inline
Definition at line 1309 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Float(ctx, (float)v)); }
Int64()
template<bool audit> bool VWReaderHandler< audit >::Int64 (int64_t v) inline
Definition at line 1311 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Float(ctx, (float)v)); }
Key()
template<bool audit> bool VWReaderHandler< audit >::Key (const char * str, SizeType len, bool copy) inline
Definition at line 1319 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
   {
     return ctx.TransitionState(ctx.current_state->Key(ctx, str, len, copy));
   }
Null()
template<bool audit> bool VWReaderHandler< audit >::Null () inline
Definition at line 1326 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Null(ctx)); }
RawNumber()
template<bool audit> bool VWReaderHandler< audit >::RawNumber (const char * , rapidjson::SizeType , bool) inline
Definition at line 1332 of file parse_example_json.h.
 { return false; }
StartArray()
template<bool audit> bool VWReaderHandler< audit >::StartArray () inline
Definition at line 1324 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->StartArray(ctx)); }
StartObject()
template<bool audit> bool VWReaderHandler< audit >::StartObject () inline
Definition at line 1318 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->StartObject(ctx)); }
String()
template<bool audit> bool VWReaderHandler< audit >::String (const char * str, SizeType len, bool copy) inline
Definition at line 1314 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
   {
     return ctx.TransitionState(ctx.current_state->String(ctx, str, len, copy));
   }
Uint()
template<bool audit> bool VWReaderHandler< audit >::Uint (unsigned v) inline
Definition at line 1310 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Uint(ctx, v)); }
Uint64()
template<bool audit> bool VWReaderHandler< audit >::Uint64 (uint64_t v) inline
Definition at line 1312 of file parse_example_json.h.
References Context< audit >::current_state, and Context< audit >::TransitionState().
 { return ctx.TransitionState(ctx.current_state->Float(ctx, (float)v)); }
VWReaderHandlerDefault()
template<bool audit> bool VWReaderHandler< audit >::VWReaderHandlerDefault () inline
Definition at line 1329 of file parse_example_json.h.
 { return false; }
VWReaderHandlerNull()
template<bool audit> bool VWReaderHandler< audit >::VWReaderHandlerNull () inline
Definition at line 1328 of file parse_example_json.h.
 { return true; }
Member Data Documentation
ctx
template<bool audit> Context<audit> VWReaderHandler< audit >::ctx
Definition at line 1291 of file parse_example_json.h.
Referenced by VW::read_line_decision_service_json().
The documentation for this struct was generated from the following file:
/mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/parse_example_json.h