Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/topk.cc File Reference
topk.cc File Reference
#include <float.h>
#include <sstream>
#include <queue>
#include "reductions.h"
#include "vw.h"
Classes
struct compare_scored_examples
struct topk
Typedefs
using scored_example = pair< float, v_array< char > >
Functions
void print_result (int f, priority_queue< scored_example, vector< scored_example >, compare_scored_examples > &pr_queue)
void output_example (vw &all, example &ec)
template<bool is_learn>
void predict_or_learn (topk &d, LEARNER::single_learner &base, multi_ex &ec_seq)
void finish_example (vw &all, topk &d, multi_ex &ec_seq)
void finish (topk &d)
LEARNER::base_learner * topk_setup (options_i &options, vw &all)
Typedef Documentation
scored_example
using scored_example = pair<float, v_array<char> >
Definition at line 16 of file topk.cc.
Function Documentation
finish()
void finish (topk & d)
Definition at line 102 of file topk.cc.
References topk::pr_queue.
Referenced by topk_setup().
 { d.pr_queue = priority_queue<scored_example, vector<scored_example>, compare_scored_examples>(); }
finish_example()
void finish_example (vw & all, topk & d, multi_ex & ec_seq)
Definition at line 95 of file topk.cc.
References VW::clear_seq_and_finish_examples(), vw::final_prediction_sink, topk::pr_queue, and print_result().
Referenced by topk_setup().
 {
   for (int sink : all.final_prediction_sink) print_result(sink, d.pr_queue);
   VW::clear_seq_and_finish_examples(all, ec_seq);
 }
output_example()
void output_example (vw & all, example & ec)
Definition at line 60 of file topk.cc.
References example::l, label_data::label, example::loss, example::num_features, CB::print_update(), vw::sd, polylabel::simple, example::test_only, shared_data::update(), example::weight, and shared_data::weighted_labels.
Referenced by predict_or_learn().
 {
   label_data& ld = ec.l.simple;
   all.sd->update(ec.test_only, ld.label != FLT_MAX, ec.loss, ec.weight, ec.num_features);
   if (ld.label != FLT_MAX)
     all.sd->weighted_labels += ((double)ld.label) * ec.weight;
   print_update(all, ec);
 }
predict_or_learn()
template<bool is_learn> void predict_or_learn (topk & d, LEARNER::single_learner & base, multi_ex & ec_seq)
Definition at line 72 of file topk.cc.
References topk::all, topk::K, LEARNER::learner< T, E >::learn(), output_example(), topk::pr_queue, and LEARNER::learner< T, E >::predict().
 {
   for (auto example : ec_seq)
   {
     auto ec = *example;
     if (is_learn)
       base.learn(ec);
     else
       base.predict(ec);
     if (d.pr_queue.size() < d.K)
       d.pr_queue.push(make_pair(ec.pred.scalar, ec.tag));
     else if (d.pr_queue.top().first < ec.pred.scalar)
     {
       d.pr_queue.pop();
       d.pr_queue.push(make_pair(ec.pred.scalar, ec.tag));
     }
     output_example(*d.all, ec);
   }
 }
print_result()
void print_result (int f, priority_queue< scored_example, vector< scored_example >, compare_scored_examples > & pr_queue)
Definition at line 30 of file topk.cc.
References print_tag().
Referenced by finish_example().
 {
   if (f >= 0)
   {
     char temp[30];
     std::stringstream ss;
     scored_example tmp_example;
     while (!pr_queue.empty())
     {
       tmp_example = pr_queue.top();
       pr_queue.pop();
       sprintf(temp, "%f", tmp_example.first);
       ss << temp;
       ss << ' ';
       print_tag(ss, tmp_example.second);
       ss << ' ';
       ss << '\n';
     }
     ss << '\n';
     ssize_t len = ss.str().size();
 #ifdef _WIN32
     ssize_t t = _write(f, ss.str().c_str(), (unsigned int)len);
 #else
     ssize_t t = write(f, ss.str().c_str(), (unsigned int)len);
 #endif
     if (t != len)
       cerr << "write error: " << strerror(errno) << endl;
   }
 }
topk_setup()
LEARNER::base_learner* topk_setup (options_i & options, vw & all)
Definition at line 104 of file topk.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), finish(), finish_example(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<topk>();
   option_group_definition new_options("Top K");
   new_options.add(make_option("top", data->K).keep().help("top k recommendation"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("top"))
     return nullptr;
   data->all = &all;
   LEARNER::learner<topk, multi_ex>& l =
       init_learner(data, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>);
   l.set_finish_example(finish_example);
   l.set_finish(finish);
   return make_base(l);
 }