Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/unique_sort.h File Reference
unique_sort.h File Reference
#include "parser.h"
#include "example.h"
Functions
void unique_sort_features (uint64_t parse_mask, example *ae)
void unique_features (features &fs, int max=-1)
Function Documentation
unique_features()
void unique_features (features & fs, int max = -1)
Definition at line 9 of file unique_sort.cc.
References features_value_index_audit_iterator::audit(), features::features_value_index_audit_range::begin(), v_array< T >::empty(), features::features_value_index_audit_range::end(), features_value_index_iterator::index(), features::indicies, min(), features::size(), features::space_names, features::truncate_to(), features_value_iterator::value(), and features::values_indices_audit().
Referenced by feature_limit(), and unique_sort_features().
 {
   if (fs.indicies.empty())
     return;
   features::features_value_index_audit_range range = fs.values_indices_audit();
   features::iterator_all last_index = range.begin();
   features::iterator_all end = max > 0 ? range.begin() + min(fs.size(), (size_t)max) : range.end();
   for (features::iterator_all i = ++range.begin(); i != end; ++i)
     if (i.index() != last_index.index())
       if (i != ++last_index)
       {
         last_index.value() = i.value();
         last_index.index() = i.index();
         if (!fs.space_names.empty())
           last_index.audit() = i.audit();
       }
   ++last_index;
   fs.truncate_to(last_index);
 }
unique_sort_features()
void unique_sort_features (uint64_t parse_mask, example * ae)
Definition at line 32 of file unique_sort.cc.
References unique_features().
Referenced by VW::setup_example().
 {
   for (features& fs : *ae)
     if (fs.sort(parse_mask))
       unique_features(fs);
   ae->sorted = true;
 }