Vowpal Wabbit: /mnt/c/w/repos/vowpal_wabbit_jackgerrits/vowpalwabbit/v_array.h File Reference
v_array.h File Reference
#include <iostream>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <stdint.h>
#include "vw_exception.h"
#include "memory.h"
Classes
struct v_array< T >
Macros
#define __INLINE inline
Typedefs
typedef v_array< unsigned char > v_string
Functions
size_t max (size_t a, size_t b)
size_t min (size_t a, size_t b)
template<class T >
v_array< T > v_init ()
template<class T >
void copy_array (v_array< T > &dst, const v_array< T > &src)
template<class T >
void copy_array_no_memcpy (v_array< T > &dst, const v_array< T > &src)
template<class T >
void copy_array (v_array< T > &dst, const v_array< T > &src, T(*copy_item)(T &))
template<class T >
void push_many (v_array< T > &v, const T *_begin, size_t num)
template<class T >
void calloc_reserve (v_array< T > &v, size_t length)
template<class T >
v_array< T > pop (v_array< v_array< T > > &stack)
template<class T >
bool v_array_contains (v_array< T > &A, T x)
template<class T >
std::ostream & operator<< (std::ostream &os, const v_array< T > &v)
template<class T , class U >
std::ostream & operator<< (std::ostream &os, const v_array< std::pair< T, U > > &v)
v_string string2v_string (const std::string &s)
std::string v_string2string (const v_string &v_s)
Variables
const size_t erase_point = ~((1 << 10) - 1)
Macro Definition Documentation
__INLINE
#define __INLINE inline
Definition at line 17 of file v_array.h.
Typedef Documentation
v_string
typedef v_array<unsigned char> v_string
Definition at line 271 of file v_array.h.
Function Documentation
calloc_reserve()
template<class T > void calloc_reserve (v_array< T > & v, size_t length)
Definition at line 228 of file v_array.h.
References v_array< T >::_begin, v_array< T >::_end, and v_array< T >::end_array.
Referenced by mwt_setup().
 {
   v._begin = calloc_or_throw<T>(length);
   v._end = v._begin;
   v.end_array = v._begin + length;
 }
copy_array() [1/2]
template<class T > void copy_array (v_array< T > & dst, const v_array< T > & src)
Definition at line 197 of file v_array.h.
References v_array< T >::_begin, v_array< T >::clear(), push_many(), and v_array< T >::size().
Referenced by memory_tree_ns::copy_example_data(), VW::copy_example_data(), VW::copy_example_metadata(), MULTILABEL::copy_label(), CB::copy_label(), COST_SENSITIVE::copy_label(), CCB::copy_label(), features::deep_copy_from(), learn(), predict(), SelectiveBranchingMT::run(), and CCB::save_action_scores().
 {
   dst.clear();
   push_many(dst, src._begin, src.size());
 }
copy_array() [2/2]
template<class T > void copy_array (v_array< T > & dst, const v_array< T > & src, T(*)(T &) copy_item)
Definition at line 212 of file v_array.h.
References v_array< T >::_begin, v_array< T >::_end, v_array< T >::clear(), and v_array< T >::push_back().
 {
   dst.clear();
   for (T* item = src._begin; item != src._end; ++item) dst.push_back(copy_item(*item));
 }
copy_array_no_memcpy()
template<class T > void copy_array_no_memcpy (v_array< T > & dst, const v_array< T > & src)
Definition at line 205 of file v_array.h.
References v_array< T >::_begin, v_array< T >::_end, v_array< T >::clear(), and v_array< T >::push_back().
Referenced by features::deep_copy_from().
 {
   dst.clear();
   for (T* item = src._begin; item != src._end; ++item) dst.push_back(*item);
 }
max()
size_t max (size_t a, size_t b) inline
Definition at line 175 of file v_array.h.
References a.
Referenced by Search::add_example_conditioning(), Beam::beam< T >::compact(), recall_tree_ns::compute_recall_lbest(), enable_sources(), find_cost_range(), GEN_CS::gen_cs_example_dr(), GEN_CS::gen_cs_example_ips(), GEN_CS::gen_cs_label(), get_active_coin_bias(), CB_EXPLORE_ADF::get_cost_ranges(), Search::hoopla_permute(), Beam::beam< T >::insert(), learn(), CB_ADF::learn_MTR(), lrq_setup(), max_elem(), Beam::beam< T >::pop_best_item(), Search::predictor::predict(), predict_or_learn(), CB_EXPLORE::predict_or_learn_cover(), CB_EXPLORE_ADF::predict_or_learn_cover(), push_many(), AllReduceSockets::reduce(), ArgmaxTask::run(), set_mm(), memory_tree_ns::split_leaf(), and recall_tree_ns::to_prob().
 {
   if (a < b)
     return b;
   else
     return a;
 }
min()
size_t min (size_t a, size_t b) inline
Definition at line 182 of file v_array.h.
References a.
Referenced by CB_EXPLORE_ADF::binary_search(), binarySearch(), AllReduceSockets::broadcast(), Search::choose_oracle_action(), compute_coherence_metrics(), EXPLORE_EVAL::do_actual_learning(), DepParserTask::extract_features(), find_cost_range(), GEN_CS::gen_cs_example_dm(), exploration::generate_softmax(), get_active_coin_bias(), CB_EXPLORE_ADF::get_cost_ranges(), CB_EXPLORE::get_cover_probabilities(), get_top_weights(), lda_setup(), min_elem(), min_left_right(), COST_SENSITIVE::output_example(), AllReduceSockets::pass_down(), AllReduceSockets::pass_up(), predict_or_learn(), CB_EXPLORE::predict_or_learn_cover(), CB_EXPLORE_ADF::predict_or_learn_cover(), memory_io_buf::read_file(), recall_tree_setup(), AllReduceSockets::reduce(), SelectiveBranchingMT::run(), GraphTask::run(), save_load_header(), set_mm(), recall_tree_ns::to_prob(), unique_features(), and VW::version_struct::version_struct().
 {
   if (a < b)
     return a;
   else
     return b;
 }
operator<<() [1/2]
template<class T > std::ostream& operator<< (std::ostream & os, const v_array< T > & v)
Definition at line 254 of file v_array.h.
 {
   os << '[';
   for (T* i = v._begin; i != v._end; ++i) os << ' ' << *i;
   os << " ]";
   return os;
 }
operator<<() [2/2]
template<class T , class U > std::ostream& operator<< (std::ostream & os, const v_array< std::pair< T, U > > & v)
Definition at line 263 of file v_array.h.
 {
   os << '[';
   for (std::pair<T, U>* i = v._begin; i != v._end; ++i) os << ' ' << i->first << ':' << i->second;
   os << " ]";
   return os;
 }
pop()
template<class T > v_array<T> pop (v_array< v_array< T > > & stack)
Definition at line 236 of file v_array.h.
 {
   if (stack._end != stack._begin)
     return *(--stack._end);
   else
     return v_array<T>();
 }
push_many()
template<class T > void push_many (v_array< T > & v, const T * _begin, size_t num)
Definition at line 219 of file v_array.h.
References v_array< T >::_begin, v_array< T >::_end, v_array< T >::end_array, max(), and v_array< T >::resize().
Referenced by copy_array(), make_write_cache(), TC_parser< audit >::maybeFeature(), TC_parser< audit >::nameSpaceInfo(), TagState< audit >::String(), string2v_string(), and substring_to_example().
 {
   if (v._end + num >= v.end_array)
     v.resize(max(2 * (size_t)(v.end_array - v._begin) + 3, v._end - v._begin + num));
   memcpy(v._end, _begin, num * sizeof(T));
   v._end += num;
 }
string2v_string()
v_string string2v_string (const std::string & s) inline
Definition at line 273 of file v_array.h.
References push_many(), and v_array< T >::size().
 {
   v_string res = v_init<unsigned char>();
   if (!s.empty())
     push_many(res, (unsigned char*)s.data(), s.size());
   return res;
 }
v_array_contains()
template<class T > bool v_array_contains (v_array< T > & A, T x)
Definition at line 245 of file v_array.h.
References v_array< T >::_begin, and v_array< T >::_end.
Referenced by memory_tree_ns::collect_labels_from_leaf(), Search::get_training_timesteps(), Search::single_prediction_notLDF(), and memory_tree_ns::train_one_against_some_at_leaf().
 {
   for (T* e = A._begin; e != A._end; ++e)
     if (*e == x)
       return true;
   return false;
 }
v_init()
template<class T > v_array<T> v_init () inline
Definition at line 191 of file v_array.h.
 {
   return {nullptr, nullptr, nullptr, 0};
 }
v_string2string()
std::string v_string2string (const v_string & v_s) inline
Definition at line 281 of file v_array.h.
References v_array< T >::_begin, and v_array< T >::_end.
 {
   std::string res;
   for (unsigned char* i = v_s._begin; i != v_s._end; ++i) res.push_back(*i);
   return res;
 }
Variable Documentation
erase_point
const size_t erase_point = ~((1 << 10) - 1)
Definition at line 23 of file v_array.h.
Referenced by v_array< uint64_t >::clear().