Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/active_cover.h File Reference
active_cover.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * active_cover_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* active_cover_setup (VW::config::options_i & options, vw & all)
Definition at line 234 of file active_cover.cc.
References add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), f, vw::get_random_state(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<active_cover>();
   option_group_definition new_options("Active Learning with Cover");
   bool active_cover_option = false;
   new_options.add(make_option("active_cover", active_cover_option).keep().help("enable active learning with cover"))
       .add(make_option("mellowness", data->active_c0)
                .default_value(8.f)
                .help("active learning mellowness parameter c_0. Default 8."))
       .add(make_option("alpha", data->alpha)
                .default_value(1.f)
                .help("active learning variance upper bound parameter alpha. Default 1."))
       .add(make_option("beta_scale", data->beta_scale)
                .default_value(sqrtf(10.f))
                .help("active learning variance upper bound parameter beta_scale. Default std::sqrt(10)."))
       .add(make_option("cover", data->cover_size).keep().default_value(12).help("cover size. Default 12."))
       .add(make_option("oracular", data->oracular).help("Use Oracular-CAL style query or not. Default false."));
   options.add_and_parse(new_options);
   if (!active_cover_option)
     return nullptr;
   data->all = &all;
   data->_random_state = all.get_random_state();
   data->beta_scale *= data->beta_scale;
   if (data->oracular)
     data->cover_size = 0;
   if (options.was_supplied("lda"))
     THROW("error: you can't combine lda and active learning");
   if (options.was_supplied("active"))
     THROW("error: you can't use --active_cover and --active at the same time");
   auto base = as_singleline(setup_base(options, all));
   data->lambda_n = new float[data->cover_size];
   data->lambda_d = new float[data->cover_size];
   for (size_t i = 0; i < data->cover_size; i++)
   {
     data->lambda_n[i] = 0.f;
     data->lambda_d[i] = 1.f / 8.f;
   }
   // Create new learner
   learner<active_cover, example>& l = init_learner(
       data, base, predict_or_learn_active_cover<true>, predict_or_learn_active_cover<false>, data->cover_size + 1);
   return make_base(l);
 }