Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/audit_regressor.h File Reference
audit_regressor.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * audit_regressor_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* audit_regressor_setup (VW::config::options_i & options, vw & all)
Definition at line 244 of file audit_regressor.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), vw::audit, audit_regressor(), end_examples(), VW::finish(), VW::finish_example(), init_driver(), LEARNER::init_learner(), VW::config::make_option(), vw::numpasses, LEARNER::learner< T, E >::set_end_examples(), LEARNER::learner< T, E >::set_finish(), LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_init_driver(), setup_base(), vw::stdin_off, THROW, VW::config::options_i::was_supplied(), and io_buf::WRITE.
Referenced by parse_reductions().
 {
   std::string out_file;
   option_group_definition new_options("Audit Regressor");
   new_options.add(make_option("audit_regressor", out_file)
                       .keep()
                       .help("stores feature names and their regressor values. Same dataset must be used for both "
                             "regressor training and this mode."));
   options.add_and_parse(new_options);
   if (!options.was_supplied("audit_regressor"))
     return nullptr;
   if (out_file.empty())
     THROW("audit_regressor argument (output filename) is missing.");
   if (all.numpasses > 1)
     THROW("audit_regressor can't be used with --passes > 1.");
   all.audit = true;
   auto dat = scoped_calloc_or_throw<audit_regressor_data>();
   dat->all = &all;
   dat->ns_pre = new std::vector<std::string>();  // explicitly invoking std::vector's constructor
   dat->out_file = new io_buf();
   dat->out_file->open_file(out_file.c_str(), all.stdin_off, io_buf::WRITE);
   LEARNER::learner<audit_regressor_data, example>& ret =
       LEARNER::init_learner(dat, as_singleline(setup_base(options, all)), audit_regressor, audit_regressor, 1);
   ret.set_end_examples(end_examples);
   ret.set_finish_example(finish_example);
   ret.set_finish(finish);
   ret.set_init_driver(init_driver);
   return LEARNER::make_base<audit_regressor_data>(ret);
 }