Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/baseline.h File Reference
baseline.h File Reference
#include "reductions_fwd.h"
Namespaces
BASELINE
Functions
LEARNER::base_learner * baseline_setup (VW::config::options_i &options, vw &all)
void BASELINE::set_baseline_enabled (example *ec)
void BASELINE::reset_baseline_disabled (example *ec)
bool BASELINE::baseline_enabled (example *ec)
Function Documentation
LEARNER::base_learner* baseline_setup (VW::config::options_i & options, vw & all)
Definition at line 192 of file baseline.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), VW::alloc_examples(), LEARNER::as_singleline(), loss_function::getType(), LEARNER::init_learner(), vw::interactions, label_parser::label_size, vw::loss, LEARNER::make_base(), VW::config::make_option(), sensitivity(), LEARNER::learner< T, E >::set_sensitivity(), setup_base(), and simple_label.
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<baseline>();
   bool baseline_option = false;
   std::string loss_function;
   option_group_definition new_options("Baseline options");
   new_options
       .add(make_option("baseline", baseline_option)
                .keep()
                .help("Learn an additive baseline (from constant features) and a residual separately in regression."))
       .add(make_option("lr_multiplier", data->lr_multiplier).help("learning rate multiplier for baseline model"))
       .add(make_option("global_only", data->global_only)
                .keep()
                .help("use separate example with only global constant for baseline predictions"))
       .add(make_option("check_enabled", data->check_enabled)
                .keep()
                .help("only use baseline when the example contains enabled flag"));
   options.add_and_parse(new_options);
   if (!baseline_option)
     return nullptr;
   // initialize baseline example
   data->ec = VW::alloc_examples(simple_label.label_size, 1);
   data->ec->interactions = &all.interactions;
   data->all = &all;
   auto loss_function_type = all.loss->getType();
   if (loss_function_type != "logistic")
     data->lr_scaling = true;
   auto base = as_singleline(setup_base(options, all));
   learner<baseline, example>& l = init_learner(data, base, predict_or_learn<true>, predict_or_learn<false>);
   l.set_sensitivity(sensitivity);
   return make_base(l);
 }