Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/best_constant.h File Reference
best_constant.h File Reference
#include <cfloat>
#include "vw.h"
Functions
void count_label (shared_data *sd, float l)
bool get_best_constant (vw &all, float &best_constant, float &best_constant_loss)
Function Documentation
void count_label (shared_data * sd, float l) inline
Definition at line 9 of file best_constant.h.
References shared_data::first_observed_label, get_best_constant(), shared_data::is_more_than_two_labels_observed, and shared_data::second_observed_label.
Referenced by bufread_simple_label(), LabelObjectState< audit >::EndObject(), and parse_simple_label().
 {
   if (sd->is_more_than_two_labels_observed || l == FLT_MAX)
     return;
   if (sd->first_observed_label != FLT_MAX)
   {
     if (sd->first_observed_label != l)
     {
       if (sd->second_observed_label != FLT_MAX)
       {
         if (sd->second_observed_label != l)
           sd->is_more_than_two_labels_observed = true;
       }
       else
         sd->second_observed_label = l;
     }
   }
   else
     sd->first_observed_label = l;
 }
bool get_best_constant (vw & all, float & best_constant, float & best_constant_loss)
Definition at line 7 of file best_constant.cc.
References shared_data::first_observed_label, VW::config::options_i::get_typed_option(), loss_function::getLoss(), loss_function::getType(), shared_data::is_more_than_two_labels_observed, vw::loss, vw::options, vw::sd, shared_data::second_observed_label, VW::config::options_i::was_supplied(), shared_data::weighted_labeled_examples, and shared_data::weighted_labels.
Referenced by count_label(), and VW::finish().
 {
   if (all.sd->first_observed_label == FLT_MAX ||  // no non-test labels observed or function was never called
       (all.loss == nullptr) || (all.sd == nullptr))
     return false;
   float label1 = all.sd->first_observed_label;  // observed labels might be inside [sd->Min_label, sd->Max_label], so
                                                 // can't use Min/Max
   float label2 = (all.sd->second_observed_label == FLT_MAX)
       ? 0
       : all.sd->second_observed_label;  // if only one label observed, second might be 0
   if (label1 > label2)
   {
     float tmp = label1;
     label1 = label2;
     label2 = tmp;
   }  // as don't use min/max - make sure label1 < label2
   float label1_cnt;
   float label2_cnt;
   if (label1 != label2)
   {
     label1_cnt = (float)(all.sd->weighted_labels - label2 * all.sd->weighted_labeled_examples) / (label1 - label2);
     label2_cnt = (float)all.sd->weighted_labeled_examples - label1_cnt;
   }
   else
     return false;
   if ((label1_cnt + label2_cnt) <= 0.)
     return false;
   auto funcName = all.loss->getType();
   if (funcName.compare("squared") == 0 || funcName.compare("Huber") == 0 || funcName.compare("classic") == 0)
     best_constant = (float)all.sd->weighted_labels / (float)(all.sd->weighted_labeled_examples);
   else if (all.sd->is_more_than_two_labels_observed)
   {
     // loss functions below don't have generic formuas for constant yet.
     return false;
   }
   else if (funcName.compare("hinge") == 0)
   {
     best_constant = label2_cnt <= label1_cnt ? -1.f : 1.f;
   }
   else if (funcName.compare("logistic") == 0)
   {
     label1 = -1.;  // override {-50, 50} to get proper loss
     label2 = 1.;
     if (label1_cnt <= 0)
       best_constant = 1.;
     else if (label2_cnt <= 0)
       best_constant = -1.;
     else
       best_constant = log(label2_cnt / label1_cnt);
   }
   else if (funcName.compare("quantile") == 0 || funcName.compare("pinball") == 0 || funcName.compare("absolute") == 0)
   {
     float tau = 0.5;
     if (all.options->was_supplied("quantile_tau"))
       tau = all.options->get_typed_option<float>("quantile_tau").value();
     float q = tau * (label1_cnt + label2_cnt);
     if (q < label2_cnt)
       best_constant = label2;
     else
       best_constant = label1;
   }
   else
     return false;
   if (!all.sd->is_more_than_two_labels_observed)
   {
     best_constant_loss = (label1_cnt > 0) ? all.loss->getLoss(all.sd, best_constant, label1) * label1_cnt : 0.0f;
     best_constant_loss += (label2_cnt > 0) ? all.loss->getLoss(all.sd, best_constant, label2) * label2_cnt : 0.0f;
     best_constant_loss /= label1_cnt + label2_cnt;
   }
   else
     best_constant_loss = FLT_MIN;
   return true;
 }