Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/bfgs.h File Reference
bfgs.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * bfgs_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* bfgs_setup (VW::config::options_i & options, vw & all)
Definition at line 1091 of file bfgs.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), vw::audit, vw::bfgs, LEARNER::end_pass(), VW::config::options_i::get_typed_option(), vw::hash_inv, vw::hessian_on, shared_data::holdout_best_loss, vw::holdout_set_off, init_driver(), LEARNER::init_learner(), vw::logger, LEARNER::make_base(), VW::config::make_option(), vw::numpasses, vw_logger::quiet, save_load(), vw::sd, parameters::stride(), parameters::stride_shift(), THROW, vw::training, and vw::weights.
Referenced by parse_reductions().
 {
   auto b = scoped_calloc_or_throw<bfgs>();
   bool conjugate_gradient = false;
   bool bfgs_option = false;
   option_group_definition bfgs_outer_options("LBFGS and Conjugate Gradient options");
   bfgs_outer_options.add(
       make_option("conjugate_gradient", conjugate_gradient).keep().help("use conjugate gradient based optimization"));
   option_group_definition bfgs_inner_options("LBFGS and Conjugate Gradient options");
   bfgs_inner_options.add(make_option("bfgs", bfgs_option).keep().help("use conjugate gradient based optimization"));
   bfgs_inner_options.add(make_option("hessian_on", all.hessian_on).help("use second derivative in line search"));
   bfgs_inner_options.add(make_option("mem", b->m).default_value(15).help("memory in bfgs"));
   bfgs_inner_options.add(
       make_option("termination", b->rel_threshold).default_value(0.001f).help("Termination threshold"));
   options.add_and_parse(bfgs_outer_options);
   if (!conjugate_gradient)
   {
     options.add_and_parse(bfgs_inner_options);
     if (!bfgs_option)
     {
       return nullptr;
     }
   }
   b->all = &all;
   b->wolfe1_bound = 0.01;
   b->first_hessian_on = true;
   b->first_pass = true;
   b->gradient_pass = true;
   b->preconditioner_pass = true;
   b->backstep_on = false;
   b->final_pass = all.numpasses;
   b->no_win_counter = 0;
   if (!all.holdout_set_off)
   {
     all.sd->holdout_best_loss = FLT_MAX;
     b->early_stop_thres = options.get_typed_option<size_t>("early_terminate").value();
   }
   if (b->m == 0)
     all.hessian_on = true;
   if (!all.logger.quiet)
   {
     if (b->m > 0)
       b->all->trace_message << "enabling BFGS based optimization ";
     else
       b->all->trace_message << "enabling conjugate gradient optimization via BFGS ";
     if (all.hessian_on)
       b->all->trace_message << "with curvature calculation" << std::endl;
     else
       b->all->trace_message << "**without** curvature calculation" << std::endl;
   }
   if (all.numpasses < 2 && all.training)
     THROW("you must make at least 2 passes to use BFGS");
   all.bfgs = true;
   all.weights.stride_shift(2);
   void (*learn_ptr)(bfgs&, base_learner&, example&) = nullptr;
   if (all.audit)
     learn_ptr = learn<true>;
   else
     learn_ptr = learn<false>;
   learner<bfgs, example>* l;
   if (all.audit || all.hash_inv)
     l = &init_learner(b, learn_ptr, predict<true>, all.weights.stride());
   else
     l = &init_learner(b, learn_ptr, predict<false>, all.weights.stride());
   l->set_save_load(save_load);
   l->set_init_driver(init_driver);
   l->set_end_pass(end_pass);
   return make_base(*l);
 }