Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/boosting.h File Reference
boosting.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * boosting_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* boosting_setup (VW::config::options_i & options, vw & all)
Definition at line 394 of file boosting.cc.
References add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), f, vw::get_random_state(), vw::logger, LEARNER::make_base(), VW::config::make_option(), vw_logger::quiet, return_example(), save_load(), save_load_sampling(), LEARNER::learner< T, E >::set_save_load(), setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   free_ptr<boosting> data = scoped_calloc_or_throw<boosting>();
   option_group_definition new_options("Boosting");
   new_options.add(make_option("boosting", data->N).keep().help("Online boosting with <N> weak learners"))
       .add(make_option("gamma", data->gamma)
                .default_value(0.1f)
                .help("weak learner's edge (=0.1), used only by online BBM"))
       .add(
           make_option("alg", data->alg)
               .keep()
               .default_value("BBM")
               .help("specify the boosting algorithm: BBM (default), logistic (AdaBoost.OL.W), adaptive (AdaBoost.OL)"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("boosting"))
     return nullptr;
   // Description of options:
   // "BBM" implements online BBM (Algorithm 1 in BLK'15)
   // "logistic" implements AdaBoost.OL.W (importance weighted version
   //        of Algorithm 2 in BLK'15)
   // "adaptive" implements AdaBoost.OL (Algorithm 2 in BLK'15,
   //        using sampling rather than importance weighting)
   if (!all.logger.quiet)
     cerr << "Number of weak learners = " << data->N << endl;
   if (!all.logger.quiet)
     cerr << "Gamma = " << data->gamma << endl;
   data->C = std::vector<std::vector<int64_t> >(data->N, std::vector<int64_t>(data->N, -1));
   data->t = 0;
   data->all = &all;
   data->_random_state = all.get_random_state();
   data->alpha = std::vector<float>(data->N, 0);
   data->v = std::vector<float>(data->N, 1);
   learner<boosting, example>* l;
   if (data->alg == "BBM")
     l = &init_learner<boosting, example>(
         data, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>, data->N);
   else if (data->alg == "logistic")
   {
     l = &init_learner<boosting, example>(data, as_singleline(setup_base(options, all)), predict_or_learn_logistic<true>,
         predict_or_learn_logistic<false>, data->N);
     l->set_save_load(save_load);
   }
   else if (data->alg == "adaptive")
   {
     l = &init_learner<boosting, example>(data, as_singleline(setup_base(options, all)), predict_or_learn_adaptive<true>,
         predict_or_learn_adaptive<false>, data->N);
     l->set_save_load(save_load_sampling);
   }
   else
     THROW("Unrecognized boosting algorithm: \'" << data->alg << "\' Bailing!");
   l->set_finish_example(return_example);
   return make_base(*l);
 }