Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/bs.h File Reference
bs.h File Reference
#include <memory>
#include "reductions_fwd.h"
Namespaces
BS
Macros
#define BS_TYPE_MEAN 0
#define BS_TYPE_VOTE 1
Functions
LEARNER::base_learner * bs_setup (VW::config::options_i &options, vw &all)
uint32_t BS::weight_gen (std::shared_ptr< rand_state > &state)
Macro Definition Documentation
#define BS_TYPE_MEAN 0
Definition at line 8 of file bs.h.
Referenced by bs_setup(), and predict_or_learn().
#define BS_TYPE_VOTE 1
Definition at line 9 of file bs.h.
Referenced by bs_setup(), and predict_or_learn().
Function Documentation
LEARNER::base_learner* bs_setup (VW::config::options_i & options, vw & all)
Definition at line 229 of file bs.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), BS_TYPE_MEAN, BS_TYPE_VOTE, finish_example(), vw::get_random_state(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<bs>();
   std::string type_string("mean");
   option_group_definition new_options("Bootstrap");
   new_options.add(make_option("bootstrap", data->B).keep().help("k-way bootstrap by online importance resampling"))
       .add(make_option("bs_type", type_string).keep().help("prediction type {mean,vote}"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("bootstrap"))
     return nullptr;
   data->ub = FLT_MAX;
   data->lb = -FLT_MAX;
   if (options.was_supplied("bs_type"))
   {
     if (type_string == "mean")
       data->bs_type = BS_TYPE_MEAN;
     else if (type_string == "vote")
       data->bs_type = BS_TYPE_VOTE;
     else
     {
       std::cerr << "warning: bs_type must be in {'mean','vote'}; resetting to mean." << std::endl;
       data->bs_type = BS_TYPE_MEAN;
     }
   }
   else  // by default use mean
     data->bs_type = BS_TYPE_MEAN;
   data->pred_vec = new std::vector<double>();
   data->pred_vec->reserve(data->B);
   data->all = &all;
   data->_random_state = all.get_random_state();
   learner<bs, example>& l = init_learner(
       data, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>, data->B);
   l.set_finish_example(finish_example);
   return make_base(l);
 }