Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cb_dro.cc File Reference
cb_dro.cc File Reference
#include "reductions.h"
#include "cb_dro.h"
#include "distributionally_robust.h"
#include "explore.h"
#include "rand48.h"
Classes
struct VW::cb_dro_data
Namespaces
VW
Functions
template<bool is_learn, bool is_explore>
void learn_or_predict (cb_dro_data &data, multi_learner &base, multi_ex &examples)
base_learner * cb_dro_setup (options_i &options, vw &all)
Function Documentation
base_learner* cb_dro_setup (options_i & options, vw & all)
Definition at line 96 of file cb_dro.cc.
References action_probs, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), LEARNER::init_learner(), vw::logger, LEARNER::make_base(), VW::config::make_option(), vw_logger::quiet, setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   double alpha;
   double tau;
   double wmax;
   bool cb_dro_option = false;
   option_group_definition new_options("CB Distributionally Robust Optimization");
   new_options.add(make_option("cb_dro", cb_dro_option).keep().help("Use DRO for cb learning"))
       .add(make_option("cb_dro_alpha", alpha).default_value(0.05).keep().help("Confidence level for cb dro"))
       .add(make_option("cb_dro_tau", tau).default_value(0.999).keep().help("Time constant for count decay for cb dro"))
       .add(make_option("cb_dro_wmax", wmax).default_value(std::numeric_limits<double>::infinity()).keep().help("maximum importance weight for cb_dro"));
   options.add_and_parse(new_options);
   if (!cb_dro_option)
     return nullptr;
   if (options.was_supplied("no_predict"))
   {
     THROW("cb_dro cannot be used with no_predict");
   }
   if (!options.was_supplied("cb_adf") && !options.was_supplied("cb_explore_adf"))
   {
     THROW("cb_dro requires cb_adf or cb_explore_adf");
   }
   if (alpha <= 0 || alpha >= 1)
   {
     THROW("cb_dro_alpha must be in (0, 1)");
   }
   if (tau <= 0 || tau > 1)
   {
     THROW("cb_dro_tau must be in (0, 1]");
   }
   if (wmax <= 1)
   {
     THROW("cb_dro_wmax must exceed 1");
   }
   if (!all.logger.quiet)
   {
     std::cerr << "Using DRO for CB learning" << std::endl;
     std::cerr << "cb_dro_alpha = " << alpha << std::endl;
     std::cerr << "cb_dro_tau = " << tau << std::endl;
     std::cerr << "cb_dro_wmax = " << wmax << std::endl;
   }
   auto data = scoped_calloc_or_throw<cb_dro_data>(alpha, tau, wmax);
   if (!data->isValid())
   {
     THROW("invalid cb_dro parameter values supplied");
   }
   if (options.was_supplied("cb_explore_adf"))
   {
     return make_base(init_learner(data, as_multiline(setup_base(options, all)), learn_or_predict<true, true>, learn_or_predict<false, true>, 1 /* weights */, prediction_type_t::action_probs));
   }
   else
   {
     return make_base(init_learner(data, as_multiline(setup_base(options, all)), learn_or_predict<true, false>, learn_or_predict<false, false>, 1 /* weights */, prediction_type_t::action_probs));
   }
 }
template<bool is_learn, bool is_explore> void learn_or_predict (cb_dro_data & data, multi_learner & base, multi_ex & examples)
Definition at line 91 of file cb_dro.cc.
References VW::cb_dro_data::learn_or_predict().
 {
   data.learn_or_predict<is_learn, is_explore>(base, examples);
 }