Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cbify.h File Reference
cbify.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * cbify_setup (VW::config::options_i &options, vw &all)
LEARNER::base_learner * cbifyldf_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* cbify_setup (VW::config::options_i & options, vw & all)
Definition at line 387 of file cbify.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), LEARNER::as_singleline(), vw::delete_prediction, f, init_adf_data(), LEARNER::init_cost_sensitive_learner(), LEARNER::init_multiclass_learner(), VW::config::options_i::insert(), LEARNER::make_base(), VW::config::make_option(), vw::p, setup_base(), to_string(), uniform_hash(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   uint32_t num_actions = 0;
   auto data = scoped_calloc_or_throw<cbify>();
   bool use_cs;
   option_group_definition new_options("Make Multiclass into Contextual Bandit");
   new_options
       .add(make_option("cbify", num_actions)
                .keep()
                .help("Convert multiclass on <k> classes into a contextual bandit problem"))
       .add(make_option("cbify_cs", use_cs).help("consume cost-sensitive classification examples instead of multiclass"))
       .add(make_option("loss0", data->loss0).default_value(0.f).help("loss for correct label"))
       .add(make_option("loss1", data->loss1).default_value(1.f).help("loss for incorrect label"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("cbify"))
     return nullptr;
   data->use_adf = options.was_supplied("cb_explore_adf");
   data->app_seed = uniform_hash("vw", 2, 0);
   data->a_s = v_init<action_score>();
   data->all = &all;
   if (data->use_adf)
     init_adf_data(*data, num_actions);
   if (!options.was_supplied("cb_explore") && !data->use_adf)
   {
     std::stringstream ss;
     ss << num_actions;
     options.insert("cb_explore", ss.str());
   }
   if (data->use_adf)
   {
     options.insert("cb_min_cost", std::to_string(data->loss0));
     options.insert("cb_max_cost", std::to_string(data->loss1));
   }
   if (options.was_supplied("baseline"))
   {
     std::stringstream ss;
     ss << std::max(std::abs(data->loss0), std::abs(data->loss1)) / (data->loss1 - data->loss0);
     options.insert("lr_multiplier", ss.str());
   }
   learner<cbify, example>* l;
   if (data->use_adf)
   {
     multi_learner* base = as_multiline(setup_base(options, all));
     if (use_cs)
       l = &init_cost_sensitive_learner(
           data, base, predict_or_learn_adf<true, true>, predict_or_learn_adf<false, true>, all.p, 1);
     else
       l = &init_multiclass_learner(
           data, base, predict_or_learn_adf<true, false>, predict_or_learn_adf<false, false>, all.p, 1);
   }
   else
   {
     single_learner* base = as_singleline(setup_base(options, all));
     if (use_cs)
       l = &init_cost_sensitive_learner(
           data, base, predict_or_learn<true, true>, predict_or_learn<false, true>, all.p, 1);
     else
       l = &init_multiclass_learner(data, base, predict_or_learn<true, false>, predict_or_learn<false, false>, all.p, 1);
   }
   all.delete_prediction = nullptr;
   return make_base(*l);
 }
LEARNER::base_learner* cbifyldf_setup (VW::config::options_i & options, vw & all)
Definition at line 460 of file cbify.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), COST_SENSITIVE::cs_label, vw::delete_prediction, f, finish_multiline_example(), LEARNER::init_learner(), VW::config::options_i::insert(), parser::lp, LEARNER::make_base(), VW::config::make_option(), multiclass, vw::p, LEARNER::learner< T, E >::set_finish_example(), setup_base(), to_string(), uniform_hash(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<cbify>();
   bool cbify_ldf_option = false;
   option_group_definition new_options("Make csoaa_ldf into Contextual Bandit");
   new_options
       .add(make_option("cbify_ldf", cbify_ldf_option).keep().help("Convert csoaa_ldf into a contextual bandit problem"))
       .add(make_option("loss0", data->loss0).default_value(0.f).help("loss for correct label"))
       .add(make_option("loss1", data->loss1).default_value(1.f).help("loss for incorrect label"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("cbify_ldf"))
     return nullptr;
   data->app_seed = uniform_hash("vw", 2, 0);
   data->all = &all;
   data->use_adf = true;
   if (!options.was_supplied("cb_explore_adf"))
   {
     options.insert("cb_explore_adf", "");
   }
   options.insert("cb_min_cost", std::to_string(data->loss0));
   options.insert("cb_max_cost", std::to_string(data->loss1));
   if (options.was_supplied("baseline"))
   {
     std::stringstream ss;
     ss << std::max(std::abs(data->loss0), std::abs(data->loss1)) / (data->loss1 - data->loss0);
     options.insert("lr_multiplier", ss.str());
   }
   multi_learner* base = as_multiline(setup_base(options, all));
   learner<cbify, multi_ex>& l = init_learner(
       data, base, do_actual_learning_ldf<true>, do_actual_learning_ldf<false>, 1, prediction_type_t::multiclass);
   l.set_finish_example(finish_multiline_example);
   all.p->lp = COST_SENSITIVE::cs_label;
   all.delete_prediction = nullptr;
   return make_base(l);
 }