Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/classweight.h File Reference
classweight.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * classweight_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* classweight_setup (VW::config::options_i & options, vw & all)
Definition at line 75 of file classweight.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), vw::logger, LEARNER::make_base(), VW::config::make_option(), multiclass, LEARNER::learner< T, E >::pred_type, vw_logger::quiet, scalar, setup_base(), THROW, vw::trace_message, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   std::vector<std::string> classweight_array;
   auto cweights = scoped_calloc_or_throw<classweights>();
   option_group_definition new_options("importance weight classes");
   new_options.add(make_option("classweight", classweight_array).help("importance weight multiplier for class"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("classweight"))
     return nullptr;
   for (auto& s : classweight_array) cweights->load_string(s);
   if (!all.logger.quiet)
     all.trace_message << "parsed " << cweights->weights.size() << " class weights" << std::endl;
   LEARNER::single_learner* base = as_singleline(setup_base(options, all));
   LEARNER::learner<classweights, example>* ret;
   if (base->pred_type == prediction_type_t::scalar)
     ret = &LEARNER::init_learner<classweights>(cweights, base, predict_or_learn<true, prediction_type_t::scalar>,
         predict_or_learn<false, prediction_type_t::scalar>);
   else if (base->pred_type == prediction_type_t::multiclass)
     ret = &LEARNER::init_learner<classweights>(cweights, base, predict_or_learn<true, prediction_type_t::multiclass>,
         predict_or_learn<false, prediction_type_t::multiclass>);
   else
     THROW("--classweight not implemented for this type of prediction");
   return make_base(*ret);
 }