Vowpal Wabbit: sparse_iterator< T > Class Template Reference
sparse_iterator< T > Class Template Reference
#include <array_parameters.h>
Public Types
typedef std::forward_iterator_tag iterator_category
typedef T value_type
typedef ptrdiff_t difference_type
typedef T * pointer
typedef T & reference
Public Member Functions
sparse_iterator (weight_map::iterator &iter, uint32_t stride)
sparse_iterator & operator= (const sparse_iterator &other)=default
sparse_iterator (const sparse_iterator &other)=default
sparse_iterator & operator= (sparse_iterator &&other)=default
sparse_iterator (sparse_iterator &&other)=default
uint64_t index ()
T & operator* ()
sparse_iterator & operator++ ()
bool operator== (const sparse_iterator &rhs) const
bool operator!= (const sparse_iterator &rhs) const
Private Attributes
weight_map::iterator _iter
uint32_t _stride
Detailed Description
template<typename T>
class sparse_iterator< T >
Definition at line 28 of file array_parameters.h.
Member Typedef Documentation
template<typename T > typedef ptrdiff_t sparse_iterator< T >::difference_type
Definition at line 37 of file array_parameters.h.
template<typename T > typedef std::forward_iterator_tag sparse_iterator< T >::iterator_category
Definition at line 35 of file array_parameters.h.
template<typename T > typedef T* sparse_iterator< T >::pointer
Definition at line 38 of file array_parameters.h.
template<typename T > typedef T& sparse_iterator< T >::reference
Definition at line 39 of file array_parameters.h.
template<typename T > typedef T sparse_iterator< T >::value_type
Definition at line 36 of file array_parameters.h.
Constructor & Destructor Documentation
template<typename T > sparse_iterator< T >::sparse_iterator (weight_map::iterator & iter, uint32_t stride) inline
Definition at line 41 of file array_parameters.h.
References sparse_iterator< T >::operator=().
 : _iter(iter), _stride(stride) {}
template<typename T > sparse_iterator< T >::sparse_iterator (const sparse_iterator< T > & other) default
template<typename T > sparse_iterator< T >::sparse_iterator (sparse_iterator< T > && other) default
Member Function Documentation
template<typename T > uint64_t sparse_iterator< T >::index () inline
Definition at line 48 of file array_parameters.h.
Referenced by sparse_parameters::operator[]().
 { return _iter->first; }
template<typename T > bool sparse_iterator< T >::operator!= (const sparse_iterator< T > & rhs) const inline
Definition at line 59 of file array_parameters.h.
References sparse_iterator< T >::_iter.
 { return _iter != rhs._iter; }
template<typename T > T& sparse_iterator< T >::operator* () inline
Definition at line 50 of file array_parameters.h.
 { return *(_iter->second); }
template<typename T > sparse_iterator& sparse_iterator< T >::operator++ () inline
Definition at line 52 of file array_parameters.h.
   {
     _iter++;
     return *this;
   }
template<typename T > sparse_iterator& sparse_iterator< T >::operator= (const sparse_iterator< T > & other) default
Referenced by sparse_iterator< T >::sparse_iterator().
template<typename T > sparse_iterator& sparse_iterator< T >::operator= (sparse_iterator< T > && other) default
template<typename T > bool sparse_iterator< T >::operator== (const sparse_iterator< T > & rhs) const inline
Definition at line 58 of file array_parameters.h.
References sparse_iterator< T >::_iter.
 { return _iter == rhs._iter; }
Member Data Documentation
template<typename T > weight_map::iterator sparse_iterator< T >::_iter private
Definition at line 31 of file array_parameters.h.
Referenced by sparse_iterator< T >::operator!=(), and sparse_iterator< T >::operator==().
template<typename T > uint32_t sparse_iterator< T >::_stride private
Definition at line 32 of file array_parameters.h.
The documentation for this class was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/array_parameters.h