Vowpal Wabbit: loss_function Class Reference
loss_function Class Reference abstract
#include <loss_functions.h>
Public Member Functions
virtual std::string getType ()=0
virtual float getLoss (shared_data *, float prediction, float label)=0
virtual float getUpdate (float prediction, float label, float update_scale, float pred_per_update)=0
virtual float getUnsafeUpdate (float prediction, float label, float eta_t)=0
virtual float getRevertingWeight (shared_data *, float prediction, float eta_t)=0
virtual float getSquareGrad (float prediction, float label)=0
virtual float first_derivative (shared_data *, float prediction, float label)=0
virtual float second_derivative (shared_data *, float prediction, float label)=0
virtual ~loss_function ()
Detailed Description
Definition at line 11 of file loss_functions.h.
Constructor & Destructor Documentation
virtual loss_function::~loss_function () inline virtual
Definition at line 39 of file loss_functions.h.
References getLossFunction().
 {};
Member Function Documentation
virtual float loss_function::first_derivative (shared_data * , float prediction, float label) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by GD::compute_update(), SVRG::gradient_scalar(), learn(), predict_and_gradient(), predict_or_learn_multi(), update_after_prediction_cb(), update_after_prediction_pistol(), and update_after_prediction_proximal().
virtual float loss_function::getLoss (shared_data * , float prediction, float label) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by bs_predict_mean(), MARGINAL::compute_expert_loss(), GD::compute_update(), get_best_constant(), MARGINAL::make_marginal(), mf_predict(), predict_or_learn(), process_example(), receive_result(), and MARGINAL::update_marginal().
virtual float loss_function::getRevertingWeight (shared_data * , float prediction, float eta_t) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
virtual float loss_function::getSquareGrad (float prediction, float label) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by GD::get_pred_per_update().
virtual std::string loss_function::getType () pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by baseline_setup(), cs_active_setup(), CSOAA::csldf_setup(), get_best_constant(), and oaa_setup().
virtual float loss_function::getUnsafeUpdate (float prediction, float label, float eta_t) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by GD::compute_update().
virtual float loss_function::getUpdate (float prediction, float label, float update_scale, float pred_per_update) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by GD::compute_update(), and mf_train().
virtual float loss_function::second_derivative (shared_data * , float prediction, float label) pure virtual
Implemented in poisson_loss, quantileloss, logloss, hingeloss, classic_squaredloss, and squaredloss.
Referenced by process_example(), and update_preconditioner().
The documentation for this class was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/loss_functions.h