Vowpal Wabbit: TC_parser< audit > Class Template Reference
TC_parser< audit > Class Template Reference
Public Member Functions
~TC_parser ()
void parserWarning (const char *message, VW::string_view var_msg, const char *message2)
VW::string_view stringFeatureValue (VW::string_view sv)
bool isFeatureValueFloat (float &float_feature_value)
VW::string_view read_name ()
void maybeFeature ()
void nameSpaceInfoValue ()
void nameSpaceInfo ()
void listFeatures ()
void nameSpace ()
void listNameSpace ()
TC_parser (VW::string_view line, vw &all, example *ae)
Public Attributes
VW::string_view _line
size_t _read_idx
float _cur_channel_v
bool _new_index
size_t _anon
uint64_t _channel_hash
VW::string_view _base
unsigned char _index
float _v
bool _redefine_some
std::array< unsigned char, NUM_NAMESPACES > * _redefine
parser * _p
example * _ae
std::array< uint64_t, NUM_NAMESPACES > * _affix_features
std::array< bool, NUM_NAMESPACES > * _spelling_features
v_array< char > _spelling
uint32_t _hash_seed
uint64_t _parse_mask
bool _chain_hash
std::array< std::vector< std::shared_ptr< feature_dict > >, NUM_NAMESPACES > * _namespace_dictionaries
Detailed Description
template<bool audit>
class TC_parser< audit >
Definition at line 48 of file parse_example.cc.
Constructor & Destructor Documentation
template<bool audit> TC_parser< audit >::~TC_parser () inline
Definition at line 73 of file parse_example.cc.
 {}
template<bool audit> TC_parser< audit >::TC_parser (VW::string_view line, vw & all, example * ae) inline
Definition at line 459 of file parse_example.cc.
References vw::affix_features, vw::chain_hash, vw::hash_seed, TC_parser< audit >::listNameSpace(), vw::namespace_dictionaries, vw::p, vw::parse_mask, vw::redefine, vw::redefine_some, and vw::spelling_features.
                                                       : _line(line)
   {
     _spelling = v_init<char>();
     if (!_line.empty())
     {
       this->_read_idx = 0;
       this->_p = all.p;
       this->_redefine_some = all.redefine_some;
       this->_redefine = &all.redefine;
       this->_ae = ae;
       this->_affix_features = &all.affix_features;
       this->_spelling_features = &all.spelling_features;
       this->_namespace_dictionaries = &all.namespace_dictionaries;
       this->_hash_seed = all.hash_seed;
       this->_parse_mask = all.parse_mask;
       this->_chain_hash = all.chain_hash;
       listNameSpace();
     }
   }
Member Function Documentation
template<bool audit> bool TC_parser< audit >::isFeatureValueFloat (float & float_feature_value) inline
Definition at line 114 of file parse_example.cc.
References TC_parser< audit >::_read_idx, parseFloat(), and TC_parser< audit >::parserWarning().
Referenced by TC_parser< audit >::maybeFeature().
   {
     if (_read_idx >= _line.size() || _line[_read_idx] == ' ' || _line[_read_idx] == '\t' || _line[_read_idx] == '|' ||
         _line[_read_idx] == '\r')
     {
       float_feature_value = 1.;
       return true;
     }
     else if (_line[_read_idx] == ':')
     {
       // featureValue --> ':' 'Float'
       ++_read_idx;
       size_t end_read = 0;
       VW::string_view sv = _line.substr(_read_idx);
       _v = float_feature_value = parseFloat(sv.begin(), end_read, sv.end());
       if (end_read == 0)
       {
         return false;
       }
       if (std::isnan(_v))
       {
         _v = float_feature_value = 0.f;
         parserWarning(
             "warning: invalid feature value:\"", _line.substr(_read_idx), "\" read as NaN. Replacing with 0.");
       }
       _read_idx += end_read;
       return true;
     }
     else
     {
       _v = float_feature_value = 0.f;
       // syntax error
       parserWarning("malformed example! '|', ':', space, or EOL expected after : \"", _line.substr(0, _read_idx), "\"");
       return true;
     }
   }
template<bool audit> void TC_parser< audit >::listFeatures () inline
Definition at line 392 of file parse_example.cc.
References TC_parser< audit >::_read_idx, TC_parser< audit >::maybeFeature(), and TC_parser< audit >::parserWarning().
Referenced by TC_parser< audit >::nameSpace().
   {
     while ((_read_idx < _line.size()) && (_line[_read_idx] == ' ' || _line[_read_idx] == '\t'))
     {
       // listFeatures --> ' ' MaybeFeature ListFeatures
       ++_read_idx;
       maybeFeature();
     }
     if (!(_read_idx >= _line.size() || _line[_read_idx] == '|' || _line[_read_idx] == '\r'))
     {
       // syntax error
       parserWarning("malformed example! '|',space, or EOL expected after : \"", _line.substr(0, _read_idx), "\"");
     }
   }
template<bool audit> void TC_parser< audit >::listNameSpace () inline
Definition at line 445 of file parse_example.cc.
References TC_parser< audit >::_read_idx, TC_parser< audit >::nameSpace(), and TC_parser< audit >::parserWarning().
Referenced by TC_parser< audit >::TC_parser().
   {
     while ((_read_idx < _line.size()) && (_line[_read_idx] == '|'))  // ListNameSpace --> '|' NameSpace ListNameSpace
     {
       ++_read_idx;
       nameSpace();
     }
     if (_read_idx < _line.size() && _line[_read_idx] != '\r')
     {
       // syntax error
       parserWarning("malformed example! '|' or EOL expected after : \"", _line.substr(0, _read_idx), "\"");
     }
   }
template<bool audit> void TC_parser< audit >::maybeFeature () inline
Definition at line 162 of file parse_example.cc.
References TC_parser< audit >::_channel_hash, TC_parser< audit >::_index, TC_parser< audit >::_parse_mask, TC_parser< audit >::_read_idx, affix_constant, affix_namespace, v_array< T >::begin(), c, v_array< T >::clear(), dictionary_namespace, example_predict::feature_space, parser::hasher, hashstring(), id(), example_predict::indices, features::indicies, TC_parser< audit >::isFeatureValueFloat(), v_array< T >::push_back(), features::push_back(), push_many(), quadratic_constant, TC_parser< audit >::read_name(), v_array< T >::size(), features::size(), features::space_names, spelling_namespace, TC_parser< audit >::stringFeatureValue(), features::sum_feat_sq, and features::values.
Referenced by TC_parser< audit >::listFeatures().
   {
     if (_read_idx >= _line.size() || _line[_read_idx] == ' ' || _line[_read_idx] == '\t' ||
         _line[_read_idx] == '|' || _line[_read_idx] == '\r')
     {
       // maybeFeature -->
     }
     else
     {
       // maybeFeature --> 'String' FeatureValue
       VW::string_view feature_name = read_name();
       VW::string_view string_feature_value;
       float float_feature_value = 0.f;
       bool is_feature_float = isFeatureValueFloat(float_feature_value);
       if (_chain_hash && !is_feature_float)
       {
         string_feature_value = stringFeatureValue(_line.substr(_read_idx));
         _v = 1;
       }
       else
       {
         _v = _cur_channel_v * float_feature_value;
       }
       uint64_t word_hash;
       if (_chain_hash && !string_feature_value.empty())
       {
         word_hash = (_p->hasher(feature_name.begin(), feature_name.length(),
                          _p->hasher(string_feature_value.begin(), string_feature_value.length(), _channel_hash)) & _parse_mask);
       }
       else if (!feature_name.empty())
       {
         word_hash = (_p->hasher(feature_name.begin(), feature_name.length(), _channel_hash) & _parse_mask);
       }
       else
       {
         word_hash = _channel_hash + _anon++;
       }
       if (_v == 0)
         return;  // dont add 0 valued features to list of features
       features& fs = _ae->feature_space[_index];
       fs.push_back(_v, word_hash);
       if (audit)
       {
         if (_chain_hash && !string_feature_value.empty())
         {
           std::stringstream ss;
           ss << feature_name << "^" << string_feature_value;
           fs.space_names.push_back(audit_strings_ptr(new audit_strings(_base.to_string(), ss.str())));
         }
         else
         {
           fs.space_names.push_back(audit_strings_ptr(new audit_strings(_base.to_string(), feature_name.to_string())));
         }
       }
       if (((*_affix_features)[_index] > 0) && (!feature_name.empty()))
       {
         features& affix_fs = _ae->feature_space[affix_namespace];
         if (affix_fs.size() == 0)
           _ae->indices.push_back(affix_namespace);
         uint64_t affix = (*_affix_features)[_index];
         while (affix > 0)
         {
           bool is_prefix = affix & 0x1;
           uint64_t len = (affix >> 1) & 0x7;
           VW::string_view affix_name(feature_name);
           if (affix_name.size() > len)
           {
             if (is_prefix)
               affix_name.remove_suffix(affix_name.size() - len);
             else
               affix_name.remove_prefix(affix_name.size() - len);
           }
           word_hash = _p->hasher(affix_name.begin(), affix_name.length(), (uint64_t)_channel_hash) * (affix_constant + (affix & 0xF) * quadratic_constant);
           affix_fs.push_back(_v, word_hash);
           if (audit)
           {
             v_array<char> affix_v = v_init<char>();
             if (_index != ' ')
               affix_v.push_back(_index);
             affix_v.push_back(is_prefix ? '+' : '-');
             affix_v.push_back('0' + (char)len);
             affix_v.push_back('=');
             push_many(affix_v, affix_name.begin(), affix_name.size());
             affix_v.push_back('\0');
             affix_fs.space_names.push_back(audit_strings_ptr(new audit_strings("affix", affix_v.begin())));
           }
           affix >>= 4;
         }
       }
       if ((*_spelling_features)[_index])
       {
         features& spell_fs = _ae->feature_space[spelling_namespace];
         if (spell_fs.size() == 0)
           _ae->indices.push_back(spelling_namespace);
         // v_array<char> spelling;
         _spelling.clear();
         for (char c : feature_name)
         {
           char d = 0;
           if ((c >= '0') && (c <= '9'))
             d = '0';
           else if ((c >= 'a') && (c <= 'z'))
             d = 'a';
           else if ((c >= 'A') && (c <= 'Z'))
             d = 'A';
           else if (c == '.')
             d = '.';
           else
             d = '#';
           // if ((spelling.size() == 0) || (spelling.last() != d))
           _spelling.push_back(d);
         }
         VW::string_view spelling_strview(_spelling.begin(), _spelling.size());
         uint64_t word_hash = hashstring(spelling_strview.begin(), spelling_strview.length(), (uint64_t)_channel_hash);
         spell_fs.push_back(_v, word_hash);
         if (audit)
         {
           v_array<char> spelling_v = v_init<char>();
           if (_index != ' ')
           {
             spelling_v.push_back(_index);
             spelling_v.push_back('_');
           }
           push_many(spelling_v, spelling_strview.begin(), spelling_strview.size());
           spelling_v.push_back('\0');
           spell_fs.space_names.push_back(audit_strings_ptr(new audit_strings("spelling", spelling_v.begin())));
         }
       }
       if ((*_namespace_dictionaries)[_index].size() > 0)
       {
         // Heterogeneous lookup not yet implemented in std
         // http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p0919r0.html
         const std::string feature_name_str(feature_name);
         for (const auto& map : (*_namespace_dictionaries)[_index])
         {
           const auto& feats_it = map->find(feature_name_str);
           if ((feats_it != map->end()) && (feats_it->second->values.size() > 0))
           {
             const auto& feats = feats_it->second;
             features& dict_fs = _ae->feature_space[dictionary_namespace];
             if (dict_fs.size() == 0)
               _ae->indices.push_back(dictionary_namespace);
             push_many(dict_fs.values, feats->values.begin(), feats->values.size());
             push_many(dict_fs.indicies, feats->indicies.begin(), feats->indicies.size());
             dict_fs.sum_feat_sq += feats->sum_feat_sq;
             if (audit)
               for (const auto& id : feats->indicies)
               {
                 std::stringstream ss;
                 ss << _index << '_';
                 ss << feature_name;
                 ss << '=' << id;
                 dict_fs.space_names.push_back(audit_strings_ptr(new audit_strings("dictionary", ss.str())));
               }
           }
         }
       }
     }
   }
template<bool audit> void TC_parser< audit >::nameSpace () inline
Definition at line 407 of file parse_example.cc.
References TC_parser< audit >::_read_idx, example_predict::feature_space, example_predict::indices, TC_parser< audit >::listFeatures(), TC_parser< audit >::nameSpaceInfo(), TC_parser< audit >::parserWarning(), v_array< T >::push_back(), and uniform_hash().
Referenced by TC_parser< audit >::listNameSpace().
   {
     _cur_channel_v = 1.0;
     _index = 0;
     _new_index = false;
     _anon = 0;
     if (_read_idx >= _line.size() || _line[_read_idx] == ' ' || _line[_read_idx] == '\t' ||
         _line[_read_idx] == '|' || _line[_read_idx] == '\r')
     {
       // NameSpace --> ListFeatures
       _index = (unsigned char)' ';
       if (_ae->feature_space[_index].size() == 0)
         _new_index = true;
       if (audit)
       {
         // TODO: c++17 allows VW::string_view literals, eg: " "sv
         static const char* space = " ";
         _base = space;
       }
       _channel_hash = this->_hash_seed == 0 ? 0 : uniform_hash("", 0, this->_hash_seed);
       listFeatures();
     }
     else if (_line[_read_idx] != ':')
     {
       // NameSpace --> NameSpaceInfo ListFeatures
       nameSpaceInfo();
       listFeatures();
     }
     else
     {
       // syntax error
       parserWarning(
           "malformed example! '|',String,space, or EOL expected after : \"", _line.substr(0, _read_idx), "\"");
     }
     if (_new_index && _ae->feature_space[_index].size() > 0)
       _ae->indices.push_back(_index);
   }
template<bool audit> void TC_parser< audit >::nameSpaceInfo () inline
Definition at line 366 of file parse_example.cc.
References TC_parser< audit >::_hash_seed, TC_parser< audit >::_index, TC_parser< audit >::_read_idx, example_predict::feature_space, parser::hasher, TC_parser< audit >::nameSpaceInfoValue(), TC_parser< audit >::parserWarning(), and TC_parser< audit >::read_name().
Referenced by TC_parser< audit >::nameSpace().
   {
     if (_read_idx >= _line.size() || _line[_read_idx] == '|' || _line[_read_idx] == ' ' ||
         _line[_read_idx] == '\t' || _line[_read_idx] == ':' || _line[_read_idx] == '\r')
     {
       // syntax error
       parserWarning("malformed example! String expected after : \"", _line.substr(0, _read_idx), "\"");
     }
     else
     {
       // NameSpaceInfo --> 'String' NameSpaceInfoValue
       _index = (unsigned char)(_line[_read_idx]);
       if (_redefine_some)
         _index = (*_redefine)[_index];  // redefine _index
       if (_ae->feature_space[_index].size() == 0)
         _new_index = true;
       VW::string_view name = read_name();
       if (audit)
       {
         _base = name;
       }
       _channel_hash = _p->hasher(name.begin(), name.length(), this->_hash_seed);
       nameSpaceInfoValue();
     }
   }
template<bool audit> void TC_parser< audit >::nameSpaceInfoValue () inline
Definition at line 333 of file parse_example.cc.
References TC_parser< audit >::_read_idx, parseFloat(), and TC_parser< audit >::parserWarning().
Referenced by TC_parser< audit >::nameSpaceInfo().
   {
     if (_read_idx >= _line.size() || _line[_read_idx] == ' ' || _line[_read_idx] == '\t' ||
         _line[_read_idx] == '|' || _line[_read_idx] == '\r')
     {
       // nameSpaceInfoValue -->
     }
     else if (_line[_read_idx] == ':')
     {
       // nameSpaceInfoValue --> ':' 'Float'
       ++_read_idx;
       size_t end_read = 0;
       VW::string_view sv = _line.substr(_read_idx);
       _cur_channel_v = parseFloat(sv.begin(), end_read, sv.end());
       if (end_read + _read_idx >= _line.size())
       {
         parserWarning("malformed example! Float expected after : \"", _line.substr(0, _read_idx), "\"");
       }
       if (std::isnan(_cur_channel_v))
       {
         _cur_channel_v = 1.f;
         parserWarning(
             "warning: invalid namespace value:\"", _line.substr(_read_idx), "\" read as NaN. Replacing with 1.");
       }
       _read_idx += end_read;
     }
     else
     {
       // syntax error
       parserWarning("malformed example! '|',':', space, or EOL expected after : \"", _line.substr(0, _read_idx), "\"");
     }
   }
template<bool audit> void TC_parser< audit >::parserWarning (const char * message, VW::string_view var_msg, const char * message2) inline
Definition at line 75 of file parse_example.cc.
References parser::end_parsed_examples, parser::strict_parse, and THROW_EX.
Referenced by TC_parser< audit >::isFeatureValueFloat(), TC_parser< audit >::listFeatures(), TC_parser< audit >::listNameSpace(), TC_parser< audit >::nameSpace(), TC_parser< audit >::nameSpaceInfo(), and TC_parser< audit >::nameSpaceInfoValue().
   {
     // VW::string_view will output the entire view into the output stream.
     // That means if there is a null character somewhere in the range, it will terminate
     // the stringstream at that point! Minor hack to give us the behavior we actually want here (i think)..
     // the alternative is to do what the old code was doing.. str(_line).c_str()...
     // TODO: Find a sane way to handle nulls in the middle of a string (either VW::string_view or substring)
     auto tmp_view = _line.substr(0, _line.find('\0'));
     std::stringstream ss;
     ss << message << var_msg << message2 << "in Example #" << this->_p->end_parsed_examples.load() << ": \"" << tmp_view << "\""
        << std::endl;
     if (_p->strict_parse)
     {
       THROW_EX(VW::strict_parse_exception, ss.str());
     }
     else
     {
       std::cerr << ss.str();
     }
   }
template<bool audit> VW::string_view TC_parser< audit >::read_name () inline
Definition at line 152 of file parse_example.cc.
References TC_parser< audit >::_read_idx.
Referenced by TC_parser< audit >::maybeFeature(), and TC_parser< audit >::nameSpaceInfo().
   {
     size_t name_start = _read_idx;
     while (!(_read_idx >= _line.size() || _line[_read_idx] == ' ' || _line[_read_idx] == ':' ||
         _line[_read_idx] == '\t' || _line[_read_idx] == '|' || _line[_read_idx] == '\r'))
       ++_read_idx;
     return _line.substr(name_start, _read_idx - name_start);
   }
template<bool audit> VW::string_view TC_parser< audit >::stringFeatureValue (VW::string_view sv) inline
Definition at line 96 of file parse_example.cc.
Referenced by TC_parser< audit >::maybeFeature().
   {
     size_t start_idx = sv.find_first_not_of(" \t\r\n");
     if (start_idx > 0 && start_idx != std::string::npos)
     {
       _read_idx += start_idx;
       sv.remove_prefix(start_idx);
     }
     size_t end_idx = sv.find_first_of(" \t\r\n");
     if (end_idx == std::string::npos)
     {
       end_idx = sv.size();
     }
     _read_idx += end_idx;
     return sv.substr(0, end_idx);
   }
Member Data Documentation
template<bool audit> example* TC_parser< audit >::_ae
Definition at line 63 of file parse_example.cc.
template<bool audit> std::array<uint64_t, NUM_NAMESPACES>* TC_parser< audit >::_affix_features
Definition at line 64 of file parse_example.cc.
template<bool audit> size_t TC_parser< audit >::_anon
Definition at line 55 of file parse_example.cc.
template<bool audit> VW::string_view TC_parser< audit >::_base
Definition at line 57 of file parse_example.cc.
template<bool audit> bool TC_parser< audit >::_chain_hash
Definition at line 69 of file parse_example.cc.
template<bool audit> uint64_t TC_parser< audit >::_channel_hash
Definition at line 56 of file parse_example.cc.
Referenced by TC_parser< audit >::maybeFeature().
template<bool audit> float TC_parser< audit >::_cur_channel_v
Definition at line 53 of file parse_example.cc.
template<bool audit> uint32_t TC_parser< audit >::_hash_seed
Definition at line 67 of file parse_example.cc.
Referenced by TC_parser< audit >::nameSpaceInfo().
template<bool audit> unsigned char TC_parser< audit >::_index
Definition at line 58 of file parse_example.cc.
Referenced by TC_parser< audit >::maybeFeature(), and TC_parser< audit >::nameSpaceInfo().
template<bool audit> VW::string_view TC_parser< audit >::_line
Definition at line 51 of file parse_example.cc.
template<bool audit> std::array<std::vector<std::shared_ptr<feature_dict> >, NUM_NAMESPACES>* TC_parser< audit >::_namespace_dictionaries
Definition at line 71 of file parse_example.cc.
template<bool audit> bool TC_parser< audit >::_new_index
Definition at line 54 of file parse_example.cc.
template<bool audit> parser* TC_parser< audit >::_p
Definition at line 62 of file parse_example.cc.
template<bool audit> uint64_t TC_parser< audit >::_parse_mask
Definition at line 68 of file parse_example.cc.
Referenced by TC_parser< audit >::maybeFeature().
template<bool audit> size_t TC_parser< audit >::_read_idx
Definition at line 52 of file parse_example.cc.
Referenced by TC_parser< audit >::isFeatureValueFloat(), TC_parser< audit >::listFeatures(), TC_parser< audit >::listNameSpace(), TC_parser< audit >::maybeFeature(), TC_parser< audit >::nameSpace(), TC_parser< audit >::nameSpaceInfo(), TC_parser< audit >::nameSpaceInfoValue(), and TC_parser< audit >::read_name().
template<bool audit> std::array<unsigned char, NUM_NAMESPACES>* TC_parser< audit >::_redefine
Definition at line 61 of file parse_example.cc.
template<bool audit> bool TC_parser< audit >::_redefine_some
Definition at line 60 of file parse_example.cc.
template<bool audit> v_array<char> TC_parser< audit >::_spelling
Definition at line 66 of file parse_example.cc.
template<bool audit> std::array<bool, NUM_NAMESPACES>* TC_parser< audit >::_spelling_features
Definition at line 65 of file parse_example.cc.
template<bool audit> float TC_parser< audit >::_v
Definition at line 59 of file parse_example.cc.
The documentation for this class was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example.cc