Vowpal Wabbit: LabelObjectState< audit > Class Template Reference
LabelObjectState< audit > Class Template Reference
#include <parse_example_json.h>
Public Member Functions
LabelObjectState ()
void init (vw *)
BaseState< audit > * StartObject (Context< audit > &ctx) override
BaseState< audit > * Key (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool) override
BaseState< audit > * String (Context< audit > &ctx, const char *str, rapidjson::SizeType, bool) override
BaseState< audit > * Float (Context< audit > &ctx, float v) override
BaseState< audit > * Uint (Context< audit > &ctx, unsigned v) override
BaseState< audit > * EndObject (Context< audit > &ctx, rapidjson::SizeType) override
Public Member Functions inherited from BaseState< audit >
BaseState (const char *pname)
virtual BaseState< audit > * Null (Context< audit > &ctx)
virtual BaseState< audit > * Bool (Context< audit > &ctx, bool b)
virtual BaseState< audit > * StartArray (Context< audit > &ctx)
virtual BaseState< audit > * EndArray (Context< audit > &ctx, rapidjson::SizeType)
Public Attributes
CB::cb_class cb_label
bool found
bool found_cb
std::vector< unsigned int > actions
std::vector< float > probs
std::vector< unsigned int > inc
Public Attributes inherited from BaseState< audit >
const char * name
Private Attributes
BaseState< audit > * return_state
Detailed Description
template<bool audit>
class LabelObjectState< audit >
Definition at line 167 of file parse_example_json.h.
Constructor & Destructor Documentation
template<bool audit> LabelObjectState< audit >::LabelObjectState () inline
Definition at line 180 of file parse_example_json.h.
 : BaseState<audit>("LabelObject") {}
Member Function Documentation
template<bool audit> BaseState<audit>* LabelObjectState< audit >::EndObject (Context< audit > & ctx, rapidjson::SizeType) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 302 of file parse_example_json.h.
References Context< audit >::all, ccb, CB::cb_class::cost, CB::label::costs, count_label(), Context< audit >::ex, example::l, label_data::label, vw::label_type, vw::sd, polylabel::simple, and THROW.
   {
     if (ctx.all->label_type == label_type_t::ccb)
     {
       auto ld = (CCB::label*)&ctx.ex->l;
       for (auto id : inc)
       {
         ld->explicit_included_actions.push_back(id);
       }
       inc.clear();
       if ((actions.size() != 0) && (probs.size() != 0))
       {
         auto outcome = new CCB::conditional_contextual_bandit_outcome();
         outcome->cost = cb_label.cost;
         if (actions.size() != probs.size())
         {
           THROW("Actions and probabilties must be the same length.");
         }
         for (size_t i = 0; i < this->actions.size(); i++)
         {
           outcome->probabilities.push_back({actions[i], probs[i]});
         }
         actions.clear();
         probs.clear();
         ld->outcome = outcome;
         cb_label = {0., 0, 0., 0.};
       }
     }
     else if (found_cb)
     {
       CB::label* ld = (CB::label*)&ctx.ex->l;
       ld->costs.push_back(cb_label);
       found_cb = false;
       cb_label = {0., 0, 0., 0.};
     }
     else if (found)
     {
       count_label(ctx.all->sd, ctx.ex->l.simple.label);
       found = false;
     }
     return return_state;
   }
template<bool audit> BaseState<audit>* LabelObjectState< audit >::Float (Context< audit > & ctx, float v) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 257 of file parse_example_json.h.
References _stricmp, CB::cb_class::action, CB::cb_class::cost, Context< audit >::error(), Context< audit >::ex, label_data::initial, Context< audit >::key, Context< audit >::key_length, example::l, label_data::label, CB::cb_class::probability, polylabel::simple, and label_data::weight.
   {
     // simple
     if (!_stricmp(ctx.key, "Label"))
     {
       ctx.ex->l.simple.label = v;
       found = true;
     }
     else if (!_stricmp(ctx.key, "Initial"))
     {
       ctx.ex->l.simple.initial = v;
       found = true;
     }
     else if (!_stricmp(ctx.key, "Weight"))
     {
       ctx.ex->l.simple.weight = v;
       found = true;
     }
     // CB
     else if (!_stricmp(ctx.key, "Action"))
     {
       cb_label.action = (uint32_t)v;
       found_cb = true;
     }
     else if (!_stricmp(ctx.key, "Cost"))
     {
       cb_label.cost = v;
       found_cb = true;
     }
     else if (!_stricmp(ctx.key, "Probability"))
     {
       cb_label.probability = v;
       found_cb = true;
     }
     else
     {
       ctx.error() << "Unsupported label property: '" << ctx.key << "' len: " << ctx.key_length;
       return nullptr;
     }
     return this;
   }
template<bool audit> void LabelObjectState< audit >::init (vw *) inline
Definition at line 182 of file parse_example_json.h.
Referenced by Context< audit >::init().
   {
     found = found_cb = false;
     cb_label = {0., 0, 0., 0.};
   }
template<bool audit> BaseState<audit>* LabelObjectState< audit >::Key (Context< audit > & ctx, const char * str, rapidjson::SizeType len, bool) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 206 of file parse_example_json.h.
References Context< audit >::key, and Context< audit >::key_length.
   {
     ctx.key = str;
     ctx.key_length = len;
     return this;
   }
template<bool audit> BaseState<audit>* LabelObjectState< audit >::StartObject (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 189 of file parse_example_json.h.
References Context< audit >::all, label_parser::default_label, Context< audit >::error(), Context< audit >::ex, example::l, parser::lp, vw::p, and Context< audit >::previous_state.
   {
     ctx.all->p->lp.default_label(&ctx.ex->l);
     // don't allow { { { } } }
     if (ctx.previous_state == this)
     {
       ctx.error() << "invalid label object. nested objected.";
       return nullptr;
     }
     // keep previous state
     return_state = ctx.previous_state;
     return this;
   }
template<bool audit> BaseState<audit>* LabelObjectState< audit >::String (Context< audit > & ctx, const char * str, rapidjson::SizeType , bool) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 213 of file parse_example_json.h.
References _stricmp, CB::cb_class::cost, Context< audit >::error(), Context< audit >::ex, label_data::initial, Context< audit >::key, Context< audit >::key_length, example::l, label_data::label, CB::cb_class::probability, polylabel::simple, and label_data::weight.
   {
     if (_stricmp(str, "NaN") != 0)
     {
       ctx.error() << "Unsupported label property: '" << ctx.key << "' len: " << ctx.key_length << ". The only string value supported in this context is NaN.";
       return nullptr;
     }
     // simple
     if (!_stricmp(ctx.key, "Label"))
     {
       ctx.ex->l.simple.label = std::numeric_limits<float>::quiet_NaN();
       found = true;
     }
     else if (!_stricmp(ctx.key, "Initial"))
     {
       ctx.ex->l.simple.initial = std::numeric_limits<float>::quiet_NaN();
       found = true;
     }
     else if (!_stricmp(ctx.key, "Weight"))
     {
       ctx.ex->l.simple.weight = std::numeric_limits<float>::quiet_NaN();
       found = true;
     }
     // CB
     else if (!_stricmp(ctx.key, "Cost"))
     {
       cb_label.cost = std::numeric_limits<float>::quiet_NaN();
       found_cb = true;
     }
     else if (!_stricmp(ctx.key, "Probability"))
     {
       cb_label.probability = std::numeric_limits<float>::quiet_NaN();
       found_cb = true;
     }
     else
     {
       ctx.error() << "Unsupported label property: '" << ctx.key << "' len: " << ctx.key_length;
       return nullptr;
     }
     return this;
   }
template<bool audit> BaseState<audit>* LabelObjectState< audit >::Uint (Context< audit > & ctx, unsigned v) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 300 of file parse_example_json.h.
 { return Float(ctx, (float)v); }
Member Data Documentation
template<bool audit> std::vector<unsigned int> LabelObjectState< audit >::actions
Definition at line 176 of file parse_example_json.h.
template<bool audit> CB::cb_class LabelObjectState< audit >::cb_label
Definition at line 173 of file parse_example_json.h.
template<bool audit> bool LabelObjectState< audit >::found
Definition at line 174 of file parse_example_json.h.
template<bool audit> bool LabelObjectState< audit >::found_cb
Definition at line 175 of file parse_example_json.h.
template<bool audit> std::vector<unsigned int> LabelObjectState< audit >::inc
Definition at line 178 of file parse_example_json.h.
template<bool audit> std::vector<float> LabelObjectState< audit >::probs
Definition at line 177 of file parse_example_json.h.
template<bool audit> BaseState<audit>* LabelObjectState< audit >::return_state private
Definition at line 170 of file parse_example_json.h.
The documentation for this class was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example_json.h