Vowpal Wabbit: squaredloss Class Reference
squaredloss Class Reference
Public Member Functions
std::string getType ()
float getLoss (shared_data *sd, float prediction, float label)
float getUpdate (float prediction, float label, float update_scale, float pred_per_update)
float getUnsafeUpdate (float prediction, float label, float update_scale)
float getRevertingWeight (shared_data *sd, float prediction, float eta_t)
float getSquareGrad (float prediction, float label)
float first_derivative (shared_data *sd, float prediction, float label)
float second_derivative (shared_data *sd, float prediction, float)
Public Member Functions inherited from loss_function
virtual ~loss_function ()
Detailed Description
Definition at line 13 of file loss_functions.cc.
Member Function Documentation
float squaredloss::first_derivative (shared_data * sd, float prediction, float label) inline virtual
Implements loss_function.
Definition at line 64 of file loss_functions.cc.
References shared_data::max_label, and shared_data::min_label.
Referenced by hingeloss::getSquareGrad(), logloss::getSquareGrad(), and quantileloss::getSquareGrad().
   {
     if (prediction < sd->min_label)
       prediction = sd->min_label;
     else if (prediction > sd->max_label)
       prediction = sd->max_label;
     return 2.f * (prediction - label);
   }
float squaredloss::getLoss (shared_data * sd, float prediction, float label) inline virtual
Implements loss_function.
Definition at line 18 of file loss_functions.cc.
References shared_data::max_label, and shared_data::min_label.
   {
     if (prediction <= sd->max_label && prediction >= sd->min_label)
     {
       float example_loss = (prediction - label) * (prediction - label);
       return example_loss;
     }
     else if (prediction < sd->min_label)
       if (label == sd->min_label)
         return 0.;
       else
         return (float)((label - sd->min_label) * (label - sd->min_label) +
             2. * (label - sd->min_label) * (sd->min_label - prediction));
     else if (label == sd->max_label)
       return 0.;
     else
       return float((sd->max_label - label) * (sd->max_label - label) +
           2. * (sd->max_label - label) * (prediction - sd->max_label));
   }
float squaredloss::getRevertingWeight (shared_data * sd, float prediction, float eta_t) inline virtual
Implements loss_function.
Definition at line 56 of file loss_functions.cc.
References shared_data::max_label, and shared_data::min_label.
   {
     float t = 0.5f * (sd->min_label + sd->max_label);
     float alternative = (prediction > t) ? sd->min_label : sd->max_label;
     return log((alternative - prediction) / (alternative - t)) / eta_t;
   }
float squaredloss::getSquareGrad (float prediction, float label) inline virtual
Implements loss_function.
Definition at line 63 of file loss_functions.cc.
 { return 4.f * (prediction - label) * (prediction - label); }
std::string squaredloss::getType () inline virtual
Implements loss_function.
Definition at line 16 of file loss_functions.cc.
 { return "squared"; }
float squaredloss::getUnsafeUpdate (float prediction, float label, float update_scale) inline virtual
Implements loss_function.
Definition at line 51 of file loss_functions.cc.
   {
     return 2.f * (label - prediction) * update_scale;
   }
float squaredloss::getUpdate (float prediction, float label, float update_scale, float pred_per_update) inline virtual
Implements loss_function.
Definition at line 38 of file loss_functions.cc.
References correctedExp, and f.
   {
     if (update_scale * pred_per_update < 1e-6)
     {
       /* When exp(-eta_t)~= 1 we replace 1-exp(-eta_t)
        * with its first order Taylor expansion around 0
        * to avoid catastrophic cancellation.
        */
       return 2.f * (label - prediction) * update_scale;
     }
     return (label - prediction) * (1.f - correctedExp(-2.f * update_scale * pred_per_update)) / pred_per_update;
   }
float squaredloss::second_derivative (shared_data * sd, float prediction, float) inline virtual
Implements loss_function.
Definition at line 72 of file loss_functions.cc.
References shared_data::min_label.
   {
     if (prediction <= sd->max_label && prediction >= sd->min_label)
       return 2.;
     else
       return 0.;
   }
The documentation for this class was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/loss_functions.cc