Vowpal Wabbit: DefaultState< audit > Class Template Reference
DefaultState< audit > Class Template Reference
#include <parse_example_json.h>
Public Member Functions
DefaultState ()
BaseState< audit > * Ignore (Context< audit > &ctx, rapidjson::SizeType length)
BaseState< audit > * Key (Context< audit > &ctx, const char *str, rapidjson::SizeType length, bool) override
BaseState< audit > * String (Context< audit > &ctx, const char *str, rapidjson::SizeType length, bool) override
BaseState< audit > * Bool (Context< audit > &ctx, bool b) override
BaseState< audit > * StartObject (Context< audit > &ctx) override
BaseState< audit > * EndObject (Context< audit > &ctx, rapidjson::SizeType memberCount) override
BaseState< audit > * Float (Context< audit > &ctx, float f) override
BaseState< audit > * Uint (Context< audit > &ctx, unsigned f) override
BaseState< audit > * StartArray (Context< audit > &ctx) override
Public Member Functions inherited from BaseState< audit >
BaseState (const char *pname)
virtual BaseState< audit > * Null (Context< audit > &ctx)
virtual BaseState< audit > * EndArray (Context< audit > &ctx, rapidjson::SizeType)
Additional Inherited Members
Public Attributes inherited from BaseState< audit >
const char * name
Detailed Description
template<bool audit>
class DefaultState< audit >
Definition at line 674 of file parse_example_json.h.
Constructor & Destructor Documentation
template<bool audit> DefaultState< audit >::DefaultState () inline
Definition at line 677 of file parse_example_json.h.
 : BaseState<audit>("Default") {}
Member Function Documentation
template<bool audit> BaseState<audit>* DefaultState< audit >::Bool (Context< audit > & ctx, bool b) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 859 of file parse_example_json.h.
References Context< audit >::all, Context< audit >::CurrentNamespace(), and Context< audit >::key.
   {
     if (b)
       ctx.CurrentNamespace().AddFeature(ctx.all, ctx.key);
     return this;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::EndObject (Context< audit > & ctx, rapidjson::SizeType memberCount) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 873 of file parse_example_json.h.
References Context< audit >::all, v_array< T >::begin(), ccb, polylabel::conditional_contextual_bandit, label_parser::default_label, v_array< T >::end(), Context< audit >::error(), Context< audit >::ex, Context< audit >::example_factory, Context< audit >::example_factory_context, Context< audit >::examples, example::l, Context< audit >::label_index_state, Context< audit >::label_object_state, vw::label_type, parser::lp, Context< audit >::namespace_path, CCB::label::outcome, vw::p, Context< audit >::PopNamespace(), v_array< T >::push_back(), Context< audit >::root_state, v_array< T >::size(), CCB::slot, and CCB::label::type.
   {
     BaseState<audit>* return_state = ctx.PopNamespace();
     if (ctx.namespace_path.empty())
     {
       int label_index = ctx.label_index_state.index;
       // we're at the end of the example
       if (label_index >= 0)
       {
         // skip shared example
         label_index++;
         if (label_index >= (int)ctx.examples->size())
         {
           ctx.error() << "Out of bounds error: _labelIndex must be smaller than number of actions! _labelIndex="
                       << (label_index - 1) << " Number of actions=" << ctx.examples->size() - 1 << " ";
           return nullptr;
         }
         // apply labelIndex
         ctx.ex = (*ctx.examples)[label_index];
         // reset for next example
         ctx.label_index_state.index = -1;
       }
       // inject label
       ctx.label_object_state.EndObject(ctx, memberCount);
       // If we are in CCB mode and there have been no slots. Check label cost, prob and action were passed. In that
       // case this is CB, so generate a single slot with this info.
       if (ctx.all->label_type == label_type_t::ccb)
       {
         auto num_slots = std::count_if(ctx.examples->begin(), ctx.examples->end(),
             [](example* ex) { return ex->l.conditional_contextual_bandit.type == CCB::example_type::slot; });
         if (num_slots == 0 && ctx.label_object_state.found_cb)
         {
           ctx.ex = &(*ctx.example_factory)(ctx.example_factory_context);
           ctx.all->p->lp.default_label(&ctx.ex->l);
           ctx.ex->l.conditional_contextual_bandit.type = CCB::example_type::slot;
           ctx.examples->push_back(ctx.ex);
           auto outcome = new CCB::conditional_contextual_bandit_outcome();
           outcome->cost = ctx.label_object_state.cb_label.cost;
           outcome->probabilities.push_back(
               {ctx.label_object_state.cb_label.action, ctx.label_object_state.cb_label.probability});
           ctx.ex->l.conditional_contextual_bandit.outcome = outcome;
         }
       }
     }
     // if we're at the top-level go back to ds_state
     return ctx.namespace_path.empty() ? ctx.root_state : return_state;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::Float (Context< audit > & ctx, float f) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 928 of file parse_example_json.h.
References Context< audit >::all, Context< audit >::CurrentNamespace(), VW::hash_feature_cstr(), and Context< audit >::key.
   {
     auto& ns = ctx.CurrentNamespace();
     ns.AddFeature(f, VW::hash_feature_cstr(*ctx.all, const_cast<char*>(ctx.key), ns.namespace_hash), ctx.key);
     return this;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::Ignore (Context< audit > & ctx, rapidjson::SizeType length) inline
Definition at line 679 of file parse_example_json.h.
References Context< audit >::error(), Context< audit >::ignore_state, Context< audit >::stream, and Context< audit >::stream_end.
   {
     // fast ignore
     // skip key + \0 + "
     char* head = ctx.stream->src_ + length + 2;
     if (head >= ctx.stream_end || *head != ':')
     {
       ctx.error() << "Expected ':' found '" << *head << "'";
       return nullptr;
     }
     head++;
     // scan for ,}
     // support { { ... } }
     int depth = 0, sq_depth = 0;
     bool stop = false;
     while (!stop)
     {
       switch (*head)
       {
         case '\0':
           ctx.error() << "Found EOF";
           return nullptr;
         case '"':
         {
           // skip strings
           bool stopInner = false;
           while (!stopInner)
           {
             head++;
             switch (*head)
             {
               case '\0':
                 ctx.error() << "Found EOF";
                 return nullptr;
               case '\\':
                 head++;
                 break;
               case '"':
                 stopInner = true;
                 break;
             }
           }
           break;
         }
         case '{':
           depth++;
           break;
         case '}':
           if (depth == 0 && sq_depth == 0)
             stop = true;
           else
             depth--;
           break;
         case '[':
           sq_depth++;
           break;
         case ']':
           if (depth == 0 && sq_depth == 0)
             stop = true;
           else
             sq_depth--;
           break;
         case ',':
           if (depth == 0 && sq_depth == 0)
             stop = true;
           break;
       }
       head++;
     }
     // skip key + \0 + ":
     char* value = ctx.stream->src_ + length + 3;
     if (value >= ctx.stream_end)
     {
       ctx.error() << "Found EOF";
       return nullptr;
     }
     *value = '0';
     value++;
     memset(value, ' ', head - value - 1);
     return &ctx.ignore_state;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::Key (Context< audit > & ctx, const char * str, rapidjson::SizeType length, bool) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 765 of file parse_example_json.h.
References _stricmp, Context< audit >::array_float_state, Context< audit >::array_uint_state, Context< audit >::error(), Context< audit >::key, Context< audit >::key_length, Context< audit >::label_index_state, Context< audit >::label_object_state, Context< audit >::label_single_property_state, Context< audit >::label_state, Context< audit >::multi_state, ArrayToVectorState< audit, T >::output_array, ArrayToVectorState< audit, T >::return_state, Context< audit >::slots_state, Context< audit >::tag_state, and Context< audit >::text_state.
   {
     ctx.key = str;
     ctx.key_length = length;
     if (length > 0 && str[0] == '_')
     {
       // match _label*
       if (ctx.key_length >= 6 && !strncmp(ctx.key, "_label", 6))
       {
         if (ctx.key_length >= 7 && ctx.key[6] == '_')
           return &ctx.label_single_property_state;
         else if (ctx.key_length == 6)
           return &ctx.label_state;
         else if (ctx.key_length == 11 && !_stricmp(ctx.key, "_labelIndex"))
           return &ctx.label_index_state;
         else
         {
           ctx.error() << "Unsupported key '" << ctx.key << "' len: " << length;
           return nullptr;
         }
       }
       if (ctx.key_length == 5 && !strcmp(ctx.key, "_text"))
         return &ctx.text_state;
       // TODO: _multi in _multi...
       if (ctx.key_length == 6 && !strcmp(ctx.key, "_multi"))
         return &ctx.multi_state;
       if (ctx.key_length == 6 && !strcmp(ctx.key, "_slots"))
         return &ctx.slots_state;
       if (ctx.key_length == 4 && !_stricmp(ctx.key, "_tag"))
         return &ctx.tag_state;
       if (ctx.key_length == 4 && !_stricmp(ctx.key, "_inc"))
       {
         ctx.array_uint_state.output_array = &ctx.label_object_state.inc;
         ctx.array_uint_state.return_state = this;
         return &ctx.array_uint_state;
       }
       if (ctx.key_length == 2 && ctx.key[1] == 'a')
       {
         ctx.array_uint_state.output_array = &ctx.label_object_state.actions;
         ctx.array_uint_state.return_state = this;
         return &ctx.array_uint_state;
       }
       if (ctx.key_length == 2 && ctx.key[1] == 'p')
       {
         ctx.array_float_state.output_array = &ctx.label_object_state.probs;
         ctx.array_float_state.return_state = this;
         return &ctx.array_float_state;
       }
       return Ignore(ctx, length);
     }
     return this;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::StartArray (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 938 of file parse_example_json.h.
References Context< audit >::array_state.
 { return ctx.array_state.StartArray(ctx); }
template<bool audit> BaseState<audit>* DefaultState< audit >::StartObject (Context< audit > & ctx) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 867 of file parse_example_json.h.
References Context< audit >::key, and Context< audit >::PushNamespace().
   {
     ctx.PushNamespace(ctx.key, this);
     return this;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::String (Context< audit > & ctx, const char * str, rapidjson::SizeType length, bool) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 828 of file parse_example_json.h.
References Context< audit >::all, vw::chain_hash, Context< audit >::CurrentNamespace(), Context< audit >::key, and Context< audit >::key_length.
   {
     // string escape
     const char* end = str + length;
     for (char* p = (char*)str; p != end; p++)
     {
       switch (*p)
       {
         case ' ':
         case '\t':
         case '|':
         case ':':
           *p = '_';
       }
     }
     if (ctx.all->chain_hash)
     {
       ctx.CurrentNamespace().AddFeature(ctx.all, ctx.key, str);
     }
     else
     {
       char* prepend = (char*)str - ctx.key_length;
       memmove(prepend, ctx.key, ctx.key_length);
       ctx.CurrentNamespace().AddFeature(ctx.all, prepend);
     }
     return this;
   }
template<bool audit> BaseState<audit>* DefaultState< audit >::Uint (Context< audit > & ctx, unsigned f) inline override virtual
Reimplemented from BaseState< audit >.
Definition at line 936 of file parse_example_json.h.
 { return Float(ctx, (float)f); }
The documentation for this class was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example_json.h