Vowpal Wabbit: vw_slim::example_predict_builder Class Reference
vw_slim::example_predict_builder Class Reference
#include <example_predict_builder.h>
Public Member Functions
example_predict_builder (example_predict *ex, char *namespace_name, uint32_t feature_index_num_bits=18)
example_predict_builder (example_predict *ex, namespace_index namespace_idx, uint32_t feature_index_num_bits=18)
void push_feature_string (char *feature_idx, feature_value value)
void push_feature (feature_index feature_idx, feature_value value)
Private Member Functions
void add_namespace (namespace_index feature_group)
Private Attributes
example_predict * _ex
namespace_index _namespace_idx
uint64_t _namespace_hash
uint64_t _feature_index_bit_mask
Detailed Description
Definition at line 7 of file example_predict_builder.h.
Constructor & Destructor Documentation
vw_slim::example_predict_builder::example_predict_builder (example_predict * ex, char * namespace_name, uint32_t feature_index_num_bits = 18)
Definition at line 7 of file example_predict_builder.cc.
References _feature_index_bit_mask, _namespace_hash, add_namespace(), and hashstring().
     : _ex(ex)
 {
   _feature_index_bit_mask = ((uint64_t)1 << feature_index_num_bits) - 1;
   add_namespace(namespace_name[0]);
   _namespace_hash = hashstring(namespace_name, strlen(namespace_name), 0);
 }
vw_slim::example_predict_builder::example_predict_builder (example_predict * ex, namespace_index namespace_idx, uint32_t feature_index_num_bits = 18)
Definition at line 16 of file example_predict_builder.cc.
References _feature_index_bit_mask, and add_namespace().
     : _ex(ex), _namespace_hash(namespace_idx)
 {
   _feature_index_bit_mask = ((uint64_t)1 << feature_index_num_bits) - 1;
   add_namespace(namespace_idx);
 }
Member Function Documentation
void vw_slim::example_predict_builder::add_namespace (namespace_index feature_group) private
Definition at line 24 of file example_predict_builder.cc.
References _ex, _namespace_idx, example_predict::indices, and v_array< T >::unique_add_sorted().
Referenced by example_predict_builder().
 {
   _namespace_idx = feature_group;
   _ex->indices.unique_add_sorted(feature_group);
 }
void vw_slim::example_predict_builder::push_feature (feature_index feature_idx, feature_value value)
Definition at line 37 of file example_predict_builder.cc.
References _ex, _namespace_hash, _namespace_idx, and example_predict::feature_space.
Referenced by cb_data_epsilon_0_skype_jb_test_runner(), generate_cb_data_5(), run_predict_in_memory(), and TEST().
 {
   _ex->feature_space[_namespace_idx].push_back(value, _namespace_hash + feature_idx);
 }
void vw_slim::example_predict_builder::push_feature_string (char * feature_idx, feature_value value)
Definition at line 30 of file example_predict_builder.cc.
References _ex, _feature_index_bit_mask, _namespace_hash, _namespace_idx, example_predict::feature_space, and hashstring().
Referenced by run_predict_in_memory(), and TEST().
 {
   feature_index feature_hash =
       _feature_index_bit_mask & hashstring(feature_name, strlen(feature_name), _namespace_hash);
   _ex->feature_space[_namespace_idx].push_back(value, feature_hash);
 }
Member Data Documentation
example_predict* vw_slim::example_predict_builder::_ex private
Definition at line 9 of file example_predict_builder.h.
Referenced by add_namespace(), push_feature(), and push_feature_string().
uint64_t vw_slim::example_predict_builder::_feature_index_bit_mask private
Definition at line 12 of file example_predict_builder.h.
Referenced by example_predict_builder(), and push_feature_string().
uint64_t vw_slim::example_predict_builder::_namespace_hash private
Definition at line 11 of file example_predict_builder.h.
Referenced by example_predict_builder(), push_feature(), and push_feature_string().
namespace_index vw_slim::example_predict_builder::_namespace_idx private
Definition at line 10 of file example_predict_builder.h.
Referenced by add_namespace(), push_feature(), and push_feature_string().
The documentation for this class was generated from the following files:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/slim/include/example_predict_builder.h
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/slim/src/example_predict_builder.cc