Vowpal Wabbit: VW::distributionally_robust::ChiSquared Class Reference
VW::distributionally_robust::ChiSquared Class Reference
#include <distributionally_robust.h>
Classes
struct Duals
Public Member Functions
ChiSquared (double _alpha, double _tau, double _wmin=0, double _wmax=std::numeric_limits< double >::infinity(), double _rmin=0, double _rmax=1)
bool isValid ()
ChiSquared & update (double w, double r)
double qlb (double w, double r)
Duals recompute_duals ()
const double & effn ()
Static Public Member Functions
static double chisq_onedof_isf (double alpha)
Private Attributes
double alpha
double tau
double wmin
double wmax
double rmin
double rmax
double n
double sumw
double sumwsq
double sumwr
double sumwsqr
double sumwsqrsq
double delta
bool duals_stale
Duals duals
Detailed Description
Definition at line 18 of file distributionally_robust.h.
Constructor & Destructor Documentation
VW::distributionally_robust::ChiSquared::ChiSquared (double _alpha, double _tau, double _wmin = 0, double _wmax = std::numeric_limits<double>::infinity(), double _rmin = 0, double _rmax = 1) inline explicit
Definition at line 55 of file distributionally_robust.h.
       : alpha(_alpha),
         tau(_tau),
         wmin(_wmin),
         wmax(_wmax),
         rmin(_rmin),
         rmax(_rmax),
         n(0),
         sumw(0),
         sumwsq(0),
         sumwr(0),
         sumwsqr(0),
         sumwsqrsq(0),
         delta(chisq_onedof_isf(alpha)),
         duals_stale(true)
       {
       }
Member Function Documentation
double VW::distributionally_robust::ChiSquared::chisq_onedof_isf (double alpha) static
Definition at line 13 of file distributionally_robust.cc.
Referenced by qlb().
 {
   // the following is a polynomial approximation to the
   // inverse survival function for chi-squared distribution with 1 dof
   // using log and exp as basis functions
   // "constants" below found with the following Mathematica code
   //
   // data = Table[{ alpha, InverseCDF[ChiSquareDistribution[1], 1 - alpha] }, { alpha, 0.001, 0.999, 0.0005 }]
   // lm = LinearModelFit[data, { Log[alpha], Log[alpha]^2, Log[alpha]^3, Log[alpha]^4 , Log[alpha]^5, Log[alpha]^6, Log[alpha]^7, Log[alpha]^8, Exp[alpha], Exp[alpha]^2, Exp[alpha]^3, Exp[alpha]^4, Exp[alpha]^5, Exp[alpha]^6, Exp[alpha]^7, Exp[alpha]^8}, alpha]
   // ListPlot[lm["FitResiduals"]]
   // lm["BestFitParameters"]
   // Show[Plot[InverseCDF[ChiSquareDistribution[1], 1 - alpha], { alpha, 0 , 1}],  Plot[lm[alpha], { alpha, 0, 1 }], Frame->True]
   constexpr double constants[] = {-1.73754,-1.40684,0.0758363,0.00726577,0.000468688,0.0000214395,1.0643e-6,6.43011e-8,2.0475e-9,1.16356,-0.575446,0.329796,-0.136076,0.0396764,-0.00763232,0.00087113,-0.0000445128};
   double logalpha = std::log(alpha);
   double expalpha = std::exp(alpha);
   double logalphapow = logalpha;
   double expalphapow = expalpha;
   double rv = constants[0];
   for (int i = 1; i <= 8; ++i)
     {
       rv += constants[i] * logalphapow;
       rv += constants[i + 8] * expalphapow;
       logalphapow *= logalpha;
       expalphapow *= expalpha;
     }
   return rv;
 }
const double& VW::distributionally_robust::ChiSquared::effn () inline
Definition at line 123 of file distributionally_robust.h.
References VW::distributionally_robust::ChiSquared::Duals::n.
 { return n; }
bool VW::distributionally_robust::ChiSquared::isValid () inline
Definition at line 78 of file distributionally_robust.h.
       {
         if (alpha > 1 || alpha <= 0) return false;
         if (tau > 1 || tau <= 0) return false;
         if (wmin >= wmax || wmin >= 1 || wmax <= 1) return false;
         if (rmin > rmax) return false;
         return true;
       }
double VW::distributionally_robust::ChiSquared::qlb (double w, double r) inline
Definition at line 111 of file distributionally_robust.h.
References chisq_onedof_isf(), VW::distributionally_robust::ChiSquared::Duals::qfunc(), and recompute_duals().
       {
         if (duals_stale)
           {
             recompute_duals();
           }
         return duals.qfunc(w, r);
       }
ChiSquared::Duals VW::distributionally_robust::ChiSquared::recompute_duals ()
Definition at line 52 of file distributionally_robust.cc.
References delta, duals, VW::distributionally_robust::isclose(), n, rmin, sign(), sumw, sumwr, sumwsq, sumwsqr, sumwsqrsq, wmax, and wmin.
Referenced by qlb().
 {
   if (n <= 0)
     {
       duals = { true, 0, 0, 0, 0 };
       return duals;
     }
   double uncwfake = sumw < n ? wmax : wmin;
   double uncgstar;
   if (uncwfake == std::numeric_limits<double>::infinity())
     {
       uncgstar = 1.0 + 1.0 / n;
     }
   else
     {
       double unca = (uncwfake + sumw) / (1 + n);
       double uncb = (uncwfake*uncwfake + sumwsq) / (1 + n);
       // NB: (uncb > unca * unca) is guaranteed
       uncgstar = (n + 1) * (unca - 1) * (unca - 1) / (uncb - unca * unca);
     }
   double phi = (-uncgstar - delta) / (2 * (n + 1));
   double r = rmin;
   double sign = 1;
   typedef std::pair<double, Duals> ScoredDual;
   std::list<ScoredDual> candidates;
   for (auto wfake : { wmin, wmax })
     {
       if (wfake == std::numeric_limits<double>::infinity())
         {
           double x = r + (sumwr - sumw * r) / n;
           double y = (r * sumw - sumwr) * (r * sumw - sumwr) / (n * (1 + n))
                      - (r*r * sumwsq - 2 * r * sumwsqr + sumwsqrsq) / (1 + n);
           double z = phi + 1 / (2 * n);
           if (isclose(y * z, 0, 1e-9))
             {
               y = 0;
             }
           if (z <= 0 && y * z >= 0)
             {
               double kappa = std::sqrt(y / (2 * z));
               if (isclose(kappa, 0))
                 {
                   Duals candidate = { true, 0, 0, 0, n };
                   candidates.push_back(std::make_pair(r, candidate));
                 }
               else
                 {
                   double gstar = x - std::sqrt(2 * y * z);
                   double gamma = -kappa * (1 + n) / n + (r * sumw - sumwr) / n;
                   double beta = -sign * r;
                   Duals candidate = { false, kappa, gamma, beta, n };
                   candidates.push_back(std::make_pair(gstar, candidate));
                 }
             }
         }
       else
         {
            double barw = (wfake + sumw) / (1 + n);
            double barwsq = (wfake*wfake + sumwsq) / (1 + n);
            double barwr = sign * (wfake * r + sumwr) / (1 + n);
            double barwsqr = sign * (wfake * wfake * r + sumwsqr) / (1 + n);
            double barwsqrsq = (wfake * wfake * r * r + sumwsqrsq) / (1 + n);
            if (barwsq > barw*barw)
              {
                 double x = barwr + ((1 - barw) * (barwsqr - barw * barwr) / (barwsq - barw*barw));
                 double y = (barwsqr - barw * barwr)*(barwsqr - barw * barwr) / (barwsq - barw*barw) - (barwsqrsq - barwr*barwr);
                 double z = phi + 0.5 * (1 - barw)*(1 - barw) / (barwsq - barw*barw);
                 if (isclose(y * z, 0, 1e-9))
                   {
                     y = 0;
                   }
                 if (z <= 0 && y * z >= 0)
                   {
                     double kappa = std::sqrt(y / (2 * z));
                     if (isclose(kappa, 0))
                       {
                         Duals candidate = { true, 0, 0, 0, n };
                         candidates.push_back(std::make_pair(r, candidate));
                       }
                     else
                       {
                         double gstar = x - std::sqrt(2 * y * z);
                         double beta = (-kappa * (1 - barw) - (barwsqr - barw * barwr)) / (barwsq - barw*barw);
                         double gamma = -kappa - beta * barw - barwr;
                         Duals candidate = { false, kappa, gamma, beta, n };
                         candidates.push_back(std::make_pair(gstar, candidate));
                       }
                   }
              }
         }
     }
   if (candidates.empty())
     {
       duals = { true, 0, 0, 0, n };
     }
   else
     {
       auto it = std::min_element(candidates.begin(),
                                  candidates.end(),
                                  [](const ScoredDual& x, const ScoredDual& y)
{
                                      return std::get<0>(x) < std::get<0>(y);
                                    }
                                  );
       duals = std::get<1>(*it);
     }
   return duals;
 }
ChiSquared& VW::distributionally_robust::ChiSquared::update (double w, double r) inline
Definition at line 88 of file distributionally_robust.h.
       {
         if (w >= 0)
           {
             n = tau * n + 1;
             sumw = tau * sumw + w;
             sumwsq = tau * sumwsq + w*w;
             sumwr = tau * sumwr + w*r;
             sumwsqr = tau * sumwsqr + w*w*r;
             sumwsqrsq = tau * sumwsqrsq + w*w*r*r;
             rmin = std::min(rmin, r);
             rmax = std::max(rmax, r);
             wmin = std::min(wmin, w);
             wmax = std::max(wmax, w);
             duals_stale = true;
           }
         return *this;
       }
Member Data Documentation
double VW::distributionally_robust::ChiSquared::alpha private
Definition at line 33 of file distributionally_robust.h.
double VW::distributionally_robust::ChiSquared::delta private
Definition at line 47 of file distributionally_robust.h.
Referenced by recompute_duals().
Duals VW::distributionally_robust::ChiSquared::duals private
Definition at line 50 of file distributionally_robust.h.
Referenced by recompute_duals().
bool VW::distributionally_robust::ChiSquared::duals_stale private
Definition at line 49 of file distributionally_robust.h.
double VW::distributionally_robust::ChiSquared::n private
Definition at line 40 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::rmax private
Definition at line 38 of file distributionally_robust.h.
double VW::distributionally_robust::ChiSquared::rmin private
Definition at line 37 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::sumw private
Definition at line 41 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::sumwr private
Definition at line 43 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::sumwsq private
Definition at line 42 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::sumwsqr private
Definition at line 44 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::sumwsqrsq private
Definition at line 45 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::tau private
Definition at line 34 of file distributionally_robust.h.
double VW::distributionally_robust::ChiSquared::wmax private
Definition at line 36 of file distributionally_robust.h.
Referenced by recompute_duals().
double VW::distributionally_robust::ChiSquared::wmin private
Definition at line 35 of file distributionally_robust.h.
Referenced by recompute_duals().
The documentation for this class was generated from the following files:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/distributionally_robust.h
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/distributionally_robust.cc