Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/conditional_contextual_bandit.cc File Reference
conditional_contextual_bandit.cc File Reference
#include "conditional_contextual_bandit.h"
#include "reductions.h"
#include "example.h"
#include "global_data.h"
#include "vw.h"
#include "interactions.h"
#include "label_dictionary.h"
#include "cb_adf.h"
#include "cb_algs.h"
#include "constant.h"
#include "v_array_pool.h"
#include <numeric>
#include <algorithm>
#include <unordered_set>
#include <bitset>
Classes
struct ccb
Namespaces
CCB
Functions
template<typename T >
void return_v_array (v_array< T > &array, VW::v_array_pool< T > &pool)
void CCB::clear_all (ccb &data)
bool CCB::split_multi_example_and_stash_labels (const multi_ex &examples, ccb &data)
template<bool is_learn>
bool CCB::sanity_checks (ccb &data)
void CCB::create_cb_labels (ccb &data)
void CCB::delete_cb_labels (ccb &data)
void CCB::attach_label_to_example (uint32_t action_index_one_based, example *example, conditional_contextual_bandit_outcome *outcome, ccb &data)
void CCB::save_action_scores (ccb &data, decision_scores_t &decision_scores)
void CCB::clear_pred_and_label (ccb &data)
bool CCB::has_action (multi_ex &cb_ex)
void CCB::inject_slot_features (example *shared, example *slot)
template<bool audit>
void CCB::inject_slot_id (ccb &data, example *shared, size_t id)
template<bool audit>
void CCB::remove_slot_id (example *shared)
void CCB::remove_slot_features (example *shared, example *slot)
void CCB::calculate_and_insert_interactions (example *shared, std::vector< example * > actions, std::vector< std::string > &generated_interactions)
template<bool is_learn>
void CCB::build_cb_example (multi_ex &cb_ex, example *slot, ccb &data)
template<bool is_learn>
void CCB::learn_or_predict (ccb &data, multi_learner &base, multi_ex &examples)
void CCB::print_decision_scores (int f, decision_scores_t &decision_scores)
void CCB::print_update (vw &all, std::vector< example * > &slots, decision_scores_t &decision_scores, size_t num_features)
void CCB::output_example (vw &all, ccb &, multi_ex &ec_seq)
void CCB::finish_multiline_example (vw &all, ccb &data, multi_ex &ec_seq)
base_learner * CCB::ccb_explore_adf_setup (options_i &options, vw &all)
bool CCB::ec_is_example_header (example const &ec)
Variables
static constexpr uint32_t CCB::SHARED_EX_INDEX = 0
static constexpr uint32_t CCB::TOP_ACTION_INDEX = 0
Function Documentation
template<typename T > void return_v_array (v_array< T > & array, VW::v_array_pool< T > & pool)
Definition at line 27 of file conditional_contextual_bandit.cc.
References v_array< T >::clear(), and VW::value_object_pool< T, TAllocator, TDeleter >::return_object().
Referenced by CCB::delete_cb_labels(), and CCB::finish_multiline_example().
 {
   array.clear();
   pool.return_object(array);
 }