Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/confidence.h File Reference
confidence.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * confidence_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* confidence_setup (VW::config::options_i & options, vw & all)
Definition at line 90 of file confidence.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), return_confidence_example(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), and vw::training.
Referenced by parse_reductions().
 {
   bool confidence_arg = false;
   bool confidence_after_training = false;
   option_group_definition new_options("Confidence");
   new_options.add(make_option("confidence", confidence_arg).keep().help("Get confidence for binary predictions"))
       .add(make_option("confidence_after_training", confidence_after_training).help("Confidence after training"));
   options.add_and_parse(new_options);
   if (!confidence_arg)
     return nullptr;
   if (!all.training)
   {
     std::cout
         << "Confidence does not work in test mode because learning algorithm state is needed.  Use --save_resume when "
            "saving the model and avoid --test_only"
         << std::endl;
     return nullptr;
   }
   auto data = scoped_calloc_or_throw<confidence>();
   data->all = &all;
   void (*learn_with_confidence_ptr)(confidence&, single_learner&, example&) = nullptr;
   void (*predict_with_confidence_ptr)(confidence&, single_learner&, example&) = nullptr;
   if (confidence_after_training)
   {
     learn_with_confidence_ptr = predict_or_learn_with_confidence<true, true>;
     predict_with_confidence_ptr = predict_or_learn_with_confidence<false, true>;
   }
   else
   {
     learn_with_confidence_ptr = predict_or_learn_with_confidence<true, false>;
     predict_with_confidence_ptr = predict_or_learn_with_confidence<false, false>;
   }
   // Create new learner
   learner<confidence, example>& l = init_learner(
       data, as_singleline(setup_base(options, all)), learn_with_confidence_ptr, predict_with_confidence_ptr);
   l.set_finish_example(return_confidence_example);
   return make_base(l);
 }