Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/decision_scores.cc File Reference
decision_scores.cc File Reference
#include "decision_scores.h"
#include "slates.h"
#include "conditional_contextual_bandit.h"
#include "action_score.h"
#include "io_buf.h"
#include "global_data.h"
#include <iostream>
Namespaces
VW
Functions
template<typename LabelPrintFunc >
void print_update (vw &all, std::vector< example * > &slots, VW::decision_scores_t &decision_scores, size_t num_features, LabelPrintFunc label_print_func)
void VW::print_decision_scores (int f, VW::decision_scores_t &decision_scores)
void VW::delete_decision_scores (void *polypred)
void VW::print_update_ccb (vw &all, std::vector< example * > &slots, VW::decision_scores_t &decision_scores, size_t num_features)
void VW::print_update_slates (vw &all, std::vector< example * > &slots, VW::decision_scores_t &decision_scores, size_t num_features)
Function Documentation
template<typename LabelPrintFunc > void print_update (vw & all, std::vector< example * > & slots, VW::decision_scores_t & decision_scores, size_t num_features, LabelPrintFunc label_print_func)
Definition at line 16 of file decision_scores.cc.
References vw::bfgs, shared_data::col_current_label, shared_data::col_current_predict, vw::current_pass, shared_data::dump_interval, vw::holdout_set_off, vw::logger, shared_data::print_update(), vw::progress_add, vw::progress_arg, vw_logger::quiet, vw::sd, CCB::slot, and shared_data::weighted_examples().
Referenced by VW::print_update_ccb(), and VW::print_update_slates().
 {
   if (all.sd->weighted_examples() >= all.sd->dump_interval && !all.logger.quiet && !all.bfgs)
   {
     std::ostringstream label_buf;
     label_buf << std::setw(shared_data::col_current_label) << std::right << std::setfill(' ')
               << label_print_func(slots);
     std::stringstream pred_ss;
     std::string delim;
     size_t counter = 0;
     for (auto slot : decision_scores)
     {
       counter++;
       pred_ss << delim << slot[0].action;
       delim = ",";
       // Stop after 3...
       if (counter > 2)
       {
         pred_ss << delim << "...";
         break;
       }
     }
     std::ostringstream pred_buf;
     pred_buf << std::setw(shared_data::col_current_predict) << std::right << std::setfill(' ') << pred_ss.str();
     all.sd->print_update(all.holdout_set_off, all.current_pass, label_buf.str(), pred_buf.str(), num_features,
         all.progress_add, all.progress_arg);
   }
 }