Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/ect.h File Reference
ect.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * ect_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* ect_setup (VW::config::options_i & options, vw & all)
Definition at line 338 of file ect.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), create_circuit(), LEARNER::init_multiclass_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), vw::p, predict(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<ect>();
   std::string link;
   option_group_definition new_options("Error Correcting Tournament Options");
   new_options.add(make_option("ect", data->k).keep().help("Error correcting tournament with <k> labels"))
       .add(make_option("error", data->errors).keep().default_value(0).help("errors allowed by ECT"))
       // Used to check value. TODO replace
       .add(make_option("link", link)
                .default_value("identity")
                .keep()
                .help("Specify the link function: identity, logistic, glf1 or poisson"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("ect"))
     return nullptr;
   size_t wpp = create_circuit(*data.get(), data->k, data->errors + 1);
   base_learner* base = setup_base(options, all);
   if (link == "logistic")
     data->class_boundary = 0.5;  // as --link=logistic maps predictions in [0;1]
   learner<ect, example>& l = init_multiclass_learner(data, as_singleline(base), learn, predict, all.p, wpp);
   return make_base(l);
 }