Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/global_data.h File Reference
global_data.h File Reference
#include <iostream>
#include <iomanip>
#include <vector>
#include <map>
#include <cfloat>
#include <cstdint>
#include <cstdio>
#include <inttypes.h>
#include <climits>
#include <stack>
#include <unordered_map>
#include <string>
#include <array>
#include <memory>
#include "vw_string_view.h"
#include <thread>
#include "v_array.h"
#include "array_parameters.h"
#include "parse_primitives.h"
#include "loss_functions.h"
#include "comp_io.h"
#include "example.h"
#include "config.h"
#include "learner.h"
#include <time.h>
#include "hash.h"
#include "crossplat_compat.h"
#include "error_reporting.h"
#include "constant.h"
#include "rand48.h"
#include "hashstring.h"
#include "options.h"
#include "version.h"
Classes
struct dictionary_info
class namedlabels
struct shared_data
struct rand_state
struct vw_logger
struct vw
Typedefs
typedef float weight
typedef std::unordered_map< std::string, std::unique_ptr< features > > feature_dict
Enumerations
enum AllReduceType { Socket, Thread }
enum label_type_t {
label_type_t::simple, label_type_t::cb, label_type_t::cb_eval, label_type_t::cs,
label_type_t::multi, label_type_t::mc, label_type_t::ccb
}
Functions
void print_result (int f, float res, float weight, v_array< char > tag)
void print_result_by_ref (int f, float res, float weight, const v_array< char > &tag)
void binary_print_result (int f, float res, float weight, v_array< char > tag)
void binary_print_result_by_ref (int f, float res, float weight, const v_array< char > &tag)
void noop_mm (shared_data *, float label)
void get_prediction (int sock, float &res, float &weight)
void compile_gram (std::vector< std::string > grams, std::array< uint32_t, NUM_NAMESPACES > &dest, char *descriptor, bool quiet)
void compile_limits (std::vector< std::string > limits, std::array< uint32_t, NUM_NAMESPACES > &dest, bool quiet)
int print_tag (std::stringstream &ss, v_array< char > tag)
int print_tag_by_ref (std::stringstream &ss, const v_array< char > &tag)
Typedef Documentation
typedef std::unordered_map<std::string, std::unique_ptr<features> > feature_dict
Definition at line 53 of file global_data.h.
typedef float weight
Definition at line 51 of file global_data.h.
Enumeration Type Documentation
enum AllReduceType
Enumerator
Socket
Thread
Definition at line 314 of file global_data.h.
 {
   Socket,
   Thread
 };
enum label_type_t strong
Enumerator
simple
cb
cb_eval
cs
multi
mc
ccb
Definition at line 322 of file global_data.h.
 {
   simple,
   cb,       // contextual-bandit
   cb_eval,  // contextual-bandit evaluation
   cs,       // cost-sensitive
   multi,
   mc,
   ccb  // conditional contextual-bandit
 };
Function Documentation
void binary_print_result (int f, float res, float weight, v_array< char > tag)
Definition at line 80 of file global_data.cc.
References binary_print_result_by_ref().
Referenced by enable_sources(), vw::get_random_state(), and reset_source().
 {
   binary_print_result_by_ref(f, res, weight, array);
 }
void binary_print_result_by_ref (int f, float res, float weight, const v_array< char > & tag)
Definition at line 85 of file global_data.cc.
References send_prediction().
Referenced by binary_print_result(), enable_sources(), vw::get_random_state(), and reset_source().
 {
   if (f >= 0)
   {
     global_prediction ps = {res, weight};
     send_prediction(f, ps);
   }
 }
void compile_gram (std::vector< std::string > grams, std::array< uint32_t, NUM_NAMESPACES > & dest, char * descriptor, bool quiet)
Definition at line 244 of file global_data.cc.
Referenced by vw::get_random_state(), and parse_feature_tweaks().
 {
   for (size_t i = 0; i < grams.size(); i++)
   {
     std::string ngram = grams[i];
     if (isdigit(ngram[0]))
     {
       int n = atoi(ngram.c_str());
       if (!quiet)
         std::cerr << "Generating " << n << "-" << descriptor << " for all namespaces." << std::endl;
       for (size_t j = 0; j < 256; j++) dest[j] = n;
     }
     else if (ngram.size() == 1)
       std::cout << "You must specify the namespace index before the n" << std::endl;
     else
     {
       int n = atoi(ngram.c_str() + 1);
       dest[(uint32_t)(unsigned char)*ngram.c_str()] = n;
       if (!quiet)
         std::cerr << "Generating " << n << "-" << descriptor << " for " << ngram[0] << " namespaces." << std::endl;
     }
   }
 }
void compile_limits (std::vector< std::string > limits, std::array< uint32_t, NUM_NAMESPACES > & dest, bool quiet)
Definition at line 269 of file global_data.cc.
Referenced by vw::get_random_state(), and parse_feature_tweaks().
 {
   for (size_t i = 0; i < limits.size(); i++)
   {
     std::string limit = limits[i];
     if (isdigit(limit[0]))
     {
       int n = atoi(limit.c_str());
       if (!quiet)
         std::cerr << "limiting to " << n << "features for each namespace." << std::endl;
       for (size_t j = 0; j < 256; j++) dest[j] = n;
     }
     else if (limit.size() == 1)
       std::cout << "You must specify the namespace index before the n" << std::endl;
     else
     {
       int n = atoi(limit.c_str() + 1);
       dest[(uint32_t)limit[0]] = n;
       if (!quiet)
         std::cerr << "limiting to " << n << " for namespaces " << limit[0] << std::endl;
     }
   }
 }
void get_prediction (int sock, float & res, float & weight)
Definition at line 60 of file global_data.cc.
References global_prediction::p, really_read(), and global_prediction::weight.
Referenced by vw::get_random_state().
 {
   global_prediction p;
   really_read(sock, &p, sizeof(p));
   res = p.p;
   weight = p.weight;
 }
void noop_mm (shared_data * , float label)
Definition at line 177 of file global_data.cc.
Referenced by vw::get_random_state(), getLossFunction(), parse_example_tweaks(), and predict_or_learn_multi().
 {}
void print_result (int f, float res, float weight, v_array< char > tag)
Definition at line 109 of file global_data.cc.
References print_result_by_ref().
Referenced by vw::get_random_state(), and vw::vw().
 {
   print_result_by_ref(f, res, unused, tag);
 }
void print_result_by_ref (int f, float res, float weight, const v_array< char > & tag)
Definition at line 114 of file global_data.cc.
References print_tag_by_ref(), and io_buf::write_file_or_socket().
Referenced by enable_sources(), vw::get_random_state(), mf_print_audit_features(), GD::print_audit_features(), print_result(), reset_source(), and vw::vw().
 {
   if (f >= 0)
   {
     std::stringstream ss;
     auto saved_precision = ss.precision();
     if (floorf(res) == res)
       ss << std::setprecision(0);
     ss << std::fixed << res << std::setprecision(saved_precision);
     print_tag_by_ref(ss, tag);
     ss << '\n';
     ssize_t len = ss.str().size();
     ssize_t t = io_buf::write_file_or_socket(f, ss.str().c_str(), (unsigned int)len);
     if (t != len)
     {
       std::cerr << "write error: " << strerror(errno) << std::endl;
     }
   }
 }
int print_tag (std::stringstream & ss, v_array< char > tag)
Definition at line 104 of file global_data.cc.
References print_tag_by_ref().
Referenced by vw::get_random_state().
 {
   return print_tag_by_ref(ss, tag);
 }
int print_tag_by_ref (std::stringstream & ss, const v_array< char > & tag)
Definition at line 94 of file global_data.cc.
References v_array< T >::begin(), v_array< T >::end(), and v_array< T >::size().
Referenced by active_print_result(), confidence_print_result(), vw::get_random_state(), ACTION_SCORE::print_action_score(), print_raw_text(), print_raw_text_by_ref(), print_result(), print_result_by_ref(), and print_tag().
 {
   if (tag.begin() != tag.end())
   {
     ss << ' ';
     ss.write(tag.begin(), sizeof(char) * tag.size());
   }
   return tag.begin() != tag.end();
 }