Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/global_data.cc File Reference
global_data.cc File Reference
#include <cstdio>
#include <cfloat>
#include <cerrno>
#include <iostream>
#include <sstream>
#include <cmath>
#include <cassert>
#include "global_data.h"
#include "gd.h"
#include "vw_exception.h"
#include "future_compat.h"
#include <sys/socket.h>
Classes
struct global_prediction
Functions
size_t really_read (int sock, void *in, size_t count)
void get_prediction (int sock, float &res, float &weight)
void send_prediction (int sock, global_prediction p)
void binary_print_result (int f, float res, float weight, v_array< char > array)
void binary_print_result_by_ref (int f, float res, float weight, const v_array< char > &)
int print_tag_by_ref (std::stringstream &ss, const v_array< char > &tag)
int print_tag (std::stringstream &ss, v_array< char > tag)
void print_result (int f, float res, float unused, v_array< char > tag)
void print_result_by_ref (int f, float res, float, const v_array< char > &tag)
void print_raw_text (int f, std::string s, v_array< char > tag)
void print_raw_text_by_ref (int f, const std::string &s, const v_array< char > &tag)
void set_mm (shared_data *sd, float label)
void noop_mm (shared_data *, float)
void compile_gram (std::vector< std::string > grams, std::array< uint32_t, NUM_NAMESPACES > &dest, char *descriptor, bool quiet)
void compile_limits (std::vector< std::string > limits, std::array< uint32_t, NUM_NAMESPACES > &dest, bool quiet)
void trace_listener_cerr (void *, const std::string &message)
Function Documentation
void binary_print_result (int f, float res, float weight, v_array< char > array)
Definition at line 80 of file global_data.cc.
References binary_print_result_by_ref().
Referenced by enable_sources(), vw::get_random_state(), and reset_source().
 {
   binary_print_result_by_ref(f, res, weight, array);
 }
void binary_print_result_by_ref (int f, float res, float weight, const v_array< char > &)
Definition at line 85 of file global_data.cc.
References send_prediction().
Referenced by binary_print_result(), enable_sources(), vw::get_random_state(), and reset_source().
 {
   if (f >= 0)
   {
     global_prediction ps = {res, weight};
     send_prediction(f, ps);
   }
 }
void compile_gram (std::vector< std::string > grams, std::array< uint32_t, NUM_NAMESPACES > & dest, char * descriptor, bool quiet)
Definition at line 244 of file global_data.cc.
Referenced by vw::get_random_state(), and parse_feature_tweaks().
 {
   for (size_t i = 0; i < grams.size(); i++)
   {
     std::string ngram = grams[i];
     if (isdigit(ngram[0]))
     {
       int n = atoi(ngram.c_str());
       if (!quiet)
         std::cerr << "Generating " << n << "-" << descriptor << " for all namespaces." << std::endl;
       for (size_t j = 0; j < 256; j++) dest[j] = n;
     }
     else if (ngram.size() == 1)
       std::cout << "You must specify the namespace index before the n" << std::endl;
     else
     {
       int n = atoi(ngram.c_str() + 1);
       dest[(uint32_t)(unsigned char)*ngram.c_str()] = n;
       if (!quiet)
         std::cerr << "Generating " << n << "-" << descriptor << " for " << ngram[0] << " namespaces." << std::endl;
     }
   }
 }
void compile_limits (std::vector< std::string > limits, std::array< uint32_t, NUM_NAMESPACES > & dest, bool quiet)
Definition at line 269 of file global_data.cc.
Referenced by vw::get_random_state(), and parse_feature_tweaks().
 {
   for (size_t i = 0; i < limits.size(); i++)
   {
     std::string limit = limits[i];
     if (isdigit(limit[0]))
     {
       int n = atoi(limit.c_str());
       if (!quiet)
         std::cerr << "limiting to " << n << "features for each namespace." << std::endl;
       for (size_t j = 0; j < 256; j++) dest[j] = n;
     }
     else if (limit.size() == 1)
       std::cout << "You must specify the namespace index before the n" << std::endl;
     else
     {
       int n = atoi(limit.c_str() + 1);
       dest[(uint32_t)limit[0]] = n;
       if (!quiet)
         std::cerr << "limiting to " << n << " for namespaces " << limit[0] << std::endl;
     }
   }
 }
void get_prediction (int sock, float & res, float & weight)
Definition at line 60 of file global_data.cc.
References global_prediction::p, really_read(), and global_prediction::weight.
Referenced by vw::get_random_state().
 {
   global_prediction p;
   really_read(sock, &p, sizeof(p));
   res = p.p;
   weight = p.weight;
 }
void noop_mm (shared_data * , float)
Definition at line 177 of file global_data.cc.
Referenced by vw::get_random_state(), getLossFunction(), parse_example_tweaks(), and predict_or_learn_multi().
 {}
void print_raw_text (int f, std::string s, v_array< char > tag)
Definition at line 134 of file global_data.cc.
References print_tag_by_ref(), and io_buf::write_file_or_socket().
Referenced by vw::vw().
 {
   if (f < 0)
     return;
   std::stringstream ss;
   ss << s;
   print_tag_by_ref(ss, tag);
   ss << '\n';
   ssize_t len = ss.str().size();
   ssize_t t = io_buf::write_file_or_socket(f, ss.str().c_str(), (unsigned int)len);
   if (t != len)
   {
     std::cerr << "write error: " << strerror(errno) << std::endl;
   }
 }
void print_raw_text_by_ref (int f, const std::string & s, const v_array< char > & tag)
Definition at line 152 of file global_data.cc.
References print_tag_by_ref(), and io_buf::write_file_or_socket().
Referenced by vw::vw().
 {
   if (f < 0)
     return;
   std::stringstream ss;
   ss << s;
   print_tag_by_ref(ss, tag);
   ss << '\n';
   ssize_t len = ss.str().size();
   ssize_t t = io_buf::write_file_or_socket(f, ss.str().c_str(), (unsigned int)len);
   if (t != len)
   {
     std::cerr << "write error: " << strerror(errno) << std::endl;
   }
 }
void print_result (int f, float res, float unused, v_array< char > tag)
Definition at line 109 of file global_data.cc.
References print_result_by_ref().
Referenced by vw::get_random_state(), and vw::vw().
 {
   print_result_by_ref(f, res, unused, tag);
 }
void print_result_by_ref (int f, float res, float , const v_array< char > & tag)
Definition at line 114 of file global_data.cc.
References print_tag_by_ref(), and io_buf::write_file_or_socket().
Referenced by enable_sources(), vw::get_random_state(), mf_print_audit_features(), GD::print_audit_features(), print_result(), reset_source(), and vw::vw().
 {
   if (f >= 0)
   {
     std::stringstream ss;
     auto saved_precision = ss.precision();
     if (floorf(res) == res)
       ss << std::setprecision(0);
     ss << std::fixed << res << std::setprecision(saved_precision);
     print_tag_by_ref(ss, tag);
     ss << '\n';
     ssize_t len = ss.str().size();
     ssize_t t = io_buf::write_file_or_socket(f, ss.str().c_str(), (unsigned int)len);
     if (t != len)
     {
       std::cerr << "write error: " << strerror(errno) << std::endl;
     }
   }
 }
int print_tag (std::stringstream & ss, v_array< char > tag)
Definition at line 104 of file global_data.cc.
References print_tag_by_ref().
Referenced by vw::get_random_state().
 {
   return print_tag_by_ref(ss, tag);
 }
int print_tag_by_ref (std::stringstream & ss, const v_array< char > & tag)
Definition at line 94 of file global_data.cc.
References v_array< T >::begin(), v_array< T >::end(), and v_array< T >::size().
Referenced by active_print_result(), confidence_print_result(), vw::get_random_state(), ACTION_SCORE::print_action_score(), print_raw_text(), print_raw_text_by_ref(), print_result(), print_result_by_ref(), and print_tag().
 {
   if (tag.begin() != tag.end())
   {
     ss << ' ';
     ss.write(tag.begin(), sizeof(char) * tag.size());
   }
   return tag.begin() != tag.end();
 }
size_t really_read (int sock, void * in, size_t count)
Definition at line 32 of file global_data.cc.
References endif(), and THROWERRNO.
Referenced by get_prediction().
 {
   char* buf = (char*)in;
   size_t done = 0;
   int r = 0;
   while (done < count)
   {
     if ((r =
 #ifdef _WIN32
                 recv(sock, buf, (unsigned int)(count - done), 0)
 #else
                 read(sock, buf, (unsigned int)(count - done))
 #endif
                 ) == 0)
       return 0;
     else if (r < 0)
     {
       THROWERRNO("read(" << sock << "," << count << "-" << done << ")");
     }
     else
     {
       done += r;
       buf += r;
     }
   }
   return done;
 }
void send_prediction (int sock, global_prediction p)
Definition at line 68 of file global_data.cc.
References endif(), and THROWERRNO.
Referenced by binary_print_result_by_ref().
 {
   if (
 #ifdef _WIN32
       send(sock, reinterpret_cast<const char*>(&p), sizeof(p), 0)
 #else
       write(sock, &p, sizeof(p))
 #endif
       < (int)sizeof(p))
     THROWERRNO("send_prediction write(" << sock << ")");
 }
void set_mm (shared_data * sd, float label)
Definition at line 170 of file global_data.cc.
References shared_data::max_label, and shared_data::min_label.
Referenced by vw::vw().
 {
   sd->min_label = std::min(sd->min_label, label);
   if (label != FLT_MAX)
     sd->max_label = std::max(sd->max_label, label);
 }
void trace_listener_cerr (void * , const std::string & message)
Definition at line 293 of file global_data.cc.
Referenced by vw_ostream::vw_ostream().
 {
   std::cerr << message;
   std::cerr.flush();
 }