Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/kernel_svm.h File Reference
kernel_svm.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * kernel_svm_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* kernel_svm_setup (VW::config::options_i & options, vw & all)
Definition at line 861 of file kernel_svm.cc.
References vw::active, VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), vw::all_reduce, f, vw::get_random_state(), getLossFunction(), LEARNER::init_learner(), vw::l2_lambda, learn(), vw::loss, LEARNER::make_base(), VW::config::make_option(), predict(), save_load(), LEARNER::learner< T, E >::set_save_load(), SVM_KER_LIN, SVM_KER_POLY, SVM_KER_RBF, AllReduce::total, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto params = scoped_calloc_or_throw<svm_params>();
   std::string kernel_type;
   float bandwidth = 1.f;
   int degree = 2;
   bool ksvm = false;
   option_group_definition new_options("Kernel SVM");
   new_options.add(make_option("ksvm", ksvm).keep().help("kernel svm"))
       .add(make_option("reprocess", params->reprocess).default_value(1).help("number of reprocess steps for LASVM"))
       .add(make_option("pool_greedy", params->active_pool_greedy).help("use greedy selection on mini pools"))
       .add(make_option("para_active", params->para_active).help("do parallel active learning"))
       .add(make_option("pool_size", params->pool_size).default_value(1).help("size of pools for active learning"))
       .add(make_option("subsample", params->subsample)
                .default_value(1)
                .help("number of items to subsample from the pool"))
       .add(make_option("kernel", kernel_type)
                .keep()
                .default_value("linear")
                .help("type of kernel (rbf or linear (default))"))
       .add(make_option("bandwidth", bandwidth).keep().default_value(1.f).help("bandwidth of rbf kernel"))
       .add(make_option("degree", degree).keep().default_value(2).help("degree of poly kernel"));
   options.add_and_parse(new_options);
   if (!ksvm)
   {
     return nullptr;
   }
   std::string loss_function = "hinge";
   float loss_parameter = 0.0;
   delete all.loss;
   all.loss = getLossFunction(all, loss_function, (float)loss_parameter);
   params->model = &calloc_or_throw<svm_model>();
   params->model->num_support = 0;
   params->maxcache = 1024 * 1024 * 1024;
   params->loss_sum = 0.;
   params->all = &all;
   params->_random_state = all.get_random_state();
   // This param comes from the active reduction.
   // During options refactor: this changes the semantics a bit - now this will only be true if --active was supplied and
   // NOT --simulation
   if (all.active)
     params->active = true;
   if (params->active)
     params->active_c = 1.;
   params->pool = calloc_or_throw<svm_example*>(params->pool_size);
   params->pool_pos = 0;
   if (!options.was_supplied("subsample") && params->para_active)
     params->subsample = (size_t)ceil(params->pool_size / all.all_reduce->total);
   params->lambda = all.l2_lambda;
   if (params->lambda == 0.)
     params->lambda = 1.;
   params->all->trace_message << "Lambda = " << params->lambda << endl;
   params->all->trace_message << "Kernel = " << kernel_type << endl;
   if (kernel_type.compare("rbf") == 0)
   {
     params->kernel_type = SVM_KER_RBF;
     params->all->trace_message << "bandwidth = " << bandwidth << endl;
     params->kernel_params = &calloc_or_throw<double>();
     *((float*)params->kernel_params) = bandwidth;
   }
   else if (kernel_type.compare("poly") == 0)
   {
     params->kernel_type = SVM_KER_POLY;
     params->all->trace_message << "degree = " << degree << endl;
     params->kernel_params = &calloc_or_throw<int>();
     *((int*)params->kernel_params) = degree;
   }
   else
     params->kernel_type = SVM_KER_LIN;
   params->all->weights.stride_shift(0);
   learner<svm_params, example>& l = init_learner(params, learn, predict, 1);
   l.set_save_load(save_load);
   return make_base(l);
 }