Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/lda_core.h File Reference
lda_core.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * lda_setup (VW::config::options_i &, vw &)
void get_top_weights (vw *all, int top_words_count, int topic, std::vector< feature > &output)
Function Documentation
void get_top_weights (vw * all, int top_words_count, int topic, std::vector< feature > & output)
Definition at line 1102 of file lda_core.cc.
References parameters::dense_weights, get_top_weights(), parameters::sparse, parameters::sparse_weights, and vw::weights.
 {
   if (all->weights.sparse)
     get_top_weights(all, top_words_count, topic, output, all->weights.sparse_weights);
   else
     get_top_weights(all, top_words_count, topic, output, all->weights.dense_weights);
 }
LEARNER::base_learner* lda_setup (VW::config::options_i & , vw &)
Definition at line 1324 of file lda_core.cc.
References parser::_shared_data, add(), VW::config::options_i::add_and_parse(), vw::add_constant, vw::delete_prediction, delete_scalars(), end_examples(), end_pass(), vw::eta, f, VW::finish_example(), LEARNER::init_learner(), vw::initial_t, vw::lda, learn(), learn_with_metrics(), parser::lp, LEARNER::make_base(), VW::config::make_option(), next_pow2(), no_label::no_label_parser, vw::num_bits, vw::p, predict(), predict_with_metrics(), vw::random_weights, parser::ring_size, save_load(), scalars, vw::sd, LEARNER::learner< T, E >::set_end_examples(), LEARNER::learner< T, E >::set_end_pass(), LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_save_load(), parser::strict_parse, parameters::stride_shift(), UINT64_ONE, USE_SIMD, VW::config::options_i::was_supplied(), and vw::weights.
Referenced by parse_reductions().
 {
   auto ld = scoped_calloc_or_throw<lda>();
   option_group_definition new_options("Latent Dirichlet Allocation");
   int math_mode;
   new_options.add(make_option("lda", ld->topics).keep().help("Run lda with <int> topics"))
       .add(make_option("lda_alpha", ld->lda_alpha)
                .keep()
                .default_value(0.1f)
                .help("Prior on sparsity of per-document topic weights"))
       .add(make_option("lda_rho", ld->lda_rho)
                .keep()
                .default_value(0.1f)
                .help("Prior on sparsity of topic distributions"))
       .add(make_option("lda_D", ld->lda_D).default_value(10000.0f).help("Number of documents"))
       .add(make_option("lda_epsilon", ld->lda_epsilon).default_value(0.001f).help("Loop convergence threshold"))
       .add(make_option("minibatch", ld->minibatch).default_value(1).help("Minibatch size, for LDA"))
       .add(make_option("math-mode", math_mode).default_value(USE_SIMD).help("Math mode: simd, accuracy, fast-approx"))
       .add(make_option("metrics", ld->compute_coherence_metrics).help("Compute metrics"));
   options.add_and_parse(new_options);
   // Convert from int to corresponding enum value.
   ld->mmode = static_cast<lda_math_mode>(math_mode);
   ld->finish_example_count = 0;
   if (!options.was_supplied("lda"))
     return nullptr;
   all.lda = (uint32_t)ld->topics;
   all.delete_prediction = delete_scalars;
   ld->sorted_features = std::vector<index_feature>();
   ld->total_lambda_init = false;
   ld->all = &all;
   ld->example_t = all.initial_t;
   if (ld->compute_coherence_metrics)
   {
     ld->feature_counts.resize((uint32_t)(UINT64_ONE << all.num_bits));
     ld->feature_to_example_map.resize((uint32_t)(UINT64_ONE << all.num_bits));
   }
   float temp = ceilf(logf((float)(all.lda * 2 + 1)) / logf(2.f));
   all.weights.stride_shift((size_t)temp);
   all.random_weights = true;
   all.add_constant = false;
   if (all.eta > 1.)
   {
     std::cerr << "your learning rate is too high, setting it to 1" << std::endl;
     all.eta = std::min(all.eta, 1.f);
   }
   size_t minibatch2 = next_pow2(ld->minibatch);
   if (minibatch2 > all.p->ring_size)
   {
     bool previous_strict_parse = all.p->strict_parse;
     delete all.p;
     all.p = new parser{minibatch2, previous_strict_parse};
     all.p->_shared_data = all.sd;
   }
   ld->v.resize(all.lda * ld->minibatch);
   ld->decay_levels.push_back(0.f);
   all.p->lp = no_label::no_label_parser;
   LEARNER::learner<lda, example> &l = init_learner(ld, ld->compute_coherence_metrics ? learn_with_metrics : learn,
       ld->compute_coherence_metrics ? predict_with_metrics : predict, UINT64_ONE << all.weights.stride_shift(),
       prediction_type_t::scalars);
   l.set_save_load(save_load);
   l.set_finish_example(finish_example);
   l.set_end_examples(end_examples);
   l.set_end_pass(end_pass);
   return make_base(l);
 }