Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/learner.cc File Reference
learner.cc File Reference
#include "learner.h"
#include "parser.h"
#include "vw.h"
#include "parse_regressor.h"
#include "parse_dispatch_loop.h"
Classes
class LEARNER::single_instance_context
class LEARNER::multi_instance_context
class LEARNER::single_example_handler< context_type >
class LEARNER::multi_example_handler< context_type >
class LEARNER::ready_examples_queue
class LEARNER::custom_examples_queue
Namespaces
LEARNER
Macros
#define CASE(type)
Functions
const char * to_string (prediction_type_t prediction_type)
void LEARNER::learn_ex (example &ec, vw &all)
void LEARNER::learn_multi_ex (multi_ex &ec_seq, vw &all)
void LEARNER::end_pass (example &ec, vw &all)
void LEARNER::save (example &ec, vw &all)
bool LEARNER::example_is_newline_not_header (example &ec, vw &all)
bool LEARNER::is_save_cmd (example *ec)
void LEARNER::drain_examples (vw &all)
template<typename queue_type , typename handler_type >
void LEARNER::process_examples (queue_type &examples, handler_type &handler)
template<typename context_type >
void LEARNER::generic_driver (ready_examples_queue &examples, context_type &context)
void LEARNER::generic_driver (vw &all)
void LEARNER::generic_driver (const std::vector< vw * > &all)
template<typename handler_type >
void LEARNER::generic_driver_onethread (vw &all)
float LEARNER::recur_sensitivity (void *, base_learner &base, example &ec)
Macro Definition Documentation
#define CASE (type)
Value:
case type:       \
    return #type;
Definition at line 12 of file learner.cc.
Referenced by to_string().
Function Documentation
const char* to_string (prediction_type_t prediction_type)
Definition at line 16 of file learner.cc.
References action_probs, action_scores, CASE, multiclass, multiclassprobs, multilabels, prob, scalar, and scalars.
Referenced by audit_regressor_feature(), cbify_setup(), cbifyldf_setup(), Search::end_examples(), GD::end_pass(), Search::end_pass(), CCB::inject_slot_id(), make_write_cache(), CCB::print_update(), save_load_header(), Search::setup(), and warm_cb_setup().
 {
   switch (prediction_type)
   {
     CASE(prediction_type_t::scalar)
     CASE(prediction_type_t::scalars)
     CASE(prediction_type_t::action_scores)
     CASE(prediction_type_t::action_probs)
     CASE(prediction_type_t::multiclass)
     CASE(prediction_type_t::multilabels)
     CASE(prediction_type_t::prob)
     CASE(prediction_type_t::multiclassprobs)
     default:
       return "<unsupported>";
   }
 }