Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/learner.h File Reference
learner.h File Reference
#include <iostream>
#include "memory.h"
#include "multiclass.h"
#include "simple_label.h"
#include "parser.h"
#include "future_compat.h"
#include <memory>
Classes
struct LEARNER::learner< T, E >
struct LEARNER::func_data
struct LEARNER::learn_data
struct LEARNER::sensitivity_data
struct LEARNER::save_load_data
struct LEARNER::finish_example_data
struct LEARNER::learner< T, E >
Namespaces
LEARNER
Typedefs
using LEARNER::single_learner = learner< char, example >
using LEARNER::multi_learner = learner< char, multi_ex >
Enumerations
enum prediction_type_t {
prediction_type_t::scalar, prediction_type_t::scalars, prediction_type_t::action_scores, prediction_type_t::action_probs,
prediction_type_t::multiclass, prediction_type_t::multilabels, prediction_type_t::prob, prediction_type_t::multiclassprobs,
prediction_type_t::decision_probs
}
Functions
const char * to_string (prediction_type_t prediction_type)
func_data LEARNER::tuple_dbf (void *data, base_learner *base, void(*func)(void *))
void LEARNER::generic_driver (vw &all)
void LEARNER::generic_driver (const std::vector< vw * > &all)
template<typename handler_type >
void LEARNER::generic_driver_onethread (vw &all)
void LEARNER::noop_sl (void *, io_buf &, bool, bool)
void LEARNER::noop (void *)
float LEARNER::noop_sensitivity (void *, base_learner &, example &)
float LEARNER::recur_sensitivity (void *, base_learner &base, example &ec)
void LEARNER::increment_offset (example &ex, const size_t increment, const size_t i)
void LEARNER::increment_offset (multi_ex &ec_seq, const size_t increment, const size_t i)
void LEARNER::decrement_offset (example &ex, const size_t increment, const size_t i)
void LEARNER::decrement_offset (multi_ex &ec_seq, const size_t increment, const size_t i)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws, prediction_type_t pred_type)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (free_ptr< T > &dat, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t params_per_weight)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (void(*predict)(T &, L &, E &), size_t params_per_weight)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (free_ptr< T > &dat, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t params_per_weight, prediction_type_t pred_type)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &))
template<class T , class E , class L >
learner< T, E > & LEARNER::init_learner (L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &))
template<class T , class E , class L >
learner< T, E > & LEARNER::init_multiclass_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), parser *p, size_t ws, prediction_type_t pred_type=prediction_type_t::multiclass)
template<class T , class E , class L >
learner< T, E > & LEARNER::init_cost_sensitive_learner (free_ptr< T > &dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), parser *p, size_t ws, prediction_type_t pred_type=prediction_type_t::multiclass)
template<class T , class E >
base_learner * LEARNER::make_base (learner< T, E > &base)
template<class T , class E >
multi_learner * LEARNER::as_multiline (learner< T, E > *l)
template<class T , class E >
single_learner * LEARNER::as_singleline (learner< T, E > *l)
template<bool is_learn>
void LEARNER::multiline_learn_or_predict (multi_learner &base, multi_ex &examples, const uint64_t offset, const uint32_t id=0)
Enumeration Type Documentation
enum prediction_type_t strong
Enumerator
scalar
scalars
action_scores
action_probs
multiclass
multilabels
prob
multiclassprobs
decision_probs
Definition at line 15 of file learner.h.
 {
   scalar,
   scalars,
   action_scores,
   action_probs,
   multiclass,
   multilabels,
   prob,
   multiclassprobs,
   decision_probs
 };
Function Documentation
const char* to_string (prediction_type_t prediction_type)
Definition at line 16 of file learner.cc.
References action_probs, action_scores, CASE, multiclass, multiclassprobs, multilabels, prob, scalar, and scalars.
Referenced by audit_regressor_feature(), cbify_setup(), cbifyldf_setup(), Search::end_examples(), GD::end_pass(), Search::end_pass(), CCB::inject_slot_id(), make_write_cache(), CCB::print_update(), save_load_header(), Search::setup(), and warm_cb_setup().
 {
   switch (prediction_type)
   {
     CASE(prediction_type_t::scalar)
     CASE(prediction_type_t::scalars)
     CASE(prediction_type_t::action_scores)
     CASE(prediction_type_t::action_probs)
     CASE(prediction_type_t::multiclass)
     CASE(prediction_type_t::multilabels)
     CASE(prediction_type_t::prob)
     CASE(prediction_type_t::multiclassprobs)
     default:
       return "<unsupported>";
   }
 }