Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/log_multi.h File Reference
log_multi.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * log_multi_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* log_multi_setup (VW::config::options_i & options, vw & all)
Definition at line 495 of file log_multi.cc.
References add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), getLossFunction(), LEARNER::init_multiclass_learner(), init_tree(), learn(), vw::loss, LEARNER::make_base(), VW::config::make_option(), vw::p, predict(), save_load_tree(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<log_multi>();
   option_group_definition new_options("Logarithmic Time Multiclass Tree");
   new_options.add(make_option("log_multi", data->k).keep().help("Use online tree for multiclass"))
       .add(make_option("no_progress", data->progress).help("disable progressive validation"))
       .add(make_option("swap_resistance", data->swap_resist).default_value(4).help("disable progressive validation"))
       .add(make_option("swap_resistance", data->swap_resist)
                .default_value(4)
                .help("higher = more resistance to swap, default=4"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("log_multi"))
     return nullptr;
   data->progress = !data->progress;
   std::string loss_function = "quantile";
   float loss_parameter = 0.5;
   delete (all.loss);
   all.loss = getLossFunction(all, loss_function, loss_parameter);
   data->max_predictors = data->k - 1;
   init_tree(*data.get());
   learner<log_multi, example>& l = init_multiclass_learner(
       data, as_singleline(setup_base(options, all)), learn, predict, all.p, data->max_predictors);
   l.set_save_load(save_load_tree);
   return make_base(l);
 }