Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/loss_functions.h File Reference
loss_functions.h File Reference
#include <string>
#include "parse_primitives.h"
Classes
class loss_function
Functions
loss_function * getLossFunction (vw &, std::string funcName, float function_parameter=0)
Function Documentation
loss_function* getLossFunction (vw & , std::string funcName, float function_parameter = 0)
Definition at line 361 of file loss_functions.cc.
References shared_data::max_label, shared_data::min_label, noop_mm(), vw::sd, vw::set_minmax, and THROW.
Referenced by kernel_svm_setup(), log_multi_setup(), nn_setup(), parse_example_tweaks(), and loss_function::~loss_function().
 {
   if (funcName.compare("squared") == 0 || funcName.compare("Huber") == 0)
     return new squaredloss();
   else if (funcName.compare("classic") == 0)
     return new classic_squaredloss();
   else if (funcName.compare("hinge") == 0)
     return new hingeloss();
   else if (funcName.compare("logistic") == 0)
   {
     if (all.set_minmax != noop_mm)
     {
       all.sd->min_label = -50;
       all.sd->max_label = 50;
     }
     return new logloss();
   }
   else if (funcName.compare("quantile") == 0 || funcName.compare("pinball") == 0 || funcName.compare("absolute") == 0)
   {
     return new quantileloss(function_parameter);
   }
   else if (funcName.compare("poisson") == 0)
   {
     if (all.set_minmax != noop_mm)
     {
       all.sd->min_label = -50;
       all.sd->max_label = 50;
     }
     return new poisson_loss();
   }
   else
     THROW("Invalid loss function name: \'" << funcName << "\' Bailing!");
 }