Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/marginal.cc File Reference
marginal.cc File Reference
#include <unordered_map>
#include "reductions.h"
#include "correctedMath.h"
Classes
struct MARGINAL::expert
struct MARGINAL::data
Namespaces
MARGINAL
Typedefs
typedef std::pair< double, double > MARGINAL::marginal
typedef std::pair< expert, expert > MARGINAL::expert_pair
Functions
float MARGINAL::get_adanormalhedge_weights (float R, float C)
template<bool is_learn>
void MARGINAL::make_marginal (data &sm, example &ec)
void MARGINAL::undo_marginal (data &sm, example &ec)
template<bool is_learn>
void MARGINAL::compute_expert_loss (data &sm, example &ec)
void MARGINAL::update_marginal (data &sm, example &ec)
template<bool is_learn>
void MARGINAL::predict_or_learn (data &sm, LEARNER::single_learner &base, example &ec)
void MARGINAL::save_load (data &sm, io_buf &io, bool read, bool text)
LEARNER::base_learner * marginal_setup (options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* marginal_setup (options_i & options, vw & all)
Definition at line 350 of file marginal.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), MARGINAL::save_load(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   free_ptr<MARGINAL::data> d = scoped_calloc_or_throw<MARGINAL::data>();
   std::string marginal;
   option_group_definition marginal_options("VW options");
   marginal_options.add(make_option("marginal", marginal).keep().help("substitute marginal label estimates for ids"));
   marginal_options.add(
       make_option("initial_denominator", d->initial_denominator).default_value(1.f).help("initial denominator"));
   marginal_options.add(
       make_option("initial_numerator", d->initial_numerator).default_value(0.5f).help("initial numerator"));
   marginal_options.add(make_option("compete", d->compete).help("enable competition with marginal features"));
   marginal_options.add(
       make_option("update_before_learn", d->update_before_learn).help("update marginal values before learning"));
   marginal_options.add(make_option("unweighted_marginals", d->unweighted_marginals)
                            .help("ignore importance weights when computing marginals"));
   marginal_options.add(
       make_option("decay", d->decay).default_value(0.f).help("decay multiplier per event (1e-3 for example)"));
   options.add_and_parse(marginal_options);
   if (!options.was_supplied("marginal"))
   {
     return nullptr;
   }
   d->all = &all;
   for (size_t u = 0; u < 256; u++)
     if (marginal.find((char)u) != std::string::npos)
       d->id_features[u] = true;
   LEARNER::learner<MARGINAL::data, example>& ret =
       init_learner(d, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>);
   ret.set_save_load(save_load);
   return make_base(ret);
 }