Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/mf.h File Reference
mf.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * mf_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* mf_setup (VW::config::options_i & options, vw & all)
Definition at line 195 of file mf.cc.
References VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), finish(), LEARNER::init_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), vw::pairs, vw::random_positive_weights, LEARNER::learner< T, E >::set_finish(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<mf>();
   option_group_definition new_options("Matrix Factorization Reduction");
   new_options.add(make_option("new_mf", data->rank).keep().help("rank for reduction-based matrix factorization"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("new_mf"))
     return nullptr;
   data->all = &all;
   // store global pairs in local data structure and clear global pairs
   // for eventual calls to base learner
   data->pairs = all.pairs;
   all.pairs.clear();
   all.random_positive_weights = true;
   learner<mf, example>& l =
       init_learner(data, as_singleline(setup_base(options, all)), learn, predict<false>, 2 * data->rank + 1);
   l.set_finish(finish);
   return make_base(l);
 }