Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/mwt.cc File Reference
mwt.cc File Reference
#include "vw.h"
#include "reductions.h"
#include "gd.h"
#include "cb_algs.h"
#include "io_buf.h"
Classes
struct MWT::policy_data
struct MWT::mwt
Namespaces
MWT
Functions
bool MWT::observed_cost (CB::cb_class *cl)
CB::cb_class * MWT::get_observed_cost (CB::label &ld)
void MWT::value_policy (mwt &c, float val, uint64_t index)
template<bool learn, bool exclude, bool is_learn>
void MWT::predict_or_learn (mwt &c, single_learner &base, example &ec)
void MWT::print_scalars (int f, v_array< float > &scalars, v_array< char > &tag)
void MWT::finish_example (vw &all, mwt &c, example &ec)
void MWT::save_load (mwt &c, io_buf &model_file, bool read, bool text)
base_learner * mwt_setup (options_i &options, vw &all)
Function Documentation
base_learner* mwt_setup (options_i & options, vw & all)
Definition at line 233 of file mwt.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), c, calloc_reserve(), cb, CB::cb_label, vw::delete_prediction, delete_scalars(), MWT::finish_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, vw::length(), parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, MWT::save_load(), scalars, LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_save_load(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto c = scoped_calloc_or_throw<mwt>();
   std::string s;
   bool exclude_eval = false;
   option_group_definition new_options("Multiworld Testing Options");
   new_options.add(make_option("multiworld_test", s).keep().help("Evaluate features as a policies"))
       .add(make_option("learn", c->num_classes).help("Do Contextual Bandit learning on <n> classes."))
       .add(make_option("exclude_eval", exclude_eval).help("Discard mwt policy features before learning"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("multiworld_test"))
     return nullptr;
   for (char i : s) c->namespaces[(unsigned char)i] = true;
   c->all = &all;
   calloc_reserve(c->evals, all.length());
   c->evals.end() = c->evals.begin() + all.length();
   all.delete_prediction = delete_scalars;
   all.p->lp = CB::cb_label;
   all.label_type = label_type_t::cb;
   if (c->num_classes > 0)
   {
     c->learn = true;
     if (!options.was_supplied("cb"))
     {
       std::stringstream ss;
       ss << c->num_classes;
       options.insert("cb", ss.str());
     }
   }
   learner<mwt, example>* l;
   if (c->learn)
     if (exclude_eval)
       l = &init_learner(c, as_singleline(setup_base(options, all)), predict_or_learn<true, true, true>,
           predict_or_learn<true, true, false>, 1, prediction_type_t::scalars);
     else
       l = &init_learner(c, as_singleline(setup_base(options, all)), predict_or_learn<true, false, true>,
           predict_or_learn<true, false, false>, 1, prediction_type_t::scalars);
   else
     l = &init_learner(c, as_singleline(setup_base(options, all)), predict_or_learn<false, false, true>,
         predict_or_learn<false, false, false>, 1, prediction_type_t::scalars);
   l->set_save_load(save_load);
   l->set_finish_example(finish_example);
   return make_base(*l);
 }