Vowpal Wabbit: EXPLORE_EVAL Namespace Reference
EXPLORE_EVAL Namespace Reference
Classes
struct explore_eval
Functions
void finish (explore_eval &data)
void output_example (vw &all, explore_eval &c, example &ec, multi_ex *ec_seq)
void output_example_seq (vw &all, explore_eval &data, multi_ex &ec_seq)
void finish_multiline_example (vw &all, explore_eval &data, multi_ex &ec_seq)
template<bool is_learn>
void do_actual_learning (explore_eval &data, multi_learner &base, multi_ex &ec_seq)
Function Documentation
template<bool is_learn> void EXPLORE_EVAL::do_actual_learning (explore_eval & data, multi_learner & base, multi_ex & ec_seq)
Definition at line 128 of file explore_eval.cc.
References EXPLORE_EVAL::explore_eval::_random_state, CB::cb_class::action, EXPLORE_EVAL::explore_eval::action_label, polylabel::cb, CB::label::costs, EXPLORE_EVAL::explore_eval::empty_label, EXPLORE_EVAL::explore_eval::fixed_multiplier, CB_ADF::get_observed_cost(), EXPLORE_EVAL::explore_eval::known_cost, example::l, EXPLORE_EVAL::explore_eval::multiplier, EXPLORE_EVAL::explore_eval::offset, CB::cb_class::probability, v_array< T >::size(), CB_ADF::test_adf_sequence(), EXPLORE_EVAL::explore_eval::update_count, EXPLORE_EVAL::explore_eval::violations, and example::weight.
 {
   example* label_example = CB_ADF::test_adf_sequence(ec_seq);
   if (label_example != nullptr)  // extract label
   {
     data.action_label = label_example->l.cb;
     label_example->l.cb = data.empty_label;
   }
   multiline_learn_or_predict<false>(base, ec_seq, data.offset);
   if (label_example != nullptr)  // restore label
     label_example->l.cb = data.action_label;
   data.known_cost = CB_ADF::get_observed_cost(ec_seq);
   if (label_example != nullptr && is_learn)
   {
     ACTION_SCORE::action_scores& a_s = ec_seq[0]->pred.a_s;
     float action_probability = 0;
     for (size_t i = 0; i < a_s.size(); i++)
       if (data.known_cost.action == a_s[i].action)
         action_probability = a_s[i].score;
     float threshold = action_probability / data.known_cost.probability;
     if (!data.fixed_multiplier)
       data.multiplier = std::min(data.multiplier, 1 / threshold);
     else
       threshold *= data.multiplier;
     if (threshold > 1. + 1e-6)
       data.violations++;
     if (data._random_state->get_and_update_random() < threshold)
     {
       example* ec_found = nullptr;
       for (example*& ec : ec_seq)
       {
         if (ec->l.cb.costs.size() == 1 && ec->l.cb.costs[0].cost != FLT_MAX && ec->l.cb.costs[0].probability > 0)
           ec_found = ec;
         if (threshold > 1)
           ec->weight *= threshold;
       }
       ec_found->l.cb.costs[0].probability = action_probability;
       multiline_learn_or_predict<true>(base, ec_seq, data.offset);
       if (threshold > 1)
       {
         float inv_threshold = 1.f / threshold;
         for (auto& ec : ec_seq) ec->weight *= inv_threshold;
       }
       ec_found->l.cb.costs[0].probability = data.known_cost.probability;
       data.update_count++;
     }
   }
 }
void EXPLORE_EVAL::finish (explore_eval & data)
Definition at line 40 of file explore_eval.cc.
References EXPLORE_EVAL::explore_eval::all, EXPLORE_EVAL::explore_eval::fixed_multiplier, vw::logger, EXPLORE_EVAL::explore_eval::multiplier, vw_logger::quiet, vw::trace_message, EXPLORE_EVAL::explore_eval::update_count, and EXPLORE_EVAL::explore_eval::violations.
Referenced by explore_eval_setup().
 {
   if (!data.all->logger.quiet)
   {
     data.all->trace_message << "update count = " << data.update_count << std::endl;
     if (data.violations > 0)
       data.all->trace_message << "violation count = " << data.violations << std::endl;
     if (!data.fixed_multiplier)
       data.all->trace_message << "final multiplier = " << data.multiplier << std::endl;
   }
 }
void EXPLORE_EVAL::finish_multiline_example (vw & all, explore_eval & data, multi_ex & ec_seq)
Definition at line 117 of file explore_eval.cc.
References vw::final_prediction_sink, VW::finish_example(), CB_ADF::global_print_newline(), and output_example_seq().
 {
   if (ec_seq.size() > 0)
   {
     output_example_seq(all, data, ec_seq);
     CB_ADF::global_print_newline(all.final_prediction_sink);
   }
   VW::finish_example(all, ec_seq);
 }
void EXPLORE_EVAL::output_example (vw & all, explore_eval & c, example & ec, multi_ex * ec_seq)
Definition at line 56 of file explore_eval.cc.
References polyprediction::a_s, polylabel::cb, CB::label::costs, CB::ec_is_example_header(), LEARNER::example_is_newline_not_header(), vw::final_prediction_sink, CB_ALGS::get_cost_estimate(), EXPLORE_EVAL::explore_eval::known_cost, example::l, loss(), example::pred, ACTION_SCORE::print_action_score(), vw::print_text_by_ref, CB::print_update(), CB::cb_class::probability, vw::raw_prediction, vw::sd, v_array< T >::size(), example::tag, shared_data::update(), and example::weight.
Referenced by output_example_seq().
 {
   if (example_is_newline_not_header(ec))
     return;
   size_t num_features = 0;
   float loss = 0.;
   ACTION_SCORE::action_scores preds = (*ec_seq)[0]->pred.a_s;
   for (size_t i = 0; i < (*ec_seq).size(); i++)
     if (!CB::ec_is_example_header(*(*ec_seq)[i]))
       num_features += (*ec_seq)[i]->num_features;
   bool labeled_example = true;
   if (c.known_cost.probability > 0)
   {
     for (uint32_t i = 0; i < preds.size(); i++)
     {
       float l = get_cost_estimate(&c.known_cost, preds[i].action);
       loss += l * preds[i].score;
     }
   }
   else
     labeled_example = false;
   bool holdout_example = labeled_example;
   for (size_t i = 0; i < ec_seq->size(); i++) holdout_example &= (*ec_seq)[i]->test_only;
   all.sd->update(holdout_example, labeled_example, loss, ec.weight, num_features);
   for (int sink : all.final_prediction_sink) print_action_score(sink, ec.pred.a_s, ec.tag);
   if (all.raw_prediction > 0)
   {
     std::string outputString;
     std::stringstream outputStringStream(outputString);
     const auto& costs = ec.l.cb.costs;
     for (size_t i = 0; i < costs.size(); i++)
     {
       if (i > 0)
         outputStringStream << ' ';
       outputStringStream << costs[i].action << ':' << costs[i].partial_prediction;
     }
     all.print_text_by_ref(all.raw_prediction, outputStringStream.str(), ec.tag);
   }
   CB::print_update(all, !labeled_example, ec, ec_seq, true);
 }
void EXPLORE_EVAL::output_example_seq (vw & all, explore_eval & data, multi_ex & ec_seq)
Definition at line 107 of file explore_eval.cc.
References output_example(), vw::print_text_by_ref, and vw::raw_prediction.
 {
   if (ec_seq.size() > 0)
   {
     output_example(all, data, **(ec_seq.begin()), &(ec_seq));
     if (all.raw_prediction > 0)
       all.print_text_by_ref(all.raw_prediction, "", ec_seq[0]->tag);
   }
 }