Vowpal Wabbit: DebugMT Namespace Reference
DebugMT Namespace Reference
Functions
void run (Search::search &sch, multi_ex &ec)
Variables
Search::search_metatask metatask = {"debug", run, nullptr, nullptr, nullptr, nullptr}
Function Documentation
void DebugMT::run (Search::search & sch, multi_ex & ec)
Definition at line 18 of file search_meta.cc.
References a, Search::search::base_task(), Search::BaseTask::foreach_action(), and Search::BaseTask::Run().
 {
   sch.base_task(ec)
       .foreach_action(
           [](Search::search& /*sch*/, size_t t, float min_cost, action a, bool taken, float a_cost) -> void {
             std::cerr << "==DebugMT== foreach_action(t=" << t << ", min_cost=" << min_cost << ", a=" << a
                       << ", taken=" << taken << ", a_cost=" << a_cost << ")" << std::endl;
           })
       .post_prediction([](Search::search& /*sch*/, size_t t, action a, float a_cost) -> void {
         std::cerr << "==DebugMT== post_prediction(t=" << t << ", a=" << a << ", a_cost=" << a_cost << ")" << std::endl;
       })
       .maybe_override_prediction([](Search::search& /*sch*/, size_t t, action& a, float& a_cost) -> bool {
         std::cerr << "==DebugMT== maybe_override_prediction(t=" << t << ", a=" << a << ", a_cost=" << a_cost << ")"
                   << std::endl;
         return false;
       })
       .final_run()
       .Run();
 }
Variable Documentation
Search::search_metatask DebugMT::metatask = {"debug", run, nullptr, nullptr, nullptr, nullptr}
Definition at line 16 of file search_meta.cc.