Vowpal Wabbit: VW::cb_explore_adf::first Namespace Reference
VW::cb_explore_adf::first Namespace Reference
Classes
struct cb_explore_adf_first
Functions
LEARNER::base_learner * setup (config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner * VW::cb_explore_adf::first::setup (config::options_i & options, vw & all)
Definition at line 74 of file cb_explore_adf_first.cc.
References action_probs, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), cb, CB::cb_label, ACTION_SCORE::delete_action_scores(), vw::delete_prediction, finish_multiline_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, learn(), parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, predict(), LEARNER::learner< T, E >::set_finish_example(), setup_base(), THROW, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   using config::make_option;
   bool cb_explore_adf_option = false;
   size_t tau = 0;
   float epsilon = 0.;
   config::option_group_definition new_options("Contextual Bandit Exploration with Action Dependent Features");
   new_options
       .add(make_option("cb_explore_adf", cb_explore_adf_option)
                .keep()
                .help("Online explore-exploit for a contextual bandit problem with multiline action dependent features"))
       .add(make_option("first", tau).keep().help("tau-first exploration"))
       .add(make_option("epsilon", epsilon).keep().allow_override().help("epsilon-greedy exploration"));
   options.add_and_parse(new_options);
   if (!cb_explore_adf_option || !options.was_supplied("first"))
     return nullptr;
   // Ensure serialization of cb_adf in all cases.
   if (!options.was_supplied("cb_adf"))
   {
     options.insert("cb_adf", "");
   }
   all.delete_prediction = ACTION_SCORE::delete_action_scores;
   size_t problem_multiplier = 1;
   LEARNER::multi_learner* base = LEARNER::as_multiline(setup_base(options, all));
   all.p->lp = CB::cb_label;
   all.label_type = label_type_t::cb;
   using explore_type = cb_explore_adf_base<cb_explore_adf_first>;
   auto data = scoped_calloc_or_throw<explore_type>(tau, epsilon);
   if (epsilon < 0.0 || epsilon > 1.0)
   {
     THROW("The value of epsilon must be in [0,1]");
   }
   LEARNER::learner<explore_type, multi_ex>& l = LEARNER::init_learner(
       data, base, explore_type::learn, explore_type::predict, problem_multiplier, prediction_type_t::action_probs);
   l.set_finish_example(explore_type::finish_multiline_example);
   return make_base(l);
 }