Vowpal Wabbit: slates Namespace Reference
slates Namespace Reference
Classes
struct label
struct slates_data
Enumerations
enum example_type : uint8_t { unset = 0, shared = 1, action = 2, slot = 3 }
Functions
std::string generate_slates_label_printout (const std::vector< example * > &slots)
void output_example (vw &all, slates_data &, multi_ex &ec_seq)
void finish_multiline_example (vw &all, slates_data &data, multi_ex &ec_seq)
template<bool is_learn>
void learn_or_predict (slates_data &data, LEARNER::multi_learner &base, multi_ex &examples)
LEARNER::base_learner * slates_setup (options_i &options, vw &all)
void default_label (void *v)
size_t read_cached_label (shared_data *, void *v, io_buf &cache)
void cache_label (void *v, io_buf &cache)
float weight (void *v)
bool test_label (void *v)
void delete_label (void *v)
void copy_label (void *dst, void *src)
void parse_label (parser *p, shared_data *, void *v, v_array< VW::string_view > &words)
Variables
label_parser slates_label_parser
Enumeration Type Documentation
enum slates::example_type : uint8_t
Enumerator
unset
shared
action
slot
Definition at line 15 of file slates_label.h.
                   : uint8_t
 {
   unset = 0,
   shared = 1,
   action = 2,
   slot = 3
 };
Function Documentation
void slates::cache_label (void * v, io_buf & cache)
Definition at line 57 of file slates_label.cc.
References io_buf::buf_write(), c, VW::convert(), slates::label::cost, slates::label::labeled, slates::label::probabilities, v_array< T >::size(), slates::label::slot_id, slates::label::type, slates::label::weight, and WRITE_CACHED_VALUE.
 {
   char* c;
   slates::label* ld = static_cast<slates::label*>(v);
   size_t size = sizeof(ld->type)
       + sizeof(ld->weight)
       + sizeof(ld->labeled)
       + sizeof(ld->cost)
       + sizeof(ld->slot_id)
       + sizeof(uint32_t) // Size of probabilities
       + sizeof(ACTION_SCORE::action_score) * ld->probabilities.size();
   cache.buf_write(c, size);
   WRITE_CACHED_VALUE(ld->type, slates::example_type);
   WRITE_CACHED_VALUE(ld->weight, float);
   WRITE_CACHED_VALUE(ld->labeled, bool);
   WRITE_CACHED_VALUE(ld->cost, float);
   WRITE_CACHED_VALUE(VW::convert(ld->slot_id), uint32_t);
   WRITE_CACHED_VALUE(VW::convert(ld->probabilities.size()), uint32_t);
   for (const auto& score : ld->probabilities)
   {
     WRITE_CACHED_VALUE(score, ACTION_SCORE::action_score);
   }
 }
void slates::copy_label (void * dst, void * src)
Definition at line 110 of file slates_label.cc.
References copy_array().
 {
   auto& ldDst = static_cast<polylabel*>(dst)->slates;
   auto& ldSrc = static_cast<polylabel*>(src)->slates;
   ldDst.type = ldSrc.type;
   ldDst.weight = ldSrc.weight;
   ldDst.labeled = ldSrc.labeled;
   ldDst.cost = ldSrc.cost;
   ldDst.slot_id = ldSrc.slot_id;
   copy_array(ldDst.probabilities, ldSrc.probabilities);
 }
void slates::default_label (void * v)
Definition at line 87 of file slates_label.cc.
References v_array< T >::clear(), slates::label::cost, slates::label::labeled, slates::label::probabilities, slates::label::slot_id, slates::label::type, CCB::unset, and slates::label::weight.
Referenced by read_cached_label().
 {
   auto& label = static_cast<polylabel*>(v)->slates;
   label.type = example_type::unset;
   label.weight = 1.f;
   label.labeled = false;
   label.cost = 0.f;
   label.slot_id = 0;
   label.probabilities.clear();
 }
void slates::delete_label (void * v)
Definition at line 104 of file slates_label.cc.
 {
   auto& ld = static_cast<polylabel*>(v)->slates;
   ld.probabilities.delete_v();
 }
void slates::finish_multiline_example (vw & all, slates_data & data, multi_ex & ec_seq)
Definition at line 213 of file slates.cc.
References vw::final_prediction_sink, VW::finish_example(), CB_ADF::global_print_newline(), and output_example().
 {
   if (!ec_seq.empty())
   {
     output_example(all, data, ec_seq);
     CB_ADF::global_print_newline(all.final_prediction_sink);
   }
   VW::finish_example(all, ec_seq);
 }
std::string slates::generate_slates_label_printout (const std::vector< example * > & slots)
Definition at line 128 of file slates.cc.
References slates::label::labeled, slates::label::probabilities, and CCB::slot.
Referenced by VW::print_update_slates().
 {
   size_t counter = 0;
   std::stringstream label_ss;
   std::string delim;
   for (const auto& slot : slots)
   {
     counter++;
     const auto& label = slot->l.slates;
     if (label.labeled )
     {
       label_ss << delim << label.probabilities[0].action;
     }
     else
     {
       label_ss << delim << "?";
     }
     delim = ",";
     // Stop after 2...
     if (counter > 1 && slots.size() > 2)
     {
       label_ss << delim << "...";
       break;
     }
   }
   return label_ss.str();
 }
template<bool is_learn> void slates::learn_or_predict (slates_data & data, LEARNER::multi_learner & base, multi_ex & examples)
Definition at line 225 of file slates.cc.
References slates::slates_data::learn(), and slates::slates_data::predict().
 {
   if (is_learn)
   {
     data.learn(base, examples);
   }
   else
   {
     data.predict(base, examples);
   }
 }
void slates::output_example (vw & all, slates_data & , multi_ex & ec_seq)
Definition at line 159 of file slates.cc.
References vw::final_prediction_sink, CB_ALGS::get_cost_estimate(), loss(), VW::print_decision_scores(), VW::print_update_slates(), vw::sd, SHARED_EX_INDEX, CCB::slot, example::test_only, THROW, TOP_ACTION_INDEX, and shared_data::update().
Referenced by finish_multiline_example().
 {
   std::vector<example*> slots;
   size_t num_features = 0;
   float loss = 0.;
   bool is_labelled = ec_seq[SHARED_EX_INDEX]->l.slates.labeled;
   float cost = is_labelled ? ec_seq[SHARED_EX_INDEX]->l.slates.cost : 0.f;
   for (auto ec : ec_seq)
   {
     num_features += ec->num_features;
     if (ec->l.slates.type == slates::example_type::slot)
     {
       slots.push_back(ec);
     }
   }
   auto predictions = ec_seq[0]->pred.decision_scores;
   for (size_t slot_index = 0; slot_index < slots.size(); slot_index++)
   {
     const auto& label_probabilties = slots[slot_index]->l.slates.probabilities;
     if (is_labelled)
     {
       if (label_probabilties.empty())
       {
         THROW("Probabilities missing for labeled example");
       }
       float l = CB_ALGS::get_cost_estimate(
           label_probabilties[TOP_ACTION_INDEX], cost, predictions[slot_index][TOP_ACTION_INDEX].action);
       loss += l * predictions[slot_index][TOP_ACTION_INDEX].score;
     }
   }
   bool holdout_example = is_labelled;
   if (holdout_example != false)
   {
     for (const auto& example : ec_seq)
     {
       holdout_example &= example->test_only;
     }
   }
   all.sd->update(holdout_example, is_labelled, loss, ec_seq[SHARED_EX_INDEX]->weight, num_features);
   for (auto sink : all.final_prediction_sink)
   {
     VW::print_decision_scores(sink, ec_seq[SHARED_EX_INDEX]->pred.decision_scores);
   }
   VW::print_update_slates(all, slots, predictions, num_features);
 }
void slates::parse_label (parser * p, shared_data * , void * v, v_array< VW::string_view > & words)
Definition at line 130 of file slates_label.cc.
References accumulate(), ACTION_TYPE, VW::math::are_same(), f, float_of_string(), int_of_string(), parser::parse_name, CCB::shared, SHARED_TYPE, v_array< T >::size(), SLATES_LABEL, CCB::slot, SLOT_TYPE, THROW, and tokenize().
 {
   auto& ld = static_cast<polylabel*>(v)->slates;
   ld.weight = 1;
   if (words.size() == 0)
   {
     THROW("Slates labels may not be empty");
   }
   if (!(words[0] == SLATES_LABEL))
   {
     THROW("Slates labels require the first word to be slates");
   }
   if (words.size() == 1)
   {
     THROW("Slates labels require a type. It must be one of: [shared, action, slot]");
   }
   const auto& type = words[1];
   if (type == SHARED_TYPE)
   {
     // There is a cost defined.
     if (words.size() == 3)
     {
       ld.cost = float_of_string(words[2]);
       ld.labeled = true;
     }
     else if (words.size() != 2)
     {
       THROW("Slates shared labels must be of the form: slates shared [global_cost]");
     }
     ld.type = example_type::shared;
   }
   else if (type == ACTION_TYPE)
   {
     if (words.size() != 3)
     {
       THROW("Slates action labels must be of the form: slates action <slot_id>");
     }
     ld.slot_id = int_of_string(words[2]);
     ld.type = example_type::action;
   }
   else if (type == SLOT_TYPE)
   {
     if (words.size() == 3)
     {
       ld.labeled = true;
       tokenize(',', words[2], p->parse_name);
       auto split_colons = v_init<VW::string_view>();
       for (auto& token : p->parse_name)
       {
         tokenize(':', token, split_colons);
         if (split_colons.size() != 2)
         {
           THROW("Malformed action score token");
         }
         // Element 0 is the action, element 1 is the probability
         ld.probabilities.push_back(
             {static_cast<uint32_t>(int_of_string(split_colons[0])), float_of_string(split_colons[1])});
       }
       split_colons.delete_v();
       // If a full distribution has been given, check if it sums to 1, otherwise throw.
       if (ld.probabilities.size() > 1)
       {
         float total_pred = std::accumulate(ld.probabilities.begin(), ld.probabilities.end(), 0.f,
             [](float result_so_far, const ACTION_SCORE::action_score& action_pred) {
               return result_so_far + action_pred.score;
             });
         if (!VW::math::are_same(total_pred, 1.f))
         {
           THROW(
               "When providing all prediction probabilities they must add up to 1.0, instead summed to " << total_pred);
         }
       }
     }
     else if (words.size() > 3)
     {
       THROW(
           "Slates shared labels must be of the form: slates slot "
           "[chosen_action_id:probability[,action_id:probability...]]");
     }
     ld.type = example_type::slot;
   }
   else
   {
     THROW("Unknown slates label type: " << type);
   }
 }
size_t slates::read_cached_label (shared_data * , void * v, io_buf & cache)
Definition at line 29 of file slates_label.cc.
References slates::label::cost, default_label(), slates::label::labeled, slates::label::probabilities, v_array< T >::push_back(), READ_CACHED_VALUE, slates::label::slot_id, slates::label::type, and slates::label::weight.
 {
   // Since read_cached_features doesn't default the label we must do it here.
   default_label(v);
   slates::label* ld = static_cast<slates::label*>(v);
   size_t read_count = 0;
   char* read_ptr;
   size_t next_read_size = 0;
   READ_CACHED_VALUE(ld->type, slates::example_type);
   READ_CACHED_VALUE(ld->weight, float);
   READ_CACHED_VALUE(ld->labeled, bool);
   READ_CACHED_VALUE(ld->cost, float);
   READ_CACHED_VALUE(ld->slot_id, uint32_t);
   uint32_t size_probs = 0;
   READ_CACHED_VALUE(size_probs, uint32_t);
   for (uint32_t i = 0; i < size_probs; i++)
   {
     ACTION_SCORE::action_score a_s;
     READ_CACHED_VALUE(a_s, ACTION_SCORE::action_score);
     ld->probabilities.push_back(a_s);
   }
   return read_count;
 }
LEARNER::base_learner * slates::slates_setup (options_i & options, vw & all)
Definition at line 237 of file slates.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), decision_probs, VW::delete_decision_scores(), vw::delete_prediction, finish_multiline_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, setup_base(), slates, slates_label_parser, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<slates_data>();
   bool slates_option = false;
   option_group_definition new_options("Slates");
   new_options.add(make_option("slates", slates_option).keep().help("EXPERIMENTAL"));
   options.add_and_parse(new_options);
   if (!slates_option)
   {
     return nullptr;
   }
   if (!options.was_supplied("ccb_explore_adf"))
   {
     options.insert("ccb_explore_adf", "");
     options.add_and_parse(new_options);
   }
   auto base = as_multiline(setup_base(options, all));
   all.p->lp = slates_label_parser;
   all.label_type = label_type_t::slates;
   all.delete_prediction = VW::delete_decision_scores;
   auto& l = LEARNER::init_learner(
       data, base, learn_or_predict<true>, learn_or_predict<false>, 1, prediction_type_t::decision_probs);
   l.set_finish_example(finish_multiline_example);
   return LEARNER::make_base(l);
 }
bool slates::test_label (void * v)
Definition at line 98 of file slates_label.cc.
 {
   auto& ld = static_cast<polylabel*>(v)->slates;
   return ld.labeled == false;
 }
float slates::weight (void * v)
Definition at line 82 of file slates_label.cc.
 {
   return static_cast<polylabel*>(v)->slates.weight;
 }
Variable Documentation
label_parser slates::slates_label_parser
Initial value:
= {default_label, parse_label, cache_label, read_cached_label, delete_label, weight,
    copy_label, test_label, sizeof(slates::label)}
Definition at line 226 of file slates_label.cc.
Referenced by slates_setup().