Vowpal Wabbit: vw_slim Namespace Reference
vw_slim Namespace Reference
Namespaces
internal
Classes
class example_predict_builder
class feature_offset_guard
class model_parser
class namespace_copy_guard
class stride_shift_guard
class vw_predict
Vowpal Wabbit slim predictor. Supports: regression, multi-class classification and contextual bandits.
Enumerations
enum vw_predict_exploration { epsilon_greedy, softmax, bag }
Exploration algorithm specified by the model.
Functions
void find_opt (std::string const &command_line_args, std::string arg_name, std::vector< std::string > &out_values)
std::vector< std::string > find_opt (std::string const &command_line_args, std::string arg_name)
bool find_opt_float (std::string const &command_line_args, std::string arg_name, float &value)
bool find_opt_int (std::string const &command_line_args, std::string arg_name, int &value)
uint64_t ceil_log_2 (uint64_t v)
template<typename T , typename S , S(*)(const char *) F>
bool find_opt_parse (std::string const &command_line_args, std::string arg_name, T &value)
Enumeration Type Documentation
enum vw_slim::vw_predict_exploration
Exploration algorithm specified by the model.
Enumerator
epsilon_greedy
softmax
bag
Definition at line 170 of file vw_slim_predict.h.
 {
   epsilon_greedy,
   softmax,
   bag
 };
Function Documentation
uint64_t vw_slim::ceil_log_2 (uint64_t v)
Definition at line 8 of file vw_slim_predict.cc.
Referenced by vw_slim::vw_predict< W >::load().
 {
   if (v == 0)
     return 0;
   else
     return 1 + ceil_log_2(v >> 1);
 }
void vw_slim::find_opt (std::string const & command_line_args, std::string arg_name, std::vector< std::string > & out_values)
Definition at line 9 of file opts.cc.
Referenced by find_opt(), find_opt_parse(), vw_slim::vw_predict< W >::load(), and TEST().
 {
   // append space to search for '--quadratic '
   arg_name += ' ';
   // support -q ab -v -q cd
   for (size_t start = 0; start < command_line_args.size();)
   {
     auto idx = command_line_args.find(arg_name, start);
     if (idx == std::string::npos)
       return;  // no more occurences found, exit
     auto idx_after_arg = idx + arg_name.size();
     // skip all white space
     for (; idx_after_arg < command_line_args.size() && std::isspace(command_line_args[idx_after_arg]); ++idx_after_arg)
       ;
     if (idx_after_arg == command_line_args.size())
       return;
     if (command_line_args[idx_after_arg] == '-' &&
         // make sure we allow -5.2 (negative numbers)
         !(idx_after_arg + 1 < command_line_args.size() &&
             (command_line_args[idx_after_arg + 1] >= '0' && command_line_args[idx_after_arg + 1] <= '9')))
     {
       start = idx_after_arg;
       continue;  // next option found
     }
     // find next non-white space character
     auto idx_after_value = idx_after_arg;
     for (; idx_after_value < command_line_args.size() && !std::isspace(command_line_args[idx_after_value]);
          ++idx_after_value)
       ;
     auto value_size = idx_after_value - idx_after_arg;
     if (value_size > 0)
       out_values.push_back(command_line_args.substr(idx_after_arg, value_size));
     start = idx_after_arg + 1;
   }
 }
std::vector< std::string > vw_slim::find_opt (std::string const & command_line_args, std::string arg_name)
Definition at line 53 of file opts.cc.
References find_opt().
 {
   std::vector<std::string> values;
   find_opt(command_line_args, arg_name, values);
   return values;
 }
bool vw_slim::find_opt_float (std::string const & command_line_args, std::string arg_name, float & value)
Definition at line 73 of file opts.cc.
Referenced by vw_slim::vw_predict< W >::load(), and TEST().
 {
   return find_opt_parse<float, double, atof>(command_line_args, arg_name, value);
 }
bool vw_slim::find_opt_int (std::string const & command_line_args, std::string arg_name, int & value)
Definition at line 78 of file opts.cc.
Referenced by vw_slim::vw_predict< W >::load(), and TEST().
 {
   return find_opt_parse<int, int, atoi>(command_line_args, arg_name, value);
 }
template<typename T , typename S , S(*)(const char *) F> bool vw_slim::find_opt_parse (std::string const & command_line_args, std::string arg_name, T & value)
Definition at line 61 of file opts.cc.
References find_opt().
 {
   std::vector<std::string> opts = find_opt(command_line_args, arg_name);
   if (opts.size() != 1)
     return false;
   value = (T)F(opts[0].c_str());
   return true;
 }