Vowpal Wabbit: ACTION_SCORE Namespace Reference
ACTION_SCORE Namespace Reference
Classes
struct action_score
class score_iterator
Typedefs
typedef v_array< action_score > action_scores
Functions
void print_action_score (int f, v_array< action_score > &a_s, v_array< char > &tag)
void delete_action_scores (void *v)
score_iterator begin_scores (action_scores &a_s)
score_iterator end_scores (action_scores &a_s)
int cmp (size_t a, size_t b)
int score_comp (const void *p1, const void *p2)
int reverse_order (const void *p1, const void *p2)
Typedef Documentation
typedef v_array< action_score > ACTION_SCORE::action_scores
Definition at line 18 of file action_score.h.
Function Documentation
score_iterator ACTION_SCORE::begin_scores (action_scores & a_s) inline
Definition at line 51 of file action_score.h.
References v_array< T >::begin().
Referenced by do_actual_learning_ldf(), CB_EXPLORE::get_cover_probabilities(), VW::cb_sample_data::learn_or_predict(), CB_ADF::cb_adf::learn_SM(), predict_bandit_adf(), predict_or_learn(), predict_or_learn_adf(), CB_EXPLORE::predict_or_learn_greedy(), VW::cb_explore_adf::softmax::cb_explore_adf_softmax::predict_or_learn_impl(), VW::cb_explore_adf::first::cb_explore_adf_first::predict_or_learn_impl(), VW::cb_explore_adf::bag::cb_explore_adf_bag::predict_or_learn_impl(), VW::cb_explore_adf::cover::cb_explore_adf_cover::predict_or_learn_impl(), and VW::cb_explore_adf::regcb::cb_explore_adf_regcb::predict_or_learn_impl().
 { return {a_s.begin()}; }
int ACTION_SCORE::cmp (size_t a, size_t b) inline
Definition at line 55 of file action_score.h.
Referenced by compute_coherence_metrics(), get_top_weights(), and score_comp().
 {
   if (a == b)
     return 0;
   if (a > b)
     return 1;
   return -1;
 }
void ACTION_SCORE::delete_action_scores (void * v)
Definition at line 34 of file action_score.cc.
References cs, and v_array< T >::delete_v().
Referenced by cb_adf_setup(), cb_explore_setup(), CCB::ccb_explore_adf_setup(), CSOAA::csldf_setup(), reverse_order(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), VW::cb_explore_adf::bag::setup(), VW::cb_explore_adf::cover::setup(), and VW::cb_explore_adf::regcb::setup().
 {
   v_array<action_score>* cs = (v_array<action_score>*)v;
   cs->delete_v();
 }
score_iterator ACTION_SCORE::end_scores (action_scores & a_s) inline
Definition at line 53 of file action_score.h.
References v_array< T >::end().
Referenced by do_actual_learning_ldf(), CB_EXPLORE::get_cover_probabilities(), VW::cb_sample_data::learn_or_predict(), CB_ADF::cb_adf::learn_SM(), predict_bandit_adf(), predict_or_learn(), predict_or_learn_adf(), CB_EXPLORE::predict_or_learn_greedy(), VW::cb_explore_adf::softmax::cb_explore_adf_softmax::predict_or_learn_impl(), VW::cb_explore_adf::first::cb_explore_adf_first::predict_or_learn_impl(), VW::cb_explore_adf::bag::cb_explore_adf_bag::predict_or_learn_impl(), VW::cb_explore_adf::cover::cb_explore_adf_cover::predict_or_learn_impl(), and VW::cb_explore_adf::regcb::cb_explore_adf_regcb::predict_or_learn_impl().
 { return {a_s.end()}; }
void ACTION_SCORE::print_action_score (int f, v_array< action_score > & a_s, v_array< char > & tag)
Definition at line 13 of file action_score.cc.
References print_tag_by_ref(), v_array< T >::size(), and io_buf::write_file_or_socket().
Referenced by EXPLORE_EVAL::output_example(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example(), CB_ADF::output_rank_example(), CSOAA::output_rank_example(), and reverse_order().
 {
   if (f >= 0)
   {
     std::stringstream ss;
     for (size_t i = 0; i < a_s.size(); i++)
     {
       if (i > 0)
         ss << ',';
       ss << a_s[i].action << ':' << a_s[i].score;
     }
     print_tag_by_ref(ss, tag);
     ss << '\n';
     ssize_t len = ss.str().size();
     ssize_t t = io_buf::write_file_or_socket(f, ss.str().c_str(), (unsigned int)len);
     if (t != len)
       std::cerr << "write error: " << strerror(errno) << std::endl;
   }
 }
int ACTION_SCORE::reverse_order (const void * p1, const void * p2) inline
Definition at line 79 of file action_score.h.
References delete_action_scores(), f, print_action_score(), and score_comp().
 { return score_comp(p2, p1); }
int ACTION_SCORE::score_comp (const void * p1, const void * p2) inline
Definition at line 64 of file action_score.h.
References ACTION_SCORE::action_score::action, cmp(), and ACTION_SCORE::action_score::score.
Referenced by CSOAA::do_actual_learning(), VW::cb_dro_data::learn_or_predict(), and reverse_order().
 {
   action_score* s1 = (action_score*)p1;
   action_score* s2 = (action_score*)p2;
   // Most sorting algos do not guarantee the output order of elements that compare equal.
   // Tie-breaking on the index ensures that the result is deterministic across platforms.
   // However, this forces a strict ordering, rather than a weak ordering, which carries a performance cost.
   if (s2->score == s1->score)
     return cmp(s1->action, s2->action);
   else if (s2->score >= s1->score)
     return -1;
   else
     return 1;
 }