Vowpal Wabbit: VW::cb_explore_adf::regcb Namespace Reference
VW::cb_explore_adf::regcb Namespace Reference
Classes
struct cb_explore_adf_regcb
Functions
LEARNER::base_learner * setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner * VW::cb_explore_adf::regcb::setup (VW::config::options_i & options, vw & all)
Definition at line 233 of file cb_explore_adf_regcb.cc.
References action_probs, VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_multiline(), cb, CB::cb_label, ACTION_SCORE::delete_action_scores(), vw::delete_prediction, f, finish_multiline_example(), LEARNER::init_learner(), VW::config::options_i::insert(), vw::label_type, learn(), parser::lp, LEARNER::make_base(), VW::config::make_option(), vw::p, predict(), VW::config::options_i::replace(), setup_base(), vw::trace_message, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   using config::make_option;
   bool cb_explore_adf_option = false;
   bool regcb = false;
   const std::string mtr = "mtr";
   std::string type_string(mtr);
   bool regcbopt = false;
   float c0 = 0.;
   bool first_only = false;
   float min_cb_cost = 0.;
   float max_cb_cost = 0.;
   config::option_group_definition new_options("Contextual Bandit Exploration with Action Dependent Features");
   new_options
       .add(make_option("cb_explore_adf", cb_explore_adf_option)
                .keep()
                .help("Online explore-exploit for a contextual bandit problem with multiline action dependent features"))
       .add(make_option("regcb", regcb).keep().help("RegCB-elim exploration"))
       .add(make_option("regcbopt", regcbopt).keep().help("RegCB optimistic exploration"))
       .add(make_option("mellowness", c0).keep().default_value(0.1f).help("RegCB mellowness parameter c_0. Default 0.1"))
       .add(make_option("cb_min_cost", min_cb_cost).keep().default_value(0.f).help("lower bound on cost"))
       .add(make_option("cb_max_cost", max_cb_cost).keep().default_value(1.f).help("upper bound on cost"))
       .add(make_option("first_only", first_only).keep().help("Only explore the first action in a tie-breaking event"))
       .add(make_option("cb_type", type_string)
                .keep()
                .help("contextual bandit method to use in {ips,dr,mtr}. Default: mtr"));
   options.add_and_parse(new_options);
   if (!cb_explore_adf_option || !(options.was_supplied("regcb") || options.was_supplied("regcbopt")))
     return nullptr;
   // Ensure serialization of cb_adf in all cases.
   if (!options.was_supplied("cb_adf"))
   {
     options.insert("cb_adf", "");
   }
   if (type_string != mtr)
   {
     all.trace_message << "warning: bad cb_type, RegCB only supports mtr; resetting to mtr." << std::endl;
     options.replace("cb_type", mtr);
   }
   all.delete_prediction = ACTION_SCORE::delete_action_scores;
   // Set explore_type
   size_t problem_multiplier = 1;
   LEARNER::multi_learner* base = as_multiline(setup_base(options, all));
   all.p->lp = CB::cb_label;
   all.label_type = label_type_t::cb;
   using explore_type = cb_explore_adf_base<cb_explore_adf_regcb>;
   auto data = scoped_calloc_or_throw<explore_type>(regcbopt, c0, first_only, min_cb_cost, max_cb_cost);
   LEARNER::learner<explore_type, multi_ex>& l = LEARNER::init_learner(
       data, base, explore_type::learn, explore_type::predict, problem_multiplier, prediction_type_t::action_probs);
   l.set_finish_example(explore_type::finish_multiline_example);
   return make_base(l);
 }