Vowpal Wabbit: SequenceTask_DemoLDF Namespace Reference
SequenceTask_DemoLDF Namespace Reference
Classes
struct task_data
Functions
void initialize (Search::search &sch, size_t &num_actions, options_i &)
void finish (Search::search &sch)
void my_update_example_indicies (Search::search &sch, bool, example *ec, uint64_t mult_amount, uint64_t plus_amount)
void run (Search::search &sch, multi_ex &ec)
Variables
Search::search_task task = {"sequence_demoldf", run, initialize, finish, nullptr, nullptr}
Function Documentation
void SequenceTask_DemoLDF::finish (Search::search & sch)
Definition at line 400 of file search_sequencetask.cc.
References a, COST_SENSITIVE::cs_label, VW::dealloc_example(), CB::delete_label(), Search::search::get_task_data(), SequenceTask_DemoLDF::task_data::ldf_examples, and SequenceTask_DemoLDF::task_data::num_actions.
 {
   task_data* data = sch.get_task_data<task_data>();
   for (size_t a = 0; a < data->num_actions; a++) VW::dealloc_example(CS::cs_label.delete_label, data->ldf_examples[a]);
   free(data->ldf_examples);
   free(data);
 }
void SequenceTask_DemoLDF::initialize (Search::search & sch, size_t & num_actions, options_i &)
Definition at line 377 of file search_sequencetask.cc.
References a, VW::alloc_examples(), Search::AUTO_CONDITION_FEATURES, Search::AUTO_HAMMING_LOSS, COST_SENSITIVE::label::costs, polylabel::cs, COST_SENSITIVE::cs_label, label_parser::default_label, Search::search::get_vw_pointer_unsafe(), example_predict::interactions, vw::interactions, Search::IS_LDF, example::l, SequenceTask_DemoLDF::task_data::ldf_examples, SequenceTask_DemoLDF::task_data::num_actions, Search::search::set_options(), and Search::search::set_task_data().
 {
   CS::wclass default_wclass = {0., 0, 0., 0.};
   example* ldf_examples = VW::alloc_examples(sizeof(CS::label), num_actions);
   for (size_t a = 0; a < num_actions; a++)
   {
     CS::label& lab = ldf_examples[a].l.cs;
     CS::cs_label.default_label(&lab);
     lab.costs.push_back(default_wclass);
     ldf_examples[a].interactions = &sch.get_vw_pointer_unsafe().interactions;
   }
   task_data* data = &calloc_or_throw<task_data>();
   data->ldf_examples = ldf_examples;
   data->num_actions = num_actions;
   sch.set_task_data<task_data>(data);
   sch.set_options(Search::AUTO_CONDITION_FEATURES |  // automatically add history features to our examples, please
       Search::AUTO_HAMMING_LOSS |  // please just use hamming loss on individual predictions -- we won't declare loss
       Search::IS_LDF);             // we generate ldf examples
 }
void SequenceTask_DemoLDF::my_update_example_indicies (Search::search & sch, bool , example * ec, uint64_t mult_amount, uint64_t plus_amount)
Definition at line 409 of file search_sequencetask.cc.
References Search::search::get_stride_shift().
Referenced by run().
 {
   size_t ss = sch.get_stride_shift();
   for (features& fs : *ec)
     for (feature_index& idx : fs.indicies) idx = (((idx >> ss) * mult_amount) + plus_amount) << ss;
 }
void SequenceTask_DemoLDF::run (Search::search & sch, multi_ex & ec)
Definition at line 417 of file search_sequencetask.cc.
References a, VW::copy_example_data(), COST_SENSITIVE::label::costs, polylabel::cs, Search::search::get_history_length(), Search::search::get_task_data(), example::l, SequenceTask_DemoLDF::task_data::ldf_examples, my_update_example_indicies(), SequenceTask_DemoLDF::task_data::num_actions, Search::search::output(), predict(), and Search::search::predictNeedsExample().
 {
   task_data* data = sch.get_task_data<task_data>();
   Search::predictor P(sch, (ptag)0);
   for (ptag i = 0; i < ec.size(); i++)
   {
     for (uint32_t a = 0; a < data->num_actions; a++)
     {
       if (sch.predictNeedsExample())  // we can skip this work if `predict` won't actually use the example data
       {
         VW::copy_example_data(false, &data->ldf_examples[a], ec[i]);  // copy but leave label alone!
         // now, offset it appropriately for the action id
         my_update_example_indicies(sch, true, &data->ldf_examples[a], 28904713, 4832917 * (uint64_t)a);
       }
       // regardless of whether the example is needed or not, the class info is needed
       CS::label& lab = data->ldf_examples[a].l.cs;
       // need to tell search what the action id is, so that it can add history features correctly!
       lab.costs[0].x = 0.;
       lab.costs[0].class_index = a + 1;
       lab.costs[0].partial_prediction = 0.;
       lab.costs[0].wap_value = 0.;
     }
     action oracle = ec[i]->l.multi.label - 1;
     action pred_id = P.set_tag((ptag)(i + 1))
                          .set_input(data->ldf_examples, data->num_actions)
                          .set_oracle(oracle)
                          .set_condition_range(i, sch.get_history_length(), 'p')
                          .predict();
     action prediction = pred_id + 1;  // or ldf_examples[pred_id]->ld.costs[0].weight_index
     if (sch.output().good())
       sch.output() << prediction << ' ';
   }
 }
Variable Documentation
Search::search_task SequenceTask_DemoLDF::task = {"sequence_demoldf", run, initialize, finish, nullptr, nullptr}
Definition at line 27 of file search_sequencetask.cc.