Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/nn.h File Reference
nn.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * nn_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* nn_setup (VW::config::options_i & options, vw & all)
Definition at line 439 of file nn.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), LEARNER::end_pass(), finish_example(), vw::get_random_state(), getLossFunction(), LEARNER::init_learner(), vw::logger, LEARNER::make_base(), VW::config::make_option(), multipredict(), nn::multitask, vw_logger::quiet, vw::random_seed, LEARNER::learner< T, E >::set_end_pass(), LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_multipredict(), setup_base(), vw::training, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto n = scoped_calloc_or_throw<nn>();
   bool meanfield = false;
   option_group_definition new_options("Neural Network");
   new_options.add(make_option("nn", n->k).keep().help("Sigmoidal feedforward network with <k> hidden units"))
       .add(make_option("inpass", n->inpass)
                .keep()
                .help("Train or test sigmoidal feedforward network with input passthrough."))
       .add(make_option("multitask", n->multitask).keep().help("Share hidden layer across all reduced tasks."))
       .add(make_option("dropout", n->dropout).keep().help("Train or test sigmoidal feedforward network using dropout."))
       .add(make_option("meanfield", meanfield).help("Train or test sigmoidal feedforward network using mean field."));
   options.add_and_parse(new_options);
   if (!options.was_supplied("nn"))
     return nullptr;
   n->all = &all;
   n->_random_state = all.get_random_state();
   if (n->multitask && !all.logger.quiet)
     std::cerr << "using multitask sharing for neural network " << (all.training ? "training" : "testing") << std::endl;
   if (options.was_supplied("meanfield"))
   {
     n->dropout = false;
     if (!all.logger.quiet)
       std::cerr << "using mean field for neural network " << (all.training ? "training" : "testing") << std::endl;
   }
   if (n->dropout && !all.logger.quiet)
     std::cerr << "using dropout for neural network " << (all.training ? "training" : "testing") << std::endl;
   if (n->inpass && !all.logger.quiet)
     std::cerr << "using input passthrough for neural network " << (all.training ? "training" : "testing") << std::endl;
   n->finished_setup = false;
   n->squared_loss = getLossFunction(all, "squared", 0);
   n->xsubi = all.random_seed;
   n->save_xsubi = n->xsubi;
   n->hidden_units = calloc_or_throw<float>(n->k);
   n->dropped_out = calloc_or_throw<bool>(n->k);
   n->hidden_units_pred = calloc_or_throw<polyprediction>(n->k);
   n->hiddenbias_pred = calloc_or_throw<polyprediction>(n->k);
   auto base = as_singleline(setup_base(options, all));
   n->increment = base->increment;  // Indexing of output layer is odd.
   nn& nv = *n.get();
   learner<nn, example>& l =
       init_learner(n, base, predict_or_learn_multi<true, true>, predict_or_learn_multi<false, true>, n->k + 1);
   if (nv.multitask)
     l.set_multipredict(multipredict);
   l.set_finish_example(finish_example);
   l.set_end_pass(end_pass);
   return make_base(l);
 }