Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/noop.h File Reference
noop.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * noop_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* noop_setup (VW::config::options_i & options, vw & all)
Definition at line 13 of file noop.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::init_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), and LEARNER::noop().
Referenced by parse_reductions().
 {
   bool noop = false;
   option_group_definition new_options("Noop Learner");
   new_options.add(make_option("noop", noop).keep().help("do no learning"));
   options.add_and_parse(new_options);
   if (!noop)
     return nullptr;
   return make_base(LEARNER::init_learner(learn, 1));
 }