Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/oaa.h File Reference
oaa.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * oaa_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* oaa_setup (VW::config::options_i & options, vw & all)
Definition at line 200 of file oaa.cc.
References VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), vw::delete_prediction, delete_scalars(), vw::get_random_state(), namedlabels::getK(), loss_function::getType(), LEARNER::init_multiclass_learner(), shared_data::ldict, learn_randomized(), vw::loss, LEARNER::make_base(), VW::config::make_option(), multiclass, oaa::num_subsample, vw::p, vw::raw_prediction, shared_data::report_multiclass_log_loss, scalars, vw::sd, LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_learn(), setup_base(), THROW, vw::trace_message, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto data = scoped_calloc_or_throw<oaa>();
   bool probabilities = false;
   bool scores = false;
   option_group_definition new_options("One Against All Options");
   new_options.add(make_option("oaa", data->k).keep().help("One-against-all multiclass with <k> labels"))
       .add(make_option("oaa_subsample", data->num_subsample)
                .help("subsample this number of negative examples when learning"))
       .add(make_option("probabilities", probabilities).help("predict probabilites of all classes"))
       .add(make_option("scores", scores).help("output raw scores per class"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("oaa"))
     return nullptr;
   if (all.sd->ldict && (data->k != all.sd->ldict->getK()))
     THROW("error: you have " << all.sd->ldict->getK() << " named labels; use that as the argument to oaa")
   data->all = &all;
   data->pred = calloc_or_throw<polyprediction>(data->k);
   data->subsample_order = nullptr;
   data->subsample_id = 0;
   if (data->num_subsample > 0)
   {
     if (data->num_subsample >= data->k)
     {
       data->num_subsample = 0;
       all.trace_message << "oaa is turning off subsampling because your parameter >= K" << std::endl;
     }
     else
     {
       data->subsample_order = calloc_or_throw<uint32_t>(data->k);
       for (size_t i = 0; i < data->k; i++) data->subsample_order[i] = (uint32_t)i;
       for (size_t i = 0; i < data->k; i++)
       {
         size_t j = (size_t)(all.get_random_state()->get_and_update_random() * (float)(data->k - i)) + i;
         uint32_t tmp = data->subsample_order[i];
         data->subsample_order[i] = data->subsample_order[j];
         data->subsample_order[j] = tmp;
       }
     }
   }
   oaa* data_ptr = data.get();
   LEARNER::learner<oaa, example>* l;
   auto base = as_singleline(setup_base(options, all));
   if (probabilities || scores)
   {
     all.delete_prediction = delete_scalars;
     if (probabilities)
     {
       auto loss_function_type = all.loss->getType();
       if (loss_function_type != "logistic")
         all.trace_message << "WARNING: --probabilities should be used only with --loss_function=logistic" << std::endl;
       // the three boolean template parameters are: is_learn, print_all and scores
       l = &LEARNER::init_multiclass_learner(data, base, predict_or_learn<true, false, true, true>,
           predict_or_learn<false, false, true, true>, all.p, data->k, prediction_type_t::scalars);
       all.sd->report_multiclass_log_loss = true;
       l->set_finish_example(finish_example_scores<true>);
     }
     else
     {
       l = &LEARNER::init_multiclass_learner(data, base, predict_or_learn<true, false, true, false>,
           predict_or_learn<false, false, true, false>, all.p, data->k, prediction_type_t::scalars);
       l->set_finish_example(finish_example_scores<false>);
     }
   }
   else if (all.raw_prediction > 0)
     l = &LEARNER::init_multiclass_learner(data, base, predict_or_learn<true, true, false, false>,
         predict_or_learn<false, true, false, false>, all.p, data->k, prediction_type_t::multiclass);
   else
     l = &LEARNER::init_multiclass_learner(data, base, predict_or_learn<true, false, false, false>,
         predict_or_learn<false, false, false, false>, all.p, data->k, prediction_type_t::multiclass);
   if (data_ptr->num_subsample > 0)
   {
     l->set_learn(learn_randomized);
     l->set_finish_example(MULTICLASS::finish_example_without_loss<oaa>);
   }
   return make_base(*l);
 }