Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/OjaNewton.h File Reference
OjaNewton.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * OjaNewton_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* OjaNewton_setup (VW::config::options_i & options, vw & all)
Definition at line 531 of file OjaNewton.cc.
References OjaNewton::_random_state, OjaNewton::A, VW::config::option_group_definition::add(), add(), VW::config::options_i::add_and_parse(), OjaNewton::all, OjaNewton::alpha, update_data::AZx, OjaNewton::b, OjaNewton::buffer, OjaNewton::cnt, OjaNewton::D, OjaNewton::data, update_data::delta, OjaNewton::epoch_size, OjaNewton::ev, f, vw::get_random_state(), LEARNER::init_learner(), OjaNewton::K, keep_example(), learn(), OjaNewton::learning_rate_cnt, OjaNewton::m, LEARNER::make_base(), VW::config::make_option(), OjaNewton::normalize, update_data::ON, predict(), OjaNewton::random_init, save_load(), LEARNER::learner< T, E >::set_finish_example(), LEARNER::learner< T, E >::set_save_load(), parameters::stride(), parameters::stride_shift(), OjaNewton::t, OjaNewton::tmp, OjaNewton::vv, VW::config::options_i::was_supplied(), OjaNewton::weight_buffer, vw::weights, OjaNewton::zv, and update_data::Zx.
Referenced by parse_reductions().
 {
   auto ON = scoped_calloc_or_throw<OjaNewton>();
   bool oja_newton;
   float alpha_inverse;
   // These two are the only two boolean options that default to true. For now going to do this hack
   // as the infrastructure doesn't easily support this possibility at the same time providing the
   // ease of bool switches elsewhere. It seems that the switch behavior is more critical because
   // of the positional data argument.
   std::string normalize = "true";
   std::string random_init = "true";
   option_group_definition new_options("OjaNewton options");
   new_options.add(make_option("OjaNewton", oja_newton).keep().help("Online Newton with Oja's Sketch"))
       .add(make_option("sketch_size", ON->m).default_value(10).help("size of sketch"))
       .add(make_option("epoch_size", ON->epoch_size).default_value(1).help("size of epoch"))
       .add(make_option("alpha", ON->alpha).default_value(1.f).help("mutiplicative constant for indentiy"))
       .add(make_option("alpha_inverse", alpha_inverse).help("one over alpha, similar to learning rate"))
       .add(make_option("learning_rate_cnt", ON->learning_rate_cnt)
                .default_value(2.f)
                .help("constant for the learning rate 1/t"))
       .add(make_option("normalize", normalize).help("normalize the features or not"))
       .add(make_option("random_init", random_init).help("randomize initialization of Oja or not"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("OjaNewton"))
     return nullptr;
   ON->all = &all;
   ON->_random_state = all.get_random_state();
   ON->normalize = normalize == "true";
   ON->random_init = random_init == "true";
   if (options.was_supplied("alpha_inverse"))
     ON->alpha = 1.f / alpha_inverse;
   ON->cnt = 0;
   ON->t = 1;
   ON->ev = calloc_or_throw<float>(ON->m + 1);
   ON->b = calloc_or_throw<float>(ON->m + 1);
   ON->D = calloc_or_throw<float>(ON->m + 1);
   ON->A = calloc_or_throw<float*>(ON->m + 1);
   ON->K = calloc_or_throw<float*>(ON->m + 1);
   for (int i = 1; i <= ON->m; i++)
   {
     ON->A[i] = calloc_or_throw<float>(ON->m + 1);
     ON->K[i] = calloc_or_throw<float>(ON->m + 1);
     ON->A[i][i] = 1;
     ON->K[i][i] = 1;
     ON->D[i] = 1;
   }
   ON->buffer = calloc_or_throw<example*>(ON->epoch_size);
   ON->weight_buffer = calloc_or_throw<float>(ON->epoch_size);
   ON->zv = calloc_or_throw<float>(ON->m + 1);
   ON->vv = calloc_or_throw<float>(ON->m + 1);
   ON->tmp = calloc_or_throw<float>(ON->m + 1);
   ON->data.ON = ON.get();
   ON->data.Zx = calloc_or_throw<float>(ON->m + 1);
   ON->data.AZx = calloc_or_throw<float>(ON->m + 1);
   ON->data.delta = calloc_or_throw<float>(ON->m + 1);
   all.weights.stride_shift((uint32_t)ceil(log2(ON->m + 2)));
   learner<OjaNewton, example>& l = init_learner(ON, learn, predict, all.weights.stride());
   l.set_save_load(save_load);
   l.set_finish_example(keep_example);
   return make_base(l);
 }