Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example.h File Reference
parse_example.h File Reference
#include <cstdint>
#include "parse_primitives.h"
#include "example.h"
#include "vw.h"
#include "vw_string_view.h"
Namespaces
VW
Enumerations
enum FeatureInputType { StringFeatures, JsonFeatures }
Functions
void substring_to_example (vw *all, example *ae, VW::string_view example)
example & VW::get_unused_example (vw *all)
void VW::read_line (vw &all, example *ex, char *line)
void VW::read_lines (vw *all, char *line, size_t, v_array< example * > &examples)
int read_features_string (vw *all, v_array< example * > &examples)
size_t read_features (vw *all, char *&line, size_t &num_chars)
Enumeration Type Documentation
enum FeatureInputType
Enumerator
StringFeatures
JsonFeatures
Definition at line 12 of file parse_example.h.
 {
   StringFeatures,
   JsonFeatures
 } FeatureInputType;
Function Documentation
size_t read_features (vw * all, char *& line, size_t & num_chars)
Definition at line 14 of file parse_example.cc.
References parser::input, vw::p, and readto().
Referenced by read_features_json(), and read_features_string().
 {
   line = nullptr;
   size_t num_chars_initial = readto(*(all->p->input), line, '\n');
   if (num_chars_initial < 1)
     return num_chars_initial;
   num_chars = num_chars_initial;
   if (line[0] == '\xef' && num_chars >= 3 && line[1] == '\xbb' && line[2] == '\xbf')
   {
     line += 3;
     num_chars -= 3;
   }
   if (num_chars > 0 && line[num_chars - 1] == '\n')
     num_chars--;
   if (num_chars > 0 && line[num_chars - 1] == '\r')
     num_chars--;
   return num_chars_initial;
 }
int read_features_string (vw * all, v_array< example * > & examples)
Definition at line 33 of file parse_example.cc.
References read_features(), and substring_to_example().
Referenced by enable_sources(), and reset_source().
 {
   char* line;
   size_t num_chars;
   size_t num_chars_initial = read_features(all, line, num_chars);
   if (num_chars_initial < 1)
     return (int)num_chars_initial;
   VW::string_view example(line, num_chars);
   substring_to_example(all, examples[0], example);
   return (int)num_chars_initial;
 }
void substring_to_example (vw * all, example * ae, VW::string_view example)
Definition at line 480 of file parse_example.cc.
References parser::_shared_data, vw::audit, v_array< T >::begin(), v_array< T >::clear(), label_parser::default_label, v_array< T >::empty(), vw::hash_inv, example::l, v_array< T >::last(), parser::lp, vw::p, label_parser::parse_label, v_array< T >::pop(), push_many(), v_array< T >::size(), example::tag, tokenize(), and parser::words.
Referenced by prepare_for_learner(), read_features_string(), and VW::read_line().
 {
   all->p->lp.default_label(&ae->l);
   size_t bar_idx = example.find('|');
   all->p->words.clear();
   if (bar_idx != 0)
   {
     VW::string_view label_space(example);
     if (bar_idx != VW::string_view::npos)
     {
       // a little bit iffy since bar_idx is based on example and we're working off label_space
       // but safe as long as this is the first manipulation after the copy
       label_space.remove_suffix(label_space.size() - bar_idx);
     }
     size_t tab_idx = label_space.find('\t');
     if (tab_idx != VW::string_view::npos)
     {
       label_space.remove_prefix(tab_idx + 1);
     }
     std::vector<VW::string_view> tokenized;
     tokenize(' ', label_space, all->p->words);
     if (all->p->words.size() > 0 &&
         (all->p->words.last().end() == label_space.end() ||
         all->p->words.last().front() == '\''))  // The last field is a tag, so record and strip it off
     {
       VW::string_view tag = all->p->words.pop();
       if (tag.front() == '\'')
         tag.remove_prefix(1);
       push_many(ae->tag, tag.begin(), tag.size());
     }
   }
   if (!all->p->words.empty())
     all->p->lp.parse_label(all->p, all->p->_shared_data, &ae->l, all->p->words);
   if (bar_idx != VW::string_view::npos)
   {
     if (all->audit || all->hash_inv)
       TC_parser<true> parser_line(example.substr(bar_idx), *all, ae);
     else
       TC_parser<false> parser_line(example.substr(bar_idx), *all, ae);
   }
 }