Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example_json.h File Reference
parse_example_json.h File Reference
#include "parse_primitives.h"
#include "v_array.h"
#include <rapidjson/reader.h>
#include <rapidjson/error/en.h>
#include "cb.h"
#include "conditional_contextual_bandit.h"
#include "best_constant.h"
#include "vw_string_view.h"
#include <algorithm>
#include <vector>
#include <limits>
#include <sstream>
Classes
struct BaseState< audit >
struct Context< audit >
struct Namespace< audit >
struct BaseState< audit >
class LabelObjectState< audit >
struct LabelSinglePropertyState< audit >
struct LabelIndexState< audit >
struct LabelState< audit >
struct TextState< audit >
struct TagState< audit >
struct MultiState< audit >
struct SlotsState< audit >
class ArrayState< audit >
struct IgnoreState< audit >
class DefaultState< audit >
class ArrayToVectorState< audit, T >
class StringToStringState< audit >
class FloatToFloatState< audit >
class BoolToBoolState< audit >
struct DecisionServiceInteraction
class CCBOutcomeList< audit >
class DecisionServiceState< audit >
struct Context< audit >
struct VWReaderHandler< audit >
struct json_parser< audit >
Namespaces
VW
Macros
#define _stricmp strcasecmp
Functions
template<bool audit>
void VW::read_line_json (vw &all, v_array< example * > &examples, char *line, example_factory_t example_factory, void *ex_factory_context)
void VW::apply_pdrop (vw &all, float pdrop, v_array< example * > &examples)
template<bool audit>
void VW::read_line_decision_service_json (vw &all, v_array< example * > &examples, char *line, size_t length, bool copy_line, example_factory_t example_factory, void *ex_factory_context, DecisionServiceInteraction *data)
template<bool audit>
bool parse_line_json (vw *all, char *line, size_t num_chars, v_array< example * > &examples)
void prepare_for_learner (vw *all, v_array< example * > &examples)
template<bool audit>
void line_to_examples_json (vw *all, char *line, size_t num_chars, v_array< example * > &examples)
template<bool audit>
int read_features_json (vw *all, v_array< example * > &examples)
Macro Definition Documentation
#define _stricmp strcasecmp
Definition at line 41 of file parse_example_json.h.
Referenced by LabelObjectState< audit >::Float(), DefaultState< audit >::Key(), DecisionServiceState< audit >::Key(), LabelObjectState< audit >::String(), and ArrayToVectorState< audit, unsigned >::String().
Function Documentation
template<bool audit> void line_to_examples_json (vw * all, char * line, size_t num_chars, v_array< example * > & examples)
Definition at line 1584 of file parse_example_json.h.
References VW::get_unused_example(), prepare_for_learner(), v_array< T >::push_back(), and VW::return_multiple_example().
 {
   bool good_example = parse_line_json<audit>(all, line, num_chars, examples);
   if (!good_example)
   {
     VW::return_multiple_example(*all, examples);
     examples.push_back(&VW::get_unused_example(all));
     return;
   }
   prepare_for_learner(all, examples);
 }
template<bool audit> bool parse_line_json (vw * all, char * line, size_t num_chars, v_array< example * > & examples)
Definition at line 1524 of file parse_example_json.h.
References DecisionServiceInteraction::actions, parser::decision_service_json, VW::get_unused_example(), vw::p, VW::return_multiple_example(), and DecisionServiceInteraction::skipLearn.
 {
   if (all->p->decision_service_json)
   {
     // Skip lines that do not start with "{"
     if (line[0] != '{')
     {
       return false;
     }
     DecisionServiceInteraction interaction;
     VW::template read_line_decision_service_json<audit>(*all, examples, line, num_chars, false,
         reinterpret_cast<VW::example_factory_t>(&VW::get_unused_example), all, &interaction);
     // TODO: In refactoring the parser to be usable standalone, we need to ensure that we
     // stop suppressing "skipLearn" interactions. Also, not sure if this is the right logic
     // for counterfactual. (@marco)
     if (interaction.skipLearn)
     {
       VW::return_multiple_example(*all, examples);
       examples.push_back(&VW::get_unused_example(all));
       return false;
     }
     // let's ask to continue reading data until we find a line with actions provided
     if (interaction.actions.size() == 0)
     {
       // VW::return_multiple_example(*all, examples);
       // examples.push_back(&VW::get_unused_example(all));
       return false;
     }
   }
   else
     VW::template read_line_json<audit>(
         *all, examples, line, reinterpret_cast<VW::example_factory_t>(&VW::get_unused_example), all);
   return true;
 }
void prepare_for_learner (vw * all, v_array< example * > & examples) inline
Definition at line 1563 of file parse_example_json.h.
References VW::get_unused_example(), v_array< T >::push_back(), v_array< T >::size(), and substring_to_example().
Referenced by line_to_examples_json(), and read_features_json().
 {
   // note: the json parser does single pass parsing and cannot determine if a shared example is needed.
   // since the communication between the parsing thread the main learner expects examples to be requested in order (as
   // they're layed out in memory) there is no way to determine upfront if a shared example exists thus even if there are
   // no features for the shared example, still an empty example is returned.
   // insert new line example at the end
   if (examples.size() > 1)
   {
     example& ae = VW::get_unused_example(all);
     static const char empty[] = "";
     VW::string_view example(empty);
     substring_to_example(all, &ae, example);
     examples.push_back(&ae);
   }
 }
template<bool audit> int read_features_json (vw * all, v_array< example * > & examples)
Definition at line 1598 of file parse_example_json.h.
References prepare_for_learner(), and read_features().
 {
   // Keep reading lines until a valid set of examples is produced.
   bool reread;
   do
   {
     reread = false;
     char* line;
     size_t num_chars;
     size_t num_chars_initial = read_features(all, line, num_chars);
     if (num_chars_initial < 1)
       return (int)num_chars_initial;
     // Ensure there is a null terminator.
     line[num_chars] = '\0';
     reread = !parse_line_json<audit>(all, line, num_chars, examples);
   } while (reread);
   prepare_for_learner(all, examples);
   return 1;
 }