Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/print.h File Reference
print.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * print_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* print_setup (VW::config::options_i & options, vw & all)
Definition at line 48 of file print.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::init_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), parameters::stride_shift(), and vw::weights.
Referenced by parse_reductions().
 {
   bool print_option = false;
   option_group_definition new_options("Print psuedolearner");
   new_options.add(make_option("print", print_option).keep().help("print examples"));
   options.add_and_parse(new_options);
   if (!print_option)
     return nullptr;
   auto p = scoped_calloc_or_throw<print>();
   p->all = &all;
   all.weights.stride_shift(0);
   LEARNER::learner<print, example>& ret = init_learner(p, learn, learn, 1);
   return make_base(ret);
 }