Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/recall_tree.cc File Reference
recall_tree.cc File Reference
#include <algorithm>
#include <cmath>
#include <cstdio>
#include <float.h>
#include <sstream>
#include <memory>
#include "reductions.h"
#include "rand48.h"
Classes
struct recall_tree_ns::node_pred
struct recall_tree_ns::node
struct recall_tree_ns::recall_tree
struct recall_tree_ns::predict_type
Namespaces
recall_tree_ns
Functions
float recall_tree_ns::to_prob (float x)
void recall_tree_ns::init_tree (recall_tree &b, uint32_t root, uint32_t depth, uint32_t &routers_used)
void recall_tree_ns::init_tree (recall_tree &b)
node_pred * recall_tree_ns::find (recall_tree &b, uint32_t cn, example &ec)
node_pred * recall_tree_ns::find_or_create (recall_tree &b, uint32_t cn, example &ec)
void recall_tree_ns::compute_recall_lbest (recall_tree &b, node *n)
double recall_tree_ns::plogp (double c, double n)
double recall_tree_ns::updated_entropy (recall_tree &b, uint32_t cn, example &ec)
void recall_tree_ns::insert_example_at_node (recall_tree &b, uint32_t cn, example &ec)
void recall_tree_ns::add_node_id_feature (recall_tree &b, uint32_t cn, example &ec)
void recall_tree_ns::remove_node_id_feature (recall_tree &, uint32_t, example &ec)
uint32_t recall_tree_ns::oas_predict (recall_tree &b, single_learner &base, uint32_t cn, example &ec)
bool recall_tree_ns::is_candidate (recall_tree &b, uint32_t cn, example &ec)
uint32_t recall_tree_ns::descend (node &n, float prediction)
bool recall_tree_ns::stop_recurse_check (recall_tree &b, uint32_t parent, uint32_t child)
predict_type recall_tree_ns::predict_from (recall_tree &b, single_learner &base, example &ec, uint32_t cn)
void recall_tree_ns::predict (recall_tree &b, single_learner &base, example &ec)
float recall_tree_ns::train_node (recall_tree &b, single_learner &base, example &ec, uint32_t cn)
void recall_tree_ns::learn (recall_tree &b, single_learner &base, example &ec)
void recall_tree_ns::save_load_tree (recall_tree &b, io_buf &model_file, bool read, bool text)
base_learner * recall_tree_setup (options_i &options, vw &all)
Function Documentation
base_learner* recall_tree_setup (options_i & options, vw & all)
Definition at line 500 of file recall_tree.cc.
References add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), f, vw::get_random_state(), LEARNER::init_multiclass_learner(), init_tree(), recall_tree_ns::learn(), vw::logger, LEARNER::make_base(), VW::config::make_option(), vw::p, recall_tree_ns::predict(), vw_logger::quiet, save_load_tree(), LEARNER::learner< T, E >::set_save_load(), setup_base(), vw::trace_message, vw::training, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   auto tree = scoped_calloc_or_throw<recall_tree>();
   option_group_definition new_options("Recall Tree");
   new_options.add(make_option("recall_tree", tree->k).keep().help("Use online tree for multiclass"))
       .add(make_option("max_candidates", tree->max_candidates)
                .keep()
                .help("maximum number of labels per leaf in the tree"))
       .add(make_option("bern_hyper", tree->bern_hyper).default_value(1.f).help("recall tree depth penalty"))
       .add(make_option("max_depth", tree->max_depth).keep().help("maximum depth of the tree, default log_2 (#classes)"))
       .add(make_option("node_only", tree->node_only).keep().help("only use node features, not full path features"))
       .add(make_option("randomized_routing", tree->randomized_routing).keep().help("randomized routing"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("recall_tree"))
     return nullptr;
   tree->all = &all;
   tree->_random_state = all.get_random_state();
   tree->max_candidates = options.was_supplied("max_candidates")
       ? tree->max_candidates
       : std::min(tree->k, 4 * (uint32_t)(ceil(log(tree->k) / log(2.0))));
   tree->max_depth =
       options.was_supplied("max_depth") ? tree->max_depth : (uint32_t)std::ceil(std::log(tree->k) / std::log(2.0));
   init_tree(*tree.get());
   if (!all.logger.quiet)
     all.trace_message << "recall_tree:"
                       << " node_only = " << tree->node_only << " bern_hyper = " << tree->bern_hyper
                       << " max_depth = " << tree->max_depth << " routing = "
                       << (all.training ? (tree->randomized_routing ? "randomized" : "deterministic") : "n/a testonly")
                       << std::endl;
   learner<recall_tree, example>& l = init_multiclass_learner(
       tree, as_singleline(setup_base(options, all)), learn, predict, all.p, tree->max_routers + tree->k);
   l.set_save_load(save_load_tree);
   return make_base(l);
 }