Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/sender.h File Reference
sender.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * sender_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* sender_setup (VW::config::options_i & options, vw & all)
Definition at line 104 of file sender.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), end_examples(), VW::finish_example(), LEARNER::init_learner(), learn(), LEARNER::make_base(), VW::config::make_option(), open_sockets(), vw::p, parser::ring_size, and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   std::string host;
   option_group_definition sender_options("Network sending");
   sender_options.add(make_option("sendto", host).keep().help("send examples to <host>"));
   options.add_and_parse(sender_options);
   if (!options.was_supplied("sendto"))
   {
     return nullptr;
   }
   auto s = scoped_calloc_or_throw<sender>();
   s->sd = -1;
   open_sockets(*s.get(), host);
   s->all = &all;
   s->delay_ring = calloc_or_throw<example*>(all.p->ring_size);
   LEARNER::learner<sender, example>& l = init_learner(s, learn, learn, 1);
   l.set_finish_example(finish_example);
   l.set_end_examples(end_examples);
   return make_base(l);
 }