Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/spanning_tree.cc File Reference
spanning_tree.cc File Reference
#include "spanning_tree.h"
#include "vw_exception.h"
#include <string.h>
#include <errno.h>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <iostream>
#include <fstream>
#include <cmath>
#include <map>
#include <future>
Classes
struct client
struct partial
Namespaces
VW
Functions
static int socket_sort (const void *s1, const void *s2)
int build_tree (int *parent, uint16_t *kid_count, size_t source_count, int offset)
void fail_send (const socket_t fd, const void *buf, const int count)
Function Documentation
int build_tree (int * parent, uint16_t * kid_count, size_t source_count, int offset)
Definition at line 41 of file spanning_tree.cc.
Referenced by VW::SpanningTree::Run().
 {
   if (source_count == 1)
   {
     kid_count[offset] = 0;
     return offset;
   }
   int height = (int)floor(log((double)source_count) / log(2.0));
   int root = (1 << height) - 1;
   int left_count = root;
   int left_offset = offset;
   int left_child = build_tree(parent, kid_count, left_count, left_offset);
   int oroot = root + offset;
   parent[left_child] = oroot;
   size_t right_count = source_count - left_count - 1;
   if (right_count > 0)
   {
     int right_offset = oroot + 1;
     int right_child = build_tree(parent, kid_count, right_count, right_offset);
     parent[right_child] = oroot;
     kid_count[oroot] = 2;
   }
   else
     kid_count[oroot] = 1;
   return oroot;
 }
void fail_send (const socket_t fd, const void * buf, const int count)
Definition at line 72 of file spanning_tree.cc.
References THROWERRNO.
Referenced by VW::SpanningTree::Run().
 {
   if (send(fd, (char*)buf, count, 0) == -1)
     THROWERRNO("send: ");
 }
static int socket_sort (const void * s1, const void * s2) static
Definition at line 31 of file spanning_tree.cc.
References client::client_ip, and client::socket.
Referenced by VW::SpanningTree::Run().
 {
   client* socket1 = (client*)s1;
   client* socket2 = (client*)s2;
   if (socket1->client_ip != socket2->client_ip)
     return socket1->client_ip - socket2->client_ip;
   else
     return (int)(socket1->socket - socket2->socket);
 }