Vowpal Wabbit: VW::config::options_serializer_boost_po Struct Reference
VW::config::options_serializer_boost_po Struct Reference
#include <options_serializer_boost_po.h>
Public Member Functions
options_serializer_boost_po ()
virtual void add (base_option &option) override
virtual std::string str () override
virtual const char * data () override
virtual size_t size () override
Private Member Functions
template<typename T >
bool serialize_if_t (base_option &base_option)
template<typename T >
void serialize (typed_option< T > &typed_option)
template<typename T >
void serialize (typed_option< std::vector< T >> &typed_option)
template<typename TTypes >
void add_impl (base_option &options)
template<>
void serialize (typed_option< bool > &typed_option)
template<>
void add_impl (base_option &)
template<>
void serialize (typed_option< bool > &typed_argument)
template<>
void add_impl (base_option &options)
Private Attributes
std::stringstream m_output_stream
Detailed Description
Definition at line 19 of file options_serializer_boost_po.h.
Constructor & Destructor Documentation
VW::config::options_serializer_boost_po::options_serializer_boost_po () inline
Definition at line 21 of file options_serializer_boost_po.h.
References add(), data(), m_output_stream, size(), and str().
 { m_output_stream.precision(15); }
Member Function Documentation
void options_serializer_boost_po::add (base_option & option) override virtual
Implements VW::config::options_serializer_i.
Definition at line 15 of file options_serializer_boost_po.cc.
Referenced by options_serializer_boost_po(), save_load_header(), and VW::seed_vw_model().
 { add_impl<supported_options_types>(option); }
template<> void VW::config::options_serializer_boost_po::add_impl (base_option &) private
Definition at line 27 of file options_serializer_boost_po.cc.
References THROW.
 {
   THROW("That is an unsupported option type.");
 }
template<typename TTypes > void VW::config::options_serializer_boost_po::add_impl (base_option & options) inline private
Definition at line 63 of file options_serializer_boost_po.h.
   {
     if (serialize_if_t<typename TTypes::head>(options))
     {
       return;
     }
     add_impl<typename TTypes::tail>(options);
   }
template<> void VW::config::options_serializer_boost_po::add_impl (base_option & options) private
const char * options_serializer_boost_po::data () override virtual
Implements VW::config::options_serializer_i.
Definition at line 11 of file options_serializer_boost_po.cc.
References m_output_stream.
Referenced by options_serializer_boost_po().
 { return m_output_stream.str().c_str(); }
template<> void VW::config::options_serializer_boost_po::serialize (typed_option< bool > & typed_option) private
Definition at line 18 of file options_serializer_boost_po.cc.
References VW::config::base_option::m_name, m_output_stream, and VW::config::typed_option< T >::value().
 {
   if (typed_option.value())
   {
     m_output_stream << " --" << typed_option.m_name;
   }
 }
template<typename T > void VW::config::options_serializer_boost_po::serialize (typed_option< T > & typed_option) inline private
Definition at line 43 of file options_serializer_boost_po.h.
References VW::config::base_option::m_name, m_output_stream, and VW::config::typed_option< T >::value().
Referenced by serialize_if_t().
   {
     m_output_stream << " --" << typed_option.m_name << " " << typed_option.value();
   }
template<typename T > void VW::config::options_serializer_boost_po::serialize (typed_option< std::vector< T >> & typed_option) inline private
Definition at line 49 of file options_serializer_boost_po.h.
References VW::config::base_option::m_name, m_output_stream, and VW::config::typed_option< T >::value().
   {
     auto vec = typed_option.value();
     if (vec.size() > 0)
     {
       for (auto const& value : vec)
       {
         m_output_stream << " --" << typed_option.m_name;
         m_output_stream << " " << value;
       }
     }
   }
template<> void VW::config::options_serializer_boost_po::serialize (typed_option< bool > & typed_argument) private
template<typename T > bool VW::config::options_serializer_boost_po::serialize_if_t (base_option & base_option) inline private
Definition at line 30 of file options_serializer_boost_po.h.
References VW::config::base_option::m_type_hash, and serialize().
   {
     if (base_option.m_type_hash == typeid(T).hash_code())
     {
       auto typed = dynamic_cast<typed_option<T>&>(base_option);
       serialize(typed);
       return true;
     }
     return false;
   }
size_t options_serializer_boost_po::size () override virtual
Implements VW::config::options_serializer_i.
Definition at line 13 of file options_serializer_boost_po.cc.
References m_output_stream.
Referenced by options_serializer_boost_po().
 { return m_output_stream.str().size(); }
std::string options_serializer_boost_po::str () override virtual
Implements VW::config::options_serializer_i.
Definition at line 9 of file options_serializer_boost_po.cc.
References m_output_stream.
Referenced by options_serializer_boost_po(), save_load_header(), and VW::seed_vw_model().
 { return m_output_stream.str(); }
Member Data Documentation
std::stringstream VW::config::options_serializer_boost_po::m_output_stream private
Definition at line 72 of file options_serializer_boost_po.h.
Referenced by data(), options_serializer_boost_po(), serialize(), size(), and str().
The documentation for this struct was generated from the following files:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/options_serializer_boost_po.h
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/options_serializer_boost_po.cc