Vowpal Wabbit: VW::cb_explore_adf::regcb::cb_explore_adf_regcb Struct Reference
VW::cb_explore_adf::regcb::cb_explore_adf_regcb Struct Reference
Public Member Functions
cb_explore_adf_regcb (bool regcbopt, float c0, bool first_only, float min_cb_cost, float max_cb_cost)
~cb_explore_adf_regcb ()=default
void predict (LEARNER::multi_learner &base, multi_ex &examples)
void learn (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void predict_or_learn_impl (LEARNER::multi_learner &base, multi_ex &examples)
void get_cost_ranges (float delta, LEARNER::multi_learner &base, multi_ex &examples, bool min_only)
float binary_search (float fhat, float delta, float sens, float tol=1e-6)
Private Attributes
size_t _counter
bool _regcbopt
float _c0
bool _first_only
float _min_cb_cost
float _max_cb_cost
std::vector< float > _min_costs
std::vector< float > _max_costs
std::vector< ACTION_SCORE::action_scores > _ex_as
std::vector< v_array< CB::cb_class > > _ex_costs
Detailed Description
Definition at line 30 of file cb_explore_adf_regcb.cc.
Constructor & Destructor Documentation
VW::cb_explore_adf::regcb::cb_explore_adf_regcb::cb_explore_adf_regcb (bool regcbopt, float c0, bool first_only, float min_cb_cost, float max_cb_cost)
Definition at line 63 of file cb_explore_adf_regcb.cc.
     : _regcbopt(regcbopt), _c0(c0), _first_only(first_only), _min_cb_cost(min_cb_cost), _max_cb_cost(max_cb_cost)
 {
 }
VW::cb_explore_adf::regcb::cb_explore_adf_regcb::~cb_explore_adf_regcb () default
Member Function Documentation
float VW::cb_explore_adf::regcb::cb_explore_adf_regcb::binary_search (float fhat, float delta, float sens, float tol = 1e-6) private
Definition at line 70 of file cb_explore_adf_regcb.cc.
References B_SEARCH_MAX_ITER, and f.
Referenced by get_cost_ranges(), and learn().
 {
   const float maxw = (std::min)(fhat / sens, FLT_MAX);
   if (maxw * fhat * fhat <= delta)
     return maxw;
   float l = 0;
   float u = maxw;
   float w, v;
   for (int iter = 0; iter < B_SEARCH_MAX_ITER; iter++)
   {
     w = (u + l) / 2.f;
     v = w * (fhat * fhat - (fhat - sens * w) * (fhat - sens * w)) - delta;
     if (v > 0)
       u = w;
     else
       l = w;
     if (fabs(v) <= tol || u - l <= tol)
       break;
   }
   return l;
 }
void VW::cb_explore_adf::regcb::cb_explore_adf_regcb::get_cost_ranges (float delta, LEARNER::multi_learner & base, multi_ex & examples, bool min_only) private
Definition at line 96 of file cb_explore_adf_regcb.cc.
References _ex_as, _ex_costs, _max_cb_cost, _max_costs, _min_cb_cost, _min_costs, a, binary_search(), example::l, label_data::label, example::pred, polyprediction::scalar, LEARNER::learner< T, E >::sensitivity(), and polylabel::simple.
Referenced by learn(), and predict_or_learn_impl().
 {
   const size_t num_actions = examples[0]->pred.a_s.size();
   _min_costs.resize(num_actions);
   _max_costs.resize(num_actions);
   _ex_as.clear();
   _ex_costs.clear();
   // backup cb example data
   for (const auto& ex : examples)
   {
     _ex_as.push_back(ex->pred.a_s);
     _ex_costs.push_back(ex->l.cb.costs);
   }
   // set regressor predictions
   for (const auto& as : _ex_as[0])
   {
     examples[as.action]->pred.scalar = as.score;
   }
   const float cmin = _min_cb_cost;
   const float cmax = _max_cb_cost;
   for (size_t a = 0; a < num_actions; ++a)
   {
     example* ec = examples[a];
     ec->l.simple.label = cmin - 1;
     float sens = base.sensitivity(*ec);
     float w = 0;  // importance weight
     if (ec->pred.scalar < cmin || std::isnan(sens) || std::isinf(sens))
       _min_costs[a] = cmin;
     else
     {
       w = binary_search(ec->pred.scalar - cmin + 1, delta, sens);
       _min_costs[a] = (std::max)(ec->pred.scalar - sens * w, cmin);
       if (_min_costs[a] > cmax)
         _min_costs[a] = cmax;
     }
     if (!min_only)
     {
       ec->l.simple.label = cmax + 1;
       sens = base.sensitivity(*ec);
       if (ec->pred.scalar > cmax || std::isnan(sens) || std::isinf(sens))
       {
         _max_costs[a] = cmax;
       }
       else
       {
         w = binary_search(cmax + 1 - ec->pred.scalar, delta, sens);
         _max_costs[a] = (std::min)(ec->pred.scalar + sens * w, cmax);
         if (_max_costs[a] < cmin)
           _max_costs[a] = cmin;
       }
     }
   }
   // reset cb example data
   for (size_t i = 0; i < examples.size(); ++i)
   {
     examples[i]->pred.a_s = _ex_as[i];
     examples[i]->l.cb.costs = _ex_costs[i];
   }
 }
void VW::cb_explore_adf::regcb::cb_explore_adf_regcb::learn (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 53 of file cb_explore_adf_regcb.cc.
References binary_search(), get_cost_ranges(), and predict_or_learn_impl().
 { predict_or_learn_impl<true>(base, examples); }
void VW::cb_explore_adf::regcb::cb_explore_adf_regcb::predict (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 52 of file cb_explore_adf_regcb.cc.
 { predict_or_learn_impl<false>(base, examples); }
template<bool is_learn> void VW::cb_explore_adf::regcb::cb_explore_adf_regcb::predict_or_learn_impl (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 165 of file cb_explore_adf_regcb.cc.
References _c0, _counter, _first_only, _max_cb_cost, _max_costs, _min_cb_cost, _min_costs, _regcbopt, a, ACTION_SCORE::begin_scores(), CB::label::costs, ACTION_SCORE::end_scores(), exploration::enforce_minimum_probability(), get_cost_ranges(), and v_array< T >::size().
Referenced by learn().
 {
   if (is_learn)
   {
     for (size_t i = 0; i < examples.size() - 1; ++i)
     {
       CB::label& ld = examples[i]->l.cb;
       if (ld.costs.size() == 1)
         ld.costs[0].probability = 1.f;  // no importance weighting
     }
     LEARNER::multiline_learn_or_predict<true>(base, examples, examples[0]->ft_offset);
     ++_counter;
   }
   else
     LEARNER::multiline_learn_or_predict<false>(base, examples, examples[0]->ft_offset);
   v_array<ACTION_SCORE::action_score>& preds = examples[0]->pred.a_s;
   uint32_t num_actions = (uint32_t)preds.size();
   const float max_range = _max_cb_cost - _min_cb_cost;
   // threshold on empirical loss difference
   const float delta = _c0 * log((float)(num_actions * _counter)) * pow(max_range, 2);
   if (!is_learn)
   {
     get_cost_ranges(delta, base, examples, /*min_only=*/_regcbopt);
     if (_regcbopt)  // optimistic variant
     {
       float min_cost = FLT_MAX;
       size_t a_opt = 0;  // optimistic action
       for (size_t a = 0; a < num_actions; ++a)
       {
         if (_min_costs[a] < min_cost)
         {
           min_cost = _min_costs[a];
           a_opt = a;
         }
       }
       for (size_t i = 0; i < preds.size(); ++i)
       {
         if (preds[i].action == a_opt || (!_first_only && _min_costs[preds[i].action] == min_cost))
           preds[i].score = 1;
         else
           preds[i].score = 0;
       }
     }
     else  // elimination variant
     {
       float min_max_cost = FLT_MAX;
       for (size_t a = 0; a < num_actions; ++a)
         if (_max_costs[a] < min_max_cost)
           min_max_cost = _max_costs[a];
       for (size_t i = 0; i < preds.size(); ++i)
       {
         if (_min_costs[preds[i].action] <= min_max_cost)
           preds[i].score = 1;
         else
           preds[i].score = 0;
         // explore uniformly on support
         exploration::enforce_minimum_probability(
             1.0, /*update_zero_elements=*/false, begin_scores(preds), end_scores(preds));
       }
     }
   }
 }
Member Data Documentation
float VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_c0 private
Definition at line 35 of file cb_explore_adf_regcb.cc.
Referenced by predict_or_learn_impl().
size_t VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_counter private
Definition at line 33 of file cb_explore_adf_regcb.cc.
Referenced by predict_or_learn_impl().
std::vector<ACTION_SCORE::action_scores> VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_ex_as private
Definition at line 44 of file cb_explore_adf_regcb.cc.
Referenced by get_cost_ranges().
std::vector<v_array<CB::cb_class> > VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_ex_costs private
Definition at line 45 of file cb_explore_adf_regcb.cc.
Referenced by get_cost_ranges().
bool VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_first_only private
Definition at line 36 of file cb_explore_adf_regcb.cc.
Referenced by predict_or_learn_impl().
float VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_max_cb_cost private
Definition at line 38 of file cb_explore_adf_regcb.cc.
Referenced by get_cost_ranges(), and predict_or_learn_impl().
std::vector<float> VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_max_costs private
Definition at line 41 of file cb_explore_adf_regcb.cc.
Referenced by get_cost_ranges(), and predict_or_learn_impl().
float VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_min_cb_cost private
Definition at line 37 of file cb_explore_adf_regcb.cc.
Referenced by get_cost_ranges(), and predict_or_learn_impl().
std::vector<float> VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_min_costs private
Definition at line 40 of file cb_explore_adf_regcb.cc.
Referenced by get_cost_ranges(), and predict_or_learn_impl().
bool VW::cb_explore_adf::regcb::cb_explore_adf_regcb::_regcbopt private
Definition at line 34 of file cb_explore_adf_regcb.cc.
Referenced by predict_or_learn_impl().
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cb_explore_adf_regcb.cc