Vowpal Wabbit: VW::cb_explore_adf::cb_explore_adf_base< ExploreType > Struct Template Reference
VW::cb_explore_adf::cb_explore_adf_base< ExploreType > Struct Template Reference
#include <cb_explore_adf_common.h>
Public Member Functions
template<typename... Args>
cb_explore_adf_base (Args &&...args)
Static Public Member Functions
static void finish_multiline_example (vw &all, cb_explore_adf_base< ExploreType > &data, multi_ex &ec_seq)
static void predict (cb_explore_adf_base< ExploreType > &data, LEARNER::multi_learner &base, multi_ex &examples)
static void learn (cb_explore_adf_base< ExploreType > &data, LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
void output_example_seq (vw &all, multi_ex &ec_seq)
void output_example (vw &all, multi_ex &ec_seq)
Private Attributes
CB::cb_class _known_cost
CB::label _action_label
CB::label _empty_label
ExploreType explore
Detailed Description
template<typename ExploreType>
struct VW::cb_explore_adf::cb_explore_adf_base< ExploreType >
Definition at line 63 of file cb_explore_adf_common.h.
Constructor & Destructor Documentation
template<typename ExploreType> template<typename... Args> VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::cb_explore_adf_base (Args &&... args) inline
Definition at line 74 of file cb_explore_adf_common.h.
References VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::finish_multiline_example(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::learn(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example_seq(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict().
                                       : explore(std::forward<Args>(args)...)
   {
   }
Member Function Documentation
template<typename ExploreType > void VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::finish_multiline_example (vw & all, cb_explore_adf_base< ExploreType > & data, multi_ex & ec_seq) static
Definition at line 193 of file cb_explore_adf_common.h.
References vw::final_prediction_sink, VW::finish_example(), CB_ADF::global_print_newline(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example_seq().
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::cb_explore_adf_base().
 {
   if (ec_seq.size() > 0)
   {
     data.output_example_seq(all, ec_seq);
     CB_ADF::global_print_newline(all.final_prediction_sink);
   }
   VW::finish_example(all, ec_seq);
 }
template<typename ExploreType > void VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::learn (cb_explore_adf_base< ExploreType > & data, LEARNER::multi_learner & base, multi_ex & examples) inline static
Definition at line 110 of file cb_explore_adf_common.h.
References VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_known_cost, VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::explore, CB_ADF::get_observed_cost(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict(), and CB_ADF::test_adf_sequence().
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::cb_explore_adf_base().
 {
   example* label_example = CB_ADF::test_adf_sequence(examples);
   if (label_example != nullptr)
   {
     data._known_cost = CB_ADF::get_observed_cost(examples);
     // learn iff label_example != nullptr
     data.explore.learn(base, examples);
   }
   else
   {
     predict(data, base, examples);
   }
 }
template<typename ExploreType > void VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example (vw & all, multi_ex & ec_seq) private
Definition at line 127 of file cb_explore_adf_common.h.
References VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_known_cost, vw::final_prediction_sink, CB_ALGS::get_cost_estimate(), loss(), example::num_features, ACTION_SCORE::print_action_score(), vw::print_text_by_ref, CB::print_update(), CB::cb_class::probability, vw::raw_prediction, vw::sd, and shared_data::update().
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::cb_explore_adf_base(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example_seq().
 {
   if (ec_seq.size() <= 0)
     return;
   size_t num_features = 0;
   float loss = 0.;
   auto& ec = *ec_seq[0];
   const auto& preds = ec.pred.a_s;
   for (const auto& example : ec_seq)
   {
     num_features += example->num_features;
   }
   bool labeled_example = true;
   if (_known_cost.probability > 0)
   {
     for (uint32_t i = 0; i < preds.size(); i++)
     {
       float l = CB_ALGS::get_cost_estimate(&_known_cost, preds[i].action);
       loss += l * preds[i].score;
     }
   }
   else
     labeled_example = false;
   bool holdout_example = labeled_example;
   for (size_t i = 0; i < ec_seq.size(); i++) holdout_example &= ec_seq[i]->test_only;
   all.sd->update(holdout_example, labeled_example, loss, ec.weight, num_features);
   for (auto sink : all.final_prediction_sink) ACTION_SCORE::print_action_score(sink, ec.pred.a_s, ec.tag);
   if (all.raw_prediction > 0)
   {
     std::string outputString;
     std::stringstream outputStringStream(outputString);
     const auto& costs = ec.l.cb.costs;
     for (size_t i = 0; i < costs.size(); i++)
     {
       if (i > 0)
         outputStringStream << ' ';
       outputStringStream << costs[i].action << ':' << costs[i].partial_prediction;
     }
     all.print_text_by_ref(all.raw_prediction, outputStringStream.str(), ec.tag);
   }
   CB::print_update(all, !labeled_example, ec, &ec_seq, true);
 }
template<typename ExploreType > void VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example_seq (vw & all, multi_ex & ec_seq) private
Definition at line 182 of file cb_explore_adf_common.h.
References VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example(), vw::print_text_by_ref, and vw::raw_prediction.
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::cb_explore_adf_base(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::finish_multiline_example().
 {
   if (ec_seq.size() > 0)
   {
     output_example(all, ec_seq);
     if (all.raw_prediction > 0)
       all.print_text_by_ref(all.raw_prediction, "", ec_seq[0]->tag);
   }
 }
template<typename ExploreType > void VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict (cb_explore_adf_base< ExploreType > & data, LEARNER::multi_learner & base, multi_ex & examples) inline static
Definition at line 87 of file cb_explore_adf_common.h.
References VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_action_label, VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_empty_label, VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_known_cost, polylabel::cb, VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::explore, CB_ADF::get_observed_cost(), example::l, and CB_ADF::test_adf_sequence().
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::cb_explore_adf_base(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::learn().
 {
   example* label_example = CB_ADF::test_adf_sequence(examples);
   data._known_cost = CB_ADF::get_observed_cost(examples);
   if (label_example != nullptr)
   {
     // predict path, replace the label example with an empty one
     data._action_label = label_example->l.cb;
     label_example->l.cb = data._empty_label;
   }
   data.explore.predict(base, examples);
   if (label_example != nullptr)
   {
     // predict path, restore label
     label_example->l.cb = data._action_label;
   }
 }
Member Data Documentation
template<typename ExploreType> CB::label VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_action_label private
Definition at line 68 of file cb_explore_adf_common.h.
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict().
template<typename ExploreType> CB::label VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_empty_label private
Definition at line 69 of file cb_explore_adf_common.h.
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict().
template<typename ExploreType> CB::cb_class VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::_known_cost private
Definition at line 66 of file cb_explore_adf_common.h.
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::learn(), VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::output_example(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict().
template<typename ExploreType> ExploreType VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::explore private
Definition at line 70 of file cb_explore_adf_common.h.
Referenced by VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::learn(), and VW::cb_explore_adf::cb_explore_adf_base< ExploreType >::predict().
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cb_explore_adf_common.h