Vowpal Wabbit: features Struct Reference
features Struct Reference
the core definition of a set of features.
#include <feature_group.h>
Classes
class features_value_index_audit_range
defines a "range" usable by C++ 11 for loops
Public Types
typedef features_value_index_iterator iterator
typedef features_value_iterator iterator_value
typedef features_value_index_audit_iterator iterator_all
Public Member Functions
features ()
~features ()
features (const features &)=delete
features & operator= (const features &)=delete
features (features &&other)
features & operator= (features &&other)
size_t size () const
bool nonempty () const
void free_space_names (size_t i)
features_value_index_audit_range values_indices_audit ()
iterator begin ()
iterator end ()
void clear ()
void truncate_to (const features_value_iterator &pos)
void truncate_to (size_t i)
void push_back (feature_value v, feature_index i)
bool sort (uint64_t parse_mask)
void deep_copy_from (const features &src)
Public Attributes
v_array< feature_value > values
v_array< feature_index > indicies
v_array< audit_strings_ptr > space_names
float sum_feat_sq
Detailed Description
the core definition of a set of features.
Definition at line 248 of file feature_group.h.
Member Typedef Documentation
typedef features_value_index_iterator features::iterator
Definition at line 256 of file feature_group.h.
typedef features_value_index_audit_iterator features::iterator_all
Definition at line 258 of file feature_group.h.
typedef features_value_iterator features::iterator_value
Definition at line 257 of file feature_group.h.
Constructor & Destructor Documentation
features::features () inline
Definition at line 276 of file feature_group.h.
   {
     values = v_init<feature_value>();
     indicies = v_init<feature_index>();
     space_names = v_init<audit_strings_ptr>();
     sum_feat_sq = 0.f;
   }
features::~features () inline
Definition at line 284 of file feature_group.h.
References v_array< T >::delete_v().
Referenced by free_flatten_example().
               {
      values.delete_v();
      indicies.delete_v();
      space_names.delete_v();
    }
features::features (const features &) delete
features::features (features && other) inline
Definition at line 295 of file feature_group.h.
References v_array< T >::_begin.
                               :
    values(std::move(other.values)),
    indicies(std::move(other.indicies)),
    space_names(std::move(other.space_names)),
    sum_feat_sq(other.sum_feat_sq)
    {
      // We need to null out all the v_arrays to prevent double freeing during moves
      auto & v = other.values;
      v._begin = nullptr;
      v._end = nullptr;
      v.end_array = nullptr;
      auto & i = other.indicies;
      i._begin = nullptr;
      i._end = nullptr;
      i.end_array = nullptr;
      auto & s = other.space_names;
      s._begin = nullptr;
      s._end = nullptr;
      s.end_array = nullptr;
      other.sum_feat_sq = 0;
    }
Member Function Documentation
iterator features::begin () inline
Definition at line 351 of file feature_group.h.
References v_array< T >::begin().
Referenced by collision_cleanup(), MARGINAL::make_marginal(), and MARGINAL::update_marginal().
 { return iterator(values.begin(), indicies.begin()); }
void features::clear () inline
Definition at line 355 of file feature_group.h.
References v_array< T >::clear().
Referenced by Search::add_example_conditioning(), GraphTask::del_edge_features(), Search::del_features_in_top_namespace(), memory_tree_ns::diag_kronecker_prod_fs_test(), MARGINAL::make_marginal(), multiply(), MWT::predict_or_learn(), recall_tree_ns::remove_node_id_feature(), VW::autolink::reset_example(), memory_tree_ns::save_load_example(), Search::search_predict(), and CSOAA::unsubtract_example().
   {
     sum_feat_sq = 0.f;
     values.clear();
     indicies.clear();
     space_names.clear();
   }
void features::deep_copy_from (const features & src) inline
Definition at line 444 of file feature_group.h.
References copy_array(), copy_array_no_memcpy(), indicies, space_names, sum_feat_sq, and values.
Referenced by Search::action_repr::action_repr(), VW::copy_example_metadata(), learn(), predict_or_learn(), and LabelDict::set_label_features().
   {
     copy_array(values, src.values);
     copy_array(indicies, src.indicies);
     copy_array_no_memcpy(space_names, src.space_names);
     sum_feat_sq = src.sum_feat_sq;
   }
iterator features::end () inline
Definition at line 353 of file feature_group.h.
References v_array< T >::end().
Referenced by MARGINAL::make_marginal(), and MARGINAL::update_marginal().
 { return iterator(values.end(), indicies.end()); }
void features::free_space_names (size_t i) inline
Definition at line 343 of file feature_group.h.
References v_array< T >::size().
   {
     for (; i < space_names.size(); i++) space_names[i].~audit_strings_ptr();
   }
bool features::nonempty () const inline
Definition at line 341 of file feature_group.h.
References v_array< T >::empty().
Referenced by INTERACTIONS::generate_interactions().
 { return !values.empty(); }
features& features::operator= (const features &) delete
features& features::operator= (features && other) inline
Definition at line 316 of file feature_group.h.
    {
      values = std::move(other.values);
      indicies = std::move(other.indicies);
      space_names = std::move(other.space_names);
      sum_feat_sq = other.sum_feat_sq;
      // We need to null out all the v_arrays to prevent double freeing during moves
      auto & v = other.values;
      v._begin = nullptr;
      v._end = nullptr;
      v.end_array = nullptr;
      auto & i = other.indicies;
      i._begin = nullptr;
      i._end = nullptr;
      i.end_array = nullptr;
      auto & s = other.space_names;
      s._begin = nullptr;
      s._end = nullptr;
      s.end_array = nullptr;
      other.sum_feat_sq = 0;
      return *this;
    }
void features::push_back (feature_value v, feature_index i) inline
Definition at line 388 of file feature_group.h.
References v_array< T >::push_back().
Referenced by DepParserTask::add_all_features(), GraphTask::add_edge_features_single_fn(), LabelDict::add_example_namespace(), Search::add_new_feature(), recall_tree_ns::add_node_id_feature(), add_passthrough_feature_magic(), Namespace< audit >::AddFeature(), addgrams(), memory_tree_ns::diag_kronecker_prod_fs_test(), finish_setup(), MARGINAL::make_marginal(), TC_parser< audit >::maybeFeature(), multiply(), predict_or_learn(), MWT::predict_or_learn(), VW::autolink::prepare_example(), read_cached_features(), memory_tree_ns::save_load_example(), and vec_ffs_store().
   {
     values.push_back(v);
     indicies.push_back(i);
     sum_feat_sq += v * v;
   }
size_t features::size () const inline
Definition at line 339 of file feature_group.h.
References v_array< T >::size().
Referenced by Search::add_example_conditioning(), LabelDict::add_example_namespace(), ezexample::add_other_example_ns(), audit_regressor(), audit_regressor_lda(), contains_valid_namespaces(), GraphTask::del_edge_features(), LabelDict::del_example_namespace(), Search::del_features_in_top_namespace(), memory_tree_ns::diag_kronecker_prod_fs_test(), INTERACTIONS::eval_count_of_generated_ft(), DepParserTask::extract_features(), learn(), memory_tree_ns::linear_kernel(), linear_kernel(), MARGINAL::make_marginal(), TC_parser< audit >::maybeFeature(), multiply(), output_features(), CSOAA::predict_or_learn(), predict_or_learn(), memory_tree_ns::save_load_example(), save_load_flat_example(), sd_offset_update(), Search::search_predict(), CSOAA::subtract_example(), synthetic_decycle(), unique_features(), and CSOAA::unsubtract_example().
 { return values.size(); }
bool features::sort (uint64_t parse_mask) inline
Definition at line 395 of file feature_group.h.
References v_array< T >::empty(), v_array< T >::push_back(), v_array< T >::size(), feature::weight_index, feature_slice::weight_index, feature::x, and feature_slice::x.
Referenced by feature_limit(), and flatten_sort_example().
   {
     if (indicies.empty())
       return false;
     if (!space_names.empty())
     {
       std::vector<feature_slice> slice;
       slice.reserve(indicies.size());
       for (size_t i = 0; i < indicies.size(); i++)
       {
         slice.push_back({values[i], indicies[i] & parse_mask, *space_names[i].get()});
       }
       // The comparator should return true if the first element is less than the second.
       std::sort(slice.begin(), slice.end(), [](const feature_slice& first, const feature_slice& second) {
         return (first.weight_index < second.weight_index) ||
             ((first.weight_index == second.weight_index) && (first.x < second.x));
       });
       for (size_t i = 0; i < slice.size(); i++)
       {
         values[i] = slice[i].x;
         indicies[i] = slice[i].weight_index;
         *space_names[i].get() = slice[i].space_name;
       }
     }
     else
     {
       std::vector<feature> slice;
       slice.reserve(indicies.size());
       for (size_t i = 0; i < indicies.size(); i++)
       {
         slice.push_back({values[i], indicies[i] & parse_mask});
       }
       // The comparator should return true if the first element is less than the second.
       std::sort(slice.begin(), slice.end(), [](const feature& first, const feature& second) {
         return (first.weight_index < second.weight_index) ||
             ((first.weight_index == second.weight_index) && (first.x < second.x));
       });
       for (size_t i = 0; i < slice.size(); i++)
       {
         values[i] = slice[i].x;
         indicies[i] = slice[i].weight_index;
       }
     }
     return true;
   }
void features::truncate_to (const features_value_iterator & pos) inline
Definition at line 363 of file feature_group.h.
References features_value_iterator::_begin, v_array< T >::begin(), and v_array< T >::end().
Referenced by LabelDict::del_example_namespace(), and unique_features().
   {
     ssize_t i = pos._begin - values.begin();
     values.end() = pos._begin;
     if (indicies.end() != indicies.begin())
       indicies.end() = indicies.begin() + i;
     if (space_names.begin() != space_names.end())
     {
       free_space_names((size_t)i);
       space_names.end() = space_names.begin() + i;
     }
   }
void features::truncate_to (size_t i) inline
Definition at line 376 of file feature_group.h.
References v_array< T >::begin(), and v_array< T >::end().
   {
     values.end() = values.begin() + i;
     if (indicies.end() != indicies.begin())
       indicies.end() = indicies.begin() + i;
     if (space_names.begin() != space_names.end())
     {
       free_space_names(i);
       space_names.end() = space_names.begin() + i;
     }
   }
features_value_index_audit_range features::values_indices_audit () inline
Definition at line 348 of file feature_group.h.
Referenced by INTERACTIONS::generate_interactions(), and unique_features().
 { return {this}; }
Member Data Documentation
v_array<feature_index> features::indicies
Definition at line 251 of file feature_group.h.
Referenced by Search::add_example_conditioning(), LabelDict::add_example_namespace(), Search::add_new_feature(), ezexample::add_other_example_ns(), addgrams(), audit_regressor(), audit_regressor_lda(), features::features_value_index_audit_range::begin(), deep_copy_from(), memory_tree_ns::diag_kronecker_prod_fs_test(), features::features_value_index_audit_range::end(), finish_setup(), INTERACTIONS::generate_interactions(), memory_tree_ns::linear_kernel(), linear_kernel(), TC_parser< audit >::maybeFeature(), multiply(), predict_or_learn(), CSOAA::predict_or_learn(), predict_or_learn_multi(), memory_tree_ns::save_load_example(), save_load_flat_example(), sd_offset_update(), Search::search_predict(), synthetic_decycle(), and unique_features().
v_array<audit_strings_ptr> features::space_names
Definition at line 252 of file feature_group.h.
Referenced by LabelDict::add_example_namespace(), Search::add_new_feature(), Namespace< audit >::AddFeature(), addgrams(), audit_regressor(), audit_regressor_lda(), features::features_value_index_audit_range::begin(), deep_copy_from(), features::features_value_index_audit_range::end(), finish_setup(), INTERACTIONS::generate_interactions(), MARGINAL::make_marginal(), TC_parser< audit >::maybeFeature(), predict_or_learn(), and unique_features().
float features::sum_feat_sq
Definition at line 254 of file feature_group.h.
Referenced by Search::add_example_conditioning(), LabelDict::add_example_namespace(), ezexample::add_other_example_ns(), deep_copy_from(), GraphTask::del_edge_features(), LabelDict::del_example_namespace(), Search::del_features_in_top_namespace(), DepParserTask::extract_features(), TC_parser< audit >::maybeFeature(), predict_or_learn(), predict_or_learn_multi(), VW::autolink::prepare_example(), VW::autolink::reset_example(), CSOAA::subtract_example(), and CSOAA::unsubtract_example().
v_array<feature_value> features::values
Definition at line 250 of file feature_group.h.
Referenced by Search::add_example_conditioning(), LabelDict::add_example_namespace(), Search::add_new_feature(), ezexample::add_other_example_ns(), audit_regressor(), features::features_value_index_audit_range::begin(), contains_valid_namespaces(), deep_copy_from(), memory_tree_ns::diag_kronecker_prod_fs_test(), features::features_value_index_audit_range::end(), INTERACTIONS::eval_count_of_generated_ft(), finish_setup(), INTERACTIONS::generate_interactions(), learn(), memory_tree_ns::linear_kernel(), linear_kernel(), TC_parser< audit >::maybeFeature(), multiply(), output_features(), predict_or_learn(), CSOAA::predict_or_learn(), predict_or_learn_multi(), memory_tree_ns::save_load_example(), save_load_flat_example(), sd_offset_update(), and Search::search_predict().
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/feature_group.h