Vowpal Wabbit: LEARNER::learner< T, E > Struct Template Reference
LEARNER::learner< T, E > Struct Template Reference
#include <cb_explore.h>
Public Types
using end_fptr_type = void(*)(vw &, void *, void *)
using finish_fptr_type = void(*)(void *)
Public Member Functions
void learn (E &ec, size_t i=0)
void predict (E &ec, size_t i=0)
void multipredict (E &ec, size_t lo, size_t count, polyprediction *pred, bool finalize_predictions)
template<class L >
void set_predict (void(*u)(T &, L &, E &))
template<class L >
void set_learn (void(*u)(T &, L &, E &))
template<class L >
void set_multipredict (void(*u)(T &, L &, E &, size_t, size_t, polyprediction *, bool))
void update (E &ec, size_t i=0)
template<class L >
void set_update (void(*u)(T &data, L &base, E &))
void set_sensitivity (float(*u)(T &data, base_learner &base, example &))
float sensitivity (example &ec, size_t i=0)
void save_load (io_buf &io, const bool read, const bool text)
void set_save_load (void(*sl)(T &, io_buf &, bool, bool))
void set_finish (void(*f)(T &))
void finish ()
void end_pass ()
void set_end_pass (void(*f)(T &))
void end_examples ()
void set_end_examples (void(*f)(T &))
void init_driver ()
void set_init_driver (void(*f)(T &))
void finish_example (vw &all, E &ec)
void set_finish_example (void(*f)(vw &all, T &, E &))
Static Public Member Functions
template<class L >
static learner< T, E > & init_learner (T *dat, L *base, void(*learn)(T &, L &, E &), void(*predict)(T &, L &, E &), size_t ws, prediction_type_t pred_type)
Public Attributes
prediction_type_t pred_type
size_t weights
size_t increment
bool is_multiline
Private Member Functions
learner ()
Private Attributes
func_data init_fd
learn_data learn_fd
sensitivity_data sensitivity_fd
finish_example_data finish_example_fd
save_load_data save_load_fd
func_data end_pass_fd
func_data end_examples_fd
func_data finisher_fd
std::shared_ptr< void > learner_data
Detailed Description
template<class T, class E>
struct LEARNER::learner< T, E >
Definition at line 10 of file cb_explore.h.
Member Typedef Documentation
template<class T, class E> using LEARNER::learner< T, E >::end_fptr_type = void (*)(vw&, void*, void*)
Definition at line 152 of file learner.h.
template<class T, class E> using LEARNER::learner< T, E >::finish_fptr_type = void (*)(void*)
Definition at line 153 of file learner.h.
Constructor & Destructor Documentation
template<class T, class E> LEARNER::learner< T, E >::learner () inline private
Definition at line 145 of file learner.h.
 {};  // Should only be able to construct a learner through init_learner function
Member Function Documentation
template<class T, class E> void LEARNER::learner< T, E >::end_examples () inline
Definition at line 285 of file learner.h.
Referenced by LEARNER::drain_examples(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::end_examples(), and LEARNER::generic_driver_onethread().
   {
     end_examples_fd.func(end_examples_fd.data);
     if (end_examples_fd.base)
       end_examples_fd.base->end_examples();
   }
template<class T, class E> void LEARNER::learner< T, E >::end_pass () inline
Definition at line 276 of file learner.h.
Referenced by LEARNER::end_pass(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::end_pass().
   {
     end_pass_fd.func(end_pass_fd.data);
     if (end_pass_fd.base)
       end_pass_fd.base->end_pass();
   }  // autorecursive
template<class T, class E> void LEARNER::learner< T, E >::finish () inline
Definition at line 262 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::finish(), and VW::finish().
   {
     if (finisher_fd.data)
     {
       finisher_fd.func(finisher_fd.data);
     }
     learner_data.~shared_ptr<void>();
     if (finisher_fd.base)
     {
       finisher_fd.base->finish();
       free(finisher_fd.base);
     }
   }
template<class T, class E> void LEARNER::learner< T, E >::finish_example (vw & all, E & ec) inline
Definition at line 298 of file learner.h.
Referenced by vw::finish_example(), LEARNER::learn_ex(), and LEARNER::learn_multi_ex().
   {
     finish_example_fd.finish_example_f(all, finish_example_fd.data, (void*)&ec);
   }
template<class T, class E> void LEARNER::learner< T, E >::init_driver () inline
Definition at line 294 of file learner.h.
Referenced by VW::initialize().
 { init_fd.func(init_fd.data); }
template<class T, class E> template<class L > static learner<T, E>& LEARNER::learner< T, E >::init_learner (T * dat, L * base, void(*)(T &, L &, E &) learn, void(*)(T &, L &, E &) predict, size_t ws, prediction_type_t pred_type) inline static
Definition at line 310 of file learner.h.
   {
     learner<T, E>& ret = calloc_or_throw<learner<T, E> >();
     if (base != nullptr)
     {  // a reduction
       // This is a copy assignment into the current object. The purpose is to copy all of the
       // function data objects so that if this reduction does not define a function such as
       // save_load then calling save_load on this object will essentially result in forwarding the
       // call the next reduction that actually implements it.
       ret = *(learner<T, E>*)(base);
       ret.learn_fd.base = make_base(*base);
       ret.sensitivity_fd.sensitivity_f = (sensitivity_data::fn)recur_sensitivity;
       ret.finisher_fd.data = dat;
       ret.finisher_fd.base = make_base(*base);
       ret.finisher_fd.func = (func_data::fn)noop;
       ret.weights = ws;
       ret.increment = base->increment * ret.weights;
     }
     else  // a base learner
     {
       ret.weights = 1;
       ret.increment = ws;
       ret.end_pass_fd.func = (func_data::fn)noop;
       ret.end_examples_fd.func = (func_data::fn)noop;
       ret.init_fd.func = (func_data::fn)noop;
       ret.save_load_fd.save_load_f = (save_load_data::fn)noop_sl;
       ret.finisher_fd.data = dat;
       ret.finisher_fd.func = (func_data::fn)noop;
       ret.sensitivity_fd.sensitivity_f = (sensitivity_data::fn)noop_sensitivity;
       ret.finish_example_fd.data = dat;
       ret.finish_example_fd.finish_example_f = (finish_example_data::fn)return_simple_example;
     }
     ret.learner_data = std::shared_ptr<T>(dat, [](T* ptr) {
       ptr->~T();
       free(ptr);
     });
     ret.learn_fd.data = dat;
     ret.learn_fd.learn_f = (learn_data::fn)learn;
     ret.learn_fd.update_f = (learn_data::fn)learn;
     ret.learn_fd.predict_f = (learn_data::fn)predict;
     ret.learn_fd.multipredict_f = nullptr;
     ret.pred_type = pred_type;
     ret.is_multiline = std::is_same<multi_ex, E>::value;
     return ret;
   }
template<class T, class E> void LEARNER::learner< T, E >::learn (E & ec, size_t i = 0) inline
Definition at line 156 of file learner.h.
Referenced by GEN_CS::call_cs_ldf(), do_actual_learning_ldf(), CSOAA::do_actual_learning_oaa(), CSOAA::do_actual_learning_wap(), ect_predict(), ect_train(), ExpReplay::end_pass(), Search::generate_training_example(), CB_ALGS::get_cost_pred(), CSOAA::inner_loop(), inner_loop(), VW::autolink::learn(), VW::topk::learn(), recall_tree_ns::learn(), vw::learn(), learn(), memory_tree_ns::learn_at_leaf_random(), learn_bandit_adf(), learn_randomized(), learn_sup_adf(), LEARNER::multiline_learn_or_predict(), VW::shared_feature_merger::predict_or_learn(), ExpReplay::predict_or_learn(), CB_ALGS::predict_or_learn(), CLASSWEIGHTS::predict_or_learn(), MWT::predict_or_learn(), predict_or_learn(), MARGINAL::predict_or_learn(), predict_or_learn_active(), predict_or_learn_active_cover(), predict_or_learn_adaptive(), predict_or_learn_adf(), CB_EXPLORE::predict_or_learn_bag(), CB_EXPLORE::predict_or_learn_cover(), CB_EXPLORE::predict_or_learn_first(), CB_EXPLORE::predict_or_learn_greedy(), predict_or_learn_logistic(), predict_or_learn_multi(), predict_or_learn_simulation(), predict_or_learn_with_confidence(), memory_tree_ns::return_reward_from_node(), memory_tree_ns::single_query_and_learn(), train_node(), recall_tree_ns::train_node(), memory_tree_ns::train_node(), and memory_tree_ns::train_one_against_some_at_leaf().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     increment_offset(ec, increment, i);
     learn_fd.learn_f(learn_fd.data, *learn_fd.base, (void*)&ec);
     decrement_offset(ec, increment, i);
   }
template<class T, class E> void LEARNER::learner< T, E >::multipredict (E & ec, size_t lo, size_t count, polyprediction * pred, bool finalize_predictions) inline
Definition at line 174 of file learner.h.
Referenced by multipredict(), ExpReplay::multipredict(), CSOAA::predict_or_learn(), predict_or_learn(), and predict_or_learn_multi().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     if (learn_fd.multipredict_f == NULL)
     {
       increment_offset(ec, increment, lo);
       for (size_t c = 0; c < count; c++)
       {
         learn_fd.predict_f(learn_fd.data, *learn_fd.base, (void*)&ec);
         if (finalize_predictions)
           pred[c] = ec.pred;  // TODO: this breaks for complex labels because = doesn't do deep copy!
         else
           pred[c].scalar = ec.partial_prediction;
         // pred[c].scalar = finalize_prediction ec.partial_prediction; // TODO: this breaks for complex labels because =
         // doesn't do deep copy! // note works if ec.partial_prediction, but only if finalize_prediction is run????
         increment_offset(ec, increment, 1);
       }
       decrement_offset(ec, increment, lo + count);
     }
     else
     {
       increment_offset(ec, increment, lo);
       learn_fd.multipredict_f(learn_fd.data, *learn_fd.base, (void*)&ec, count, increment, pred, finalize_predictions);
       decrement_offset(ec, increment, lo);
     }
   }
template<class T, class E> void LEARNER::learner< T, E >::predict (E & ec, size_t i = 0) inline
Definition at line 165 of file learner.h.
Referenced by GEN_CS::call_cs_ldf(), memory_tree_ns::compute_hamming_loss_via_oas(), do_actual_learning_ldf(), find_cost_range(), CB_ALGS::get_cost_pred(), CSOAA::inner_loop(), inner_loop(), vw::learn(), CSOAA::make_single_prediction(), LEARNER::multiline_learn_or_predict(), recall_tree_ns::oas_predict(), memory_tree_ns::pick_nearest(), VW::autolink::predict(), VW::topk::predict(), predict(), vw::predict(), memory_tree_ns::predict(), predict_bandit_adf(), recall_tree_ns::predict_from(), VW::shared_feature_merger::predict_or_learn(), ExpReplay::predict_or_learn(), CB_ALGS::predict_or_learn(), CLASSWEIGHTS::predict_or_learn(), MWT::predict_or_learn(), predict_or_learn(), MARGINAL::predict_or_learn(), predict_or_learn_active(), predict_or_learn_active_cover(), predict_or_learn_adaptive(), predict_or_learn_adf(), CB_EXPLORE::predict_or_learn_bag(), CB_EXPLORE::predict_or_learn_first(), CB_EXPLORE::predict_or_learn_greedy(), predict_or_learn_logistic(), predict_or_learn_multi(), predict_or_learn_simulation(), predict_or_learn_with_confidence(), predict_sublearner_adf(), VW::autolink::prepare_example(), query_decision(), memory_tree_ns::return_reward_from_node(), memory_tree_ns::route_to_leaf(), sensitivity(), Search::single_prediction_LDF(), Search::single_prediction_notLDF(), memory_tree_ns::split_leaf(), train_node(), recall_tree_ns::train_node(), memory_tree_ns::train_node(), VW_Predict(), and VW_PredictCostSensitive().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     increment_offset(ec, increment, i);
     learn_fd.predict_f(learn_fd.data, *learn_fd.base, (void*)&ec);
     decrement_offset(ec, increment, i);
   }
template<class T, class E> void LEARNER::learner< T, E >::save_load (io_buf & io, const bool read, const bool text) inline
Definition at line 247 of file learner.h.
Referenced by dump_regressor(), load_input_model(), parse_mask_regressor_args(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::save_load().
   {
     save_load_fd.save_load_f(save_load_fd.data, io, read, text);
     if (save_load_fd.base)
       save_load_fd.base->save_load(io, read, text);
   }
template<class T, class E> float LEARNER::learner< T, E >::sensitivity (example & ec, size_t i = 0) inline
Definition at line 238 of file learner.h.
Referenced by dis_test(), find_cost_range(), VW::cb_explore_adf::regcb::cb_explore_adf_regcb::get_cost_ranges(), predict_or_learn_active(), predict_or_learn_simulation(), predict_or_learn_with_confidence(), LEARNER::recur_sensitivity(), and sensitivity().
   {
     increment_offset(ec, increment, i);
     const float ret = sensitivity_fd.sensitivity_f(sensitivity_fd.data, *learn_fd.base, ec);
     decrement_offset(ec, increment, i);
     return ret;
   }
template<class T, class E> void LEARNER::learner< T, E >::set_end_examples (void(*)(T &) f) inline
Definition at line 291 of file learner.h.
Referenced by audit_regressor_setup(), lda_setup(), and Search::setup().
 { end_examples_fd = tuple_dbf(learn_fd.data, learn_fd.base, (func_data::fn)f); }
template<class T, class E> void LEARNER::learner< T, E >::set_end_pass (void(*)(T &) f) inline
Definition at line 282 of file learner.h.
Referenced by CSOAA::csldf_setup(), ExpReplay::expreplay_setup(), gd_mf_setup(), lda_setup(), lrq_setup(), memory_tree_setup(), nn_setup(), GD::setup(), Search::setup(), and stagewise_poly_setup().
 { end_pass_fd = tuple_dbf(learn_fd.data, learn_fd.base, (func_data::fn)f); }
template<class T, class E> void LEARNER::learner< T, E >::set_finish (void(*)(T &) f) inline
Definition at line 261 of file learner.h.
Referenced by audit_regressor_setup(), explore_eval_setup(), mf_setup(), Search::setup(), and warm_cb_setup().
 { finisher_fd = tuple_dbf(learn_fd.data, learn_fd.base, (finish_fptr_type)(f)); }
template<class T, class E> void LEARNER::learner< T, E >::set_finish_example (void(*)(vw &all, T &, E &) f) inline
Definition at line 303 of file learner.h.
Referenced by active_setup(), audit_regressor_setup(), bs_setup(), cb_adf_setup(), cb_algs_setup(), cb_explore_setup(), cbifyldf_setup(), CCB::ccb_explore_adf_setup(), confidence_setup(), cs_active_setup(), CSOAA::csldf_setup(), explore_eval_setup(), LEARNER::init_cost_sensitive_learner(), LEARNER::init_multiclass_learner(), lda_setup(), multilabel_oaa_setup(), mwt_setup(), nn_setup(), oaa_setup(), OjaNewton_setup(), VW::cb_explore_adf::softmax::setup(), VW::cb_explore_adf::greedy::setup(), VW::cb_explore_adf::first::setup(), Search::setup(), and stagewise_poly_setup().
   {
     finish_example_fd.data = learn_fd.data;
     finish_example_fd.finish_example_f = (end_fptr_type)(f);
   }
template<class T, class E> void LEARNER::learner< T, E >::set_init_driver (void(*)(T &) f) inline
Definition at line 295 of file learner.h.
Referenced by audit_regressor_setup().
 { init_fd = tuple_dbf(learn_fd.data, learn_fd.base, (func_data::fn)f); }
template<class T, class E> template<class L > void LEARNER::learner< T, E >::set_learn (void(*)(T &, L &, E &) u) inline
Definition at line 208 of file learner.h.
Referenced by oaa_setup().
   {
     learn_fd.learn_f = (learn_data::fn)u;
   }
template<class T, class E> template<class L > void LEARNER::learner< T, E >::set_multipredict (void(*)(T &, L &, E &, size_t, size_t, polyprediction *, bool) u) inline
Definition at line 213 of file learner.h.
Referenced by nn_setup(), scorer_setup(), and GD::setup().
   {
     learn_fd.multipredict_f = (learn_data::multi_fn)u;
   }
template<class T, class E> template<class L > void LEARNER::learner< T, E >::set_predict (void(*)(T &, L &, E &) u) inline
Definition at line 203 of file learner.h.
   {
     learn_fd.predict_f = (learn_data::fn)u;
   }
template<class T, class E> void LEARNER::learner< T, E >::set_save_load (void(*)(T &, io_buf &, bool, bool) sl) inline
Definition at line 253 of file learner.h.
Referenced by boosting_setup(), cb_adf_setup(), gd_mf_setup(), kernel_svm_setup(), lda_setup(), memory_tree_setup(), mwt_setup(), OjaNewton_setup(), recall_tree_setup(), GD::setup(), stagewise_poly_setup(), and svrg_setup().
   {
     save_load_fd.save_load_f = (save_load_data::fn)sl;
     save_load_fd.data = learn_fd.data;
     save_load_fd.base = learn_fd.base;
   }
template<class T, class E> void LEARNER::learner< T, E >::set_sensitivity (float(*)(T &data, base_learner< T, E > &base, example &) u) inline
Definition at line 233 of file learner.h.
Referenced by baseline_setup(), and GD::setup().
   {
     sensitivity_fd.data = learn_fd.data;
     sensitivity_fd.sensitivity_f = (sensitivity_data::fn)u;
   }
template<class T, class E> template<class L > void LEARNER::learner< T, E >::set_update (void(*)(T &data, L &base, E &) u) inline
Definition at line 227 of file learner.h.
Referenced by scorer_setup(), and GD::setup().
   {
     learn_fd.update_f = (learn_data::fn)u;
   }
template<class T, class E> void LEARNER::learner< T, E >::update (E & ec, size_t i = 0) inline
Definition at line 218 of file learner.h.
Referenced by predict_or_learn(), predict_or_learn_multi(), and update().
   {
     assert((is_multiline && std::is_same<multi_ex, E>::value) ||
         (!is_multiline && std::is_same<example, E>::value));  // sanity check under debug compile
     increment_offset(ec, increment, i);
     learn_fd.update_f(learn_fd.data, *learn_fd.base, (void*)&ec);
     decrement_offset(ec, increment, i);
   }
Member Data Documentation
template<class T, class E> func_data LEARNER::learner< T, E >::end_examples_fd private
Definition at line 141 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> func_data LEARNER::learner< T, E >::end_pass_fd private
Definition at line 140 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> finish_example_data LEARNER::learner< T, E >::finish_example_fd private
Definition at line 138 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> func_data LEARNER::learner< T, E >::finisher_fd private
Definition at line 142 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> size_t LEARNER::learner< T, E >::increment
Definition at line 149 of file learner.h.
Referenced by init_driver(), LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner(), and parse_sources().
template<class T, class E> func_data LEARNER::learner< T, E >::init_fd private
Definition at line 135 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> bool LEARNER::learner< T, E >::is_multiline
Definition at line 150 of file learner.h.
Referenced by LEARNER::as_multiline(), LEARNER::as_singleline(), LEARNER::generic_driver_onethread(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> learn_data LEARNER::learner< T, E >::learn_fd private
Definition at line 136 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> std::shared_ptr<void> LEARNER::learner< T, E >::learner_data private
Definition at line 144 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> prediction_type_t LEARNER::learner< T, E >::pred_type
Definition at line 145 of file learner.h.
Referenced by classweight_setup(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> save_load_data LEARNER::learner< T, E >::save_load_fd private
Definition at line 139 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> sensitivity_data LEARNER::learner< T, E >::sensitivity_fd private
Definition at line 137 of file learner.h.
Referenced by LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
template<class T, class E> size_t LEARNER::learner< T, E >::weights
Definition at line 148 of file learner.h.
Referenced by init_driver(), and LEARNER::learner< CB_EXPLORE::cb_explore, example >::init_learner().
The documentation for this struct was generated from the following files:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cb_explore.h
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/learner.h