Vowpal Wabbit: VW::object_pool< T, TInitializer, TCleanup > Struct Template Reference
VW::object_pool< T, TInitializer, TCleanup > Struct Template Reference
#include <object_pool.h>
Public Member Functions
object_pool ()=default
object_pool (size_t initial_chunk_size, TInitializer initializer={}, size_t chunk_size=8)
void return_object (T *obj)
T * get_object ()
bool empty () const
size_t size () const
bool is_from_pool (T *obj) const
Private Attributes
std::mutex m_lock
no_lock_object_pool< T, TInitializer, TCleanup > inner_pool
Detailed Description
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>>
struct VW::object_pool< T, TInitializer, TCleanup >
Definition at line 171 of file object_pool.h.
Constructor & Destructor Documentation
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> VW::object_pool< T, TInitializer, TCleanup >::object_pool () default
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> VW::object_pool< T, TInitializer, TCleanup >::object_pool (size_t initial_chunk_size, TInitializer initializer = {}, size_t chunk_size = 8) inline
Definition at line 174 of file object_pool.h.
                                                                     {}, size_t chunk_size = 8)
       : inner_pool(initial_chunk_size, initializer, chunk_size)
   {
   }
Member Function Documentation
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> bool VW::object_pool< T, TInitializer, TCleanup >::empty () const inline
Definition at line 191 of file object_pool.h.
Referenced by free_parser().
   {
     std::unique_lock<std::mutex> lock(m_lock);
     return inner_pool.empty();
   }
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> T* VW::object_pool< T, TInitializer, TCleanup >::get_object () inline
Definition at line 185 of file object_pool.h.
Referenced by free_parser(), and VW::get_unused_example().
   {
     std::unique_lock<std::mutex> lock(m_lock);
     return inner_pool.get_object();
   }
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> bool VW::object_pool< T, TInitializer, TCleanup >::is_from_pool (T * obj) const inline
Definition at line 203 of file object_pool.h.
Referenced by VW::is_ring_example().
   {
     std::unique_lock<std::mutex> lock(m_lock);
     return inner_pool.is_from_pool(obj);
   }
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> void VW::object_pool< T, TInitializer, TCleanup >::return_object (T * obj) inline
Definition at line 179 of file object_pool.h.
Referenced by VW::clean_example().
   {
     std::unique_lock<std::mutex> lock(m_lock);
     inner_pool.return_object(obj);
   }
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> size_t VW::object_pool< T, TInitializer, TCleanup >::size () const inline
Definition at line 197 of file object_pool.h.
   {
     std::unique_lock<std::mutex> lock(m_lock);
     return inner_pool.size();
   }
Member Data Documentation
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> no_lock_object_pool<T, TInitializer, TCleanup> VW::object_pool< T, TInitializer, TCleanup >::inner_pool private
Definition at line 211 of file object_pool.h.
template<typename T, typename TInitializer, typename TCleanup = default_cleanup<T>> std::mutex VW::object_pool< T, TInitializer, TCleanup >::m_lock mutable private
Definition at line 210 of file object_pool.h.
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/object_pool.h