Vowpal Wabbit: slates::slates_data Struct Reference
slates::slates_data Struct Reference
#include <slates.h>
Public Member Functions
void learn (LEARNER::multi_learner &base, multi_ex &examples)
void predict (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void learn_or_predict (LEARNER::multi_learner &base, multi_ex &examples)
Private Attributes
std::vector< slates::label > _stashed_labels
Detailed Description
Definition at line 17 of file slates.h.
Member Function Documentation
void slates::slates_data::learn (LEARNER::multi_learner & base, multi_ex & examples)
Definition at line 117 of file slates.cc.
Referenced by slates::learn_or_predict().
 {
   learn_or_predict<true>(base, examples);
 }
template<bool is_learn> void slates::slates_data::learn_or_predict (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 25 of file slates.cc.
References example_predict::begin(), CCB::ccb_label_parser, polylabel::conditional_contextual_bandit, CCB::conditional_contextual_bandit_outcome::cost, label_parser::default_label, label_parser::delete_label, example_predict::end(), CCB::label::explicit_included_actions, example_predict::ft_offset, example::l, CCB::label::outcome, CCB::conditional_contextual_bandit_outcome::probabilities, v_array< T >::push_back(), CCB::shared, v_array< T >::size(), polylabel::slates, CCB::slot, THROW, CCB::label::type, and CCB::label::weight.
 {
   _stashed_labels.clear();
   _stashed_labels.reserve(examples.size());
   for (auto& example : examples)
   {
     _stashed_labels.push_back(std::move(example->l.slates));
   }
   const size_t num_slots = std::count_if(examples.begin(), examples.end(),
       [](const example* example) { return example->l.conditional_contextual_bandit.type == CCB::example_type::slot; });
   float global_cost = 0.f;
   bool global_cost_found = false;
   uint32_t action_index = 0;
   size_t slot_index = 0;
   std::vector<std::vector<uint32_t>> slot_action_pools(num_slots);
   for (size_t i = 0; i < examples.size(); i++)
   {
     CCB::label ccb_label;
     memset(&ccb_label, 0, sizeof(ccb_label));
     CCB::ccb_label_parser.default_label(&ccb_label);
     const auto& slates_label = _stashed_labels[i];
     if (slates_label.type == slates::example_type::shared)
     {
       ccb_label.type = CCB::example_type::shared;
       if (slates_label.labeled)
       {
         global_cost_found = true;
         global_cost = slates_label.cost;
       }
     }
     else if (slates_label.type == slates::example_type::action)
     {
       if (slates_label.slot_id >= num_slots)
       {
         THROW("slot_id cannot be larger than or equal to the number of slots");
       }
       ccb_label.type = CCB::example_type::action;
       slot_action_pools[slates_label.slot_id].push_back(action_index);
       action_index++;
     }
     else if (slates_label.type == slates::example_type::slot)
     {
       ccb_label.type = CCB::example_type::slot;
       if (global_cost_found)
       {
         ccb_label.outcome = new CCB::conditional_contextual_bandit_outcome();
         ccb_label.outcome->cost = global_cost;
         ccb_label.outcome->probabilities = v_init<ACTION_SCORE::action_score>();
         ccb_label.explicit_included_actions = v_init<uint32_t>();
         for (const auto index : slot_action_pools[slot_index])
         {
           ccb_label.explicit_included_actions.push_back(index);
         }
         for (const auto& action_score : slates_label.probabilities)
         {
           // We need to convert from slate space which is zero based for
           // each slot to CCB where all action indices are in the same space.
           auto ccb_space_index = slot_action_pools[slot_index][action_score.action];
           ccb_label.outcome->probabilities.push_back({ccb_space_index, action_score.score});
         }
       }
       slot_index++;
     }
     ccb_label.weight = slates_label.weight;
     examples[i]->l.conditional_contextual_bandit = ccb_label;
   }
   LEARNER::multiline_learn_or_predict<is_learn>(base, examples, examples[0]->ft_offset);
   // Need to convert decision scores to the original index space. This can be
   // done by going through the prediction for each slots and subtracting the
   // number of actions seen so far.
   uint32_t size_so_far = 0;
   for (auto& action_scores : examples[0]->pred.decision_scores)
   {
     for (size_t i = 0; i < action_scores.size(); i++)
     {
       action_scores[i].action = action_scores[i].action - size_so_far;
     }
     size_so_far += static_cast<uint32_t>(action_scores.size());
   }
   for (size_t i = 0; i < examples.size(); i++)
   {
     CCB::ccb_label_parser.delete_label(&examples[i]->l.conditional_contextual_bandit);
     examples[i]->l.slates = std::move(_stashed_labels[i]);
   }
   _stashed_labels.clear();
 }
void slates::slates_data::predict (LEARNER::multi_learner & base, multi_ex & examples)
Definition at line 122 of file slates.cc.
Referenced by slates::learn_or_predict().
 {
   learn_or_predict<false>(base, examples);
 }
Member Data Documentation
std::vector<slates::label> slates::slates_data::_stashed_labels private
Definition at line 20 of file slates.h.
The documentation for this struct was generated from the following files:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/slates.h
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/slates.cc