Vowpal Wabbit: VW::cb_dro_data Struct Reference
VW::cb_dro_data Struct Reference
Public Member Functions
cb_dro_data (double alpha, double tau, double wmax)
bool isValid ()
template<bool is_learn, bool is_explore>
void learn_or_predict (multi_learner &base, multi_ex &examples)
Private Attributes
VW::distributionally_robust::ChiSquared chisq
std::vector< float > save_weight
Detailed Description
Definition at line 14 of file cb_dro.cc.
Constructor & Destructor Documentation
VW::cb_dro_data::cb_dro_data (double alpha, double tau, double wmax) inline explicit
Definition at line 16 of file cb_dro.cc.
 : chisq(alpha, tau, 0, wmax) {}
Member Function Documentation
bool VW::cb_dro_data::isValid () inline
Definition at line 18 of file cb_dro.cc.
 { return chisq.isValid(); }
template<bool is_learn, bool is_explore> void VW::cb_dro_data::learn_or_predict (multi_learner & base, multi_ex & examples) inline
Definition at line 21 of file cb_dro.cc.
References a, v_array< T >::begin(), CB::cb_class::cost, v_array< T >::end(), f, CB::cb_class::probability, and ACTION_SCORE::score_comp().
Referenced by learn_or_predict().
   {
     // Some explanation required.
     //
     // VW currently is either
     //    in prediction mode with exploration (aka --cb_explore_adf)
     //    or in (off-policy) learning without exploration (aka --cb_adf)
     //
     // In practice, nobody seems to do
     // "off policy learning of the stochastic exploration policy".
     //
     // Ergo, the following always optimizes the bound on the associated
     // deterministic argmax score policy.
     multiline_learn_or_predict<false>(base, examples, examples[0]->ft_offset);
     if (is_learn)
     {
       const auto it = std::find_if(examples.begin(), examples.end(), [](example *item) { return !item->l.cb.costs.empty(); });
       if (it != examples.end())
       {
         const CB::cb_class logged = (*it)->l.cb.costs[0];
         const uint32_t labelled_action = static_cast<uint32_t>(std::distance(examples.begin(), it));
         const auto action_scores = examples[0]->pred.a_s;
         // cb_explore_adf => want maximum probability
         // cb_adf => first action is a greedy action
         const auto maxit = is_explore
                      ? std::max_element (action_scores.begin(),
                                          action_scores.end(),
                                          [](const ACTION_SCORE::action_score& a, const ACTION_SCORE::action_score& b) { return ACTION_SCORE::score_comp(&a, &b) < 0; })
                      : action_scores.begin();
         const uint32_t chosen_action = maxit->action;
         const float w = logged.probability > 0 ? 1 / logged.probability : 0;
         const float r = -logged.cost;
         chisq.update(chosen_action == labelled_action ? w : 0, r);
         float qlb = static_cast<float>(w > 0 ? chisq.effn() * chisq.qlb(w, r) / w : 1);
         // avoid pathological cases
         qlb = std::max(qlb, 0.01f);
         // save the original weights and scale the example weights
         save_weight.clear();
         save_weight.reserve(examples.size());
         std::transform(examples.cbegin(), examples.cend(), std::back_inserter(save_weight), [](example *item) { return item->weight; });
         std::for_each(examples.begin(), examples.end(), [qlb](example* item) { item->weight *= qlb; });
         // TODO: make sure descendants "do the right thing" with example->weight
         multiline_learn_or_predict<true>(base, examples, examples[0]->ft_offset);
         // restore the original weights
         auto save_weight_it = save_weight.begin();
         std::for_each(examples.begin(), examples.end(), [&save_weight_it](example* item) { item->weight = *save_weight_it++; });
       }
     }
   }
Member Data Documentation
VW::distributionally_robust::ChiSquared VW::cb_dro_data::chisq private
Definition at line 85 of file cb_dro.cc.
std::vector<float> VW::cb_dro_data::save_weight private
Definition at line 86 of file cb_dro.cc.
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cb_dro.cc