Vowpal Wabbit: BaseState< audit > Struct Template Reference
BaseState< audit > Struct Template Reference
#include <parse_example_json.h>
Public Member Functions
BaseState (const char *pname)
virtual BaseState< audit > * Null (Context< audit > &ctx)
virtual BaseState< audit > * Bool (Context< audit > &ctx, bool b)
virtual BaseState< audit > * Float (Context< audit > &ctx, float v)
virtual BaseState< audit > * Uint (Context< audit > &ctx, unsigned v)
virtual BaseState< audit > * String (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * StartObject (Context< audit > &ctx)
virtual BaseState< audit > * Key (Context< audit > &ctx, const char *str, rapidjson::SizeType len, bool)
virtual BaseState< audit > * EndObject (Context< audit > &ctx, rapidjson::SizeType)
virtual BaseState< audit > * StartArray (Context< audit > &ctx)
virtual BaseState< audit > * EndArray (Context< audit > &ctx, rapidjson::SizeType)
Public Attributes
const char * name
Detailed Description
template<bool audit>
struct BaseState< audit >
Definition at line 49 of file parse_example_json.h.
Constructor & Destructor Documentation
template<bool audit> BaseState< audit >::BaseState (const char * pname) inline
Definition at line 103 of file parse_example_json.h.
 : name(pname) {}
Member Function Documentation
template<bool audit> virtual BaseState<audit>* BaseState< audit >::Bool (Context< audit > & ctx, bool b) inline virtual
Reimplemented in BoolToBoolState< audit >, and DefaultState< audit >.
Definition at line 111 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: bool (" << (b ? "true" : "false") << ")";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::EndArray (Context< audit > & ctx, rapidjson::SizeType) inline virtual
Reimplemented in CCBOutcomeList< audit >, ArrayToVectorState< audit, T >, ArrayToVectorState< audit, float >, ArrayToVectorState< audit, unsigned >, ArrayState< audit >, SlotsState< audit >, and MultiState< audit >.
Definition at line 159 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: ]";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::EndObject (Context< audit > & ctx, rapidjson::SizeType) inline virtual
Reimplemented in DecisionServiceState< audit >, DefaultState< audit >, and LabelObjectState< audit >.
Definition at line 147 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: }";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::Float (Context< audit > & ctx, float v) inline virtual
Reimplemented in FloatToFloatState< audit >, ArrayToVectorState< audit, T >, ArrayToVectorState< audit, float >, ArrayToVectorState< audit, unsigned >, DefaultState< audit >, ArrayState< audit >, LabelState< audit >, LabelSinglePropertyState< audit >, and LabelObjectState< audit >.
Definition at line 117 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: float (" << v << ")";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::Key (Context< audit > & ctx, const char * str, rapidjson::SizeType len, bool) inline virtual
Reimplemented in DecisionServiceState< audit >, DefaultState< audit >, and LabelObjectState< audit >.
Definition at line 141 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: key('" << str << "' len: " << len << ")";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::Null (Context< audit > & ctx) inline virtual
Reimplemented in FloatToFloatState< audit >, StringToStringState< audit >, ArrayToVectorState< audit, T >, ArrayToVectorState< audit, float >, ArrayToVectorState< audit, unsigned >, and ArrayState< audit >.
Definition at line 105 of file parse_example_json.h.
References Context< audit >::previous_state.
   {
     // ignore Null by default and stay in the current state
     return ctx.previous_state == nullptr ? this : ctx.previous_state;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::StartArray (Context< audit > & ctx) inline virtual
Reimplemented in CCBOutcomeList< audit >, ArrayToVectorState< audit, T >, ArrayToVectorState< audit, float >, ArrayToVectorState< audit, unsigned >, DefaultState< audit >, ArrayState< audit >, SlotsState< audit >, and MultiState< audit >.
Definition at line 153 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: [";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::StartObject (Context< audit > & ctx) inline virtual
Reimplemented in DecisionServiceState< audit >, CCBOutcomeList< audit >, DefaultState< audit >, ArrayState< audit >, SlotsState< audit >, MultiState< audit >, LabelState< audit >, and LabelObjectState< audit >.
Definition at line 135 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: {";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::String (Context< audit > & ctx, const char * str, rapidjson::SizeType len, bool) inline virtual
Reimplemented in StringToStringState< audit >, ArrayToVectorState< audit, T >, ArrayToVectorState< audit, float >, ArrayToVectorState< audit, unsigned >, DefaultState< audit >, TextState< audit >, LabelState< audit >, LabelSinglePropertyState< audit >, and LabelObjectState< audit >.
Definition at line 129 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: std::string('" << str << "' len: " << len << ")";
     return nullptr;
   }
template<bool audit> virtual BaseState<audit>* BaseState< audit >::Uint (Context< audit > & ctx, unsigned v) inline virtual
Reimplemented in ArrayToVectorState< audit, T >, ArrayToVectorState< audit, float >, ArrayToVectorState< audit, unsigned >, DefaultState< audit >, IgnoreState< audit >, ArrayState< audit >, LabelState< audit >, LabelSinglePropertyState< audit >, and LabelObjectState< audit >.
Definition at line 123 of file parse_example_json.h.
References Context< audit >::error().
   {
     ctx.error() << "Unexpected token: uint (" << v << ")";
     return nullptr;
   }
Member Data Documentation
template<bool audit> const char* BaseState< audit >::name
Definition at line 101 of file parse_example_json.h.
Referenced by VW::read_line_decision_service_json(), and VW::read_line_json().
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example_json.h