Vowpal Wabbit: VW::cb_explore_adf::cover::cb_explore_adf_cover Struct Reference
VW::cb_explore_adf::cover::cb_explore_adf_cover Struct Reference
Public Member Functions
cb_explore_adf_cover (size_t cover_size, float psi, bool nounif, bool first_only, LEARNER::multi_learner *cs_ldf_learner, LEARNER::single_learner *scorer, size_t cb_type)
~cb_explore_adf_cover ()
void predict (LEARNER::multi_learner &base, multi_ex &examples)
void learn (LEARNER::multi_learner &base, multi_ex &examples)
Private Member Functions
template<bool is_learn>
void predict_or_learn_impl (LEARNER::multi_learner &base, multi_ex &examples)
Private Attributes
size_t _cover_size
float _psi
bool _nounif
bool _first_only
size_t _counter
LEARNER::multi_learner * _cs_ldf_learner
GEN_CS::cb_to_cs_adf _gen_cs
v_array< ACTION_SCORE::action_score > _action_probs
std::vector< float > _scores
COST_SENSITIVE::label _cs_labels
COST_SENSITIVE::label _cs_labels_2
v_array< COST_SENSITIVE::label > _prepped_cs_labels
v_array< CB::label > _cb_labels
Detailed Description
Definition at line 26 of file cb_explore_adf_cover.cc.
Constructor & Destructor Documentation
VW::cb_explore_adf::cover::cb_explore_adf_cover::cb_explore_adf_cover (size_t cover_size, float psi, bool nounif, bool first_only, LEARNER::multi_learner * cs_ldf_learner, LEARNER::single_learner * scorer, size_t cb_type)
Definition at line 58 of file cb_explore_adf_cover.cc.
References _gen_cs, GEN_CS::cb_to_cs_adf::cb_type, and GEN_CS::cb_to_cs_adf::scorer.
     : _cover_size(cover_size), _psi(psi), _nounif(nounif), _first_only(first_only), _cs_ldf_learner(cs_ldf_learner)
 {
   _gen_cs.cb_type = cb_type;
   _gen_cs.scorer = scorer;
 }
VW::cb_explore_adf::cover::cb_explore_adf_cover::~cb_explore_adf_cover ()
Definition at line 167 of file cb_explore_adf_cover.cc.
References _action_probs, _cb_labels, _cs_labels, _cs_labels_2, _gen_cs, _prepped_cs_labels, COST_SENSITIVE::label::costs, v_array< T >::delete_v(), GEN_CS::cb_to_cs_adf::pred_scores, and v_array< T >::size().
 {
   _cb_labels.delete_v();
   for (size_t i = 0; i < _prepped_cs_labels.size(); i++) _prepped_cs_labels[i].costs.delete_v();
   _prepped_cs_labels.delete_v();
   _cs_labels_2.costs.delete_v();
   _cs_labels.costs.delete_v();
   _action_probs.delete_v();
   _gen_cs.pred_scores.costs.delete_v();
 }
Member Function Documentation
void VW::cb_explore_adf::cover::cb_explore_adf_cover::learn (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 51 of file cb_explore_adf_cover.cc.
References predict_or_learn_impl().
 { predict_or_learn_impl<true>(base, examples); }
void VW::cb_explore_adf::cover::cb_explore_adf_cover::predict (LEARNER::multi_learner & base, multi_ex & examples) inline
Definition at line 50 of file cb_explore_adf_cover.cc.
 { predict_or_learn_impl<false>(base, examples); }
template<bool is_learn> void VW::cb_explore_adf::cover::cb_explore_adf_cover::predict_or_learn_impl (LEARNER::multi_learner & base, multi_ex & examples) private
Definition at line 67 of file cb_explore_adf_cover.cc.
References _action_probs, _cb_labels, _counter, _cover_size, _cs_labels, _cs_labels_2, _cs_ldf_learner, _first_only, _gen_cs, _nounif, _prepped_cs_labels, _psi, _scores, ACTION_SCORE::begin_scores(), GEN_CS::cb_to_cs_adf::cb_type, CB_TYPE_MTR, v_array< T >::clear(), COST_SENSITIVE::label::costs, ACTION_SCORE::end_scores(), exploration::enforce_minimum_probability(), f, VW::cb_explore_adf::fill_tied(), GEN_CS::gen_cs_example_ips(), CB_ADF::get_observed_cost(), GEN_CS::cb_to_cs_adf::known_cost, v_array< T >::push_back(), v_array< T >::size(), and VW::cb_explore_adf::sort_action_probs().
Referenced by learn().
 {
   // Redundant with the call in cb_explore_adf_base, but encapsulation means we need to do this again here
   _gen_cs.known_cost = CB_ADF::get_observed_cost(examples);
   // Randomize over predictions from a base set of predictors
   // Use cost sensitive oracle to cover actions to form distribution.
   const bool is_mtr = _gen_cs.cb_type == CB_TYPE_MTR;
   if (is_learn)
   {
     if (is_mtr)  // use DR estimates for non-ERM policies in MTR
       GEN_CS::gen_cs_example_dr<true>(_gen_cs, examples, _cs_labels);
     else
       GEN_CS::gen_cs_example<false>(_gen_cs, examples, _cs_labels);
     LEARNER::multiline_learn_or_predict<true>(base, examples, examples[0]->ft_offset);
   }
   else
   {
     GEN_CS::gen_cs_example_ips(examples, _cs_labels);
     LEARNER::multiline_learn_or_predict<false>(base, examples, examples[0]->ft_offset);
   }
   v_array<ACTION_SCORE::action_score>& preds = examples[0]->pred.a_s;
   const uint32_t num_actions = (uint32_t)preds.size();
   float additive_probability = 1.f / (float)_cover_size;
   const float min_prob = (std::min)(1.f / num_actions, 1.f / (float)std::sqrt(_counter * num_actions));
   _action_probs.clear();
   for (uint32_t i = 0; i < num_actions; i++) _action_probs.push_back({i, 0.});
   _scores.clear();
   for (uint32_t i = 0; i < num_actions; i++) _scores.push_back(preds[i].score);
   if (!_first_only)
   {
     size_t tied_actions = fill_tied(preds);
     for (size_t i = 0; i < tied_actions; ++i)
       _action_probs[preds[i].action].score += additive_probability / tied_actions;
   }
   else
     _action_probs[preds[0].action].score += additive_probability;
   float norm = min_prob * num_actions + (additive_probability - min_prob);
   for (size_t i = 1; i < _cover_size; i++)
   {
     // Create costs of each action based on online cover
     if (is_learn)
     {
       _cs_labels_2.costs.clear();
       /* Cover's learn policy is similar to bag in that we have multiple learners
        * The main difference here is that Cover's learners interact with each other.
        * The following code generates cost = cost + penalty where a penalty is applied
        * to any action a previous policy has already selected
        */
       for (uint32_t j = 0; j < num_actions; j++)
       {
         float pseudo_cost =
             _cs_labels.costs[j].x - _psi * min_prob / ((std::max)(_action_probs[j].score, min_prob) / norm);
         _cs_labels_2.costs.push_back({pseudo_cost, j, 0., 0.});
       }
       GEN_CS::call_cs_ldf<true>(
           *(_cs_ldf_learner), examples, _cb_labels, _cs_labels_2, _prepped_cs_labels, examples[0]->ft_offset, i + 1);
     }
     else
       GEN_CS::call_cs_ldf<false>(
           *(_cs_ldf_learner), examples, _cb_labels, _cs_labels, _prepped_cs_labels, examples[0]->ft_offset, i + 1);
     for (uint32_t i = 0; i < num_actions; i++) _scores[i] += preds[i].score;
     if (!_first_only)
     {
       size_t tied_actions = fill_tied(preds);
       const float add_prob = additive_probability / tied_actions;
       for (size_t i = 0; i < tied_actions; ++i)
       {
         if (_action_probs[preds[i].action].score < min_prob)
           norm += (std::max)(0.f, add_prob - (min_prob - _action_probs[preds[i].action].score));
         else
           norm += add_prob;
         _action_probs[preds[i].action].score += add_prob;
       }
     }
     else
     {
       uint32_t action = preds[0].action;
       if (_action_probs[action].score < min_prob)
         norm += (std::max)(0.f, additive_probability - (min_prob - _action_probs[action].score));
       else
         norm += additive_probability;
       _action_probs[action].score += additive_probability;
     }
   }
   exploration::enforce_minimum_probability(
       min_prob * num_actions, !_nounif, begin_scores(_action_probs), end_scores(_action_probs));
   sort_action_probs(_action_probs, _scores);
   for (size_t i = 0; i < num_actions; i++) preds[i] = _action_probs[i];
   if (is_learn)
     ++_counter;
 }
Member Data Documentation
v_array<ACTION_SCORE::action_score> VW::cb_explore_adf::cover::cb_explore_adf_cover::_action_probs private
Definition at line 37 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl(), and ~cb_explore_adf_cover().
v_array<CB::label> VW::cb_explore_adf::cover::cb_explore_adf_cover::_cb_labels private
Definition at line 42 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl(), and ~cb_explore_adf_cover().
size_t VW::cb_explore_adf::cover::cb_explore_adf_cover::_counter private
Definition at line 33 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
size_t VW::cb_explore_adf::cover::cb_explore_adf_cover::_cover_size private
Definition at line 29 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
COST_SENSITIVE::label VW::cb_explore_adf::cover::cb_explore_adf_cover::_cs_labels private
Definition at line 39 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl(), and ~cb_explore_adf_cover().
COST_SENSITIVE::label VW::cb_explore_adf::cover::cb_explore_adf_cover::_cs_labels_2 private
Definition at line 40 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl(), and ~cb_explore_adf_cover().
LEARNER::multi_learner* VW::cb_explore_adf::cover::cb_explore_adf_cover::_cs_ldf_learner private
Definition at line 34 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
bool VW::cb_explore_adf::cover::cb_explore_adf_cover::_first_only private
Definition at line 32 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
GEN_CS::cb_to_cs_adf VW::cb_explore_adf::cover::cb_explore_adf_cover::_gen_cs private
Definition at line 35 of file cb_explore_adf_cover.cc.
Referenced by cb_explore_adf_cover(), predict_or_learn_impl(), and ~cb_explore_adf_cover().
bool VW::cb_explore_adf::cover::cb_explore_adf_cover::_nounif private
Definition at line 31 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
v_array<COST_SENSITIVE::label> VW::cb_explore_adf::cover::cb_explore_adf_cover::_prepped_cs_labels private
Definition at line 41 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl(), and ~cb_explore_adf_cover().
float VW::cb_explore_adf::cover::cb_explore_adf_cover::_psi private
Definition at line 30 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
std::vector<float> VW::cb_explore_adf::cover::cb_explore_adf_cover::_scores private
Definition at line 38 of file cb_explore_adf_cover.cc.
Referenced by predict_or_learn_impl().
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/cb_explore_adf_cover.cc