Vowpal Wabbit: Namespace< audit > Struct Template Reference
Namespace< audit > Struct Template Reference
#include <parse_example_json.h>
Public Member Functions
void AddFeature (feature_value v, feature_index i, const char *feature_name)
void AddFeature (vw *all, const char *str)
void AddFeature (vw *all, const char *key, const char *value)
Public Attributes
char feature_group
feature_index namespace_hash
features * ftrs
size_t feature_count
BaseState< audit > * return_state
const char * name
Detailed Description
template<bool audit>
struct Namespace< audit >
Definition at line 55 of file parse_example_json.h.
Member Function Documentation
template<bool audit> void Namespace< audit >::AddFeature (feature_value v, feature_index i, const char * feature_name) inline
Definition at line 64 of file parse_example_json.h.
References v_array< T >::push_back(), features::push_back(), and features::space_names.
   {
     // filter out 0-values
     if (v == 0)
       return;
     ftrs->push_back(v, i);
     feature_count++;
     if (audit)
       ftrs->space_names.push_back(audit_strings_ptr(new audit_strings(name, feature_name)));
   }
template<bool audit> void Namespace< audit >::AddFeature (vw * all, const char * str) inline
Definition at line 77 of file parse_example_json.h.
References VW::hash_feature_cstr(), v_array< T >::push_back(), features::push_back(), and features::space_names.
   {
     ftrs->push_back(1., VW::hash_feature_cstr(*all, const_cast<char*>(str), namespace_hash));
     feature_count++;
     if (audit)
       ftrs->space_names.push_back(audit_strings_ptr(new audit_strings(name, str)));
   }
template<bool audit> void Namespace< audit >::AddFeature (vw * all, const char * key, const char * value) inline
Definition at line 86 of file parse_example_json.h.
References VW::hash_feature(), v_array< T >::push_back(), features::push_back(), and features::space_names.
   {
     ftrs->push_back(1., VW::hash_feature(*all, value, VW::hash_feature(*all, key, namespace_hash)));
     feature_count++;
     std::stringstream ss;
     ss << key << "^" << value;
     if (audit)
       ftrs->space_names.push_back(audit_strings_ptr(new audit_strings(name, ss.str())));
   }
Member Data Documentation
template<bool audit> size_t Namespace< audit >::feature_count
Definition at line 60 of file parse_example_json.h.
Referenced by Context< audit >::PushNamespace().
template<bool audit> char Namespace< audit >::feature_group
Definition at line 57 of file parse_example_json.h.
Referenced by Context< audit >::PushNamespace().
template<bool audit> features* Namespace< audit >::ftrs
Definition at line 59 of file parse_example_json.h.
Referenced by Context< audit >::PushNamespace().
template<bool audit> const char* Namespace< audit >::name
Definition at line 62 of file parse_example_json.h.
Referenced by Context< audit >::PushNamespace().
template<bool audit> feature_index Namespace< audit >::namespace_hash
Definition at line 58 of file parse_example_json.h.
Referenced by Context< audit >::PushNamespace().
template<bool audit> BaseState<audit>* Namespace< audit >::return_state
Definition at line 61 of file parse_example_json.h.
Referenced by Context< audit >::PushNamespace().
The documentation for this struct was generated from the following file:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/parse_example_json.h