Vowpal Wabbit: VW::config::options_boost_po Struct Reference
VW::config::options_boost_po Struct Reference
#include <options_boost_po.h>
Public Member Functions
options_boost_po (int argc, char **argv)
options_boost_po (std::vector< std::string > args)
options_boost_po (options_boost_po &)=delete
options_boost_po & operator= (options_boost_po &)=delete
virtual void add_and_parse (const option_group_definition &group) override
virtual bool was_supplied (const std::string &key) override
virtual std::string help () override
virtual void check_unregistered () override
virtual std::vector< std::shared_ptr< base_option > > get_all_options () override
virtual std::shared_ptr< base_option > get_option (const std::string &key) override
virtual void insert (const std::string &key, const std::string &value) override
virtual void replace (const std::string &key, const std::string &value) override
bool try_get_positional_option_token (const std::string &key, std::string &token, int position)
template<>
po::typed_value< std::vector< bool > > * convert_to_boost_value (std::shared_ptr< typed_option< bool >> &opt)
Public Member Functions inherited from VW::config::options_i
template<typename T >
typed_option< T > & get_typed_option (const std::string &key)
virtual ~options_i ()=default
Private Member Functions
template<typename T >
po::typed_value< std::vector< T > > * get_base_boost_value (std::shared_ptr< typed_option< T >> &opt)
template<typename T >
po::typed_value< std::vector< T > > * get_base_boost_value (std::shared_ptr< typed_option< std::vector< T >>> &opt)
template<typename T >
po::typed_value< std::vector< T > > * convert_to_boost_value (std::shared_ptr< typed_option< T >> &opt)
template<typename T >
po::typed_value< std::vector< T > > * convert_to_boost_value (std::shared_ptr< typed_option< std::vector< T >>> &opt)
template<typename T >
po::typed_value< std::vector< T > > * add_notifier (std::shared_ptr< typed_option< T >> &opt, po::typed_value< std::vector< T >> *po_value)
template<typename T >
po::typed_value< std::vector< T > > * add_notifier (std::shared_ptr< typed_option< std::vector< T >>> &opt, po::typed_value< std::vector< T >> *po_value)
template<typename T >
bool add_if_t (std::shared_ptr< base_option > opt, po::options_description &options_description)
void add_to_description (std::shared_ptr< base_option > opt, po::options_description &options_description)
template<typename TTypes >
void add_to_description_impl (std::shared_ptr< base_option > opt, po::options_description &options_description)
template<typename T >
void add_to_description (std::shared_ptr< typed_option< T >> opt, po::options_description &options_description)
template<>
void add_to_description_impl (std::shared_ptr< base_option >, po::options_description &)
template<>
void add_to_description_impl (std::shared_ptr< base_option > opt, po::options_description &options_description)
Private Attributes
std::map< std::string, std::shared_ptr< base_option > > m_options
std::vector< std::string > m_command_line
std::stringstream m_help_stringstream
std::set< std::string > m_supplied_options
std::set< std::string > m_ignore_supplied
po::options_description master_description
std::set< std::string > m_defined_options
Detailed Description
Definition at line 44 of file options_boost_po.h.
Constructor & Destructor Documentation
VW::config::options_boost_po::options_boost_po (int argc, char ** argv) inline
Definition at line 46 of file options_boost_po.h.
 : options_boost_po(std::vector<std::string>(argv + 1, argv + argc)) {}
VW::config::options_boost_po::options_boost_po (std::vector< std::string > args) inline
Definition at line 48 of file options_boost_po.h.
 : m_command_line(args) {}
VW::config::options_boost_po::options_boost_po (options_boost_po &) delete
Member Function Documentation
void options_boost_po::add_and_parse (const option_group_definition & group) override virtual
Implements VW::config::options_i.
Definition at line 51 of file options_boost_po.cc.
References add_to_description(), is_number(), m_command_line, m_defined_options, m_help_stringstream, m_ignore_supplied, VW::config::option_group_definition::m_name, VW::config::option_group_definition::m_options, m_options, m_supplied_options, THROW, THROW_EX, and VW::vw_exception::what().
 {
   po::options_description new_options(group.m_name);
   for (auto opt_ptr : group.m_options)
   {
     add_to_description(opt_ptr, new_options);
     m_defined_options.insert(opt_ptr->m_name);
     m_defined_options.insert(opt_ptr->m_short_name);
     m_defined_options.insert("-" + opt_ptr->m_short_name);
     // The last definition is kept. There was a bug where using .insert at a later pointer changed the command line but
     // the previously defined option's default value was serialized into the model. This resolves that state info.
     m_options[opt_ptr->m_name] = opt_ptr;
   }
   // Add the help for the given options.
   new_options.print(m_help_stringstream);
   try
   {
     po::variables_map vm;
     auto parsed_options = po::command_line_parser(m_command_line)
                               .options(new_options)
                               .style(po::command_line_style::default_style ^ po::command_line_style::allow_guessing)
                               .allow_unregistered()
                               .run();
     for (auto const& option : parsed_options.options)
     {
       // If the supplied option is interpreted as a number, then ignore it. There are no options like this and it is
       // just a false positive.
       if (is_number(option.string_key))
       {
         m_ignore_supplied.insert(option.string_key);
       }
       m_supplied_options.insert(option.string_key);
       // If a std::string is later determined to be a value the erase it. This happens for negative numbers "-2"
       for (auto& val : option.value)
       {
         m_ignore_supplied.insert(val);
       }
       // Parsed options can contain short options in the form -k, we can only check these as the group definitions come
       // in.
       if (option.string_key.length() > 0 && option.string_key[0] == '-')
       {
         auto short_name = option.string_key.substr(1);
         for (const auto& opt_ptr : group.m_options)
         {
           if (opt_ptr->m_short_name == short_name)
           {
             m_supplied_options.insert(short_name);
           }
         }
       }
     }
     po::store(parsed_options, vm);
     po::notify(vm);
   }
   catch (boost::exception_detail::clone_impl<
       boost::exception_detail::error_info_injector<boost::program_options::invalid_option_value>>& ex)
   {
     THROW_EX(VW::vw_argument_invalid_value_exception, ex.what());
   }
   catch (boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast>>& ex)
   {
     THROW_EX(VW::vw_argument_invalid_value_exception, ex.what());
   }
   catch (boost::exception_detail::clone_impl<
       boost::exception_detail::error_info_injector<boost::program_options::ambiguous_option>>& ex)
   {
     THROW(ex.what());
   }
   catch (boost::program_options::ambiguous_option& ex)
   {
     THROW(ex.what());
   }
 }
template<typename T > bool VW::config::options_boost_po::add_if_t (std::shared_ptr< base_option > opt, po::options_description & options_description) private
Definition at line 258 of file options_boost_po.h.
 {
   if (opt->m_type_hash == typeid(T).hash_code())
   {
     auto typed = std::dynamic_pointer_cast<typed_option<T>>(opt);
     add_to_description(typed, options_description);
     return true;
   }
   return false;
 }
template<typename T > po::typed_value< std::vector< T > > * VW::config::options_boost_po::add_notifier (std::shared_ptr< typed_option< T >> & opt, po::typed_value< std::vector< T >> * po_value) private
Definition at line 218 of file options_boost_po.h.
Referenced by convert_to_boost_value().
 {
   return po_value->notifier([opt](std::vector<T> final_arguments) {
     T result = final_arguments[0];
     // Due to the way options get added to the vector, the model options are at the end, and the
     // command-line options are at the front. To allow override from command-line over model file,
     // simply keep the first item, and suppress the error.
     if (!opt->m_allow_override)
     {
       for (auto const& item : final_arguments)
       {
         if(item != result)
         {
           std::stringstream ss;
           ss << "Disagreeing option values for '" << opt->m_name << "': '" << result << "' vs '" << item << "'";
           THROW_EX(VW::vw_argument_disagreement_exception, ss.str());
         }
       }
     }
     // Set the value for the listening location.
     opt->m_location = result;
     opt->value(result);
   });
 }
template<typename T > po::typed_value< std::vector< T > > * VW::config::options_boost_po::add_notifier (std::shared_ptr< typed_option< std::vector< T >>> & opt, po::typed_value< std::vector< T >> * po_value) private
Definition at line 247 of file options_boost_po.h.
 {
   return po_value->notifier([opt](std::vector<T> final_arguments) {
     // Set the value for the listening location.
     opt->m_location = final_arguments;
     opt->value(final_arguments);
   });
 }
void options_boost_po::add_to_description (std::shared_ptr< base_option > opt, po::options_description & options_description) private
Definition at line 45 of file options_boost_po.cc.
Referenced by add_and_parse().
 {
   add_to_description_impl<supported_options_types>(std::move(opt), options_description);
 }
template<typename T > void VW::config::options_boost_po::add_to_description (std::shared_ptr< typed_option< T >> opt, po::options_description & options_description) private
Definition at line 275 of file options_boost_po.h.
 {
   std::string boost_option_name = opt->m_name;
   if (opt->m_short_name != "")
   {
     boost_option_name += ",";
     boost_option_name += opt->m_short_name;
   }
   options_description.add_options()(boost_option_name.c_str(), convert_to_boost_value(opt), opt->m_help.c_str());
   if (m_defined_options.count(opt->m_name) == 0)
   {
     // TODO may need to add noop notifier here.
     master_description.add_options()(boost_option_name.c_str(), convert_to_boost_value(opt), "");
   }
 }
template<typename TTypes > void VW::config::options_boost_po::add_to_description_impl (std::shared_ptr< base_option > opt, po::options_description & options_description) inline private
Definition at line 143 of file options_boost_po.h.
   {
     if (add_if_t<typename TTypes::head>(opt, options_description))
     {
       return;
     }
     add_to_description_impl<typename TTypes::tail>(opt, options_description);
   }
template<> void VW::config::options_boost_po::add_to_description_impl (std::shared_ptr< base_option > , po::options_description &) private
Definition at line 183 of file options_boost_po.cc.
References THROW.
 {
   THROW("That is an unsupported option type.");
 }
template<> void VW::config::options_boost_po::add_to_description_impl (std::shared_ptr< base_option > opt, po::options_description & options_description) private
void options_boost_po::check_unregistered () override virtual
Implements VW::config::options_i.
Definition at line 171 of file options_boost_po.cc.
References m_defined_options, m_ignore_supplied, m_supplied_options, and THROW_EX.
 {
   for (auto const& supplied : m_supplied_options)
   {
     if (m_defined_options.count(supplied) == 0 && m_ignore_supplied.count(supplied) == 0)
     {
       THROW_EX(VW::vw_unrecognised_option_exception, "unrecognised option '--" << supplied << "'");
     }
   }
 }
po::typed_value< std::vector< bool > > * VW::config::options_boost_po::convert_to_boost_value (std::shared_ptr< typed_option< bool >> & opt)
Definition at line 29 of file options_boost_po.cc.
References add_notifier(), get_base_boost_value(), and THROW.
 {
   auto value = get_base_boost_value(opt);
   if (opt->default_value_supplied())
   {
     THROW("Using a bool option type acts as a switch, no explicit default value is allowed.")
   }
   value->default_value({false});
   value->zero_tokens();
   value->implicit_value({true});
   return add_notifier(opt, value);
 }
template<typename T > po::typed_value< std::vector< T > > * VW::config::options_boost_po::convert_to_boost_value (std::shared_ptr< typed_option< T >> & opt) private
Definition at line 202 of file options_boost_po.h.
 {
   return get_base_boost_value(opt);
 }
template<typename T > po::typed_value< std::vector< T > > * VW::config::options_boost_po::convert_to_boost_value (std::shared_ptr< typed_option< std::vector< T >>> & opt) private
Definition at line 208 of file options_boost_po.h.
 {
   return get_base_boost_value(opt)->multitoken();
 }
std::vector< std::shared_ptr< base_option > > options_boost_po::get_all_options () override virtual
Implements VW::config::options_i.
Definition at line 149 of file options_boost_po.cc.
References m_options.
 {
   std::vector<std::shared_ptr<base_option>> output_values;
   std::transform(m_options.begin(), m_options.end(), std::back_inserter(output_values),
       [](std::pair<const std::string, std::shared_ptr<base_option>>& kv) { return kv.second; });
   return output_values;
 }
template<typename T > po::typed_value< std::vector< T > > * VW::config::options_boost_po::get_base_boost_value (std::shared_ptr< typed_option< T >> & opt) private
Definition at line 175 of file options_boost_po.h.
Referenced by convert_to_boost_value().
 {
   auto value = po::value<std::vector<T>>();
   if (opt->default_value_supplied())
   {
     value->default_value({opt->default_value()});
   }
   return add_notifier(opt, value)->composing();
 }
template<typename T > po::typed_value< std::vector< T > > * VW::config::options_boost_po::get_base_boost_value (std::shared_ptr< typed_option< std::vector< T >>> & opt) private
Definition at line 188 of file options_boost_po.h.
 {
   auto value = po::value<std::vector<T>>();
   if (opt->default_value_supplied())
   {
     value->default_value(opt->default_value());
   }
   return add_notifier(opt, value)->composing();
 }
std::shared_ptr< base_option > VW::config::options_boost_po::get_option (const std::string & key) override virtual
Implements VW::config::options_i.
Definition at line 159 of file options_boost_po.cc.
References m_options.
 {
   auto it = m_options.find(key);
   if (it != m_options.end())
   {
     return it->second;
   }
   throw std::out_of_range(key + " was not found.");
 }
std::string options_boost_po::help () override virtual
Implements VW::config::options_i.
Definition at line 147 of file options_boost_po.cc.
References m_help_stringstream.
 { return m_help_stringstream.str(); }
virtual void VW::config::options_boost_po::insert (const std::string & key, const std::string & value) inline override virtual
Implements VW::config::options_i.
Definition at line 60 of file options_boost_po.h.
   {
     m_command_line.push_back("--" + key);
     if (value != "")
     {
       m_command_line.push_back(value);
     }
   }
options_boost_po& VW::config::options_boost_po::operator= (options_boost_po &) delete
virtual void VW::config::options_boost_po::replace (const std::string & key, const std::string & value) inline override virtual
Implements VW::config::options_i.
Definition at line 70 of file options_boost_po.h.
References recall_tree_ns::find(), and THROW.
   {
     auto full_key = "--" + key;
     auto it = std::find(m_command_line.begin(), m_command_line.end(), full_key);
     // Not found, insert instead.
     if (it == m_command_line.end())
     {
       insert(key, value);
       return;
     }
     // Check if it is the final option or the next option is not a value.
     if (it + 1 == m_command_line.end() || (*(it + 1)).find("--") != std::string::npos)
     {
       THROW(key + " option does not have a value.");
     }
     // Actually replace the value.
     *(it + 1) = value;
   }
bool VW::config::options_boost_po::try_get_positional_option_token (const std::string & key, std::string & token, int position) inline
Definition at line 93 of file options_boost_po.h.
   {
     po::positional_options_description p;
     p.add(key.c_str(), position);
     po::parsed_options pos = po::command_line_parser(m_command_line)
                                  .style(po::command_line_style::default_style ^ po::command_line_style::allow_guessing)
                                  .options(master_description)
                                  .allow_unregistered()
                                  .positional(p)
                                  .run();
     auto it = std::find_if(pos.options.begin(), pos.options.end(),
         [&key](boost::program_options::option& option) { return option.string_key == key; });
     if (it != pos.options.end() && (*it).value.size() > 0)
     {
       token = (*it).value.at(0);
       return true;
     }
     return false;
   }
bool options_boost_po::was_supplied (const std::string & key) override virtual
Implements VW::config::options_i.
Definition at line 134 of file options_boost_po.cc.
References recall_tree_ns::find(), m_command_line, and m_supplied_options.
 {
   // Best check, only valid after options parsed.
   if (m_supplied_options.count(key) > 0)
   {
     return true;
   }
   // Basic check, std::string match against command line.
   auto it = std::find(m_command_line.begin(), m_command_line.end(), std::string("--" + key));
   return it != m_command_line.end();
 }
Member Data Documentation
std::vector<std::string> VW::config::options_boost_po::m_command_line private
Definition at line 158 of file options_boost_po.h.
Referenced by add_and_parse(), and was_supplied().
std::set<std::string> VW::config::options_boost_po::m_defined_options private
Definition at line 171 of file options_boost_po.h.
Referenced by add_and_parse(), and check_unregistered().
std::stringstream VW::config::options_boost_po::m_help_stringstream private
Definition at line 160 of file options_boost_po.h.
Referenced by add_and_parse(), and help().
std::set<std::string> VW::config::options_boost_po::m_ignore_supplied private
Definition at line 166 of file options_boost_po.h.
Referenced by add_and_parse(), and check_unregistered().
std::map<std::string, std::shared_ptr<base_option> > VW::config::options_boost_po::m_options private
Definition at line 156 of file options_boost_po.h.
Referenced by add_and_parse(), get_all_options(), and get_option().
std::set<std::string> VW::config::options_boost_po::m_supplied_options private
Definition at line 163 of file options_boost_po.h.
Referenced by add_and_parse(), check_unregistered(), and was_supplied().
po::options_description VW::config::options_boost_po::master_description private
Definition at line 168 of file options_boost_po.h.
The documentation for this struct was generated from the following files:
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/options_boost_po.h
/__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/options_boost_po.cc