Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/svrg.h File Reference
svrg.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * svrg_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* svrg_setup (VW::config::options_i & options, vw & all)
Definition at line 170 of file svrg.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::init_learner(), SVRG::learn(), LEARNER::make_base(), VW::config::make_option(), SVRG::predict(), SVRG::save_load(), LEARNER::learner< T, E >::set_save_load(), parameters::stride_shift(), UINT64_ONE, and vw::weights.
Referenced by parse_reductions().
 {
   auto s = scoped_calloc_or_throw<svrg>();
   bool svrg_option = false;
   option_group_definition new_options("Stochastic Variance Reduced Gradient");
   new_options.add(make_option("svrg", svrg_option).keep().help("Streaming Stochastic Variance Reduced Gradient"))
       .add(make_option("stage_size", s->stage_size).default_value(1).help("Number of passes per SVRG stage"));
   options.add_and_parse(new_options);
   if (!svrg_option)
   {
     return nullptr;
   }
   s->all = &all;
   s->prev_pass = -1;
   s->stable_grad_count = 0;
   // Request more parameter storage (4 floats per feature)
   all.weights.stride_shift(2);
   learner<svrg, example>& l = init_learner(s, learn, predict, UINT64_ONE << all.weights.stride_shift());
   l.set_save_load(save_load);
   return make_base(l);
 }