Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/topk.h File Reference
topk.h File Reference
#include "reductions_fwd.h"
Functions
LEARNER::base_learner * topk_setup (VW::config::options_i &options, vw &all)
Function Documentation
LEARNER::base_learner* topk_setup (VW::config::options_i & options, vw & all)
Definition at line 130 of file topk.cc.
References VW::config::option_group_definition::add(), VW::config::options_i::add_and_parse(), LEARNER::as_singleline(), VW::finish_example(), LEARNER::init_learner(), LEARNER::make_base(), VW::config::make_option(), setup_base(), and VW::config::options_i::was_supplied().
Referenced by parse_reductions().
 {
   uint32_t K;
   option_group_definition new_options("Top K");
   new_options.add(make_option("top", K).keep().help("top k recommendation"));
   options.add_and_parse(new_options);
   if (!options.was_supplied("top"))
     return nullptr;
   auto data = scoped_calloc_or_throw<VW::topk>(K);
   LEARNER::learner<VW::topk, multi_ex>& l =
       init_learner(data, as_singleline(setup_base(options, all)), predict_or_learn<true>, predict_or_learn<false>);
   l.set_finish_example(finish_example);
   return make_base(l);
 }