Vowpal Wabbit: /__w/vowpal_wabbit/vowpal_wabbit/vowpalwabbit/vwdll.h File Reference
vwdll.h File Reference
Macros
#define VW_CALLING_CONV
#define VW_DLL_MEMBER
#define VW_TYPE_SAFE_NULL NULL
Typedefs
typedef void * VW_HANDLE
typedef void * VW_EXAMPLE
typedef void * VW_LABEL
typedef void * VW_FEATURE_SPACE
typedef void * VW_FEATURE
typedef void * VW_IOBUF
Functions
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeA (const char *pstrArgs)
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeEscapedA (const char *pstrArgs)
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeWithModel (const char *pstrArgs, const char *modelData, size_t modelDataSize)
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeWithModelEscaped (const char *pstrArgs, const char *modelData, size_t modelDataSize)
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_SeedWithModel (VW_HANDLE handle, const char *extraArgs)
VW_DLL_MEMBER void VW_CALLING_CONV VW_Finish_Passes (VW_HANDLE handle)
VW_DLL_MEMBER void VW_CALLING_CONV VW_Finish (VW_HANDLE handle)
VW_DLL_MEMBER VW_EXAMPLE VW_CALLING_CONV VW_ImportExample (VW_HANDLE handle, const char *label, VW_FEATURE_SPACE features, size_t len)
VW_DLL_MEMBER VW_FEATURE_SPACE VW_CALLING_CONV VW_InitializeFeatureSpaces (size_t len)
VW_DLL_MEMBER VW_FEATURE_SPACE VW_CALLING_CONV VW_GetFeatureSpace (VW_FEATURE_SPACE first, size_t index)
VW_DLL_MEMBER VW_FEATURE_SPACE VW_CALLING_CONV VW_ExportExample (VW_HANDLE handle, VW_EXAMPLE e, size_t *plen)
VW_DLL_MEMBER void VW_CALLING_CONV VW_ReleaseFeatureSpace (VW_FEATURE_SPACE features, size_t len)
VW_DLL_MEMBER VW_EXAMPLE VW_CALLING_CONV VW_ReadExampleA (VW_HANDLE handle, const char *line)
VW_DLL_MEMBER void VW_CALLING_CONV VW_StartParser (VW_HANDLE handle)
VW_DLL_MEMBER void VW_CALLING_CONV VW_EndParser (VW_HANDLE handle)
VW_DLL_MEMBER VW_EXAMPLE VW_CALLING_CONV VW_GetExample (VW_HANDLE handle)
VW_DLL_MEMBER void VW_CALLING_CONV VW_FinishExample (VW_HANDLE handle, VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetLabel (VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetImportance (VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetInitial (VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetPrediction (VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetCostSensitivePrediction (VW_EXAMPLE e)
VW_DLL_MEMBER void *VW_CALLING_CONV VW_GetMultilabelPredictions (VW_EXAMPLE e, size_t *plen)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetTopicPrediction (VW_EXAMPLE e, size_t i)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetActionScore (VW_EXAMPLE e, size_t i)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_GetActionScoreLength (VW_EXAMPLE e)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_GetTagLength (VW_EXAMPLE e)
VW_DLL_MEMBER const char *VW_CALLING_CONV VW_GetTag (VW_EXAMPLE e)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_GetFeatureNumber (VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetConfidence (VW_EXAMPLE e)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_SetFeatureSpace (VW_HANDLE handle, VW_FEATURE_SPACE feature_space, const char *name)
VW_DLL_MEMBER void VW_CALLING_CONV VW_InitFeatures (VW_FEATURE_SPACE feature_space, size_t features_count)
VW_DLL_MEMBER VW_FEATURE VW_CALLING_CONV VW_GetFeature (VW_FEATURE_SPACE feature_space, size_t index)
VW_DLL_MEMBER void VW_CALLING_CONV VW_SetFeature (VW_FEATURE feature, size_t index, size_t feature_hash, float value)
VW_DLL_MEMBER VW_FEATURE VW_CALLING_CONV VW_GetFeatures (VW_HANDLE handle, VW_EXAMPLE e, size_t *plen)
VW_DLL_MEMBER void VW_CALLING_CONV VW_ReturnFeatures (VW_FEATURE f)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashSpaceA (VW_HANDLE handle, const char *s)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashSpaceStaticA (const char *s, const char *h)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashFeatureA (VW_HANDLE handle, const char *s, size_t u)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashFeatureStaticA (const char *s, size_t u, const char *h, unsigned int num_bits)
VW_DLL_MEMBER float VW_CALLING_CONV VW_Learn (VW_HANDLE handle, VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_Predict (VW_HANDLE handle, VW_EXAMPLE e)
VW_DLL_MEMBER float VW_CALLING_CONV VW_PredictCostSensitive (VW_HANDLE handle, VW_EXAMPLE e)
VW_DLL_MEMBER void VW_CALLING_CONV VW_AddLabel (VW_EXAMPLE e, float label, float weight, float base)
VW_DLL_MEMBER void VW_CALLING_CONV VW_AddStringLabel (VW_HANDLE handle, VW_EXAMPLE e, const char *label)
VW_DLL_MEMBER float VW_CALLING_CONV VW_Get_Weight (VW_HANDLE handle, size_t index, size_t offset)
VW_DLL_MEMBER void VW_CALLING_CONV VW_Set_Weight (VW_HANDLE handle, size_t index, size_t offset, float value)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_Num_Weights (VW_HANDLE handle)
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_Get_Stride (VW_HANDLE handle)
VW_DLL_MEMBER void VW_CALLING_CONV VW_SaveModel (VW_HANDLE handle)
VW_DLL_MEMBER void VW_CALLING_CONV VW_CopyModelData (VW_HANDLE handle, VW_IOBUF *bufferHandle, char **outputData, size_t *outputSize)
VW_DLL_MEMBER void VW_CALLING_CONV VW_FreeIOBuf (VW_IOBUF bufferHandle)
Variables
const VW_HANDLE INVALID_VW_HANDLE = VW_TYPE_SAFE_NULL
const VW_HANDLE INVALID_VW_EXAMPLE = VW_TYPE_SAFE_NULL
Macro Definition Documentation
#define VW_CALLING_CONV
Definition at line 20 of file vwdll.h.
Referenced by utf16_to_utf8(), VW_FinishExample(), VW_HashSpaceStaticA(), and VW_ReleaseFeatureSpace().
#define VW_DLL_MEMBER
Definition at line 36 of file vwdll.h.
Referenced by utf16_to_utf8(), VW_FinishExample(), VW_HashSpaceStaticA(), and VW_ReleaseFeatureSpace().
#define VW_TYPE_SAFE_NULL NULL
Definition at line 49 of file vwdll.h.
Typedef Documentation
typedef void* VW_EXAMPLE
Definition at line 53 of file vwdll.h.
typedef void* VW_FEATURE
Definition at line 56 of file vwdll.h.
typedef void* VW_FEATURE_SPACE
Definition at line 55 of file vwdll.h.
typedef void* VW_HANDLE
Definition at line 52 of file vwdll.h.
typedef void* VW_IOBUF
Definition at line 57 of file vwdll.h.
typedef void* VW_LABEL
Definition at line 54 of file vwdll.h.
Function Documentation
VW_DLL_MEMBER void VW_CALLING_CONV VW_AddLabel (VW_EXAMPLE e, float label, float weight, float base)
Definition at line 277 of file vwdll.cpp.
References VW::add_label().
 { example* ex = static_cast<example*>(e);
   return VW::add_label(ex, label, weight, base);
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_AddStringLabel (VW_HANDLE handle, VW_EXAMPLE e, const char * label)
Definition at line 282 of file vwdll.cpp.
References VW::parse_example_label().
 { vw * pointer = static_cast<vw*>(handle);
   example* ex = static_cast<example*>(e);
   VW::parse_example_label(*pointer, *ex, label);
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_CopyModelData (VW_HANDLE handle, VW_IOBUF * bufferHandle, char ** outputData, size_t * outputSize)
Definition at line 412 of file vwdll.cpp.
References memory_io_buf::GetDataPointer(), memory_io_buf::GetDataSize(), and VW::save_predictor().
{
     vw* pointer = static_cast<vw*>(handle);
     memory_io_buf* buf = new(memory_io_buf);
     VW::save_predictor(*pointer, *buf);
     *outputBufferHandle = buf;
     *outputSize = buf->GetDataSize();
     *outputData = buf->GetDataPointer();
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_EndParser (VW_HANDLE handle)
Definition at line 143 of file vwdll.cpp.
References VW::end_parser().
 { vw * pointer = static_cast<vw*>(handle);
   VW::end_parser(*pointer);
 }
VW_DLL_MEMBER VW_FEATURE_SPACE VW_CALLING_CONV VW_ExportExample (VW_HANDLE handle, VW_EXAMPLE e, size_t * plen)
Definition at line 113 of file vwdll.cpp.
References VW::export_example().
 { vw* pointer = static_cast<vw*>(handle);
   example* ex = static_cast<example*>(e);
   return static_cast<VW_FEATURE_SPACE>(VW::export_example(*pointer, ex, *plen));
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_Finish (VW_HANDLE handle)
Definition at line 91 of file vwdll.cpp.
References VW::finish().
 { vw * pointer = static_cast<vw*>(handle);
   VW::finish(*pointer);
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_Finish_Passes (VW_HANDLE handle)
Definition at line 80 of file vwdll.cpp.
References vw::do_reset_source, VW::end_parser(), LEARNER::generic_driver(), vw::numpasses, and VW::start_parser().
 { vw * pointer = static_cast<vw*>(handle);
   if (pointer->numpasses > 1)
   {
     pointer->do_reset_source = true;
     VW::start_parser(*pointer);
     LEARNER::generic_driver(*pointer);
     VW::end_parser(*pointer);
   }
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_FinishExample (VW_HANDLE handle, VW_EXAMPLE e)
Definition at line 230 of file vwdll.cpp.
References VW::finish_example(), utf16_to_utf8(), VW_CALLING_CONV, VW_DLL_MEMBER, VW_HashSpaceA(), and VW_HashSpaceStaticA().
 { vw * pointer = static_cast<vw*>(handle);
   VW::finish_example(*pointer, *(static_cast<example*>(e)));
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_FreeIOBuf (VW_IOBUF bufferHandle)
Definition at line 423 of file vwdll.cpp.
{
     delete static_cast<memory_io_buf*>(bufferHandle);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_Get_Stride (VW_HANDLE handle)
Definition at line 336 of file vwdll.cpp.
References VW::get_stride().
 { vw* pointer = static_cast<vw*>(handle);
   return VW::get_stride(*pointer);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_Get_Weight (VW_HANDLE handle, size_t index, size_t offset)
Definition at line 321 of file vwdll.cpp.
References VW::get_weight().
 { vw* pointer = static_cast<vw*>(handle);
   return VW::get_weight(*pointer, (uint32_t) index, (uint32_t) offset);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetActionScore (VW_EXAMPLE e, size_t i)
Definition at line 295 of file vwdll.cpp.
References VW::get_action_score().
 { example * ex = static_cast<example*>(e);
   return VW::get_action_score(ex, i);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_GetActionScoreLength (VW_EXAMPLE e)
Definition at line 300 of file vwdll.cpp.
References VW::get_action_score_length().
 { example * ex = static_cast<example*>(e);
   return VW::get_action_score_length(ex);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetConfidence (VW_EXAMPLE e)
Definition at line 194 of file vwdll.cpp.
References VW::get_confidence().
 { return VW::get_confidence(static_cast<example*>(e));
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetCostSensitivePrediction (VW_EXAMPLE e)
Definition at line 174 of file vwdll.cpp.
References VW::get_cost_sensitive_prediction().
 { return VW::get_cost_sensitive_prediction(static_cast<example*>(e));
 }
VW_DLL_MEMBER VW_EXAMPLE VW_CALLING_CONV VW_GetExample (VW_HANDLE handle)
Definition at line 148 of file vwdll.cpp.
References VW::get_example(), and vw::p.
 { vw * pointer = static_cast<vw*>(handle);
   parser * parser_pointer = static_cast<parser *>(pointer->p);
   return static_cast<VW_EXAMPLE>(VW::get_example(parser_pointer));
 }
VW_DLL_MEMBER VW_FEATURE VW_CALLING_CONV VW_GetFeature (VW_FEATURE_SPACE feature_space, size_t index)
Definition at line 210 of file vwdll.cpp.
References VW::primitive_feature_space::fs.
 {
   VW::primitive_feature_space* fs = reinterpret_cast<VW::primitive_feature_space*>(feature_space);
   return &(fs->fs[index]);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_GetFeatureNumber (VW_EXAMPLE e)
Definition at line 190 of file vwdll.cpp.
References VW::get_feature_number().
 { return VW::get_feature_number(static_cast<example*>(e));
 }
VW_DLL_MEMBER VW_FEATURE VW_CALLING_CONV VW_GetFeatures (VW_HANDLE handle, VW_EXAMPLE e, size_t * plen)
Definition at line 222 of file vwdll.cpp.
References VW::get_features().
 { vw* pointer = static_cast<vw*>(handle);
   return VW::get_features(*pointer, static_cast<example*>(e), *plen);
 }
VW_DLL_MEMBER VW_FEATURE_SPACE VW_CALLING_CONV VW_GetFeatureSpace (VW_FEATURE_SPACE first, size_t index)
Definition at line 107 of file vwdll.cpp.
References f.
 {
   VW::primitive_feature_space* f = reinterpret_cast<VW::primitive_feature_space*>(first);
   return static_cast<VW_FEATURE_SPACE>(&f[index]);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetImportance (VW_EXAMPLE e)
Definition at line 162 of file vwdll.cpp.
References VW::get_importance().
 { return VW::get_importance(static_cast<example*>(e));
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetInitial (VW_EXAMPLE e)
Definition at line 166 of file vwdll.cpp.
References VW::get_initial().
 { return VW::get_initial(static_cast<example*>(e));
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetLabel (VW_EXAMPLE e)
Definition at line 154 of file vwdll.cpp.
References VW::get_label().
 { return VW::get_label(static_cast<example*>(e));
 }
VW_DLL_MEMBER void* VW_CALLING_CONV VW_GetMultilabelPredictions (VW_EXAMPLE e, size_t * plen)
Definition at line 178 of file vwdll.cpp.
References VW::get_multilabel_predictions().
 { return VW::get_multilabel_predictions(static_cast<example*>(e), *plen);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetPrediction (VW_EXAMPLE e)
Definition at line 170 of file vwdll.cpp.
References VW::get_prediction().
 { return VW::get_prediction(static_cast<example*>(e));
 }
VW_DLL_MEMBER const char* VW_CALLING_CONV VW_GetTag (VW_EXAMPLE e)
Definition at line 186 of file vwdll.cpp.
References VW::get_tag().
 { return VW::get_tag(static_cast<example*>(e));
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_GetTagLength (VW_EXAMPLE e)
Definition at line 182 of file vwdll.cpp.
References VW::get_tag_length().
 { return VW::get_tag_length(static_cast<example*>(e));
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_GetTopicPrediction (VW_EXAMPLE e, size_t i)
Definition at line 158 of file vwdll.cpp.
References VW::get_topic_prediction().
 { return VW::get_topic_prediction(static_cast<example*>(e), i);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashFeatureA (VW_HANDLE handle, const char * s, size_t u)
Definition at line 265 of file vwdll.cpp.
References VW::hash_feature().
Referenced by VW_HashSpaceStaticA().
 { vw * pointer = static_cast<vw*>(handle);
   string str(s);
   return VW::hash_feature(*pointer, str, u);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashFeatureStaticA (const char * s, size_t u, const char * h, unsigned int num_bits)
Definition at line 271 of file vwdll.cpp.
References VW::hash_feature_static().
Referenced by VW_HashSpaceStaticA().
 { string str(s);
   string hash(h);
   return VW::hash_feature_static(str, u, hash, num_bits);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashSpaceA (VW_HANDLE handle, const char * s)
Definition at line 243 of file vwdll.cpp.
References VW::hash_space().
Referenced by VW_FinishExample(), and VW_SetFeatureSpace().
 { vw * pointer = static_cast<vw*>(handle);
   string str(s);
   return VW::hash_space(*pointer, str);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_HashSpaceStaticA (const char * s, const char * h)
Definition at line 249 of file vwdll.cpp.
References VW::hash_space_static(), utf16_to_utf8(), VW_CALLING_CONV, VW_DLL_MEMBER, VW_HashFeatureA(), and VW_HashFeatureStaticA().
Referenced by VW_FinishExample().
 { string str(s);
   string hash(h);
   return VW::hash_space_static(str, hash);
 }
VW_DLL_MEMBER VW_EXAMPLE VW_CALLING_CONV VW_ImportExample (VW_HANDLE handle, const char * label, VW_FEATURE_SPACE features, size_t len)
Definition at line 96 of file vwdll.cpp.
References f, and VW::import_example().
 { vw * pointer = static_cast<vw*>(handle);
   VW::primitive_feature_space * f = reinterpret_cast<VW::primitive_feature_space*>( features );
   return static_cast<VW_EXAMPLE>(VW::import_example(*pointer, label, f, len));
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_InitFeatures (VW_FEATURE_SPACE feature_space, size_t features_count)
Definition at line 204 of file vwdll.cpp.
References VW::init_features().
 {
   VW::primitive_feature_space* fs = reinterpret_cast<VW::primitive_feature_space*>(feature_space);
   VW::init_features(*fs, features_count);
 }
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeA (const char * pstrArgs)
Definition at line 59 of file vwdll.cpp.
References VW::initialize().
Referenced by utf16_to_utf8().
 { string s(pstrArgs);
   vw* all = VW::initialize(s);
   return static_cast<VW_HANDLE>(all);
 }
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeEscapedA (const char * pstrArgs)
Definition at line 65 of file vwdll.cpp.
References VW::initialize_escaped().
Referenced by utf16_to_utf8().
 {
   std::string s(pstrArgs);
   auto all = VW::initialize_escaped(s);
   return static_cast<VW_HANDLE>(all);
 }
VW_DLL_MEMBER VW_FEATURE_SPACE VW_CALLING_CONV VW_InitializeFeatureSpaces (size_t len)
Definition at line 102 of file vwdll.cpp.
 {
   return static_cast<VW_FEATURE_SPACE>(new VW::primitive_feature_space[len]);
 }
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeWithModel (const char * pstrArgs, const char * modelData, size_t modelDataSize)
Definition at line 394 of file vwdll.cpp.
References VW::initialize().
 {
     unique_ptr<memory_io_buf> buf(new memory_io_buf);
     buf->write_file(-1, modelData, modelDataSize);
     vw* all = VW::initialize(string(pstrArgs), buf.get());
     return static_cast<VW_HANDLE>(all);
 }
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_InitializeWithModelEscaped (const char * pstrArgs, const char * modelData, size_t modelDataSize)
Definition at line 403 of file vwdll.cpp.
References VW::initialize_escaped().
 {
   std::unique_ptr<memory_io_buf> buf(new memory_io_buf());
   buf->write_file(-1, modelData, modelDataSize);
   auto all = VW::initialize_escaped(std::string(pstrArgs), buf.get());
   return static_cast<VW_HANDLE>(all);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_Learn (VW_HANDLE handle, VW_EXAMPLE e)
Definition at line 288 of file vwdll.cpp.
References VW::get_prediction(), and vw::learn().
 { vw * pointer = static_cast<vw*>(handle);
   example * ex = static_cast<example*>(e);
   pointer->learn(*ex);
   return VW::get_prediction(ex);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_Num_Weights (VW_HANDLE handle)
Definition at line 331 of file vwdll.cpp.
References VW::num_weights().
 { vw* pointer = static_cast<vw*>(handle);
   return VW::num_weights(*pointer);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_Predict (VW_HANDLE handle, VW_EXAMPLE e)
Definition at line 305 of file vwdll.cpp.
References LEARNER::as_singleline(), VW::get_prediction(), vw::l, and LEARNER::learner< T, E >::predict().
 { vw * pointer = static_cast<vw*>(handle);
   example * ex = static_cast<example*>(e);
   LEARNER::as_singleline(pointer->l)->predict(*ex);
   //BUG: The below method may return garbage as it assumes a certain structure for ex->ld
   //which may not be the actual one used (e.g., for cost-sensitive multi-class learning)
   return VW::get_prediction(ex);
 }
VW_DLL_MEMBER float VW_CALLING_CONV VW_PredictCostSensitive (VW_HANDLE handle, VW_EXAMPLE e)
Definition at line 314 of file vwdll.cpp.
References LEARNER::as_singleline(), VW::get_cost_sensitive_prediction(), vw::l, and LEARNER::learner< T, E >::predict().
 { vw * pointer = static_cast<vw*>(handle);
   example * ex = static_cast<example*>(e);
   LEARNER::as_singleline(pointer->l)->predict(*ex);
   return VW::get_cost_sensitive_prediction(ex);
 }
VW_DLL_MEMBER VW_EXAMPLE VW_CALLING_CONV VW_ReadExampleA (VW_HANDLE handle, const char * line)
Definition at line 132 of file vwdll.cpp.
References VW::read_example().
Referenced by VW_ReleaseFeatureSpace().
 { vw * pointer = static_cast<vw*>(handle);
   // BUGBUG: I really dislike this const_cast. should VW really change the input string?
   return static_cast<VW_EXAMPLE>(VW::read_example(*pointer, const_cast<char*>(line)));
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_ReleaseFeatureSpace (VW_FEATURE_SPACE features, size_t len)
Definition at line 119 of file vwdll.cpp.
References f, utf16_to_utf8(), VW_CALLING_CONV, VW_DLL_MEMBER, and VW_ReadExampleA().
 {
   auto f = reinterpret_cast<VW::primitive_feature_space*>(features);
   for (size_t i = 0; i < len; i++)
     delete[] f[i].fs;
   delete[] f;
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_ReturnFeatures (VW_FEATURE f)
Definition at line 227 of file vwdll.cpp.
References VW::return_features().
 { VW::return_features(static_cast<feature*>(f));
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_SaveModel (VW_HANDLE handle)
Definition at line 341 of file vwdll.cpp.
References vw::final_regressor_name, and VW::save_predictor().
 { vw* pointer = static_cast<vw*>(handle);
   string name = pointer->final_regressor_name;
   if (name.empty())
   { return;
   }
   return VW::save_predictor(*pointer, name);
 }
VW_DLL_MEMBER VW_HANDLE VW_CALLING_CONV VW_SeedWithModel (VW_HANDLE handle, const char * extraArgs)
Definition at line 72 of file vwdll.cpp.
References VW::seed_vw_model().
 {
   string s(extraArgs);
   vw* origmodel = static_cast<vw*>(handle);
   vw* newmodel = VW::seed_vw_model(origmodel, s);
   return static_cast<VW_HANDLE>(newmodel);
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_Set_Weight (VW_HANDLE handle, size_t index, size_t offset, float value)
Definition at line 326 of file vwdll.cpp.
References VW::set_weight().
 { vw* pointer = static_cast<vw*>(handle);
   return VW::set_weight(*pointer, (uint32_t) index, (uint32_t)offset, value);
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_SetFeature (VW_FEATURE feature, size_t index, size_t feature_hash, float value)
Definition at line 216 of file vwdll.cpp.
References VW::set_feature().
 {
   VW::primitive_feature_space* fs = reinterpret_cast<VW::primitive_feature_space*>(feature_space);
   VW::set_feature(*fs, index, feature_hash, value);
 }
VW_DLL_MEMBER size_t VW_CALLING_CONV VW_SetFeatureSpace (VW_HANDLE handle, VW_FEATURE_SPACE feature_space, const char * name)
Definition at line 198 of file vwdll.cpp.
References f, VW::primitive_feature_space::name, and VW_HashSpaceA().
 { VW::primitive_feature_space* f = reinterpret_cast<VW::primitive_feature_space*>(feature_space);
   f->name = *name;
   return VW_HashSpaceA(handle, name);
 }
VW_DLL_MEMBER void VW_CALLING_CONV VW_StartParser (VW_HANDLE handle)
Definition at line 138 of file vwdll.cpp.
References VW::start_parser().
 { vw * pointer = static_cast<vw*>(handle);
   VW::start_parser(*pointer);
 }
Variable Documentation
const VW_HANDLE INVALID_VW_EXAMPLE = VW_TYPE_SAFE_NULL
Definition at line 60 of file vwdll.h.
const VW_HANDLE INVALID_VW_HANDLE = VW_TYPE_SAFE_NULL
Definition at line 59 of file vwdll.h.