var searchData=
[
  ['cache_5ftemp_5fbuffer',['cache_temp_buffer',['../structVW_1_1details_1_1cache__temp__buffer.html',1,'VW::details']]],
  ['cached_5flearner',['cached_learner',['../structVW_1_1cached__learner.html',1,'VW']]],
  ['cats',['cats',['../structVW_1_1reductions_1_1cats_1_1cats.html',1,'VW::reductions::cats']]],
  ['cats_5ftree',['cats_tree',['../structVW_1_1reductions_1_1cats_1_1cats__tree.html',1,'VW::reductions::cats']]],
  ['cb_5factions_5fmask',['cb_actions_mask',['../structVW_1_1reductions_1_1cb__actions__mask.html',1,'VW::reductions']]],
  ['cb_5fadf',['cb_adf',['../structCB__ADF_1_1cb__adf.html',1,'CB_ADF']]],
  ['cb_5fclass',['cb_class',['../structCB_1_1cb__class.html',1,'CB']]],
  ['cb_5fexplore_5fadf_5fbase',['cb_explore_adf_base',['../structVW_1_1cb__explore__adf_1_1cb__explore__adf__base.html',1,'VW::cb_explore_adf']]],
  ['cb_5fexplore_5fadf_5flarge_5faction_5fspace',['cb_explore_adf_large_action_space',['../structVW_1_1cb__explore__adf_1_1cb__explore__adf__large__action__space.html',1,'VW::cb_explore_adf']]],
  ['cb_5fexplore_5fmetrics',['cb_explore_metrics',['../structVW_1_1cb__explore__adf_1_1cb__explore__metrics.html',1,'VW::cb_explore_adf']]],
  ['cb_5fto_5fcs',['cb_to_cs',['../structGEN__CS_1_1cb__to__cs.html',1,'GEN_CS']]],
  ['cb_5fto_5fcs_5fadf',['cb_to_cs_adf',['../structGEN__CS_1_1cb__to__cs__adf.html',1,'GEN_CS']]],
  ['cbify_5fadf_5fdata',['cbify_adf_data',['../structVW_1_1reductions_1_1cbify__adf__data.html',1,'VW::reductions']]],
  ['chisquared',['ChiSquared',['../classVW_1_1distributionally__robust_1_1ChiSquared.html',1,'VW::distributionally_robust']]],
  ['cli_5fhelp_5fformatter',['cli_help_formatter',['../structVW_1_1config_1_1cli__help__formatter.html',1,'VW::config']]],
  ['cli_5foptions_5fserializer',['cli_options_serializer',['../structVW_1_1config_1_1cli__options__serializer.html',1,'VW::config']]],
  ['column_5fdefinition',['column_definition',['../structVW_1_1column__definition.html',1,'VW']]],
  ['common_5flearner_5fbuilder',['common_learner_builder',['../structVW_1_1LEARNER_1_1common__learner__builder.html',1,'VW::LEARNER']]],
  ['common_5flearner_5fbuilder_3c_20base_5flearner_5fbuilder_3c_20datat_2c_20examplet_20_3e_2c_20datat_2c_20examplet_2c_20base_5flearner_20_3e',['common_learner_builder&lt; base_learner_builder&lt; DataT, ExampleT &gt;, DataT, ExampleT, base_learner &gt;',['../structVW_1_1LEARNER_1_1common__learner__builder.html',1,'VW::LEARNER']]],
  ['common_5flearner_5fbuilder_3c_20reduction_5flearner_5fbuilder_3c_20char_2c_20examplet_2c_20baselearnert_20_3e_2c_20char_2c_20examplet_2c_20baselearnert_20_3e',['common_learner_builder&lt; reduction_learner_builder&lt; char, ExampleT, BaseLearnerT &gt;, char, ExampleT, BaseLearnerT &gt;',['../structVW_1_1LEARNER_1_1common__learner__builder.html',1,'VW::LEARNER']]],
  ['common_5flearner_5fbuilder_3c_20reduction_5flearner_5fbuilder_3c_20datat_2c_20examplet_2c_20baselearnert_20_3e_2c_20datat_2c_20examplet_2c_20baselearnert_20_3e',['common_learner_builder&lt; reduction_learner_builder&lt; DataT, ExampleT, BaseLearnerT &gt;, DataT, ExampleT, BaseLearnerT &gt;',['../structVW_1_1LEARNER_1_1common__learner__builder.html',1,'VW::LEARNER']]],
  ['conditional_5fcontextual_5fbandit_5foutcome',['conditional_contextual_bandit_outcome',['../structCCB_1_1conditional__contextual__bandit__outcome.html',1,'CCB']]],
  ['config_5fmanager',['config_manager',['../structVW_1_1reductions_1_1automl_1_1config__manager.html',1,'VW::reductions::automl']]],
  ['config_5foracle',['config_oracle',['../structVW_1_1reductions_1_1automl_1_1config__oracle.html',1,'VW::reductions::automl']]],
  ['context',['Context',['../structContext.html',1,'']]],
  ['continuous_5flabel',['continuous_label',['../structVW_1_1cb__continuous_1_1continuous__label.html',1,'VW::cb_continuous']]],
  ['continuous_5flabel_5felm',['continuous_label_elm',['../structVW_1_1cb__continuous_1_1continuous__label__elm.html',1,'VW::cb_continuous']]]
];
